### ISSUE TITLE
Support h-feed h-entry

### ISSUE THREAD

**Issue by sjehuda** [gohugoio/hugo#10108]
It's a great idea and would be a good to integrate in addition to the currently provided RSS feed.

h-feed is a simple, open format for publishing a stream or feed of h-entry posts, like complete posts on a home page or archive pages, or summaries or other brief lists of posts. h-feed is one of several open microformat draft standards suitable for embedding data in HTML.

https://microformats.org/wiki/h-entry
https://microformats.org/wiki/h-feed

**Comment by Seirdy** [comment]
I think this should be done manually by site or theme authors. Microformats add class names to a page, but someone still has to design a page. There's way more diversity in h-feed design than RSS, Atom, or JSON-feed design because h-feeds are webpages meant for humans first, machines second. Providing built-in h-feed templates would be akin to providing a default incomplete theme.

That being said, I could imagine other microformats getting shortcodes and templates. A shortcode and/or partial for `h-cite`, `h-card`, etc. could work. I've made a few of these and could upstream simplified versions if there is sufficient interest.
