### ISSUE TITLE
Blank taxonomy pages when using Permalink

### ISSUE THREAD

**Issue by BenSouchet** [gohugoio/hugo#10115]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.101.0+extended darwin/amd64 BuildDate=unknown
</pre>

### Does this issue reproduce with the latest release?
Yes

When using **permalink** to change the path of **taxonomy**, the old (default) path and the new path for the taxonomy page are both valid but are blank (not a 404), a blank page without any layout (even the `baseof.html` layout is ignored).

### To reproduce it

1. Create a new taxonomy in your config file:
```yaml
taxonomies:
  test: tests
```
2. Set a new permalink for that taxonomy (still in your config):
```yaml
permalinks:
  tests: /testing/:slug
```
Now add a new post and in the front matter of this post add:
```yaml
tests: [duck]
```
Now, we can access the term page of duck with: `https://example.com/testing/duck`

## But there is issues

The taxonomy pages `testing`(`https://example.com/testing/`) and `tests` (`https://example.com/tests/`) are both existing and both return a blank page, it’s not a 404 error, a true blank html page.

**Even stranger**, if we create a layout `taxonomy.html` it will be used to render the two taxonomy pages but without using `baseof.html`. Only `taxonomy.html` will be used.

**Comment by jmooring** [comment]
Here is a minimal reproducible example:

```bash
git clone --single-branch -b hugo-github-issue-10115 https://github.com/jmooring/hugo-testing hugo-github-issue-10115
cd hugo-github-issue-10115
hugo && tree public
```

Output:

```text
public/
├── post/
│   ├── test/
│   │   └── index.html
│   └── index.html
├── testing/
│   └── duck/
│       └── index.html
├── tests/
│   └── index.html
└── index.html
```

You described three problems...

#### 1\) `https://example.com/testing/` returns a blank page

This is not true. When you run `hugo` to build your site, you can see from the `tree` output above that an index.html file is _not_ generated in the public/testing directory, resulting in a 404 error. However, if you run `hugo server`, a phantom page _is_ visible at `http://localhost:1313/testing/`. Perhaps you are referring to that behavior.

#### 2\) `https://example.com/tests/` returns a blank page

This is not true. When you run `hugo` to build your site, you can see from the `tree` output above that a non-empty index.html file _is_ generated in the public/tests directory. If you want this taxonomy page to be served from public/testing/index.html, you need to create content/tests/_index.md and override the `url`:
```
+++
title = 'Tests'
date = 2022-07-22T11:43:21-07:00
draft = false
url = 'testing'
+++
```

You must perform this step because the `permalinks` configuration settings do not apply to section pages. 
See <https://github.com/gohugoio/hugo/issues/8523>.

#### 3\) if we create a layout taxonomy.html it will be used to render the two taxonomy pages but without using baseof.html

I am unable to reproduce this. Let's troubleshoot this in a new topic on the forum (https://discourse.gohugo.io/). Thanks.

**Comment by BenSouchet** [comment]
Okay, so the issues are:
\
**1. No index.html is generated for `https://example.com/testing/`**
Resulting in a 404 when site builded and a phantom page when using `hugo server`.

**2. The old / default taxonomy page (a.k.a section) is accessible, the permalink isn't applied to this page.**
After looking at #8523 it's seems it's exactly the issue.

These two issues are linked, and are directly correlated to #8523.

For the last point "**3)**", it's my bad, I forgot to use the correct syntax : ```{{- define "main" -}}...{{- end -}}```

**Comment by BenSouchet** [comment]
Btw @jmooring thanks for taking the time to check this bug report, and point me to #8523 , so I can understand why there is currently this limitation (I will define the `url` and `aliases` via front matter for now).
