### ISSUE TITLE
Why can't this access?

### ISSUE THREAD

**Issue by yigeqiji** [gohugoio/hugo#10199]
### What version of Hugo are you using (`hugo version`)?
**ubuntu 18&hugo extended v0.101.0**
hugo v0.101.0-466fa43c16709b4483689930a4f9ac8add5c9f66+extended linux/amd64 BuildDate=2022-06-16T07:09:16Z VendorInfo=gohugoio
GOOS="linux"
GOARCH="amd64"
GOVERSION="go1.18.3"

</pre>

### Does this issue reproduce with the latest release?
install hugo extended deb
sudo hugo new site ./hugo1
cd hugo1
sudo hugo serve
![image](https://user-images.githubusercontent.com/59365443/186322775-509a0c02-f405-4fd1-a31e-150bf55a5102.png)
**If I configure via nginx,I can access 165.154.72.194:1313 through nginx**
Now,165.154.72.194 can access,is nginx,but 1313 cant access,is hugo extended.
Did I forget any important settings?

**Comment by bep** [comment]
# #
Thanks for getting in touch, but it feels like this is a question  that would be better suited to the [Hugo Discussion Forum](https://discourse.gohugo.io/).  We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug. You may also find the answers you search for in [Hugo Documentation](http://gohugo.io/overview/introduction/).
