### ISSUE TITLE
Allow standalone HTML comments before front matter

### ISSUE THREAD

**Issue by ITler** [gohugoio/hugo#10221]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
- hugo v0.101.0-466fa43c16709b4483689930a4f9ac8add5c9f66+extended linux/amd64 BuildDate=2022-06-16T07:09:16Z VendorInfo=gohugoio
- hugo v0.102.0-0ff4a9326fd8ac1deb7245461bc4a56d94d0c40b+extended linux/amd64 BuildDate=2022-08-28T16:29:34Z VendorInfo=gohugoio
</pre>

### Does this issue reproduce with the latest release?
yes

#### Disclaimer
Probably this is desired behavior. If so, sorry for bothering.

#### Description
I try to `hugo build` a markdown file, which **starts** with a HTML comment line (i.e. `<!-- foo -->`). 
The file
* lacks the front matter part and
* just contains plain markdown.

In version
* 0.101.0 I got an error `Error: Error building site: [path]: starting HTML comment with no end`, which is logically wrong (because it has an end tag). 
* 0.102.0 I got an error `Error: Error building site`, but with no custom error message

However, I somehow expected to hugo not running into a build failure, as removing the HTML comment line will result in a successful build process, too (,although it couldn't get rendered (in docsy theme), but this is ok IMO).

**Comment by rrcomtech** [comment]
I also stumbled over this problem a while ago. I believe, it is supposed to be desired behavior. I have a theory to this, which would explain exactly this.

There are two types of front matters people want to use:
```
---
title: "My title"
---
```
and
```
<!--
+++
title = "Home"
+++
-->
```

Hugo supports both. Therefore comments in the beginning of a file have to be frontmatter and (now comes in a guess) have to be started with `<!--\n+++`  and ended with `+++\n-->`.  If the `+++`  is missing, Hugo might understand that as a not-yet ended front matter and tries to parse the whole document as front matter. But there is an easy workaround, that does not mean taking away content from the document: Include a frontmatter! So turn any document starting with a comment into the following (here we have a frontmatter without attributes):

```
---
---

<!-- A comment in the beginning -->
```

For further reading, here are two interesting contributions:

- [Comments are rendered THEN stripped (bug?)](https://discourse.gohugo.io/t/comments-are-rendered-then-stripped-bug/10692)
- [Templates in HTML comments are escaped if front-matter is present #7398](https://github.com/gohugoio/hugo/issues/7398)

It would be nice, if someone confirms or rejects this theory, since I am personally not sure about the correctness.

**Comment by bep** [comment]
>believe, it is supposed to be desired behavior.

You are right. We could possibly support comments that wasn't surrounding the front matter, but that would compliate the parser.
