### ISSUE TITLE
Contributor Files do not support ü,ä,ö

### ISSUE THREAD

**Issue by rrcomtech** [gohugoio/hugo#10280]
I recently noticed the following behavior in one of my documentation files:

```
---
contributors:
  - Ü
---

Some Text ...
```

For each contributor, a file is created that links to all pages, that the contributor is part of. But for the Ü, the files names are not exactly transferred. Here, Ü would not end up as the actual filename on the contributor's webpage. It requires me, e.g., to change Ü to Ue, to have exact filename matching. 

Can this be worked around?

**Comment by bep** [comment]
Thanks for getting in touch, but it feels like this is a question  that would be better suited to the [Hugo Discussion Forum](https://discourse.gohugo.io/).  We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug. You may also find the answers you search for in [Hugo Documentation](http://gohugo.io/overview/introduction/).
