### ISSUE TITLE
Make shortcode errors "ignorable"

### ISSUE THREAD

**Issue by regisphilibert** [gohugoio/hugo#10339]
## The problem

Currently, failing shortcodes references (misformed or unexisting matching template) will break the build.

```
{{< video id="xxxx" 
```
👇 
```
Error: Error building site: "/page.md:28:1": got positional parameter 'Join'. Cannot mix named and positional parameters
```
OR
```
{{< video_embed id="xxxx" >}} 
```
👇 
```
Error: Error building site: "/page.md:26:1": failed to extract shortcode: template for shortcode "video_embed" not found
```

Breaking the build means non-technical editors will no longer be able to update their content (push new commits via CMS to CI) without the intervention of a dev to:
1. access CI log to identify and locate shortcode error
2. fix the error

### A. Introducing a new global config

We could potentially add a setting `shortcodesErrorLevel` similar to [the one available for RelRef](https://gohugo.io/content-management/cross-references/#ref-and-relref-configuration)

```
# config.yaml
shortcodesErrorLevel: warning
```

With that setting set to `warning` Hugo could just print the problematic shortcode as a string. 
This would align with Goldmark's way of handling problematic markdown ref (image or url containing a white space)

### B. Assign an ID to errors produced by the Shortcode API to rely on existing `ignoreErrors` config

By marking shortcode errors with an ID the way [`errorfid`](https://gohugo.io/functions/errorf/#suppress-errors) would, user could simply add the reserved ID to the `ignoreErrors ` key.

```
# config.yaml, shortcodes as an error ID might be a bit ambiguous. Better naming welcome.
ignoreErrors: 
- shortcodes
```

**Comment by bep** [comment]
The `ignoreErrors` construct works reasonably well, let's use that.

**Comment by khayyamsaleem** [comment]
hoping to take this on but looking for validation on this plan.

Thinking that I should write a handleShortcodeErrors function and wrap all the existing error handling in `hugolib/shortcode.go` to return a raw representation of the shortcode if there's an error AND `shortcodes` is in `ignoreErrors` (checked from the config in the `s *Site` arg), or otherwise pass-through the existing failure behavior.

If this makes sense, wondering if the `ignoreErrors` key might not be the right place for this configuration, as it restricts us to an all-or-nothing approach for shortcodes. What if only _certain_ selected shortcode errors should be ignored?

If there was a separate configuration key, we could have the granularity required to only ignore errors for certain shortcodes, or some kind of wildcard operator for those who'd like to ignore all shortcode errors.

**Comment by bep** [comment]
@khayyamsaleem I don't think we want to do too much to fix this. My 50 cents:

* We currently just return any such error to the template, and most (all?) of these errors are passed into `*pageState.wrapError`, so that is a good place to add some logic.
* We currently log some errors with `ignorableLogger.Errorsf("some-id", "the error message")`
* We would want to come up with one or two new IDs for these shortcode errors and probably add a `ignoreableLogger.ShouldIgnore(ID)` method that can be used to determine if we should "log or return".
