### ISSUE TITLE
if this first line start with '-' in *.md file, report " invalid YAML delimiter" error

### ISSUE THREAD

**Issue by leechor** [gohugoio/hugo#10372]
hugo v0.104.3+extended darwin/amd64 BuildDate=unknown

if this first line start with '-' in *.md file, report ` invalid YAML delimiter` error when execute `hugo`

the error occurrence at
[here](https://github.com/gohugoio/hugo/blob/a066e98851dfbd78c17c98f0878c2e8b84a10f50/parser/pageparser/pagelexer_intro.go#L30)

**Comment by bep** [comment]
>if this first line start with '-' in *.md file, report invalid YAML delimiter error when execute hugo

Is the error message wrong? How do does this md file start?

**Comment by bep** [comment]
>it is a legal markdown file.

Yea, but it's not a valid Hugo Markdown file. I will keep this issue open, but it only gets fixed if the fix is really simple, which I suspect it would not be. The thing is 

```
--- 
foo
```

Is also a valid Markown file, but it's certainly not valid front matter.

I suggest that you either don't start your markdown with one of Hugo's delimiters, or your just put empty front matter at the top:

```
--- 
---
```
