### ISSUE TITLE
Goldmark incorrectly parses http addresses that end in a quote

### ISSUE THREAD

**Issue by TopherIsSwell** [gohugoio/hugo#10407]
### What version of Hugo are you using (`hugo version`)?
`v0.105.0-DEV-c10931404f605b88067cb66da7ec333ddeb24cc0`  
Also tried with a local build of `v0.104`, and a downloaded binary of `v0.102 `
This bug exists as of commit SHA c10931404f605b88067cb66da7ec333ddeb24cc0

### Does this issue reproduce with the latest release?
Yes, latest stable and the latest build off of main

### issue description
when you render a page that includes an http address with a slash (i.e. the address has a path) surrounded in double quotes, the trailing quote is considered part of the address and url-encoded into the href link. This makes the link invalid. It seems that a slash needs to be in the address to trigger the bug (not counting the slashes for the URI component), so `"https://google.com"` will NOT trigger this bug, but `"https://google.com/"` will and `"https://google.com/mail"` will.

### to reproduce
create an page with the content

```
go to "https://google.com/"
```

and it will be rendered as  
```
go to "<a href="https://google.com/%22">https://google.com/"</a>
```
Pic:
![image](https://user-images.githubusercontent.com/22041949/199129952-2325fd6f-3cf7-463e-8f3e-11e9fc79cc96.png)

**Comment by TopherIsSwell** [comment]
I've noticed that setting `markup.goldmark.extensions.typographer` to `false` causes the link rendered behavior to stop. Maybe this bug is in smartypants or one of the typographers?

**Comment by jmooring** [comment]
This may be caused by the linkify extension, or the interaction between linkify and typographer. The linkify extension renders strings such as `https://google.com` and `www.google.com` to anchor elements.

With both extensions enabled...

These work:

```text
"https://google.com"
"www.google.com"
```

These fail (note the trailing slash):

```text
"https://google.com/"
"www.google.com/"
```

I'm not a huge fan of the autolink extension. I would prefer to be in control of what is and is not rendered as an anchor element.

Both of these work regardless of whether or not the linkify extension is enabled.

```
"<https://google.com>"
"<https://google.com/>"
```

In any event, this needs to be reported upstream.

**Comment by jmooring** [comment]
<https://github.com/yuin/goldmark/issues/335>
