### ISSUE TITLE
Custom Chroma Highlighter Lexer

### ISSUE THREAD

**Issue by septs** [gohugoio/hugo#10421]
Allow user add custom chroma lexer, can improve theme render specific language (or new language) effect

e.g: [AT command set](https://en.wikipedia.org/wiki/Hayes_command_set)

discuss: https://discourse.gohugo.io/t/41302

simple implementation: see https://github.com/gohugoio/hugo/pull/10419

**Comment by serhack** [comment]
I think it's better to submit PR to chroma project for improvements than having weird custom lexers on themes :)

**Comment by septs** [comment]
> I think it's better to submit PR to chroma project for improvements than having weird custom lexers on themes :)

Of course, chroma is obviously not willing to support small share of DSL

**Comment by serhack** [comment]
Naturally I can not speak for the project, but I was curious to know what domain specific language you'd like to include with your theme :)

**Comment by septs** [comment]
> Naturally I can not speak for the project, but I was curious to know what domain specific language you'd like to include with your theme :)

I'm make a AT Command set ebook,
i want to pass custom highlight lexer improve at command example code reading experience

**Comment by michaeltlombardi** [comment]
This functionality would also be useful for custom lexers that don't have wide usage purpose beyond this project. For example, adding a lexer for code blocks with the `myapp-output` tag that colorize the output examples based on the application's needs is useful for that application's documentation and little else.

Similarly, this could be used for lexers of forked languages and those without enough adoption to make sense to maintain in chroma itself.

Finally, I can see value in this for custom lexers for data structure examples, colorizing required configuration keys differently or underlining invalid values to enable textual representation of that information instead of having to include (and update every instance of when a change effects them) screenshots.

**Comment by psybers** [comment]
This would definitely be helpful! At the moment, I forked Hugo and hard coded loading my DSL's custom lexer in.  This obviously works, but it makes things like CI/CD a bit more painful as now I need to ensure everything is using that custom fork of Hugo.

**Comment by premkumr** [comment]
Will be very useful for our custom clis & tools

**Comment by jmooring** [comment]
Closing in favor of #11496.
