### ISSUE TITLE
Environment variables ignored

### ISSUE THREAD

**Issue by amzon-ex** [gohugoio/hugo#10425]
### What version of Hugo are you using (`hugo version`)?

<pre>
0.105.0 (latest)
</pre>

When I use the (cross-platform) binary in [hugo_extended_0.105.0_linux-amd64.tar.gz](https://github.com/gohugoio/hugo/releases/download/v0.105.0/hugo_extended_0.105.0_linux-amd64.tar.gz), it doesn't seem to accept environment variables of the form `HUGO_BIND=0.0.0.0`. It does however accept variables like `HUGO_ENV=production`. Why is this the case?

**Comment by jmooring** [comment]
There is not a 1:1:1 relationship between CLI flags, configuration settings, and environment variables.

I _think_ you can use an environment variable to set every configuration value, but the inverse is not true. For example, you can not use a configuration setting to define `HUGO_NUMWORKERMULTIPLIER` or `DART_SASS_BINARY`.

With all the work bep did for v0.112.0, I think we have a pretty good handle on the API from the standpoint of CLI flags and configuration settings.

What we do not have is a list of the available environment variables.

Having said all that:

1. I'd like to be able to use HUGO_SERVERPORT and HUGO_SERVERINTERFACE instead of specifying the `--port` and `--bind` flags on the command line. I'll create a separate issue.
2. We need to document the env vars somewhere. I'll create an issue in the docs repository.
