### ISSUE TITLE
Footnote markers are not stripped when autogenerating `.Summary`

### ISSUE THREAD

**Issue by nekr0z** [gohugoio/hugo#10503]
When generating `.Summary`, either automatically or by taking the content above the `<--!more-->` tag, Hugo strips the tags from HTML, leaving just the text. This doesn't play well with Hugo-generated footnotes.

This markdown:

```md
A footnote[^1] here.
```

Produces this HTML when rendered with Goldmark (Hugo's default renderer):

```html
<p>A footnote<sup id="fnref:1"><a href="#fn:1" class="footnote-ref" role="doc-noteref">1</a></sup> here.</p>
```

Which, after stripping the tags, produces this `.Summary`:

    A footnote1 here.

and leaves user with no good way to get rid of that rogue "1" with `replaceRE` or other available instruments.

There seems to be no use-case such that leaving the "1" in the `.Summary` would be the desired behavior.

Hugo should delete every HTML node that has `id` prefixed with `fnref:`, and all inside it, before stripping tags when generating `.Summary`.

(from [this](https://discourse.gohugo.io/t/stripping-footnotes-from-summary/3923/1) forum thread)

### What version of Hugo are you using (`hugo version`)?

Current `master` branch.

### Does this issue reproduce with the latest release?

Yes.

**Comment by eswan18** [comment]
Just throwing in one small addition here after running into the same problem: in my case, using `<!-- more -->`  results in footnotes being rendered "properly" in the final summary HTML. The issue is that their target doesn't exist, so clicking them does nothing.

From my summary:
```html
<p>A sentence, with a caveat<sup id="fnref:1"><a href="#fn:1" class="footnote-ref" role="doc-noteref">1</a></sup>.</p>
```

This still seems like undesired behavior, but the above says "Hugo strips the tags from HTML" and that's not quite right in the case of summaries with the `<!-- more -->` approach, I think.
