### ISSUE TITLE
Error: failed to prune cache with v0.111.0 and later on Windows 

### ISSUE THREAD

**Issue by jmooring** [gohugoio/hugo#10781]
```
hugo --gc
```

> Error: failed to prune cache...

Two reports, both Windows users.

Reference: <https://discourse.gohugo.io/t/hugo-gc/43261>

**Comment by andrewd72** [comment]
I can reproduce with the quickstart steps

hugo new site quickstart
cd quickstart
git init
git submodule add https://github.com/theNewDynamic/gohugo-theme-ananke themes/ananke
echo "theme = 'ananke'" >> config.toml

Then copying the exampleSite to content and:
hugo
hugo --gc
Windows 10
Error: failed to prune cache "getjson": remove C:\Users\photo\AppData\Local\Temp\hugo_cache\quickstart\filecache\getjson: The process cannot access the file because it is being used by another process.

Seems to be an issue trying to delete empty directories.

**Comment by bep** [comment]
@alexandear I suspect this is the `ReadDir` update.  Do you have a Windows machine to test this on?

**Comment by jmooring** [comment]
> I can reproduce with the quickstart steps

Tried the same on Win 11. Can't reproduce. Tried running commands from CMD, WSL, PowerShell, Windows PowerShell, and Git Bash.

**Comment by bep** [comment]
OK, looking at this now, I'm pretty sure this is a Go 1.20 issue. I have seen similar things in unrelated tests on Windows and I have seen this issue mentioned in Go's issue tracker recently. I suspect that this issue is more prominent on certain Windows versions, and the workaround I have seen (and also remember to implement somewhere) is to just wait and try again. Also, in this particular situation we could just print a warning -- the deletion would most likely succeed on the next run.

**Comment by bep** [comment]
OK; I can reproduce this on Windows 8 (!). I'll apply a workaround + create an upstream issue.

**Comment by alexandear** [comment]
> The process cannot access the file because it is being used by another process.
Usually, Windows can't delete a file when the file is not closed from the Go code.

I have a Windows 10 machine and will try to reproduce it later today.

**Comment by andrewd72** [comment]
Multiple runs don't solve it. Tried the next day, reboot and it persists. 
Only seems to affect empty folders, it isn't that any files are locked (by anything other than the running hugo --gc command I suppose)
As per forum, only way to fix is to put a file in each of the folders that complains. 
Andrew@R5 MINGW64 ~/quickstart (master)
$ hugo --gc
Start building sites …
hugo v0.111.1-39a4a3cf676533859217805c36181c7a3dfa321c+extended windows/amd64 BuildDate=2023-03-02T10:08:26Z VendorInfo=gohugoio
15 runs og hugo --gc, the error repeats, though which folder it complains can change, it never deletes any of them. 

Error: failed to prune cache "images"
Error: failed to prune cache "getjson"
Error: failed to prune cache "getresource"
Error: failed to prune cache "getjson"
Error: failed to prune cache "getresource"
Error: failed to prune cache "images"
Error: failed to prune cache "getresource"
Error: failed to prune cache "images"
Error: failed to prune cache "getcsv"
Error: failed to prune cache "images"
Error: failed to prune cache "getjson"
Error: failed to prune cache "getresource"
Error: failed to prune cache "getjson"
Error: failed to prune cache "getjson"
Error: failed to prune cache "images"

**Comment by alexandear** [comment]
@bep I fixed the problem in #10788

Also, I copied the integration test from your PR #10786 to prove it. If you want you can use my solution instead of a workaround.

**Comment by bep** [comment]
@alexandear see my comment in the PR:
