### ISSUE TITLE
`hugo new site` should add a `.gitkeep` to the content directory.

### ISSUE THREAD

**Issue by buildwithzephyr** [gohugoio/hugo#10826]
## Description

Suppose that I generate a new site with `hugo new site`. A `content` directory will be created for me. If I immediately add a new page via `hugo new`, then there will a file within the `content` directory, so it will be tracked with Git. However, if I commit my changes without creating a page, then the result commit will capture a snapshot of my site that does not include a content directory. This will cause `hugo new <section>/<page-title>.md` to fail with the message `Error: no existing content directory configured for this project`.

## Steps to Reproduce

1. Create a new Hugo site.
```bash
$ hugo new site quickstart
$ cd quickstart
```
2. Check in the site state with Git.
```bash
$ git init
$ git add --all
$ git commit -m "Initial commit - blank Hugo site"
```

3. Reproduce the working tree from that commit. E.g. via a `git clone`, or a `git reset --hard`.
```bash
# ... add some more git history.
# ... then backtrack to the first commit
$ git reset --hard <initial commit SHA>
# Note that my content directory is now gone
$ file content
content: cannot open `content' (No such file or directory)
```

4. Try to add a new page.
```bash
$ hugo new posts/post-name.md
Error: no existing content directory configured for this project
```

## Suggested fix

`hugo new site` should create a `content/.gitkeep`. This would ensure that the output of `hugo new site`, when saved to Git, represents a working project state.
 

### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.111.2+extended darwin/amd64 BuildDate=unknown
</pre>

### Does this issue reproduce with the latest release?

Yes, I am using the latest release

**Comment by cansurmeli** [comment]
Hmmmmm, there is actually a valid point here but not sure about the strategy.

I myself naturally fall into the same situation and end up creating `.gitkeep` files all around.

I guess the point is do we want to tie Hugo to Git and a certain project structure or keep it abstract? Not everyone wants or uses Git. Plus, what you have described could also be accomplished with a simple Bash script.

I personally lie more towards the abstract side of the argument but interested to hear others’ thoughts.

Cheers.

**Comment by junderhill** [comment]
Commenting as I was about to go and implement this however I kind of agree on your point regarding keeping Hugo abstract. Although my 'go to' on any project is to initialise a git repo the moment I begin, I appreciate that not everyone does this.

Interested to hear other opinions, and if it is decided that it would be beneficial I'd be happy to raise a PR

**Comment by cansurmeli** [comment]
Ok, revisiting my thoughts and perhaps thinking out loud a little bit.

BTW, I also initialise a Git repository right after everytime I do a new Hugo site. I still think it would be wrong to implement this behaviour into Hugo by default. In that case, it might be better to enable such a feature via a flag. I just checked available flags for Hugo and `--enableGitInfo` is one for `add Git revision, date, author, and CODEOWNERS info to the pages`. So Hugo is aware of Git if it wants afterall.

Therefore, during a setup with the command `hugo new site [SITE_NAME]`, the user can add a flag such as `--introduceGit` so that the project folder is setup as a Git repository at the same time. If others want it, they can introduce other flags for other versioning systems.

From my perspective, the `--introduceGit` should do:

- `git init`,
- add `.gitkeep` files to various folders,
- add `.gitignore`,
- perhaps also do an initial commit.

I could still see myself doing a custom Bash script for a project setup with more custom options but this flag could benefit some users.

Thoughts.

p.s. you are more than welcome to criticise my flag name :]

**Comment by jmooring** [comment]
> --introduceGit should do `git init`

Unless Git isn't installed, in which case it should...

My take on this issue is:
- If you want to keep a directory, put something in it (user's choice, not Hugo's)
- If you want to do other things, script it (user's choice, not Hugo's)
- We have already have enough command options to choke a horse
