### ISSUE TITLE
Unexpected behaviour, bug when accessing content. MacOs Hugo v0.111.3+extended darwin/arm64

### ISSUE THREAD

**Issue by sanderjson** [gohugoio/hugo#10870]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.111.3+extended darwin/arm64 BuildDate=unknown
</pre>

### Does this issue reproduce with the latest release?

Bugs when building from /content.

If I start the server, my content files are not available. If I build the site, the content files are not available (see screenshot blow).

<img width="652" alt="image" src="https://user-images.githubusercontent.com/20689537/229024336-a5cbccd7-3914-4aa7-a9c1-95c4dea392b5.png">

I found a workaround for development. I start the server, then move all the content files into some new "temp" directory. Then move all the files back to content, and I can develop as expected. However, I still get an error when accessing /tags/tag or categories/category. The Taxonomy page itself works as expected, but not the Term page.

**Comment by bep** [comment]
Thanks for getting in touch, but it feels like this is a question  that would be better suited to the [Hugo Discussion Forum](https://discourse.gohugo.io/).  We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug. You may also find the answers you search for in [Hugo Documentation](http://gohugo.io/overview/introduction/).

**Comment by sanderjson** [comment]
User error! Thanks. 
[](https://discourse.gohugo.io/t/default-term-html-page-not-working/43681/4)

**Comment by dadashkarimi** [comment]
I would try this: 


`rm -rf .hugo_build.lock`
