### ISSUE TITLE
These might require closing/quick check due to deprecation/duplication

### ISSUE THREAD

**Issue by bwc69151** [gohugoio/hugo#10872]
#2424
#3949
#3918
#4063
#4412
#6487
#7083
#6995
#7406
#8549

**Comment by jmooring** [comment]
- ~[#2424]~ - Closed, no longer relevant
- [#3918] - Still relevant
- ~[#3949]~ - Closed, no longer relevant
- [#4063] - Still relevant, sort of; option still available in site config and env var
- [#4412] - ?
- [#6487] - Still relevant, sort of; not completely removed due to `autoid` backwards compatibility
- [#6995] - Still relevant, maybe
- ~[#7083]~ - Closed, addressed with [#9185]
- ~[#7406]~ - Closed, addressed with [#9920]
- ~[#8549]~ - Closed, addressed with [#8827]


[#2424]: https://github.com/gohugoio/hugo/issues/2424
[#3949]: https://github.com/gohugoio/hugo/issues/3949
[#3918]: https://github.com/gohugoio/hugo/issues/3918
[#4063]: https://github.com/gohugoio/hugo/issues/4063
[#4412]: https://github.com/gohugoio/hugo/issues/4412
[#6487]: https://github.com/gohugoio/hugo/issues/6487
[#7083]: https://github.com/gohugoio/hugo/issues/7083
[#6995]: https://github.com/gohugoio/hugo/issues/6995
[#7406]: https://github.com/gohugoio/hugo/issues/7406
[#8549]: https://github.com/gohugoio/hugo/issues/8549
[#9185]: https://github.com/gohugoio/hugo/pull/9185
[#9920]: https://github.com/gohugoio/hugo/pull/9920
[#8827]: https://github.com/gohugoio/hugo/pull/8287
