### ISSUE TITLE
Allow LanguageDirection and LanguageName in root of configuration

### ISSUE THREAD

**Issue by jmooring** [gohugoio/hugo#11027]
This would:

1. Mirror the API for `.Site.LanguageCode`
2. Allow you to do this on monolingual and multilingual sites

   ```html
   <html lang="{{ site.LanguageCode }}" dir="{{ site.LanguageDirection }}">
   ```

----

To me, this is the basic configuration for a language:

```
[languages.en]
languageCode = 'en-US'  
languageDirection = 'ltr' 
languageName = 'English'
weight = 1
```

But the way you access the values is (conceptually) inconsistent:

Key|Code|Notes
:--|:--|:--
`languageCode`|`{{ .Site.LanguageCode }}`|`{{ .Site.Language.LanguageCode }}` does not work
`languageDirection`|`{{ .Site.Language.LanguageDirection }}`|
`languageName`|`{{ .Site.Language.LanguageName }}`|
`weight`|`{{ .Site.Language.Weight }}`|Not sure why this is exposed

**Comment by bep** [comment]
I will suggest we do it the other way, we (conceptually) move `LanuageCode` down to Language. It should be easy to make the old work, but that field belongs on `Language`-- the only reason it's not there is because it came before ...

That will also make the smallest change set and keep _some_ values in `Language`.

**Comment by jmooring** [comment]
Sounds good to me.
