### ISSUE TITLE
docs: hugo new theme docs seem incorrect

### ISSUE THREAD

**Issue by schalkneethling** [gohugoio/hugo#11209]
As mentioned in the following thread on [Discourse](https://discourse.gohugo.io/t/hugo-new-theme-docs-seem-incorrect/45148), the `hugo new theme` command documentation seems to be incorrect. From what I can tell, it seems to be talking about the `hugo new site` command.

- https://gohugo.io/commands/hugo_new_theme/

On a related note, I cannot seem to find reference documentation concerning the theme config file. Perhaps it is meant to be covered on the above-referenced page? There seems to be very little documentation on the Hugo site concerning building themes for Hugo. Is this because Hugo is moving away from themes in general, or is there an alternate way to write themes for Hugo?

I did stumble on this page talking about theme components: https://gohugo.io/hugo-modules/theme-components/

**Comment by deining** [comment]
Please note that this is a known issue, reported as issue #11161 and solved via PR #11177. What is left here ist to regenerate the CLI docs and the error will disappear. Since this issue is merely a documentation issue, it should be transferred to the [hugodocs](https://github.com/gohugoio/hugoDocs) repo.

**Comment by jmooring** [comment]
Addressed with https://github.com/gohugoio/hugoDocs/pull/2127
