### ISSUE TITLE
Hugo config TOML output shows floats for int values

### ISSUE THREAD

**Issue by jmooring** [gohugoio/hugo#11345]
```
$ hugo config --format toml | grep weight -B3

[[related.indices]]
  name = 'tags'
  weight = 80.0   <-- would be nice if this were "80"
```

YAML and JSON output are fine.

This is also written to docs.json, so when we point the doc's code-toggle shortcode to a config key we also show floats. This is at odds with field descriptions. 

This may be upstream from `transform.Remarshal`.

**Comment by bep** [comment]
OK, I think I remember wrong (I don't think this is a new problem). The problem is:

* Go's json.Unmarshal into a map will make all numbers float64
* And a toml.Marshal of that map will get you the formatting as shown

So, the sad part in the above is how `json.Unmarshal` behaves (I have done some experiments about this here: https://github.com/bep/tmc).

But what I think would be a sensible workaround (which I vaguely remember that I have added somewhere) is to convert any float64 in the map in `json.Unmarshal` without any decimal into an `int`.

**Comment by bep** [comment]
Never mind, the obvious workaround is to replace docshelper.json with docshelper.yaml (or toml, if that works better).

**Comment by jmooring** [comment]
Fixed by https://github.com/gohugoio/hugo/pull/11346 (`hugo config`) and https://github.com/gohugoio/hugoDocs/pull/2181 (documentation).
