### ISSUE TITLE
Include optional extensions in Goldmark

### ISSUE THREAD

**Issue by stefanv** [gohugoio/hugo#11679]
Would it be possible to add one or two [external extensions](https://github.com/yuin/goldmark#list-of-extensions) to the version of Goldmark included with Hugo?
Specifically, we are interested in [fenced divs](https://github.com/stefanfritsch/goldmark-fences) and [figures with captions](https://github.com/mangoumbrella/goldmark-figure).

It is difficult to see how otherwise to make use of these extensions, since we do not get to control the compilation of goldmark on theme users' systems.

**Comment by jmooring** [comment]
You can use an image render hook to turn standalone images (i.e., no other elements or text on the same line) into figure elements. This gives you a lot more control than the "figures with captions" extension. 

You can use markdown attributes to assign classes, ids, and other relevant HTML attributes to most block level markdown elements. In many cases that meets the intent/need of the "fenced div" extension.

Please create a topic in the forum (https://discourse.gohugo.io/) if you need assistance with either feature.

> Would it be possible to add one or two...

If the need justifies the expense of additional dependencies, yes. But given the built-in features described above, and the ability to use a shortcode to wrap content with whatever you want, I don't see us adding either of these extensions.

**Comment by stefanv** [comment]
Thanks, @jmooring. We can indeed use the image render hook for figures.

I'm not sure how you define a "block level markdown element" for an arbitrary section of text, other than adding an explicit `<div>` tag.

**Comment by jmooring** [comment]
@stefanv Regarding markdown attributes, [this article](https://www.veriphor.com/articles/markdown-attributes/) might be helpful.

**Comment by jmooring** [comment]
@stefanv If markdown attributes are insufficient, you have two options.

### Option 1: Use a shortcode

markdown

```text
{{% div %}}
## This is a heading

This is **paragraph** one.

This is _paragraph_ two.
{{% /div %}}
```

layouts/shortcodes/div.html

```text
</div>

{{ .Inner }}
</div>
```

The blank line after the opening `div` and no indentation are both required due to markdown rules governing [indented code blocks](https://spec.commonmark.org/0.30/#indented-code-blocks) and [raw HTML mixed with markdown](https://spec.commonmark.org/0.30/#raw-html).

### Option 2: Mix raw HTML with markdown

markdown

```text
<div>

## This is a heading

This is **paragraph** one.

This is _paragraph_ two.
</div>
```

Again, the blank line after the opening `div` and no indentation are both required due to markdown rules governing [indented code blocks](https://spec.commonmark.org/0.30/#indented-code-blocks) and [raw HTML mixed with markdown](https://spec.commonmark.org/0.30/#raw-html).

#### Configuration

Note that both options require the following in your site configuration:

```text
[markup.goldmark.renderer]
unsafe = true
```

This configuration is safe if _you_ control the content, trust contributors, or review submissions before merging.

**Comment by stefanv** [comment]
Thanks @jmooring; we'll stick with shortcodes then. We are trying to map a Sphinx site using MyST / RST capability to Markdown, and it's not always obvious what the most straightforward mapping is between RST roles and markdown. Shortcodes are, at least, consistent.

**Comment by jmooring** [comment]
@stefanv I just found this in some old notes...

layouts/shortcodes/div.html

```text
<div
{{- range $k, $v := .Params }}
  {{- if $v }}
    {{- printf " %s=%q" $k $v | safeHTMLAttr }}
  {{- end }}
{{- end -}}
>

{{ .Inner }}
</div>
```

Then you can do this in markdown:

```text
{{% div id=foo class="something" %}}
## This is a heading

This is **paragraph** one.

This is _paragraph_ two.
{{% /div %}}
```

And you'll get this:

```text
<div class="something" id="foo">
  <h2 id="this-is-a-heading">This is a heading</h2>
  <p>This is <strong>paragraph</strong> one.</p>
  <p>This is <em>paragraph</em> two.</p>
</div>
```
