### ISSUE TITLE
Markdownify Not Closing A Paragraph

### ISSUE THREAD

**Issue by MarkRosemaker** [gohugoio/hugo#11698]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.120.4-f11bca5fec2ebb3a02727fb2a5cfb08da96fd9df+extended darwin/arm64 BuildDate=2023-11-08T11:18:07Z VendorInfo=brew
</pre>

### Does this issue reproduce with the latest release?

Yes

### Description

When I use markdownify on a title and paragraph, the resulting HTML leaves the paragraph unclosed.

So using `.Page.RenderString` or `markdownify` on "# My Title\nparagraph" results in:
```html
<h1 id=\"my-title\">My Title</h1>\n<p>paragraph
```

Minimal example: https://github.com/MarkRosemaker/hugo-bug-markdownify

Draft PR with failing test: https://github.com/gohugoio/hugo/pull/11699

**Comment by jmooring** [comment]
I agree this is unexpected. However, `markdownify` assumes the string is intended to be inline, not a block, and `markdownify` does not give you the option to treat the string as a block

The [`RenderString`](https://gohugo.io/methods/page/renderstring/) method on `Page` takes an options map, so this:

```text
{{ $s := `
## Title

Text
`}}
{{ $.Page.RenderString (dict "display" "block") $s }}
```

Is rendered to:

```html
<h2 id="title">Title</h2>
<p>Text</p>
```

The `markdownify` function is effectively aliased to `.Site.Home.RenderString`, but without the ability to specify inline vs. block.

Another reason to use `RenderString` instead of `markdownify` is:
<https://github.com/gohugoio/hugo/issues/9692>

**Comment by jmooring** [comment]
Yeah, we should fix this. This works fine:

```
{{ $s := `
## Title

My list:

- item one
- item two
`}}
{{ markdownify $s }}
```

So this should too:

```text
{{ $s := `
## Title

Text
`}}
{{ markdownify $s }}
```
