### ISSUE TITLE
Remove trailing slash from void elements in internal templates

### ISSUE THREAD

**Issue by VishnuSanal** [gohugoio/hugo#11867]
### What version of Hugo are you using (`hugo version`)?

<pre>
~ $ hugo version
hugo v0.121.2+extended linux/amd64 BuildDate=unknown
</pre>

### Does this issue reproduce with the latest release?

yes

hugo generates the tags with a trailing slash & the W3C validator complains about it.

find the report of the build I tested [here](https://validator.w3.org/nu/?doc=https%3A%2F%2Fvishnusanal.github.io%2F).

should the trailing slash be removed? or am I missing something here? CMIIW!

PS: this is the same issue as #11576 & creating a new issue since that is locked.

**Comment by jmooring** [comment]
This is not related to #11576; that issue was about the `meta` "generator" element that is automatically inserted on the home page.

This issue is applicable to Hugo's internal templates: opengraph.html, schema.html, and twitter_cards.html.

But in your report, the  following items are not related to the internal templates: 2, 3, 11, and 12. Have a look at your theme's templates.

**Comment by VishnuSanal** [comment]
> This is not related to #11576; that issue was about the `meta` "generator" element that is automatically inserted on the home page.
> 
> This issue is applicable to Hugo's internal templates: opengraph.html, schema.html, and twitter_cards.html.
> 
> But in your report, the following items are not related to the internal templates: 2, 3, 11, and 12. Have a look at your theme's templates.
> 
> And the easiest way for you to address this is to override the templates. Please use the forum (https://discourse.gohugo.io/) if you need additional assistance.

well, I changed the theme & all the warnings went away! so, I presume t'was the theme that was causing the issue.

PS: sorry for the delay, got caught up with exams.
