### ISSUE TITLE
Make the server flag --renderToDisk into --renderToMemory

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#11987]
I'm doing some testing on some beefy (big) sites with the new Hugo code (one of the new features is better memory management), and I have come to the conclusion that it's stupid to have the server render to memory as a default. 

* It only makes sense on small setups.
* And even then, with fast modern disks and fast render mode, the savings is very small.
* There's also some known issues with PostCSS etc. that doesn't work well with things in memory.

I think the timing for doing this is also good, so If I don't see many convincing protests about this, I'm doing it.

/cc @jmooring

**Comment by jmooring** [comment]
This sounds like a good idea. A few thoughts/questions...

1. What if someone has configured their `publishDir` or `--destination` flag to something slow (e.g., network location)?  If that happens, will they still be able to use the `--renderToMemory` flag? It seems like we would want to keep both of the `--renderToSomething` flags, but change the default behavior.

3. We do not clear the `publishDir` when building with either `hugo` or `hugo server`. So previously published content that has since been deleted will still exist in the `publishDir`. I wouldn't think that would be a problem, but it is conceptually different from rendering to memory.

**Comment by bep** [comment]
1. I'm not sure I understand. For the server we have (ok, this isn't entirely true) only one flag in this area: `--renderToDisk`. We could make `--renderToDisk=true` the new default, but making it `--renderToMemory` will make it behave exactly like the regular `hugo` command. Not sure what having both `--renderToMemory`  and `--renderToDisk` would give, other than confusion. 
2. Yea, that's true, but one could argue that this will create less surprises, making the server build closer to the production build.

**Comment by jmooring** [comment]
For some reason I thought we already had two flags, so disregard that bit. As long as someone can run:

```text
hugo server --renderToDisk=false
```

**Comment by bep** [comment]
>hugo server --renderToDisk=false

Just to be clear, for the server command, we:

* Remove the ` --renderToDisk` flag
* Add the `--renderToMemory` flag (a flag we already have on the `hugo` command)
* The default behaviour is to always render to disk (both for the server and regular builds).

**Comment by jmooring** [comment]
LGTM.
