### ISSUE TITLE
Revert auto-capitalization of term titles

### ISSUE THREAD

**Issue by jmooring** [gohugoio/hugo#12115]
This front matter:

```text
tags = ['tag-a','tag-b']
```

Produces this taxonomy page:

![image](https://github.com/gohugoio/hugo/assets/335669/7fd9b853-165a-4adf-9ae0-30da4ff1cec8)

And this term page:

![image](https://github.com/gohugoio/hugo/assets/335669/92829f34-90ef-4d7e-bbdf-75ab29f3fca0)

#### Alternative 1

You can change your templates from this:

```text
{{ range .Pages }}
  <h2><a href="{{ .RelPermalink }}">{{ .LinkTitle }}</a></h2>
{{ end }}
```

to this:

```text
{{ range .Pages }}
  <h2><a href="{{ .RelPermalink }}">{{ .Data.Term }}</a></h2>
{{ end }}
```

...but that means you need one or two more templates to handle these page kinds.

#### Alternative 2

Do this in your site configuration...

```
titleCaseStyle = 'none'
```

...but that affects how the `strings.Title` function behaves as well.

#### Alternative 3

Create a term page for every term and set the title to whatever you want...

```text
hugo new content tags/foo/_index.md
```

...but you have to do that for every term.

**Comment by bep** [comment]
<img width="202" alt="image" src="https://github.com/gohugoio/hugo/assets/394382/016299ae-f9dd-453b-af7f-ee8e1fe36b22">

What's wrong with the above? And why is the alternative better?

**Comment by LorenDB** [comment]
As the original reporter of this issue on the Hugo forum, I'll chime in here.

> What's wrong with the above? And why is the alternative better?

I personally like having my tags rendered in lowercase, so I wrote them as lowercase in my YAML front matter. When I look at my [tags page](https://lorendb.dev/tags), now I see some tags like `Ksp2`. This is clearly incorrect, since KSP2 is an abbreviation for Kerbal Space Program 2. With this update, I'm forced to either uppercase tags like `ksp2` or use a hacky workaround that may break other parts of my site.

I think auto-capitalizing things like this is also a bad idea in general. When I write text, I assume that it will be rendered without changes to its case, so if I write `tags = ["foo", "bar", "ksp2"]`, I intend for them to be rendered in all lowercase.

**Comment by bep** [comment]
OK, that's fine then (but I'm not doing the code work for this one :-))

**Comment by jmooring** [comment]
I understand that we are also auto-capitalizing automatic section pages titles, but conceptually (from a content author's standpoint) section titles and terms are different things. There's also demand for disabling auto-capitalization of automatic section page titles:

#9793

We could do something like that instead, letting it apply to section, term, and taxonomy pages.
