### ISSUE TITLE
404 page treated as paginated

### ISSUE THREAD

**Issue by earthboundkid** [gohugoio/hugo#12192]
Building my site with Hugo 0.123.7 results in a /404/ directory being created with 99 entries, as though it were paginated.

See #12174.

### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.123.7-312735366b20d64bd61bff8627f593749f86c964+extended darwin/arm64 BuildDate=2024-03-01T16:16:06Z VendorInfo=brew
</pre>

### Does this issue reproduce with the latest release?

Yes.

**Comment by jmooring** [comment]
I have no idea how to reproduce this. Can you please provide an example?

**Comment by earthboundkid** [comment]
Clone https://github.com/spotlightpa/poor-richard. Run yarn. Run `hugo`. Look at the /404/ directory.

**Comment by jmooring** [comment]
1\) [`layouts/_default/baseof.html`](https://github.com/spotlightpa/poor-richard/blob/master/layouts/_default/baseof.html#L12) calls [`layouts/partials/helper/paginator.html`](https://github.com/spotlightpa/poor-richard/blob/master/layouts/partials/helper/paginator.html).

2\) [`layouts/partials/helper/paginator.html`](https://github.com/spotlightpa/poor-richard/blob/master/layouts/partials/helper/paginator.html#L7) paginates if `Page.IsNode` is `true`.

3\) `Page.IsNode` is `true` for page kind `404`. It has been that way since v0.54.0 (maybe earlier). Whether the return value makes sense is debatable; see #12162.

So, the partial says, "Paginate this thing,"  which obviously doesn't make any sense for a 404 page. We'll get to why things changed in a minute, but you should exclude page kind `404` from pagination by changing this:

```text
{{ if .IsNode }}
```

To this:

```text
{{ if and .IsNode (ne .Kind "404") }}
```

4\) This should have been happening with v0.122.0 and earlier. Why wasn't it?

- In both versions the `.Pages` collection passed into the 404 template seems to be equivalent to `Site.Pages`. I don't understand why the 404 template needs a `.Pages` collection, but that's another topic. The fact that there _is_ a `Pages` collection means the the `Paginator` method can act upon something.
- In v0.122.0 and earlier, calling the `Paginator` method within a 404 template didn't do anything. Now it does.

It looks like we fixed (either directly or indirectly) the `Paginator` method in v0.123.0 when called from the 404 template, and that change exposed the conditional logic problem in the partial.

**Comment by earthboundkid** [comment]
Okay, sounds like this one can be closed. I will take a look Monday.
