### ISSUE TITLE
Upgrade to 1.123.0+: Preview overwrites `public/` directory

### ISSUE THREAD

**Issue by gmantele** [gohugoio/hugo#12220]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.123.0-3c8a4713908e48e6523f058ca126710397aa4ed5+extended linux/amd64 BuildDate=2024-02-19T16:32:38Z VendorInfo=gohugoio
</pre>

### Does this issue reproduce with the latest release?

Yes

-----

When migrating from v1.121.2 to v.123.x, publication with `hugo` command works very well, but then, when doing `hugo server --watch --port 1313 -DEF --printI18nWarnings` the preview version overwrites the content of `public/` (previously returned by the `hugo` command). **This means that all URL are all wrong (mainly because using the port 1313) and that all drafts are published in production (which is kind of dangerous).** Fortunately, I noticed that very quickly.

I did not have this issue with v1.122.0. It just started with v1.123.0 and is still there with v1.123.8.

I noticed that before 1.123.x, the server mode always served pages from memory, but now the default mode seems to be from disk. I assume that's why I got this unexpected behavior now.

I succeeded to avoid this problem with 2 solutions:

1. Add option `--renderToMemory` ; but since this service is running all the time and that content will continue to grow, I do not want to spoil memory resources on this server which is already used for many other things
2. Set `-d something-else-than-public` ; I will probably choose this option for the longer term.

Anyway, it would certainly worth it to write this quite important change in the change log of v1.123.0. I have not found it, but maybe I've missed it (it was a long and technical changelog).

-----

And finally, I also wanted to thank you very much for this amazing tool that Hugo is :tada:  It offers so much freedom in customization of our website, for the production version, but also for the development/preview/server one (which has some differences, including links to internal documentation and few other things for website editors).

**Comment by jmooring** [comment]
The release notes for v0.123.0 contains this:

![image](https://github.com/gohugoio/hugo/assets/335669/c2da5409-bc43-4d9d-a862-38081af49f74)

If you follow the breaking changes link...

![image](https://github.com/gohugoio/hugo/assets/335669/c5e3494f-9ceb-4367-89cf-469f43060e6e)

Which brings you to <https://github.com/gohugoio/hugo/issues/11987>.

I'm sorry we broke your workflow, but this was an intentional breaking change. In addition to the alternatives you mentioned, you can also just clear you public directory before publishing your production site. In CI/CD workflows that happens by default.

**Comment by gmantele** [comment]
Ok. I read that very quickly. I did not expect this message would mean that by default the server would run from disk. I should have been more careful. Thank you for your time to explain me this.
