### ISSUE TITLE
Site build fails if frontmatter contains "videos" parameter 

### ISSUE THREAD

**Issue by timbrock** [gohugoio/hugo#12391]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.125.1-68c5ad638c2072969e47262926b912e80fd71a77+extended linux/amd64 BuildDate=2024-04-18T08:21:19Z VendorInfo=snap:0.125.1
</pre>

### Does this issue reproduce with the latest release?
Yes

----
Updated to version 0.125.0 (from 0.124.1) and `hugo server` started failing:

``` sh
Error: error building site: render: failed to render pages: render of "section" failed: "some/file/path" execute of template failed: template: _default/community.html:5:4: executing "_default/community.html" at <partial "head.html" .>: error calling partial: execute of template failed: template: _internal/opengraph.html:50:46: executing "_internal/opengraph.html" at <absURL>: error calling absURL: unable to cast map[string]interface {}{"title":"Some title", "url":"some url"} of type map[string]interface {} to string
```

After experimenting, this issues seems to arise from the fact we have a parameter in the yaml front matter of our community page called "videos". Changing it to "video", "videoos" etc and the problem goes away. After finding this I searched the repo for "videos" and found [this](https://github.com/gohugoio/hugo/blob/d88cb5269afcf1e3e9530cc11c23cafe94616694/docs/content/en/templates/internal.md?plain=1#L135).

```
images = ["post-cover.png"]
audio = []
videos = []
series = []
tags = []
```
So I tried calling the parameter "audio" and "images" and they both failed (though I don't know whether this is new or not). Has "videos" become a reserved word in 0.125.x?

**Comment by jmooring** [comment]
To confirm, your front matter has something like this?

```text
[[videos]]
title = 'foo'
url = 'foo.mp4'
[[videos]]
title = 'bar'
url = 'bar.mp4'
```

**Comment by timbrock** [comment]
> To confirm, your front matter has something like this?

We're using YAML so it has something like this:
``` yml
videos: 
  - url: "https://www.youtube.com/watch?v=Hv3obL9HqyY"
    title: "Official Hugo trailer"
  - url: "https://www.youtube.com/watch?v=olvtV9zE-yw"
    title: "The Matrix Reloaded official trailer"
```

> If you want to continue to render Open Graph meta elements without changing your front matter...

Thanks! I think we're fine to just change the field name since it is only an issue in one place.

But I think the real issue here, please correct me if I've misunderstood, is that 0.125.x seems to have silently ([there's nothing here](https://gohugo.io/content-management/front-matter/#fields)) introduced new reserved words, that can break builds that used to work.

**Comment by jmooring** [comment]
This is the change in v0.125.0 that caused your build to fail: <https://github.com/gohugoio/hugo/pull/12335>.

We fixed a bug. Previously, if you passed a something like a map to the `absURL` template function, it would return an empty string and silently fail. With v0.125.0 and later we correctly throw an error.

The [embedded opengraph template](https://github.com/gohugoio/hugo/blob/master/tpl/tplimpl/embedded/templates/opengraph.html) has, for many years, expected `videos` in front matter to be a slice of strings, not a map. The difference is that now it throws an error (due to the bug fix) if it's not a slice of strings, which is a good thing. In your scenario, prior to v0.125.0, your HTML looked like this:

```html
<meta property="og:video" content="" />
<meta property="og:video" content="" />
```

Which is clearly wrong.

The [embedded opengraph template](https://github.com/gohugoio/hugo/blob/master/tpl/tplimpl/embedded/templates/opengraph.html) accesses a number of front matter fields, some of which are reserved (e.g., `title`, `description`) and some of which are user-defined parameters (e.g., `audio`, `images`, `videos`).

So `videos` is not and never has been a reserved word, but the embedded opengraph template expects it to be a slice of strings. This is documented here: <https://gohugo.io/templates/embedded/#configure-open-graph>

But we should find a way to document these "expected" user-defined parameters [here](https://gohugo.io/content-management/front-matter/) as well. See <https://github.com/gohugoio/hugoDocs/issues/2536>.

**Comment by timbrock** [comment]
I see (I think). Thanks for taking the time to explain.
