### ISSUE TITLE
why Extra newlines added after render image hook 

### ISSUE THREAD

**Issue by toyo2333** [gohugoio/hugo#12738]
there are the contents in render-image.html

```
{{ if site.Params.replacefunc.enable }}
    {{ if hugo.IsServer }}
<p class="md__image">
    <img src='{{ .Destination | safeURL }}' alt="{{ .Text }}" {{ with .Title }} title="{{ . }}" {{ end }} />
</p>
    {{ else }}
        {{ $image_ext := replaceRE ".*\\.([^.]+)$" "$1" .Destination }}
        {{ if in site.Params.replacefunc.convertTypeList (lower $image_ext) }}
            {{ $img_abs_src := "" }}

			{{ some logic code }}
			{{ some logic code }}
			{{ some logic code }}
			{{ some logic code }}
			{{ some logic code }}

<p class="md__image">
    <img src='{{ $img_abs_src| safeURL }}' alt="{{ .Text }}" {{ with .Title }} title="{{ . }}" {{ end }} />
</p>
        {{ else }}
<p class="md__image">
    <img src='{{ .Destination | safeURL }}' alt="{{ .Text }}" {{ with .Title }} title="{{ . }}" {{ end }} />
</p>
        {{ end }}
    {{ end }}
{{ else }}
<p class="md__image">
    <img src='{{ .Destination | safeURL }}' alt="{{ .Text }}" {{ with .Title }} title="{{ . }}" {{ end }} />
</p>
{{ end }}
```

![bughook](https://github.com/user-attachments/assets/e350ed6f-970d-4aa9-9e12-f1a8e407bf1f)

hugo version : 0.131.0

**Comment by bep** [comment]
Thanks for getting in touch, but it feels like this is a question  that would be better suited to the [Hugo Discussion Forum](https://discourse.gohugo.io/).  We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug. You may also find the answers you search for in [Hugo Documentation](http://gohugo.io/overview/introduction/).
