### ISSUE TITLE
Next/NextInSection and Prev/PrevInSection are flipped?

### ISSUE THREAD

**Issue by simonm3** [gohugoio/hugo#12776]
This was previously reported as issue  #9158 and apparently closed as resolved. However it is clearly not resolved.

I  have a contents page which sorts things in order of the page weight. I would expect the next page to be the next one in the contents but it isn't it is the previous one; and vice versa.

Even the docs say
> The behavior of the PrevInSection and NextInSection methods on a Page object is probably the reverse of what you expect.

Surely the intuitive thing is to behave as people expect rather than putting such a comment in the docs?

**Comment by bep** [comment]
I have had this issue reported ... 100s of times before, which is why that line is in the documentation. I can add that that the original implementation went in the other direction (the way you want it), but that was reported as a bug, I agreed, and we spent 100 hours on a deprecation cycle to change the meaning. The odds of us doing that again now, with even some more thousands of Hugo sites in the wild is ... close to zero, so I'm closing this issue.

The current behaviour comes from Hugo's default page sort when no weight is set: Date descending (newest first), so _next_ goes correctly to the _next_ when you look at it sorted from newest to oldest, but it goes back in time.

Anyhow, even if we wanted to (I don't), we cannot change this. 

You can use https://gohugo.io/methods/page/next/ instead if you want.

**Comment by simonm3** [comment]
Thanks for the reply. I can understand why you don't want to change the
default as this would be an issue for existing sites. Have you considered
having a config setting for the sort order? There are many circumstances
where you might want it to work differently e.g. if you have a table of
contents for a book or topic that is sorted by weight. And it seems odd to
have something in the docs that saying it acts in an unexpected way.

**Comment by bep** [comment]
@simonm3 see https://gohugo.io/methods/pages/next/

**Comment by bep** [comment]
https://gohugo.io/getting-started/configuration/#configure-page
