### ISSUE TITLE
`:slugorfilename` drops the `.html` extension if `.File.BaseFileName` contains a period for permalinks defined in url

### ISSUE THREAD

**Issue by dvdksn** [gohugoio/hugo#12845]
I recently started using the permalink tokens feature to rewrite the URLs of one of our site's sections. I'm using it to strip out the top-level section. For example: `/foo/bar/baz.md` becomes `/bar/baz.html`.

I am using the following cascade config to achieve it:

https://github.com/docker/docs/blob/c7dd62c5ab46ee0527f024272617080f44d190ed/content/manuals/_index.md?plain=1#L7-L9

But [then I noticed](https://github.com/docker/docs/pull/20820) that `:slugorfilename` seems to remove the `.html` extension of the pages in the outputdir if the content files contain a `.`

For example:

- Given a source file at `/foo/bar/baz.1.md`
- With a url config `/:sections[1:]/:slugorfilename`
- Would render the output to `public/bar/baz.1`

### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.134.1+extended darwin/arm64 BuildDate=2024-09-05T10:17:50Z VendorInfo=brew
</pre>

### Does this issue reproduce with the latest release?
yes

**Comment by bep** [comment]
I'm not sure about this one. This is how `url` in front matter has behaved since, I guess, forever. Any extension (including `1`) in the `url` is taken as is; we don't add one if it's not there. This is a feature, not a bug. If you put your permalinks config in `hugo.toml` then you don't have this restriction, not sure if that works for you. But we cannot change the behaviour of `url`.

**Comment by dvdksn** [comment]
@bep thanks, yeah I wasn't sure if this would be considered a bug. I'll see if I can add this to hugo.yaml. For now I simply removed the dots from the source filenames. Thanks!
