### ISSUE TITLE
Outdated apt package

### ISSUE THREAD

**Issue by whatthesamuel** [gohugoio/hugo#13105]
The Debian apt package of Hugo is pretty outdated (0.123.7) compared to the latest release of the git repository (0.139.3 as of writing this issue). Sure, building from source can be one solution, but a lot of people would prefer to just use the single-line command. It would be nice if the package would be updated.

![image](https://github.com/user-attachments/assets/1e06b6f0-6bee-48db-8ba2-c97e84099054)

**Comment by anthonyfok** [comment]
Hi @whatthesamuel,

The latest Debian .deb package for Hugo is at 0.131.0, though admittedly I have had been super busy with real life and haven't made any updates for 3 months.  Hope I'll have more time in January 2025.

The Hugo version 0.123.7 that you are using looks like it is from Ubuntu or its derivatives, namely Ubuntu 24.04 LTS (noble) according to https://packages.ubuntu.com/search?keywords=hugo, and no, unfortunately, the Hugo version in a Ubuntu stable release won't get updated to a newer version unless there is a backport from newer Ubuntu releases, which AFAIK no one is doing right now.

Best regards,
Anthony

**Comment by jmooring** [comment]
The package repository for any Linux distribution seldom contains the latest version of _any_ application, which is why we include this notice in our [documentation](https://gohugo.io/installation/linux/#repository-packages):

![image](https://github.com/user-attachments/assets/7f282d28-59b5-4590-a9ca-fe2939bc64af)

With a virgin installation of Debian 12.8 (Bookworm) this works great:

```text
sudo apt update
sudo apt install snapd
sudo snap install hugo
hugo version
```

> hugo v0.111.3+extended linux/amd64 BuildDate=2023-03-16T08:41:31Z VendorInfo=debian:0.111.3-1

The version available in the Snap Store will be current within a few hours of each release, and unless you pin the current version, your local installation will be automatically updated.

More information about installing snap on Debian here:
<https://snapcraft.io/docs/installing-snap-on-debian>
