### ISSUE TITLE
Please treat tags as immutable.

### ISSUE THREAD

**Issue by omenos** [gohugoio/hugo#13121]
It isn't the first time this has happened, and in the past it was due to CI errors. But please don't treat Git tags as transient or mutable refs. It reduces trust in the project if a version tag moves from one commit to another.

![image](https://github.com/user-attachments/assets/b3a4a9ae-599d-46fc-b553-671f0146ac93)

Aside: *I do understand this instance was just moving one commit forward in the branch. But without manually checking the commit log it's impossible to tell this at a glance. With all this said, cutting a release that fires off a notification also wouldn't be the smartest move for a threat actor.*

**Comment by bep** [comment]
Yea, well, mistakes happens. And the removal of the tags instead of creating a new release usually boils down to time/cost. And I would say that this is the first time since we switched from Goreleaser (which creates and pushes the tag as the first step) to Hugoreleaser.

Also, in general, I would not trust something to be immutable when it's not. GitHub should have made tags immutable, but I guess that train has left the station.

**Comment by omenos** [comment]
> Also, in general, I would not trust something to be immutable when it's not. GitHub should have made tags immutable

Wholeheartedly agree.

> but I guess that train has left the station.

Not completely. Like most forges, there are features to enforce protection policies on a per-repository basis. For GitHub, this is the [rulesets](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-rulesets/about-rulesets) feature. I wish they were configured by default, but it is what it is.

**Comment by bep** [comment]
>I wish they were configured by default, but it is what it is.

Sure, but if something can be turned off it cannot be trusted in general
