### ISSUE TITLE
error instead of quiet logging when no layout can be found

### ISSUE THREAD

**Issue by jmhodges** [gohugoio/hugo#1313]
Was porting my site from jekyll to hugo, and hadn't written a layout for my posts section yet when I copied over my articles. Hugo silently elides pages without a layout instead of erroring vocally or exiting early. My site "worked" but had no pages in it.

It would be nice for it to error out and make a lot of noise (or, at least, make a lot of noise) when it can't find a layout.

Relevant code is in [hugolib/site.go](https://github.com/spf13/hugo/blob/252ea96d1d359b485bae489327a8219d102f0607/hugolib/site.go#L1484).

**Comment by jmhodges** [comment]
(I eventually happened on --log and dug into the log file, but I could see how folks wouldn't get that far.)

**Comment by lebarde** [comment]
1. I don't know how to reproduce that because when I don't set any layout this throws no warning.
2. A workaround would be to throw an error, **but** to say that you can set a `AllowEmptyLayout` variable in the config, if you really want this. I don't see how to manage that without one more variable if it is useful for some people not to have any layout defined.

We could have something like this:

```go
// in hugolib/site.go :
func (s *Site) renderForLayouts(name string, d interface{}, w io.Writer, layouts ...string) error {
	layout, found := s.findFirstLayout(layouts...)
	// user have to define a layout, unless params.AllowEmptyLayout is set to true.
	if found == false && viper.GetBool("AllowEmptyLayout") == false {
		jww.ERROR.Printf("Unable to locate layout for %s: %s. Please set a layout or AllowEmptyLayout to true in your config file if you really want this.\n", name, layouts)
		return nil
	}

	if err := s.renderThing(d, layout, w); err != nil {
[…]
```

**Comment by bep** [comment]
* There is currently WARNING logging when a layout is missing
* I merged a patch that upped this to ERROR
* Then the CI build for the Hugo docs failed because of missing `404.html` template
* So I added a `404.html` template ...
* But then a lot of the themes on the themes site started to fail ... 
* So I reverted the change to avoid havoc in the wild

So any fix to this must have some sense of what templates are vital to render a site:

* A template for page
* A template for home page
* more? I think the above should cover the important stuff and help people in this thread.

**Comment by lebarde** [comment]
Thank you for your explanation. But maybe that WARN message is acceptable?

**Comment by tj** [comment]
👍 I have -v and --log enabled and I get no error or warning for blank pages that are rendered. It would be really helpful to see what Hugo is trying to resolve to.
