### ISSUE TITLE
Strange behaviour when using `hugo new theme test`

### ISSUE THREAD

**Issue by PipeItToDevNull** [gohugoio/hugo#13160]
Using the latest versions of Hugo I am attempting to setup a basic skeleton theme but I am being blocked by behaviors that I cannot wrap my head around. 

Running the following results in the site being served out of the theme directory:

```
hugo new site testSite
cd testSite
hugo new theme testTheme
echo "theme = 'testTheme'" >> hugo.toml
hugo server
```

```
 ls themes/testTheme/content/posts 
_index.md post-1.md post-2.md post-3
```

I see references to this being by design? #11373 and #11367

I see no official documentation about how a new theme should be designed, but putting content into the theme directory and serving directly from it seems incredibly bizarre to me.

**Comment by Whickey344** [comment]
I'm not sure what going on or what to do I don't understand. So please explain to me what I'm doing wrong I came on this app to get help in receiving my money so I need help in doing so. If I cause any problems sorry I need to contact support

**Comment by willfaught** [comment]
What is the issue? What did you expect, and what happened instead? The output file structure looks OK to me, aside from the useless content files in the theme.

**Comment by jmooring** [comment]
Historically `hugo new site` and `hugo new theme` created directory structures only; neither one created a functional example. The lack of functionality was a source of complaints from some of our new users who felt they were hitting a dead end.

In v0.118.0 we changed `hugo new theme` so that it creates demonstrative templates and sample content. That means new users can do this...

```text
hugo new site foo
cd foo
hugo new theme mytheme
echo "theme = 'mytheme'" >> hugo.toml
hugo server
```

...and have a functional site.

There's more information about the v0.118.0 change here:
<https://discourse.gohugo.io/t/creating-new-site-and-theme-skeletons-with-v0-118-0-and-later/46018>

If you want to create a new theme with no templates, assets, or content:

```text
mkdir -p mytheme/{archetypes,assets,content,data,i18n,layouts,static}
```

We may improve on this in the future. See <https://github.com/gohugoio/hugo/issues/11373>.
