### ISSUE TITLE
in function not working properly for JSON array

### ISSUE THREAD

**Issue by jmarente** [gohugoio/hugo#1468]
I'm having the following issue with "in" function when I use it with a JSON array.

This works:

```
{{ $array := (seq 1 10) }}
{{ in $array 7 }} => true
{{ in $array 12 }} => false
```

Having the following JSON:

```
{
    "array": [1,2,3,4,5,6,7,8,9,10]
}
```

This doesn't:

```
{{ $json_content := getJSON "path/to/json" }}
{{ in $json_content.array 7 }} => false
{{ in $json_content.array 12 }} => false
```

I have tried different things and I always get the same result.

**Comment by bep** [comment]
Probably a type mismatch (int vs int64), not sure what to do about that in this case.

@tatsushid any idea?

**Comment by tatsushid** [comment]
@bep, yes, as you mentioned, it is caused by a type mismatch but not `int64` vs `int` but `float64` and `int`!

According to the go official document about [encoding/json](https://golang.org/pkg/encoding/json/), JSON is unmarshaled any number values into `float64` when `interface{}` type value is passed as a container.

Which is the best introducing a something container struct at reading JSON to add special unmarshaler for `int` value or fix all template functions (includes `in`) to compare any numbers in `float` type? I prefer the former one.

**Comment by bep** [comment]
>Which is the best introducing a something container struct at reading JSON to add special unmarshaler for int value or fix all template functions (includes in) to compare any numbers in float type? I prefer the former one.

@tatsushid It would be totally preferred if this could be solved in one place.

**Comment by tatsushid** [comment]
I wrote a JSON unmarshal sample code https://play.golang.org/p/5Dyk4CvhoI. `json.Decorder` has `UseNumber()` method not to convert a number value to `float64` value but to just save it as `json.Number`. We can convert `json.Number` value to `int64` or `float64` as we like later.

The sample expands JSON element tree with `json.Number` to the one without `json.Number` not to break current behavior in other area in Hugo. It's not efficient but I can't find out the way to do it in parsing JSON.

What do you think? If it looks good, I will implement it around JSON parser in Hugo.

**Comment by bep** [comment]
@tatsushid looks fine to me. I'll gladly trade a slight performance hit in this area in favor of consistent behavior.

**Comment by bep** [comment]
**Note/Update:** This issue is marked as stale, and I may have said something earlier about "opening a thread on the discussion forum". Please don't.

If this is a **bug** and you can still reproduce this error on the latest <code>release</code> or the <code>master</code> branch, please reply with all of the information you have about it in order to keep the issue open.

If this is a **feature request**, and you feel that it is still relevant and valuable, please tell us why.

**Comment by bep** [comment]
@moorereason is this fixed?

**Comment by moorereason** [comment]
No, here's a failing test:

```go
{[]float64{1, 2, 3}, 1, true},
```

My recent updates have been in `Union` and `Intersect`, not `In`.

**Comment by bep** [comment]
The slow path to perfection ... :-)
