### ISSUE TITLE
Generated layout/404.html uses relative paths

### ISSUE THREAD

**Issue by SvenDowideit** [gohugoio/hugo#1555]
we have the following in out `config.toml`

```
canonifyurls = false
relativeURLs = true
```

which allows us to move generated docs around. 

However, when using s3's 404 document setting to point to the hugo generated html, the relative paths break. This is extremely obvious because the css and js can't be found, but the links also don't work. (s3 leaves the URL as is, and sends the 404.html file's content)

IDK if this is a good solution to this, but i can hope :)

hard coding the url's to use `<link rel="shortcut icon" href="{{ .Site.BaseURL }}images/favicon.png" type="image/png">` only helps if there is no other generated content, like menus.

**Comment by bep** [comment]
Do we generate a 404 layout? And if we do, couldn't you create your own template?

**Comment by SvenDowideit** [comment]
yes, you make your own template, but you cannot reuse any common elements that include a url - including the hugo generated menu.

painful.

**Comment by bep** [comment]
@moorereason do you have any idea what this is about, practically speaking?

**Comment by moorereason** [comment]
I still need to look at it, but my understanding is that the 404 page can be sent by the server from any location (doesn't redirect to /404.html).  With the config mentioned in the OP, the links don't work when you get a 404 in /some/subdir/path/.  It sounds like the 404 template needs to always use absolute paths regardless of the site config.

**Comment by SvenDowideit** [comment]
yup - that's exactly right @moorereason

**Comment by bep** [comment]
I see no movement on this, so I'll push it to Hugo 0.20.

**Comment by waddlesplash** [comment]
This is still around and pretty annoying to have to work around, fwiw.

**Comment by waddlesplash** [comment]
Yes, this is still an issue as far as I can tell.

**Comment by jimist** [comment]
The http handler used in hugo returns a default text on not found based on [this](https://github.com/golang/go/blob/master/src/net/http/server.go#L2359).

If I'm not mistaken a special handler should be here like gorilla mux's **NotFoundHandler** to return 404 layouts on other pages.

Is there any plan for doing this? I'm open to help If accepted.

**Comment by ptgott** [comment]
I did a little bit of digging into this and wanted to make sure I understand the issue.

Here's an integration test I added to **hugolib/404_test.go** that is passing now but I would like to make fail in order to reproduce the issue:

```go
// Issue 1555
func Test404WithRelativePaths(t *testing.T) {
	b := newTestSitesBuilder(t).WithSimpleConfigFileAndSettings(
		map[string]interface{}{
			"canonifyurls": false,
			"relativeURLs": true,
		},
	).WithTemplates("404.html", `<menu><ul>
{{ range .Site.Menus.main }}
<li>{{.Page.RelPermalink}}</li>
{{ end }}
</ul></menu>
`).WithContent("blog/post1.md",
		`---
title: "Post 1"
menu: "main"
---
`,
		"blog/post2.md",
		`---
title: "Post 2"
menu: "main"
---
`,
		"blog/post3.md",
		`---
title: "Post 3"
menu: "main"
---
`)

	b.Build(BuildCfg{})

	b.AssertFileContent("public/404.html", `<menu><ul>

<li>/blog/post1/</li>

<li>/blog/post2/</li>

<li>/blog/post3/</li>

</ul></menu>
`)
}
```

In the 404 page expected by this test, link URLs are relative but use [absolute URL paths](https://datatracker.ietf.org/doc/html/rfc1808#section-2.2), meaning that each path will [replace](https://datatracker.ietf.org/doc/html/rfc1808#section-4) the entire URL path of the current page rather than just the last segment. In other words, no matter what base URL the 404 page has, each menu item will still load as expected. Hugo is currently producing these URLs, and the test passes.

It looks like Hugo generates relative URLs with relative URL _paths_ (i.e., without a `/` prefix) when a path begins with `..` (see the [docs](https://gohugo.io/content-management/urls/#relative-urls)). But since custom 404 pages are placed [at the root](https://gohugo.io/templates/404/) of the destination file system, no resource would be at a directory level above the custom 404 page, so there would be no need to use the `..` syntax (at least as far as I can tell).

Any ideas for how to get this test to fail? Thanks!

**Comment by jmooring** [comment]
@ptgott Make sure this is something you actually want spend time on. See: https://github.com/gohugoio/hugo/issues/8924#issuecomment-904765323

**Comment by ptgott** [comment]
@jmooring Thanks for the heads up. I wanted to check whether there's still a risk for unexpected relative URL path resolution in 404 pages (e.g., related to the S3-specific issue flagged above). If there is, that may be something we would need to address while consolidating page types.

**Comment by billziss-gh** [comment]
FYI, the following hackfix resolves the problem described in the OP for me:

```diff
diff --git a/hugolib/site_render.go b/hugolib/site_render.go
index 77ece780..db51922f 100644
--- a/hugolib/site_render.go
+++ b/hugolib/site_render.go
@@ -256,6 +256,12 @@ func (s *Site) render404() error {
                return errors.New("failed to create targetPath for 404 page")
        }

+       relativeURLs := s.Info.relativeURLs
+       s.Info.relativeURLs = false
+       defer func() {
+               s.Info.relativeURLs = relativeURLs
+       }()
+
        return s.renderAndWritePage(&s.PathSpec.ProcessingStats.Pages, "404 page", targetPath, p, templ)
 }
```

**Comment by jmooring** [comment]
A lot has changed since this issue was opened 8 years ago. Today, the only reason to set `relativeURLs` to `true` is if you are creating a serverless site, navigable via the file system. This is documented here:

<https://gohugo.io/content-management/urls/#relative-urls>
