### ISSUE TITLE
Static comment injector

### ISSUE THREAD

**Issue by bbalet** [gohugoio/hugo#160]
While many goes to disqus to add comments to their blogs, I prefer having a static comment generator for my static websites written with Jekyll. The pros:
- Comments are included into the actual HTML content so they can improve it and have an impact on SEO.
- I don't know if disqus will last long or if one day they will decide to inject unsolicited content via their comments widget.

The cons: many, but I don't care.

On this website [0] dedicated to golang, I implemented this approach with Jekyll. Here an example of a post with comments [1]. The workflow is as follow :
- The visitor fills the comment form and struggle to understand what the hell is written into the recaptcha image.
- After many unsuccessful tries the visitor either give up or manage to submit the comment by asking me to indulge myself in acts reproved by moral.
- My Jekyll content includes a PHP script that prepares a file containing the comment and it sends me an e-mail notification with the comment file attached.
- The comment filename starts by a UNIX timestamp (for sorting purposes). It contains a YAML field indicating to which post it is related to.
- If I approve the comment, I copy it into a _comment folder and it will be merged to the content next time my website is generated.

What do you think about this enhancement request?

[0] http://decouvrir-golang.net/
[1] http://decouvrir-golang.net/golang/package/compress/gzip/compresser-les-reponses-http-golang.html

**Comment by michaelsync** [comment]
I started this thread http://discuss.gohugo.io/t/static-comment-for-hugo/1944  in hugo discussion before I saw this post. 

Kaiju looks great but it doesn't let us to create the static comments instead of loading them from the 3rd-party service. 

Comment Migration: We can import the existing comment to Disqus or etc. but we need to have the JS code that load the comments from 3rd-party service. It's the cost to the performance. Plus, it allows 3rd-party provider to load what they want to load along with our comment feeds. For example: Disqus load the related comments by default. Would it be better if we can import the comment to Hugo and generates the static file?  

Search (read only) : I don't search the comment much but if we need to support it, any search engine that can search the static HTML should be able to search the static comment as well. 

Commenting (public write) : We can let the blog owner to decide whether they want to do a simple 'email to comments' (https://caurea.org/2012/03/31/this-blog-has-comments-again.html) or just have a custom form that loads nothing but can send the comment to the server. 

Edit (private write) : We can use the same approach as "Commenting"  but I don't mind sacrificing this feature. 

According to this post http://discuss.gohugo.io/t/using-for-plugins-in-hugo/1239, @spf13 said that Hugo 0.13 was rewritten to add internal support for handlers based on filetype.

Is it possible for us to create a plug in that can generate the comments and expose some Api for themes to use? I wrote more details about this idea in my original post http://discuss.gohugo.io/t/static-comment-for-hugo/1944 . 

Thanks!
