### ISSUE TITLE
ENH: custom markdown processor

### ISSUE THREAD

**Issue by sglyon** [gohugoio/hugo#234]
I love how easy Hugo makes it to organize and display my content.

I am used to using pandoc to convert my markdown to various formats and would love to use it within Hugo. Is there any way we could shell out to a custom markdown processor within Hugo?

I realize that this might defeat a lot of the speed gains we get by using Hugo, but it would also add some flexibility for those who are willing to sacrifice a little performance.

**Comment by OJFord** [comment]
This would be fantastic; I think it's worth pointing out that markdown isn't any one Markdown^TM - there must be hundreds of variations that build on the basic Gruber syntax.

Pandoc is probably the most versatile (?) implementation in both the senses that 'pandoc markdown' permits a larger syntax (code, tables, amsmath) than anything else I've seen - but also that it's completely customisable. You can start with `markdown_strict` (as it calls it) and add features to it.

Anything else isn't saying so much "you can create content in markdown" as it is "you can create content in *this* markdown".

I think a really nice solution would be to have a config file something like:
```ini
[renderers]
    mymarkdown = pandoc --options
    latex = pandoc --different-options
    myownlanguage = sometooliwrote
```
and then being able to run `hugo --use-mymarkdown` et al.

**Comment by OJFord** [comment]
Also in Pandoc's favour - [the workaround for using `_` in math](https://gohugo.io/tutorials/mathjax/) in Hugo's markdown (to have it not begin emphasis) is absurd, and should be considered a bug.

Wrap my `$$` in `<div>` so it's rendered verbatim? Pandoc doesn't need that, it knows what to do if `tex_math_dollars` are enabled (they are in default pandoc markdown, or else it's `--from=markdown_strict+tex_math_dollars`).

**Comment by kebno** [comment]
👍

**Comment by Vonng** [comment]
It's a pity that hugo needs workaround on handling math blocks.
 `<div>` and  ``  doesn't needed on other markdown editors (Typora, MWeb,....) or render(pandoc).  Lots of math content broke and needs another converter before working around with hugo. 
 
If hugo can't handle this properly, at least there's could be a switch that disable `_` `\` interpretation during markdown processing.

**Comment by lsaravia** [comment]
So it is no easy way to add pandoc? could you point out where have to make the changes? because it seems that the only solution to use heavy math is by using pandoc.

**Comment by sjcjoosten** [comment]
Seems that #4060 is about to fix this issue in 'a couple of days'.

**Comment by kaushalmodi** [comment]
@OJFord @Vonng @Isaravia Can you provide example heavy math content? I am the maintainer of Org to Hugo exporter for Emacs (ox-hugo), and would like to see if those math examples get exported fine using the Org flow.

**Comment by kaushalmodi** [comment]
@OJFord @Vonng @lsaravia Can you provide example heavy math content? I am the maintainer of Org to Hugo exporter for Emacs (ox-hugo), and would like to see if those math examples get exported fine using the Org flow.

**Comment by lsaravia** [comment]
I don't remember exactly because I switched to Jekyll,  but I guess that this markdown is a good example <https://github.com/lsaravia/MultifractalsInR/blob/master/Curso3.md>

**Comment by kaushalmodi** [comment]
@lsaravia Thanks! That example post worked just fine with my flow :)

[Org source][1] -> [Exported Hugo-compatible Markdown][2] -> [Hugo generated HTML][3]

[1]: https://github.com/kaushalmodi/ox-hugo/commit/3b34bae5174bc4718351a4d173e07d35f940d836#diff-6fa190cf16cc1fe9ba0fa6673ddb5970
[2]: https://github.com/kaushalmodi/ox-hugo/commit/3b34bae5174bc4718351a4d173e07d35f940d836#diff-63f7730028819bfdcf100c74317aba95
[3]: https://ox-hugo.scripter.co/test/real-examples/multifractals-in-ecology-using-r/

**Comment by lsaravia** [comment]
mmmm is not working very well, the symbol (R) should not be in the equations :(

**Comment by Vonng** [comment]
@kaushalmodi Heres an example of rich math content: [Neural Network Notes](https://github.com/Vonng/Math/blob/master/nndl/nn-intro.md)

Actually I solved this by forking a copy of blackfriday and add  MathJax support to it. [Commit](https://github.com/Vonng/blackfriday/commit/4e5da679f1a83b9cafd86daa94e646142482ef72)

And corresponding patch to Hugo is [Here](https://github.com/Vonng/hugo/commit/eb1653894d5ecac4fb7d225ac07d447ff6a51571)

Now it work well for me.

**Comment by kaushalmodi** [comment]
@lsaravia Well the smartypants Blackfriday extension is over smart (https://github.com/russross/blackfriday/issues/411). I should be able to put a hack in ox-hugo to outsmart that. 

@Vonng You seem to be a serious Go coder (I haven't yet coded in Go). Have you considered submitting a PR for better MathJax support to Blackfriday?

**Comment by Vonng** [comment]
@kaushalmodi PR created. 
* [Add Math support (MathJaX) to blackfriday.v2](https://github.com/russross/blackfriday/pull/412)

**Comment by kaushalmodi** [comment]
@lsaravia First of all, why wouldn't you use `(x)` like normal folks and use `(r)` instead /sarcasm :)

In any case, if you ever use Hugo again, that too, with `ox-hugo`, this issue is not solved.

The trick was [simple][1] (*even if you don't understand elisp, the comment there should explain the trick*), that now transforms the earlier exported `multifractals-in-ecology-using-r.md` [as follows][2] (*I also fixed a typo manually in there*). As a result, now the `(r)` do not get converted to &reg; by Blackfriday [[See][3]].

*Let me know if you still see issues in there.*

It's strange and wonderful, you helped fix a bug in something you don't even use :). Thank you.

[1]: https://github.com/kaushalmodi/ox-hugo/commit/a9f3ab7fc9a9d248073aa04a2c33957ff458cf2f#diff-3706187515e8952de03130b195009e8a
[2]: https://github.com/kaushalmodi/ox-hugo/commit/a9f3ab7fc9a9d248073aa04a2c33957ff458cf2f#diff-63f7730028819bfdcf100c74317aba95
[3]: https://ox-hugo.scripter.co/test/real-examples/multifractals-in-ecology-using-r/

**Comment by Vonng** [comment]
@kaushalmodi markdown feature won't effect in math block, so (x) (r) is ok in equations. 
Besides, there's an option in blackfriday API that can disable smartypants (actually not that smart and necessary...)
hugo should have such options somewhere, too.

**Comment by kaushalmodi** [comment]
@Vonng 

> so (x) (r) is ok in equations.

Of course it should be OK (I had put a /sarcasm tag there :)). The problem is that Blackfriday infers the `(r)` even in equations.

> there's an option in blackfriday API that can disable smartypants

I am aware of that, but I don't want to disable the whole of smartypants (it does a [lot of things][1]). I want to disable *just smartParens component of smaryPants* **and** *only in equations*. If you click the link I just referred, you'll see that there's no way to disable *just smartParens*.

> hugo should have such options somewhere, too.

Hugo does have an option to disable things that can be disabled (like SMARTYPANT_FRACTIONS, SMARTYPANTS_DASHES, etc.) because Blackfriday has provided an API for that.. but nothing similar exists on the Blackfriday side to disable just smartParens.
[1]: https://github.com/russross/blackfriday/blob/4ca8c28b21a883c59eb518036a3fe45a3f281463/smartypants.go#L391-L430

**Comment by lsaravia** [comment]
@kaushalmodi  I don't like x-files so I never use x :), many people helped me selflessly so I try to contribute back...

**Comment by kaushalmodi** [comment]
@Vonng 

> Heres an example of rich math content: Neural Network Notes

Thanks! That was a great example! I got to fix few more things while making that example work. 

The only hurdles I faced while porting your Markdown example to Org were:
- Org emphasis (bold) characters need to have a space before and a space after. So strings like `特性：*光滑可微*，形` had to be converted to `特性： *光滑可微* ，形`.
- Just as with the emphasis characters, Org needs the inline equations to also have a space before and a space after.. So strings like `层第$k$号神` had to be converted to `层第 $k$ 号神`.
- Org supports embedded LaTeX environments.. so blocks like `\begin{align}` ..`\end{align}` do not need to be (should not be) wrapped by `$$`.

That's all I needed after converting your Markdown to Org using pandoc. I believe that your example renders fine now.. see the Hugo generated HTML linked below.

[Org source][1] -> [Exported Hugo-compatible Markdown][2] -> [Hugo generated HTML][3]

Looking forward to comments :)

[1]: https://github.com/kaushalmodi/ox-hugo/commit/95dd1ea388a9d625bec6ef4f59f09ee28a991a2e#diff-6fa190cf16cc1fe9ba0fa6673ddb5970
[2]: https://github.com/kaushalmodi/ox-hugo/commit/95dd1ea388a9d625bec6ef4f59f09ee28a991a2e#diff-b09db998688eb195c2b0409cec288e0c
[3]: https://ox-hugo.scripter.co/test/real-examples/nn-intro/

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for discussions.
