### ISSUE TITLE
Ignore dot-file directories

### ISSUE THREAD

**Issue by nwidger** [gohugoio/hugo#239]
I ran into an issue trying to build a hugo site stored in an SVN repository.  I'm using SVN client 1.6, which stores a `.svn` directory in every directory of the checked-out repo (I believe SVN 1.7 clients and above no longer do this).  When I try to build the site, I get the error:

```
2014/03/25 11:51:19 Fatal Error: Error converting unsupported file type 'unknown' for page 'entries'
```

which I believe is from trying to determine the file type for one of the `.svn/entries` files.  I believe the fix is to call `ignoreDotFile` for directories as well as regular files here:

https://github.com/spf13/hugo/blob/d84f707da1d46b7334ff10db2443ac17a17bbff2/source/filesystem.go#L90

**Comment by shreyasminocha** [comment]
Sorry for necromancing this thread, but I have a use-case where this is becoming a bit of a problem. I want to add some pgp keys within `content/.well-known/openpgpkey/*` so that they should up at `/.well-known/openpgpkey`. Is there a way I can override this behaviour? Should I open a separate issue?
