### ISSUE TITLE
MakePath function produces unexpected URLs with certain input

### ISSUE THREAD

**Issue by bryanjeal** [gohugoio/hugo#2788]
When I `|urlize` certain strings such as:
- "♪ Short musical interlude ♬"
- "Foo & bar"

I would **expect** to get:
- "Short-musical-interlude"
- "Foo-bar"; 

however, I **actually** get: 
- "-Short-musical-interlude-"
- "Foo--bar"

The double `--` and the `-` at the beginning and end of the url isn't what other slugifiers would produce (https://docs.djangoproject.com/en/1.10/_modules/django/utils/text/#slugify)

**Comment by bryanjeal** [comment]
I have submitted a pull request with a possible fix for this issue. #2789

**Comment by bep** [comment]
We will have to think a little about this. The URL produced are perfectly valid, and changing this would be somewhat a breaking change.

**Comment by bryanjeal** [comment]
My previous experience has been with PHP and Django, so that is what has shaped my expectations and prompted this bug report.

The slugifiers I have used all produce outlook similar to the fix (although do default to lowercase as well as eliminating multiple/trailing dashes).

Here are a couple other slugifiers so you can see what I mean:
- https://github.com/cocur/slugify
- https://www.npmjs.com/package/slugify
- https://github.com/slugify/slugify

Thank you for your time on this issue.

**Comment by Artiavis** [comment]
Not sure if this is the best place to put it, but I have a related concern that I didn't see in the official docs. I have an article titled "F# vs Clojure Shootout", which gets urlized as "f#-vs.-clojure-toy-problem-shootout", which is obviously a problem since "#" gets interpreted as an anchor when it's actually a semantically valid piece of the title. Can you either warn about this case or escape it automatically? (I'm porting my blog from another site generator where titles weren't automatically mapped to URL's so I didn't have this problem.)

**Comment by bep** [comment]
See https://godoc.org/github.com/russross/blackfriday#hdr-Sanitized_Anchor_Names

**Comment by jmooring** [comment]
The behavior changed a long time ago. With v0.111.3 and default site configuration:

```text
{{ urlize "♪ Short musical interlude ♬" }} --> short-musical-interlude
{{ urlize "Foo-bar" }} --> foo-bar
```
