### ISSUE TITLE
Check case handling in isset 

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#2907]
See https://discuss.gohugo.io/t/config-params-should-be-all-lowercase-or-not/5051

**Comment by ethanmad** [comment]
I'm not sure, but I expect this bug happens when using the quotation notation (i.e., `{{ . Params "exampleParam" }}`)  in any capacity since the quotes expect an exact match with what's in the in internal database (which is lowercase), whereas the dot notation (i.e., `{{ .Params.exampleParam }}`) is case insensitive.

Those looking to work around this bug (in their sites or themes), please look at https://github.com/key-amb/hugo-theme-bootie-docs/pull/19 for a solution.
