### ISSUE TITLE
taxonomy terms page is added to sitemap in spite of not having a template file

### ISSUE THREAD

**Issue by behnoodk** [gohugoio/hugo#2912]
In the docs site (http://gohugo.io/templates/terms/) it is stated that:

> If that neither file is found in either the /layouts or /theme/layouts directory, then Hugo will not render the taxonomy terms pages.

and this is in fact true, no page is generated when there is neither a `/layouts/taxonomy/SINGULAR.terms.html` nor `/layouts/_default/terms.html`. 

One would expect that this would not be added to sitemap.xml either, but it is added to sitemap.
in my case, the following node is added to my sitemap, even when I don't have a template for tags taxonomy.
```
<url>
<loc>https://www.mysite.com/tags/</loc>
</url>
```
and this is causing errors in my Google Search Console. because I'm telling google to index a page that does not exist.

**Comment by denyskoch** [comment]
same problem here.

**Comment by alanorth** [comment]
I came to report this issue as well. The Search Console in Google Webmaster Tools takes issue with the empty `tags` and `categories` URLs in the sitemap. In my case, my server serves an HTTP 403 because there is no `index.html` to display and Google doesn't like that.

![screen shot 2017-01-22 at 14 08 53-fs8](https://cloud.githubusercontent.com/assets/191754/22182372/ab926190-e0ac-11e6-81d8-0d9d27c35e62.png)

Hugo 0.18.1.

**Comment by bomzj** [comment]
To disable categories/tags in `sitemap.xml`(as well as creating them in filesystem) use the following in `config.toml`:
```
[taxonomies]
  category = ""
  tags = ""
```

**Comment by onedrawingperday** [comment]
@bomzj 
Please don't post replies to closed GitHub issues.

BTW what you posted above introduces ambiguity and it can cause unpredictable behavior in Hugo.

Instead use `disableKinds` in a project's config. See https://gohugo.io/getting-started/configuration/
