### ISSUE TITLE
POC: Test live reload with chromedp

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#3217]
This would be a cool proof of concept:

https://github.com/knq/chromedp is a Go API using the Chrome Debugging Protocol (for Chrome, Edge, Safari, etc) .

What would be cool to test out is an alternative to the current very coarse grained live-reload, which in the normal case triggers a full page reload (and, while we only read and process the changed content file, we re-render the whole shennigan).

So with the above, it should be possible to:

On file content or template file change:

1) Check what URL is active in the browser.
2) Render only that URL
3) Write the bytes directly to the browser (stream it if possible)

The above is a bit simplistic but it should work -- and it should be so fast that you hopefully can watch yourself typing ...

**Comment by rdwatters** [comment]
This would be so cool! Do you see a future wish/feature like this affecting the many SPA CMSs that seem to be headed toward Hugo as well? 

As in, helping with things like live preview of pages similar to the way that Wordpress can automatically render a specific URL to check for contributors rather than relying on the client-side piece render it a user types?

**Comment by bep** [comment]
>This would be so cool! Do you see a future wish/feature like this affecting the many SPA CMSs that seem to be headed toward Hugo as well?

You overestimate my vision for this. I think it would be cool to test. It may work, and it may lead to other ideas. And maybe not. Let us not think strategic and long term in every little issue we create. And I did not invite to a discussion here.

**Comment by rdwatters** [comment]
> And I did not invite to a discussion here.

My apologies. I get excited
