### ISSUE TITLE
Error with umlauts and Eszett in taxonomy

### ISSUE THREAD

**Issue by Brixy** [gohugoio/hugo#3476]
Dear all!

German umlauts (Umlaute) and the Eszett are not treated properly in taxonomy URLs.

E. g., the umlaut `ö` becomes an `ö`, which seems to be a different glyph. Check in VIM, if your editor or browser does not distinguish between them. 

In sitemap.xml the letter is replaced by `%C3%B6`

- Taxonomy should generate proper umlauts and Eszetts --> `äöüß`

- There should be a site param to rewrite umlauts and Eszetts:
    - `ä` --> `ae`
    - `ö` --> `oe`
    - `ü` --> `ue`
    - `ß` --> `ss`

These are conventions to break down umlauts/Eszett if these glyphs are not available and in URLs.

Thank you!

**Comment by kevingimbel** [comment]
@Brixy What's `Schönewolf` supposed to be? A copy/paste issue? 

`ß` should map to `ss`, from a "logical" point of view.

**Comment by Brixy** [comment]
Oh yes! A client’s name.

(Would you mind deleting it from your comment.)

Thank you.

**Comment by kevingimbel** [comment]
@Brixy done :)

**Comment by bep** [comment]
>There should be a site param to rewrite umlauts and Eszetts

There is. Try `removePathAccents=true`

**Comment by Brixy** [comment]
Thank you, guys.

@bep This results in 

- `ä` --> `a`  (instead of `ae`)
- …
- `ß` --> `%C3%9F`

**Comment by phauer** [comment]
@bep works pretty well. Thanks!
However, in German, `ä` is usually replaced with `ae` instead of just a single `a`. Especially in case of URLs this can make a difference for search engines.
Can I customize the mapping of the umlauts?

**Comment by muelli1975** [comment]
Hello,

I can confirm that this behaviour is definately a bug and no feature ;-). I also added `removePathAccents = true` to get rid of rendering umlauts, but the results are - as Brixy said - wrong. The correct behaviour should be like Brixy described in the first post.
`ä = ae`
`ö = oe`
`ü = ue`
and
`ß = ss`
Having `a` instead of `ä` is shurely better than having no mapping of umlauts, but it's not the correct behaviour and should be fixed.

Best regards,
Christoph

**Comment by andreseduardop** [comment]
`removePathAccents = true,` 
is it working?  
This configuration setting does not appear in the official documentation.

**Comment by istr** [comment]
I stumbled upon a possible solution for the problem here.
This is a subset of the more general problem of mapping text (e.g. page titles) to a mangled / sanitized form (e.g. IDs, anchors, URLs). A very common use case is proper diacritic mark mangling like mentioned here (not only in German!). https://www.von-laufenberg.de/blog/it/hugo-umlaute/

The idea is to

- define a generic mangling function
- pass a mapping by means of a configuration entry

I am neither (yet) fluent in go nor do I have time to dig into hugo's internals, but the post above could be a guideline to create a PR to solve this issue (along with #5687, #8997 and other related issues).
However, care must be taken, to keep things consistent (least surprise), such that a configured mapping applies to all relevant mapping functions alike or at least could be configured to do so.

**Comment by Doppelklick** [comment]
is it possible to re-open this issue?
