### ISSUE TITLE
 .File.Path returns `%2f` in link instead of `/` 

### ISSUE THREAD

**Issue by fgiorlando** [gohugoio/hugo#3492]
I am adding an edit link in a hugo site and need to return the file path to the editor.

My edit link in the template looks like this:

```
<a href="https://editor.tld/#mysite/content/{{ .File.Path }}" target="editor">Edit</a>
```
This returns the correct edit link, however, when I click on it, the file path transforms to:

https://editor.tld/#mysite/content/mypage%2f_index.md

the `/`s are replaced by `%2f`.

Is there some way to have them as slashes instead?

**Comment by LubinKerhuel** [comment]
I encountered a similar issue, affecting the hugo version tested: 0.50, 0.51, 0.53. Compiled on **windows platform**.
**It works when compiled on netlify.**
I cannot get a working link when generating a link with  {{.File.Path}} to edit page with prose.io.

I get the path separator from (.File.Path) beeing "%5c" (\) while I need either "%2f" (/) or directly "/" which works for prose.io.

not ok : http://prose.io/#repoid/hugo/edit/master/content/docs**%5c**invertedpendulum.md
ok : http://prose.io/#repoid/hugo/edit/master/content/docs**%2f**invertedpendulum.md
ok : http://prose.io/#repoid/hugo/edit/master/content/docs**/**invertedpendulum.md

I bet it's a windows platform path sep character related issue :  \" instead of "/".

**Comment by moorereason** [comment]
@LubinKerhuel,
Please open a new issue, as this one has been closed for quite some time.
