### ISSUE TITLE
Duplicated pagination if paginate = X, where X is lower than the number of posts

### ISSUE THREAD

**Issue by arikroc** [gohugoio/hugo#3507]
I have 7 pages.

If I set paginate = 5, I get two pages i.e. /page/, and /page/page/2

Both of the pages have the same 7 pages listed on them.

If I set paginate = 7, then I get one page, with all 7 pages listed on it, with no duplicate. (i.e. no problem)

What might be causing this bug?

Hugo Static Site Generator v0.20.7, MacOS 10.12.4

**Comment by domachine** [comment]
I'm having a similar issue. It lists the first slice of the pages on every paginator-page.

**Comment by domachine** [comment]
Never mind. I solved it. It was my fault :relaxed:

**Comment by bep** [comment]
Thanks for getting in touch, but it feels like this is a question  that would be better suited to the [Hugo Discussion Forum](https://discourse.gohugo.io/).  We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug. You may also find the answers you search for in [Hugo Documentation](http://gohugo.io/overview/introduction/).
