### ISSUE TITLE
menu system broken?

### ISSUE THREAD

**Issue by andi-blafasl** [gohugoio/hugo#3637]
Hi
I'm relativ new to hugo and trying to get startet with it. For better understanding I played a bit with some simple test pages. For more complex testing I cloned the Hugo Docs repository and compiled it with the latest hugo version on my system.

I do not understand why the menu system is missing an Item. In the config.toml file the main menu contains a Item "Theme Showcase" with the weight -170. But this Item is not rendered.
Btw. it is also missing on the official hugo site ;-)

If I change the weight to -165 the Item get's rendered and displayed on the site. If I change the weight to anything above -169 the Item is not rendered, but the Items "Site Showcase" and "Download Hugo" which are -180 and -200 weighted are rendered always.

Am I doing something wrong here or misunderstanding the weight system?

**Comment by bep** [comment]
Thanks for getting in touch, but it feels like this is a question  that would be better suited to the [Hugo Discussion Forum](https://discourse.gohugo.io/).  We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug. You may also find the answers you search for in [Hugo Documentation](http://gohugo.io/overview/introduction/).
