### ISSUE TITLE
Improvements to internal YouTube shortcode

### ISSUE THREAD

**Issue by rhewitt22** [gohugoio/hugo#3694]
The built-in Hugo shortcode for embedding YouTube videos obscures captions when the user is not interacting with the video. This is a simple CSS issue related to **`overflow: hidden;`** being included inline in the go template.  I removed this CSS property in Chrome Dev Tools and everything works as expected.

## overflow: hidden;

![overflow-hidden](https://user-images.githubusercontent.com/3673374/28083020-213132da-6642-11e7-9342-15fda6a0f0a7.gif)

## Removed overflow:hidden;

![overflow-not-hidden](https://user-images.githubusercontent.com/3673374/28083019-21221ba6-6642-11e7-94d2-f0efa592134a.gif)

## [From GitHub](https://github.com/gohugoio/hugo/blob/da72805a4304a57362e8e79a01cc145767b027c5/tpl/tplimpl/template_embedded.go):

```
<div {{ if .Get "class" }}class="{{ .Get "class" }}"{{ else }}style="position: relative; padding-bottom: 56.25%; padding-top: 30px; height: 0; **overflow: hidden;**"{{ end }}>
  <iframe src="//www.youtube.com/embed/{{ .Get "id" }}?{{ with .Get "autoplay" }}{{ if eq . "true" }}autoplay=1{{ end }}{{ end }}" 
  {{ if not (.Get "class") }}style="position: absolute; top: 0; left: 0; width: 100%; height: 100%;" {{ end }}allowfullscreen frameborder="0"></iframe>
</div>

```

**Comment by rdwatters** [comment]
@rhewitt22 Out of curiosity, did you try this on multiple videos with different aspect ratios?

**Comment by rhewitt22** [comment]
@rdwatters Everything our videographer handed off to me is 1920x1080 (16:9), which is pretty standard these days.  If I were to use another resolution it would be 720p, which is also 16:9.  I just tried this on a second video with the same resolution and had (unsurprisingly) the same result.

For now I'm just pasting in the shortcode html into my content and removing the inline overflow property.

**Comment by bep** [comment]
>For now I'm just pasting in the shortcode html into my content and removing the inline overflow property.

We will fix this eventually, but It would be more effectie for you to paste the Hugo youtube shortcode into your `layouts/shortcodes` and make your own correct version.

**Comment by rhewitt22** [comment]
Thanks for the suggestion.  That makes things much simpler.

**Comment by gaetawoo** [comment]
In addition to this, there is still the issue that there are black bars on the top and bottom of the video, which means the container(?) is not sized appropriately for a typical 16x9 video. This is visible in the second screenshot in this thread. How does that get fixed and still allow for the responsiveness of the container/video?

**Comment by gaetawoo** [comment]
@rhewitt22 @bep I was looking into this because I was experiencing issues with the container not being sized correctly. There is definitely something incorrect with the style parameters of the container and the iframe. After some research and help from Jonathan on the Hugo forum, I saw how Zurb Foundation was doing it, and saw how Hugo internal shortcode was doing it, and saw the difference. I took Zurb's style settings, applied them in the same way (inline) into a custom shortcode as Hugo does in its internal shortcode. The result works perfectly and as expected is completely responsive. The captions are correctly located also. The working code is below:

```
<div style="position: relative; padding-bottom: 56.25%; overflow: hidden;">
    <iframe style="position: absolute; width: 100%; height: 100%;"
        src="http://www.youtube.com/embed/{{ index .Params 0 }}" allowfullscreen frameborder="0">
    </iframe>
</div>
```

I have this as a custom youtube shortcord for now but of course it should be fixed in the internal shortcode. Replacing the current style parameters with these will do that. Should I submit a PR? 

Furthermore, Zurb's CSS had a setting whereby, without specifying the aspect ratio of the video, it would default to standard (4:3) but if you set the parameter of *widescreen* it would change appropriately. The switch was in the *padding-bottom:* parameter, where standard was 75% and widescreen was 56.25%. This may be a worthwhile parameter to include in the internal shortcode... something like: 

```
{{< youtube aa7a7a7a standard >}}
```
but would default to widescreen if standard was not given. @rdwatters this would address your comment about different aspect ratios, but what I've laid out here only pertains to 16:9 and 4:3. If there were another aspect ratio (which I have to imagine is probably pretty rare, I guess there is anamorphic and some other types but not common) then maybe some logic for an input ratio and the shortcode takes that, does the math, and determines what the *padding-bottom* should be.

Also, there is the option of including another parameter to give the start timecode position of the video. Not sure how best to handle that, but I just wanted to throw that in there for another useful option. Maybe the 1st .Params would be the video link code, 2nd would be the ratio (standard or widescreen), 3rd would be the start-time in seconds:

```
{{< youtube aa7a7a7a widescreen 45 >}}
```

**Comment by rhewitt22** [comment]
I think defaulting to 16:9 is a good start.  I also think relying on actual ratios rather than magic strings like "widescreen" or "standard" is preferable. 

I really like the idea of supporting a start-time parameter.

**Comment by rhewitt22** [comment]
I'm super embarrassed to admit I had a stray CSS selector that was causing the issue with the youtube captions.  That said with those rules removed there is still the issue of black bars at the top and bottom of the YouTube embedded video.  Given the other suggestions from @gaetawoo  perhaps this issue should be renamed?  Maybe **Improvements to internal YouTube shortcode**?

Sorry for the mixup.

**Comment by gaetawoo** [comment]
@rhewitt22 Here is the shortcode that will permit a start and stop timecode for the video. The shortcode shortcut requires that the parameters be in order and each previous one filled or else it won't work. It's not robust, but that part is a bit beyond my skill at the moment.

```
{{ if or (eq (index .Params 1) "widescreen") (not (index .Params 1) ) }}
	{{ $.Scratch.Add "ratio" 56.25 }}
{{ else if eq (index .Params 1) "standard" }}
    {{ $.Scratch.Add "ratio" 75 }}
{{ else }}
	{{ $nums := split (index .Params 1) ":" }}
	{{ $.Scratch.Add "ratio" (div (mul (int (index $nums 1)) 100.0) (int (index $nums 0))) }}
{{ end }}

{{ if (index .Params 2) }}
    {{ $.Scratch.Add "start" (add "?start=" (index .Params 2)) }}
{{ else }}
    {{ $.Scratch.Add "start" "" }}
{{ end }}

{{ if (index .Params 3) }}
    {{ $.Scratch.Add "end" (add "&end=" (index .Params 3)) }}
{{ else }}
    {{ $.Scratch.Add "end" "" }}
{{ end }}

<div style="position: relative; padding-bottom: {{ $.Scratch.Get "ratio" }}%; overflow: hidden;">
    <iframe style="position: absolute; width: 100%; height: 100%;"
        src="http://www.youtube.com/embed/{{ index .Params 0 }}{{ $.Scratch.Get "start" }}{{ $.Scratch.Get "end" }}" allowfullscreen frameborder="0">
    </iframe>
</div>
```

The entry would be thus:
```
{{< youtube B7zFRSVmN1w "16:9" 30 35 >}}
```
It works well.

**Comment by jhabdas** [comment]
Embeds now support some other useful features, such as hiding the video title, payer controls and (my favorite) an enhanced privacy mode, shown here checked:

<img width="1140" alt="screen shot 2017-10-11 at 5 17 28 pm" src="https://user-images.githubusercontent.com/440298/31432429-49bd90bc-ae3c-11e7-915c-33218228325b.png">

**Comment by jhabdas** [comment]
Regarding responsive `iframe` embeds, it would be good to tackle Vimeo while this is being addressed and potentially also [things like coub](http://coub.com/tags/privacy), which uses embeds like this:

```
<iframe src="//coub.com/embed/bwdx6?muted=false&autostart=false&originalSize=false&startWithHD=false" allowfullscreen="true" frameborder="0" width="640" height="348"></iframe>
```

It would be great if there were a push for Web standards here, as responsive iframes have been a sordid need on the Web for quite some time. Just not sure where to start personally.

**Comment by p-groarke** [comment]
The time has to be seconds. The user shouldn't have to think about that.
```

**Comment by gaetawoo** [comment]
@p-groarke I think it's more straight-forward to input with seconds, especially for Hugo users, it's not really much of an ask to convert minutes in to seconds and add. But one could always make a shortcode that takes an argument like "4:31" and parses that as 4 minutes and 31 seconds and does what you do in your code to turn it into seconds. I think the built-in youtube shortcode probably shouldn't be comprehensive and make usable every option for a video player. That's what custom shortcodes are for since most people are going to want the basic functions. My 2cents anyway.

**Comment by HughP** [comment]
Just an FYI, I am excited to see a robust youtube short code added to Hugo, as I recently ran into some problems with the default. I'm still chugging along at the moment, but will switch back to the default when it becomes available/robust.

**Comment by fgm** [comment]
Another enhancement which I think would be worthwile would be the ability to embed the video as a thumbnail linked to the player, not the player itself. This is something which has been requested more and more by clients on CMS projects, and I would like to have this for my Hugo sites too.

**Comment by roointan** [comment]
I wanted to work on this one, specially to support all player parameters https://developers.google.com/youtube/youtube_player_demo

But noticed there was a PR #7365 to support start and end time which did not end up being merged, and was closed.
A little confusing.
Should I move forward with trying to improve the Youtube shortcode?

**Comment by roointan** [comment]
The PR adds support for issues @ghost and @fgm and @gaetawoo mentioned.
Support for start/end time added, using codes from @capnfabs Thanks! (Is it ok to reuse code from unmerged PR?)
@bep please let me know if I should change or improve anything for this PR to be accepted, and feel free to edit anything.

**Comment by gaetawoo** [comment]
@roointan looks fab! thanks for taking the torch on this! hopefully it gets merged.

**Comment by jhenstridge** [comment]
I've created #10250 that implements a subset of the suggestions here. Hopefully that'll make it easier to get merged. It includes the following improvements:
* adds a "simple" mode activated through the privacy settings, that just shows a video thumbnail that links to the video page.
* in normal mode, automatically size the iframe to the video's aspect ratio (so no need to separately configure this for 4:3 videos).
* set the default iframe title to the video's title on YouTube rather than "YouTube Video".
