### ISSUE TITLE
tpl/compare: Eq is too strict on type comparisons

### ISSUE THREAD

**Issue by moorereason** [gohugoio/hugo#3721]
Numeric values from JSON always return as floats.  The following `eq` usage fails because `eq` would use `reflect.DeepEqual` to compare a `float64` to an `int`:

```
// Assume: {"one": 1}
{{ if eq .Site.Data.foo.one 1 }}
```

We should be more lenient with our comparisons so that different types can be compared.

Discussion thread:  https://discourse.gohugo.io/t/7522

**Comment by moorereason** [comment]
On second thought, I don't want to keep this enhancement request.  JSON returns floats by standard.  If you're checking a float, you should test for a float.  If the user doesn't care, they can cast as `int`.

I don't want to lose the precision we have and get "magical" with `eq`.  @bep, what do you think?

**Comment by vassudanagunta** [comment]
Right now the JSON, YAML and TOML parsers return float64, int, and int64 respectively for an integer value. I know this because I lost hours trying to figure this out for the data dir tests that wouldn't pass. Well that and because I'm a total go newb as well 😜  

Coding templates should be more akin to forgiving scripting languages like python, not unforgiving low-level languages like Go, right? 

One solution is to make all the functions such as `eq` smarter. Another is to normalize numeric data, such as we recently did for map keys with #4138.
