### ISSUE TITLE
newContentEditor does not find editor in 0.25.1 

### ISSUE THREAD

**Issue by juh2** [gohugoio/hugo#3742]
With version 0.25.1 I get this error:
 
```
Editing post/2017/2017-07-27-125830.md with "nvim" ...
Error: exec: "nvim": executable file not found in $PATH
```

I am not sure which version I used before. On another computer 0.22 works without problems.

**Comment by anthonyfok** [comment]
Are you using the Snap version of Hugo by any chance?  If so, and assuming you are using Debian or Ubuntu on amd64, the easiest way is to install the latest Debian-maintained hugo .deb here:

http://ftp.us.debian.org/debian/pool/main/h/hugo/hugo_0.25.1-1_amd64.deb

See https://packages.debian.org/sid/hugo for other architectures.  Then, check your `$PATH` and the `which hugo` command to make sure it is using /usr/bin/hugo rather than /snap/bin/hugo, then you are all set!

Snaps run in isolated containers, and thus your hugo snap cannot see `nvim` in your $PATH.
See the recent discussions at https://discourse.gohugo.io/t/hugo-v0-24-ubuntu-server-17-04-error-exec-nano-executable-file-not-found-in-path/7145
