### ISSUE TITLE
Add support for multiple contentDirs

### ISSUE THREAD

**Issue by tylerbutler** [gohugoio/hugo#3757]
*I am filing this issue per the suggestion from @bep here: https://discourse.gohugo.io/t/multiple-contentdirs/7462/4*

Here's the scenario for supporting multiple contentDirs:

> Most site content is committed to the site's git repo, in the content directory, but I also write draft posts from a variety of different devices like my phone or iPad. I use Dropbox to sync the posts between devices.
>
> What I'd like to do is configure Hugo to look for content in multiple places, so I can add my Dropbox/hugo_content/ folder to the list and get content from both locations during a site build.

**Comment by mpcabd** [comment]
@bep could you check 22e336d when you can? It might be far from perfect but I wanted to review before I write tests and update the documentation.

**Comment by bep** [comment]
@mpcabd your code looks clean and simple enough, but, in my head, the problems with this approach are

1. it isn't well defined which file will win when the same file lives in two locations. You may have a defined order in `filepath.Walk` (but we may decide to go concurrently at some point) at the moment, but we also do reloading of content based on file system events, which must be handled somehow.
2. Also, saving the new content file to `n` locations on `hugo new` wasn't the intention behind this issue -- that would lead to lots of confusion.

**Comment by mpcabd** [comment]
Thanks for the quick review!

1. My implementation takes the first instance it finds in order of directories defined in the config, I had already tested that.
2. `hugo new` creates the new content in the first folder always, see the screenshot

**Comment by tylerbutler** [comment]
@mpcabd I see in your proposal that you've added a new config property `contentDirs`. For what it's worth, I'd prefer a design where the existing property is used. I.e. if I set `contentDir` to a single path, then it pulls content from that path alone. If I specify a list of paths instead, then it pulls content from all of them.

I'm new to Hugo, though, so it's possible that that is against some design principles I'm not aware of, or has technical reasons preventing it from being implemented. But in general I find it better to have a flexible configuration property rather than multiple configuration properties that interplay.

Assuming you do have to keep them separate properties:

1. What happens if I specify both `contentDir` and `contentDirs`?
2. What happens if `contentDirs` is a string, not a list of strings?
3. What happens if `contentDir` is a list of strings, not a string?

**Comment by tylerbutler** [comment]
Sorry, I looked more closely at the PR. I'm also new to Go so I'm muddling my way through it. 😄 

Anyway, I *think* the answer to all three of my questions is that the user will see an error during site build.

**Comment by mpcabd** [comment]
@bep I'll take care of point 1 that you mentioned, and will clarify point 2 more in code as it might not be very clear what the code is trying to do.

@tylerbutler I will try to change some bits to test having `contentDir` only, but it might be harder to test since it won't have a static type. In my current implementation `contentDir` is a `string` while `contentDir` is a `[]string`.

Thanks both for the review, I'll come back with more changes.

**Comment by mpcabd** [comment]
I just pushed c218a18 that will, I hope, attend to your concerns @bep, let me know what you think.

**Comment by vassudanagunta** [comment]
I'm a big believer in the KISS principle. I think Hugo should stick to one function, that is to transform source content (provided in as simply specified as possible structure of files) into a set of static web pages. 

Editing or syncing source content from multiple devices should be solved elsewhere. There are many other avenues to address this. For example:

- One each device use an editor that can write to the single contentDirs. For example there are editors on all devices that can edit GitHub files, or DropBox files. So pick one location and then choose the editors that work with that. For example on iOS you can use Editorial + WorkingCopy to edit and publish Markdown your mobile device.
- Us a syncing tool. For example, one that pushes new content from DropBox into GitHub.
- use `git inti --separate-git-dir` or `git clone --separate-git-dir`so that your `contentDir` working tree is in DropBox but your repository (`.git` dir) is not (to avoid syncing all the repo data, and to avoid allowing DropBox sync to corrupt it.). Edits made via your mobile device will be automatically seen on your main computer, from which you can commit the changes into the repo (and push into GitHub). 

I also think the OP's specific use case is problematic and misguided. The whole point of using git or GitHub for the contentDir is so that the source content is all under source control with full history and change tracking.

**Comment by bep** [comment]
I was planning to handle this as part of #4027 -- but that got to be a little bit too big a task. Will have to put this on hold for a little.

**Comment by tnissi** [comment]
I'd very much like to see this in the next release. 

We are pulling some content from a third party service and have some static documents of our own. Currently we're just pulling the third party content on top of the content directory, but that's just plain ugly. Also somebody is going to commit the pulled content into the git repo sooner or later, which isn't desirable in our case. 

Building the site from multiple content directories would allow us to keep the pulled and static content in their rightful places.

**Comment by bep** [comment]
Note that we in Hugo 0.32 will have full support for symbolic links inside /content -- including directories, which I guess could help in these situations.

**Comment by bep** [comment]
@vassudanagunta no, they don't look related to me. If they are, you should try to explain.

**Comment by vassudanagunta** [comment]
@bep At the moment the only time that the current data _merging_ functionality ever gets invoked is between data files in the user data directory and the theme data directory. I'll bet that's rare if it occurs at all. It has limited use given that the merge is shallow.

If multiple user data directories are supported, it opens up a whole new case where it gets invoked. My thought is that it is important to be certain that data merge functionality is worth keeping before it gets harder to remove. I'm just saying be sure is all. 

Maybe merge semantics should be left to the user, in the templates. The user can use arbitrary logic to figure out how one set of data overrides or gets merged with another. 

Data merging has performance implications. It could, for example, make it difficult to implement lazy load as you suggest in #1065. Not sure though.

**Comment by vassudanagunta** [comment]
@bep since my analysis there is so long, here is the conclusion for your convenience:

> Data merging
> 
> 1. **Remove support for merging**. No two files can have the same tree path. Leave merge semantics should be left to the user, in the templates. The user can use arbitrary logic to figure out how one set of data overrides or gets merged with another.
> 
> 2. **Keep things as they are**, Shallow merging.
> 
> 3. **Support deep merges**. This option is orthogonal to the other choices, and is compatible with all of them, though making sense for some more than others. This would essentially add inheritance semantics to the data, addressing the issues with the rock and blue-eyed-soul genres in the example.
> 
> I lean toward #1. But I am unsure of current usage or its popularity. #2 as I stated in non-obvious consequences can result in confusion, and limits its use. My gut says do no merging or go all the way. But since the user can always use whatever merge logic they want in their templates, #1 makes most sense.

**Comment by bep** [comment]
>Add support for multiple contentDirs

@vassudanagunta read the issue title.

**Comment by vassudanagunta** [comment]
😳 @bep sorry! For some reason, most likely my failing brain, I read multiple data dirs. 😟🙁😬😶

**Comment by vrish88** [comment]
Any plans on merging this in? I was hoping to use this. Thanks!

**Comment by itscooper** [comment]
I would also find this really useful. I work on a documentation project where we’re using Hugo to generate, and work collaboratively on, the document itself, but also for the brochureware site around the documentation. Being able to specify separate content directories would allow me to organise the project’s structure better and make things easier for contributors.

**Comment by yordis** [comment]
Any update on it folks?

I would like to leverage Hugo in a mono-repo environment.

**Comment by jmooring** [comment]
Seems like this was resolved with mounts:
https://gohugo.io/hugo-modules/configuration/#module-config-mounts

Can we close this issue?
