### ISSUE TITLE
Add pug template support

### ISSUE THREAD

**Issue by liuhuancom** [gohugoio/hugo#3777]
Add pug template style support
[pug](https://pugjs.org)

**Comment by rdwatters** [comment]
These strikes me as a tall order...unless there is a direct Pug port to Golang. I'm not especially familiar with Pug syntax, but I seem to recall it being very similar to either Amber or Ace. Have you read the following docs?

https://gohugo.io/templates/alternatives/

Also see here:

https://github.com/pugjs/pug/issues/2343

**Comment by liuhuancom** [comment]
I know thank you my friend

**Comment by liuhuancom** [comment]
How to use amber in Content TOML or YAML?
 Not in Templates

**Comment by rdwatters** [comment]
I think at this point, this question would be better posed on the forums: https://discourse.gohugo.io since we are quickly veering off the original issue's title, please. Thanks!

**Comment by liuhuancom** [comment]
Thanks!

**Comment by bep** [comment]
https://github.com/Joker/jade

**Comment by jalberto** [comment]
I will love to see pug/jade support in hugo, there are several Go implementations of both, jade and pug (https://github.com/eknkc/pug)

**Comment by rolojf** [comment]
It would be a great addition. Consider this:

The popularity of this template pugjs comparing how many stars in github pugjs has to other templates like liquid, handlebars, jinja2 it's clear it's some what popular. (not as much as hugo  ;) 
 
https://github.com/Joker/jade  already did some heavy lifting. I just don't know how to implement it myself in hugo. But it would be a very good and would become popular I think.

**Comment by zor-el** [comment]
Pug is to HTML what Sass is to CSS: A clean and very concise markup. Amber and Ace were alternatives for Hugo that followed the spirit of Pug. Alas, Hugo 0.62 dropped support for Amber and Ace (so now we have no [alternative templating languages](https://gohugo.io/templates/alternatives/) at all).

I'd like to suggest to reconsider this issue and look into [Pug.go](https://github.com/eknkc/pug), as suggested by @jalberto.

**Comment by rudolfschmidt** [comment]
I use pug and stylus for my work and I consider to try hugo to create static websites without hassle with databases and further crap but for that I need pug and stylus support.

**Comment by mrichman** [comment]
+1 for pug support

**Comment by SGA-masatoshi-ohta** [comment]
+1

**Comment by ndastur** [comment]
Absolutely, can't believe it's not supported. Who wants to deal with closures

**Comment by clevett** [comment]
+1 Pug support

**Comment by davidsneighbour** [comment]
I love seeing "+1 on closed issues" (2.5 years in the future) in it's natural habitat :) I think the proper way to re-vive the topic of "Pug as template engine for Hugo" would be to open a new issue and committing time and resources to this topic because it's obviously not on top of the list of features that have urgency. [Jade.go](https://github.com/Joker/jade) is still active, so that would be a starting point. On a side note: I think the removal of "alternative templating engines" is something that is due to these alternatives having to be checked and tested each time anything changes in Hugo, and that seems to be a massive task. If nobody has resources to help creating this *and* maintaining it then let this issue stay closed and resting in peace now :)
