### ISSUE TITLE
RSS description tag should contain hugo .Content

### ISSUE THREAD

**Issue by irl** [gohugoio/hugo#3913]
#3219 has broken blog aggregators that previously would display the full content and now only provide the lead.

There is not even an option for turning the old behaviour back on.

As this is a template embedded in the code, it cannot be overriden from the theme or otherwise afaict.

**Comment by bep** [comment]
Thanks for getting in touch, but it feels like this is a question  that would be better suited to the [Hugo Discussion Forum](https://discourse.gohugo.io/).  We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug. You may also find the answers you search for in [Hugo Documentation](http://gohugo.io/overview/introduction/).

**Comment by irl** [comment]
This is a bug.

It has broken functionality that was previously working.

People write blogs with hugo, people have those blogs syndicated on planets (e.g. planet.debian.org or planet.fsfe.org) and this change has broken that functionality.

It may have been in the name of standards compliance or whatever, but I'd prefer to have the "default" behaviour not be breaking to my use case and the use case of other bloggers that syndicate their blogs.
