### ISSUE TITLE
Hugo server not serving all/newly added content

### ISSUE THREAD

**Issue by finferflu** [gohugoio/hugo#3925]
I have just upgraded to Hugo 0.29 on macOS High Sierra; I have placed an image in public/img where my other images are kept, however, the images that I had previously placed in that folder are accessible at `http://localhost:1313/img/image.jpg` whereas the newly added image produces a `404`. 

The output from `hugo server` isn't really helpful, so I'm unable to provide any more details. All I can say is that I have then tried to serve the `public` folder from my local Apache server, and I noticed that the `css` and a few more folders (excluding the `img` folder) were missing. Upon running `hugo` again (just `hugo`), the folders have appeared, and serving the `public` folder via Apache works as expected.

I am willing to provide more details, but I will need some guidance as to how to obtain them.

Thank you.

**Comment by bep** [comment]
Thanks for getting in touch, but it feels like this is a question  that would be better suited to the [Hugo Discussion Forum](https://discourse.gohugo.io/).  We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug. You may also find the answers you search for in [Hugo Documentation](http://gohugo.io/overview/introduction/).

**Comment by finferflu** [comment]
@bep, Thanks for the feedback. I do feel like this is a bug since this functionality is not meeting the expected behaviour. I'd like to provide as many details as possible, however, I will need some guidance as to how to obtain it. If you still feel like this isn't a bug, please let me know and I will post this in the Discussion Forum as you suggested.

Thanks!
