### ISSUE TITLE
Problem generating page referencing other pages content throught shortcodes

### ISSUE THREAD

**Issue by gvcgael** [gohugoio/hugo#3932]
Hello,

I'm using a shortcode to include other pages depending on their `code` parameter. 

```
{{ $found := where .Site.Pages ".Params.code" "=" .Params.src }}
{{ if len $found | ge 1 }}
		{{ range $found }}
			<div style="border: thin solid black">
				<h4><b>{{ .Title }}</b></h4>
				<p>{{ .Content }}</p>
			</div>
		{{ end }}
	{{ end }}
{{end}}
```

```
---
code: 'CODE02'
title: 'Some page'
---

My super page
```

I'm using it like this in other pages : 

```
---
code: 'CODE01'
title: 'Some page'
---

{{% rendering src="CODE02" %}}
```

The problem is that, sometimes, CODE02 is not rendered in CODE01 page. I need to modify the shortcode file, so that hugo server detects the change and reloads to be able to see CODE02 in CODE01.

I supposed it was caused by CODE02 not being rendered on the first pass on CODE01. So I added a call to `.Render` function, but without any effect.

It seems to be the same problem as this one : https://discourse.gohugo.io/t/simple-recipe-site-theme-with-nested-sections/6991/4

I canno't use the workaround ` .RawContent | markdownify` because all markdown files are using shortcodes.

**Comment by bep** [comment]
Thanks for getting in touch, but it feels like this is a question  that would be better suited to the [Hugo Discussion Forum](https://discourse.gohugo.io/).  We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug. You may also find the answers you search for in [Hugo Documentation](http://gohugo.io/overview/introduction/).

**Comment by gvcgael** [comment]
But I think its a bug. 

My workaround is actually to do this : 

```
./hugo.exe server -s marinefrops/ -d public/ &
hugo_pid=$!
sleep 4
touch $1/layouts/shortcodes/rendering.html
sleep 2
touch $1/layouts/shortcodes/rendering.html
sleep 2
touch $1/layouts/shortcodes/rendering.html
sleep 2
touch $1/layouts/shortcodes/rendering.html
kill $hugo_pid
```

To ensure that the subcontents are generated where they are included by the shortcode.

**Comment by moorereason** [comment]
@gvcgael, it's not a bug.  You're abusing hugo features.  Start a thread in the discussion forums to discuss this further.
