### ISSUE TITLE
Upgrade to Blackfriday v2

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#3949]
https://github.com/russross/blackfriday/releases/tag/v2.0.0

**Comment by vassudanagunta** [comment]
More flexibility for custom renderers and access to the syntax tree will be huge!

**Comment by bep** [comment]
@chaseadamsio part of me wanted to jump on this so I just pulled in v2 to get a sense of the scope of everything. And I notice that goorgeous is using the BF renderer -- which is great news in the long run of it all (think ToC support etc.) , but that means that we should update that library as part of this task. And it would be great if we could do a dugnad on this ... some time. Where you could potentially create a v2 branch of your project or something ...

**Comment by chaseadamsio** [comment]
👍 I can try and do that sometime this week.

**Comment by chaseadamsio** [comment]
@bep: https://github.com/chaseadamsio/goorgeous/tree/v2.0.0

**Comment by bep** [comment]
>. Do you want me to PR the version bump (along with the blackfriday bump) or do you want to do it?

I will do tit as part of a "bigger scope". Do you mean that you were able to pull in the BF changes without any code changes?

**Comment by chaseadamsio** [comment]
@bep that's correct. I checked out BF v2 locally and ran tests, added it as a go dependency to goorgeous and did a sanity that the [`HTMLRenderer` signature that goorgeous](https://github.com/chaseadamsio/goorgeous/blob/v2.0.0/goorgeous.go#L44) uses [from BlackFriday](https://github.com/russross/blackfriday/blob/4048872b16cc0fc2c5fd9eacf0ed2c2fedaa0c8c/html.go#L111) hasn't changed and sanitied methods that goorgeous is calling to make sure the API hasn't changed. Goorgeous is compatible with BF v2. Since there's a hard dependency on it, I went ahead and cut a 2.0.0 version of goorgeous in case the API does change.

**Comment by Nodraak** [comment]
Hi! What's the status of this? Why was PR #3994 without merging?

**Comment by dwy6626** [comment]
I need this to solve the hard linebreak issue:
https://github.com/russross/blackfriday/issues/307

**Comment by jmooring** [comment]
Blackfriday was removed a while ago. No longer relevant.
