### ISSUE TITLE
Bug: if language is specified in font matter, the complete Site is rendered in that language

### ISSUE THREAD

**Issue by MoritzFago** [gohugoio/hugo#3961]
You currently can't use the `language` font matter option for specifing the language of a post. If you do, all the pages are rendered with that language code in the html header.

**Comment by bep** [comment]
> with that language code in the html header.

What do you mean by that? Do you have a example source somewhere?

**Comment by MoritzFago** [comment]
file1:
```
+++
title = "a german title"
description = ""
keywords = []
categories = []
tags = []
language = "de"
+++
German content
```
file2:
```
+++
title = "a english title"
description = ""
keywords = []
categories = []
tags = []
language = "en"
+++
english content
```
In the hugo gen output it says: `Built site for language en:` and in the resulting html, it says, for both files:
```
<!DOCTYPE html> <html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en-us"> 
```

**Comment by adelq** [comment]
I think this is the expected behavior. Based on the [Front Matter documentation](https://gohugo.io/content-management/front-matter/), I can't see any documented variable for `language`. Indeed, the `language` front-matter variable isn't predefined in `hugolib/page.go` either.

The officially supported way of [mulitlingual website support](https://gohugo.io/content-management/multilingual/) is by using the `[languages]` block in `config.toml`, then encoding the language code into the filename (ex: `about.md` becomes `about.en.md` and `about.de.md`). I just tested the following config, and got the expected results:

```toml
[languages]
[languages.en]
lang = "en"
languageName = "English"
weight = 1

[languages.de]
lang = "de"
languageName = "Deutsch"
weight = 2
```

Hugo output:
```
Built site for language en:
0 draft content
0 future content
0 expired content
1 regular pages created
8 other pages created
0 non-page files copied
1 paginator pages created
0 tags created
0 categories created

Built site for language de:
0 draft content
0 future content
0 expired content
1 regular pages created
8 other pages created
0 non-page files copied
1 paginator pages created
0 tags created
0 categories created
total in 24 ms
```

The `DOCTYPE` support comes from the template. I used [Minimo](https://github.com/MunifTanjim/minimo) for this test, which has [proper support for translations](https://minimo.netlify.com/docs/translation/).

Now my site has English under `/` (`/en/` redirects to `/` because it's set as default) and German under `/de/`. The `.en.md` and `.md` articles are under the English site, and the `.de.md` articles are under the German site. Every page has the correct meta tag as below:

```html
<html lang='en'>
<!-- or -->
<html lang='de'>
```

You may be able to use the front-matter in a custom theme that incorporates it, however the Hugo ecosystem seems to be using the official multilanguage support linked above.
