### ISSUE TITLE
Raspbian/Debian Stretch APT repository distributes outdated Hugo v0.18.1

### ISSUE THREAD

**Issue by Paul-Reed** [gohugoio/hugo#3995]
Can the apt version be updated please, it's still at version 0.18 in the Raspbian Stretch repo, which is almost a year old.

```
pi@raspberrypi:~ $ apt-cache madison hugo
      hugo |   0.18.1-1 | http://mirrordirector.raspbian.org/raspbian stretch/main armhf Packages
```

**Comment by Paul-Reed** [comment]
A bit more digging;
```
pi@raspberrypi:~ $ apt-cache show hugo
Package: hugo
Version: 0.18.1-1
Architecture: armhf
Maintainer: Debian Go Packaging Team <pkg-go-maintainers@lists.alioth.debian.org 
```
Now checking 'Debian Go Packaging Team' brought me to;
https://wiki.debian.org/Alioth/PackagingProject
...which say's that the Alioth project is now depreciated.

I don't know if this helps.

**Comment by anthonyfok** [comment]
Hi @Paul-Reed,

I am a team member of the Debian Go Packaging Team, and the main maintainer for the Hugo package.

Alioth refers only to the GForce (Sourceforge fork) web interface for managing Debian teams, so Alioth's deprecation does not affect Debian Go Packaging Team's operation.

----

First, an immediate solution (workaround) to get the latest Debian-packaged version of Hugo:

* Visit https://packages.debian.org/sid/armhf/hugo/download and download the existing `armhf` version there, for example, http://ftp.us.debian.org/debian/pool/main/h/hugo/hugo_0.25.1-2_armhf.deb, then use `dpkg -i hugo_0.25.1-2_armhf.deb` to install it.

(Sorry, we are a bit behind and are still working to catch up to Hugo v0.30.2 partly due to the fact that each new Go library need to be packaged and be approved manually, and just that I had been a bit too busy in the past little while.)

----

Now, as you probably know, the Raspbian Stretch OS for the Raspberry Pi is based on Debian 9 (Stretch) which was released in June 2017, but it actually went into a "Soft Freeze" in 2017-01-05, and "Full Freeze" in 2017-02-05, after which no further updates can be made except for release-critical bug fixes.

Hugo v0.19 came out on 2017-02-27, and so, Hugo v0.18.1 (released 2016-12-30) was the very latest version before Stretch's Freeze.

Now, Debian is renowned for its "stability", so software in the `stretch/stable` distribution usually don't get updated to newer versions except for, say, security fixes, though there is a `stretch-backports` repository that users can use to get newer software that has been back-ported from Debian's "sid" (cutting-edge development version) to `stretch/stable`.

It is possible, but non-trivial, to have the latest Hugo backported to Debian `stretch-backports` (probably needing to backport 20 to 30 Go library packages at the same time), but it is something we can consider trying in the future.

Meanwhile, Raspbian does not use a `stretch-backports` repository as far as I know, but perhaps we (the Debian Go Team) can talk to the Raspbian developer, or becoming a Raspbian developer, to see if they can carry the latest Hugo package.  So, I'll start approaching them and see if it is a possibility, and, if so, how to actually do it.

----

So, thank you @Paul-Reed for bringing up this topic, and it is indeed a noble goal to see Raspberry Pi's recommended Raspbian OS carry the latest and greatest Hugo, but there is quite a bit of work ahead of us to reach that goal.

In the mean time, please just download either https://github.com/gohugoio/hugo/releases/download/v0.30.2/hugo_0.30.2_Linux-ARM.deb or http://ftp.us.debian.org/debian/pool/main/h/hugo/hugo_0.25.1-2_armhf.deb to get the latest Hugo running in your Raspbian Stretch.  (It works great also in the older Raspbian Jessie!)

Hope this helps,

Anthony

**Comment by Paul-Reed** [comment]
Many thanks Anthony, that's most helpful. I've just updated to v0.30.2 and continues to work fine under Raspbian Stretch. It's reassuring to be back up to date again!

Paul
