### ISSUE TITLE
source code blocks in org not rendered correctly

### ISSUE THREAD

**Issue by rafaelleru** [gohugoio/hugo#4006]
When a source code block of org-mode is tabulated from the start of the line isn't rendered correctly but it if start at the begin of the line it shows correctly. Here some example code:
```

* some tabulated code
    #+BEGIN_SRC emacs-lisp
    (defun small-shell ()
	(interactive)
	(split-window-vertically)
	(other-window 1)
	(shrink-window (- (window-height) 12))
    (ansi-term))
    #+END_SRC
```
And here it is the rendered code:
![image](https://user-images.githubusercontent.com/6851409/31960375-e11aba6e-b8f7-11e7-9758-03c2ebd88ea3.png)

**Comment by kaushalmodi** [comment]
You will have to open an issue for this on https://github.com/chaseadamsio/goorgeous.

But FWIW, I tested out your snippet using the `ox-hugo` Emacs package, and it works fine using that because it uses native Org mode to render the exports. Check out https://ox-hugo.scripter.co for more info.

PS: I maintain that package.

**Comment by bep** [comment]
@kaushalmodi please don't use slightly related issues to promote your own packages.

**Comment by kaushalmodi** [comment]
@bep Sorry, understood.

**Comment by rafaelleru** [comment]
maybe is my hugo theme??

**Comment by kaushalmodi** [comment]
No, this has nothing to do with the theme.
