### ISSUE TITLE
Proposal: Extend shortcodes to support inline property lookups

### ISSUE THREAD

**Issue by moorereason** [gohugoio/hugo#4013]
### Proposal

Extend the shortcodes syntax to allow the following inline lookups without the need for a defined shortcode template:

```
{{< .Site.BaseURL >}}
{{% .Title %}}
```

* Default context is the current page.
* Any shortcode that begins with a dot (`.`) will cause a lookup of that property.
* Normal shortcode names would not be allowed to begin with a dot.
* No pipelining is supported (such as `{{< .Site.BaseURL | urlize >}}`).

### Rationale

When wanting to insert page or site variables (such as `.Site.BaseURL`) into a content page, it's a little cumbersome to have to setup and use a shortcode template such as `{{< site "BaseURL" >}}`.  It would be simpler for the user to be able to use the shorter syntax in the proposal.  It should be more intuitive since it behaves much like Go templates (minus the pipelining).

Related to #4010

**Comment by kaushalmodi** [comment]
I'd like to have this feature.

**Comment by vassudanagunta** [comment]
@moorereason @kaushalmodi, 

First, let me say I'm writing this not to butt heads, but to understand the need, because it relates to   the [standard that I'm writing](https://github.com/Markaround/markaround/blob/placeholder/README.md).

Is this necessary? I'm a big believer in separating content from presentation.  This behind the distinct roles of HTML and CSS/JS, as well as in the design of Markdown itself. In my view the ideal SSG would both enable and encourage such a separation. The aforementioned standard is all about making it easier for authors to write content without being concerned about presentation, or portability.

For Hugo it's rather simple: the content "concern" owns the content directory, and the presentation "concern" is the realm of the themes/templates directory and the Hugo code itself.

To me shortcodes are basically ways to extend the expressivity of Markdown. The author can include a new kind of content, as defined by shortcodes such as `figure` and `tweet`. The it up to the templates/shortcode definition/CSS/Hugo to decide how to render them.

The request in this Issue goes in the other direction. Rather than handing off content to the presentation layer, it is asking the layer for content or information. In the requesting example, why would an article have to know about `.Site.BaseURL`?  It can link to the home page via `rel`/`relref` shortcodes (though I don't even think those shortcodes are necessary, but that is another topic). Is it the case the the example is actually part of the site navigation, and thus rightly belongs in the templates (presentation) and not in the Markown?

**Comment by kaushalmodi** [comment]
I see that it's almost 4 months since I last commented. Having learned about Hugo and templating a lot more since then, I don't think I would need this feature. 

I agree about separating content from layout.

**Comment by bep** [comment]
No, I have thought about this, and looking at the comments above: This is creating more work than it solves.
