### ISSUE TITLE
Tag names are always lowercase—but not in every Hugo project

### ISSUE THREAD

**Issue by Brixy** [gohugoio/hugo#4044]
Hi all,

Hugo seems to treat tags differently here (lowercase vs. uppercase as in front matter). Case 1 without, case 2 with an empty line before the trailing `---`.

Front matter:

```
---
title: Test
tag:
- Test1
- Test2
---
```

Result:

```
test1, test2
```

Front matter:

```
---
title: Test
tag:
- Test1
- Test2

---
```

Result:

```
Test1, Test2
```

Unfortunately I was not able to reproduce this issue in a personal project. The reason might be, that redundant tags appear in lower and upper case in YAML in the same (big) project.

Thank you!

**Comment by bep** [comment]
Thanks for getting in touch, but it feels like this is a question  that would be better suited to the [Hugo Discussion Forum](https://discourse.gohugo.io/).  We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug. You may also find the answers you search for in [Hugo Documentation](http://gohugo.io/overview/introduction/).
