### ISSUE TITLE
Evernote .enex directly into data directory

### ISSUE THREAD

**Issue by chris2fr** [gohugoio/hugo#4055]
Hi,

The Evernote export format exports notes into specific .json files. Can we create a Hugo theme that would be an Evernote reader?

I think it would be interesting. 

Any thoughts,

Chris

**Comment by kevingimbel** [comment]
Hi Chris,

I think this question is better suited for the Forum at https://discourse.gohugo.io/

The GitHub Issue tracker is for issues with hugo only, in the Forum however people should be able to help you or give you input on your idea and if it turns out to be a generic solution that could benefit more users you can create a new issue with a spec.

All the best,
Kevin
