### ISSUE TITLE
Shortcodes are not working

### ISSUE THREAD

**Issue by Monsterovich** [gohugoio/hugo#4066]
If there is nothing but only shortcode, it returns an error.
**mymusic.md**

> {{< soundcloud >}}

but it works when I put any text.

> I love hugo!
> 
> {{< soundcloud >}}

**Hugo version:** hugo_0.30.2
**Error:**
> Started building sites ...
> ERROR 2017/11/08 22:18:35 failed to parse page metadata for "work/mymusic.md": invalid character '{' looking for beginning of object key string
> Error: Error building site: Errors reading pages: Error: failed to parse page metadata for "work/mymusic.md": invalid character '{' looking for beginning of object key string for mymusic.md

**/layouts/shortcodes/soundcloud.html**
> 
> 
> <iframe width="100%" height="300" scrolling="no" frameborder="no" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/playlists/271632492&amp;color=%234969ac&amp;auto_play=true&amp;hide_related=false&amp;show_comments=true&amp;show_user=true&amp;show_reposts=false&amp;show_teaser=true&amp;visual=true"></iframe>
>

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).

**Comment by vassudanagunta** [comment]
@bep Maybe you should create a "read the README/docs" label? The issue just before this one: #4065.  Where is the "sigh" emoji?

**Comment by shadycuz** [comment]
@bep 

Are we sure this isn't a bug or a feature request? I would also like to put a shortcode at the top of my post but can't.

**Comment by davidsneighbour** [comment]
What we are sure of is, that it's not explicitly explained. there is no sample for `mymusic.md` and `mymusic.md` is not a feature of Hugo that anyone would know about. It's also an issue from 2017. Lastly: "I would also like to put a shortcode at the top of my post but can't." does neither explain any issue nor does it have any correlation to the original issue. 

Go to discourse.gohugo.io. Add a post. Explain what you want to do and how you try it and how it "fails" or make you "can't do" it. 

You need to understand that THIS is a bug tracker for real existing bugs and not for support requests.

**Comment by shadycuz** [comment]
@davidsneighbour 

I didn't think I had to explain it, @Monsterovich already did...

> You need to understand that THIS is a bug tracker for real existing bugs and not for support requests.

**YOU** need to understand **THIS**:

>
>If there is nothing but only shortcode, it returns an error.
>`{{< soundcloud >}}`

>  but it works when I put any text.
>```
>I love hugo!
>{{< soundcloud >}}
>```

For anyone else that is coming here for this BUG the workaround is:

```
---
---
{{ yourShortcode }}
```

**Comment by n8behavior** [comment]
Yup...it's a bug and @shadycuz's fix works great.  @davidsneighbour not sure why you are so salty with people just asking for help but hope your day starts going better.

**Comment by moorereason** [comment]
@shadycuz & @n8behavior,

1. There are few Hugo contributors.  With Hugo's relative popularity, it can be difficult to keep up with Github issues, especially when some are not real or reproducible bugs.  We prefer to flesh out potential issues in the forums in order to keep Github cleaner, which often feels like rolling a stone uphill.  Which can lead to...
2. Saltiness.  Sorry about that.  We mean well.  I'm sure @shadycuz meant well in return.  :smile:
3. Please don't comment on closed issues.  If we don't reopen the issue (as is happening here), your comment can get lost. Open a new issue and reference the old one.
4. Lastly, **I'm unable to reproduce this issue**.  If you can create a reproducible scenario with the **latest version of Hugo**, report the issue in the forums and ask for confirmation from others.  If we can't reproduce it, we're in danger of violating 1 and 2 above.  :wink:
