### ISSUE TITLE
Automatic creation of <p> class

### ISSUE THREAD

**Issue by jensamunch** [gohugoio/hugo#4074]
Hey guys,

First comment - Hugo is amazing. It's been so great for our work-flow.
Quick comment on bug/feature:

1. We wanted to insert some markdown content in a partial:
<p class="lead">{{ .Content }}</p>

2. The content was: Here **something bold** and something else

3. Hugo keeps creating new <p> tags outside of the p tags where I want them.

4. I ended up having to spend 30 mins troubleshooting and finally wrapping the .Content with a div was the only thing which worked.

**Comment by bep** [comment]
Thanks for getting in touch, but it feels like this is a question  that would be better suited to the [Hugo Discussion Forum](https://discourse.gohugo.io/).  We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug. You may also find the answers you search for in [Hugo Documentation](http://gohugo.io/overview/introduction/).

**Comment by jensamunch** [comment]
I'm sorry I don't really get why this isn't appropriate for bug/enhancement.

This:
<p class=lead>{{ .Content }}</p>

Becomes :
<p class=lead></p>
<p>{{ .Content }}</p>

That feels like a bug to me.

**Comment by jensamunch** [comment]
PS. I'm sorry I see the last post was very unclear.
