### ISSUE TITLE
Deprecate and then rename/remove Page.URL

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#4117]
I cannot think of one valid use case for it, and I see it used in the wild all the time when `RelPermalik` or `Permalink` is the correct choice.

`URL` returns the front matter value for regular pages, if set, else it return the `RelPermalink`.

**Comment by onedrawingperday** [comment]
I am not in favor of removing Page.URL. 

For example 
if eq .URL "/some-url/" provides an easy way to add an active class to page links that live outside Hugo's menu configuration (for various reasons) Also this is handy in cases where it's difficult to do a .Permalink or .RelPermalink check, like in Nested Sections list pages.

But if you really think these are not valid use cases. Go ahead and remove it. I'll look into what can be done to replace its functionality... like I always do...

**Comment by Jos512** [comment]
`.URL` and `.Permalink` are indeed much the same, although the first returns a string value and the second a `template.HTML` value. So even though they return the same data, they behave differently:

~~~plain
{{ if in .URL "hugo" }}
...
{{ end }}

{{ if in (.Permalink | string) "hugo" }}
...
{{ end }}
~~~

I agree there's some redundancy. And on one hand I think Hugo template code might become easier when there's no two variables that return the same value. But on the other hand the required conversion to string of `.Permalink` might be more odd to newcomers than two variables.

That latter might also make explaining how people can update from `.URL` to `.Permalink` somewhat confusing. (Assuming we use a terminal message for this like Hugo did with previous depreciations.)

I don't know what wisdom is in this case. 😆

**Comment by onedrawingperday** [comment]
> Or should we assume people read the release notes, where this can be explained more fully?

If the recent release of Hugo 0.32 is any indication I would say that people don't bother with the release notes. The forum is full of posts regarding `index.md`

A Warn like @Jos512 is the way to go. 

And possibly an example of the `.Permalink `translation to a string value, in the Release notes.

You cannot assume that every user of Hugo has used every one of its functions or that he/she knows what to do in advance. Not all of us are from a Dev background.

**Comment by onedrawingperday** [comment]
> {{ if in (.Permalink | string) "hugo" }}

I just want to say that the above approach would not work with `.FirstSection` list pages because obviously the `string` is also present in the Nested Sections of that section.

For example let's say that I have a section called `/women/` and a nested section called `/women/backpacks` and I want to have each custom menu entry of these links have a selected class when the user is in their corresponding URL. With the above both menu entries would have the selected class under both URLs.

But thanks to Hugo 0.45.1 and `.FirstSection` here is how I finally managed to do this.

```
{{ $currentURL := .Permalink }}
{{ with .FirstSection }}
<a {{ if eq .Permalink $currentURL }}class="selected"{{ end }} href="...">...</a>
{{ end }}
```
And then for other list pages I do the following check:
```
{{ if eq .Permalink $currentURL }}class="selected" {{ end }}
```

So at this point, I am fine with `.URL` being deprecated from Hugo, since I can have the functionality I need with other simple means.

**Comment by onedrawingperday** [comment]
Actually if `.Page.URL` is deprecated and removed it will break several older themes that are currently in the Hugo Themes showcase.

And that is not a bad thing. 

Since it will force theme authors to update their themes or if they don't we can always clean up the showcase from unmaintained themes.

So +1 for this issue.

**Comment by onedrawingperday** [comment]
@bep 

Please consider removing `.Page.URL` in the next Hugo release. I think that it's about time.

There are out-of-date themes and perhaps tutorials floating around users keep on bumping on the `.Page.URL` deprecation notice and the deprecation message is still causing questions as shown [here](https://discourse.gohugo.io/t/url-deprecated/36559/8).

It's better to break some old projects rather than wasting time explaining the deprecation message that's been there since 2017, 5 years later.

**Comment by onedrawingperday** [comment]
@bep 

Please consider removing `.Page.URL` in the next Hugo release. I think that it's about time.

There are out-of-date themes and perhaps tutorials floating around and some users keep on encountering the `.Page.URL` deprecation notice and having questions about it, as shown [here](https://discourse.gohugo.io/t/url-deprecated/36559/8).

It's better to break some old projects rather than wasting time explaining a deprecation message that was added in 2017, five years later, in 2022.

**Comment by bep** [comment]
@onedrawingperday hmm... I was sure I removed that in the previous release. O well, thanks for the heads up.
