### ISSUE TITLE
GetPage behavior differs between auto-generated and existing pages; existing pages cannot be looked up by Title

### ISSUE THREAD

**Issue by tsuereth** [gohugoio/hugo#4118]
Following on the discussion in #4092 , I'm using `Site.GetPage` to retrieve information about a page for some arbitrary TaxonomyTerm.

Meanwhile, I also have manually created content for some (but not all) of the terms used on my site.

When GetPage is invoked with a term for which I *have not* created a content page, the lookup works as I expect: for example, `$.Site.GetPage "taxonomyTerm" "game" "Game Title"` will retrieve a Page which Hugo has automatically-generated for the "Game Title" term.

However, when GetPage is invoked with a term for which a content page exists, this no longer works: searching for "Game Title" will return `nil`.

From examining the surrounding code, this is because Page behavior differs for pages which have been generated by Hugo, versus those which exist and have been indexed by Hugo.  The former are indexed by title, while the latter are indexed by document path.

(Thus, if I were to `$.Site.GetPage "taxonomyTerm" "game" "game-title"` then it would retrieve the Page I wanted.  However, since my goal was to retrieve the page without replicating path-sanitization rules, this is contrary to my purpose.)

**Comment by bep** [comment]
Thanks for getting in touch, but it feels like this is a question  that would be better suited to the [Hugo Discussion Forum](https://discourse.gohugo.io/).  We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug. You may also find the answers you search for in [Hugo Documentation](http://gohugo.io/overview/introduction/).

**Comment by tsuereth** [comment]
@bep this behavior does seem like a bug to me.  Do you disagree?

**Comment by bep** [comment]
>@bep this behavior does seem like a bug to me. Do you disagree?

Obviously, given my answer above.

In general, it would be good if you, instead of creating a PR with a proposed solution, you instead create a PR with a breaking test that explains the problem. 

There is no difference in the lookup code path for GetPage for taxonomies with and without a content page, and the PR you proposed is ambiguous.

**Comment by tsuereth** [comment]
That's a good point.  I added some tests in #4120 , which I hope will clarify the problem.

When GetPage is invoked on a Taxonomy Term title (in the initial example, "Game Title") then it will work fine.  All other cases of using GetPage with a page title will fail.

Actually, these tests helped show that my attempted fix in #4119 is not sufficient.  I will amend that PR if appropriate.
