### ISSUE TITLE
Post inheritance

### ISSUE THREAD

**Issue by joshlf** [gohugoio/hugo#414]
_[Originally proposed in [this thread](https://groups.google.com/forum/#!topic/hugo-discuss/larVTJ8H9c4) on hugo-discuss.]_

This is a suggestion for a feature similar to archetypes. With this (so far nameless) feature, it would be possible to define a skeleton content file for a particular type. The frontmatter in this file would be inherited by any content of that type (though it would be possible to override any of the inherited variables).

The impetus behind this feature is to allow the writer to define in the skeleton file any variables that often have the same value so that they don't have to re-specify them in any piece of content where they'd just be left as default. For example, if the "post" type has a taxonomy of "tags," and the template to display these tags assumes that they are defined, the writer must write "tags = []" (or equivalent) for any post which doesn't have any tags. With this feature, they could simply put that declaration in the skeleton file.

**Comment by rickb777** [comment]
I thought this was what content types were for. Now I realise I was wrong.

One might argue that being able to define content types in some way like you suggested would actually be more useful than having archetypes. In a lean world, archetypes could be dispensed with to keep things simple.

The difference is that archetypes are used only when the content is first created.  The content then diverges from its archetype as it gets edited.  Conversely, first-class content types would possibly have an impact for the entire lifetime of each post.  For example, if the content type defines some tags and a post does not override them, then the tags would change on the post if ever the content type were changed.

**Comment by quoha** [comment]
It would be handy to define that a theme level. That way if I ever updated my theme to add a new front matter variable, I wouldn't have to go back through all the prior .md files just to add in the default.

**Comment by stou** [comment]
+1 for the use with the variables used by the theme

**Comment by synful** [comment]
I'm skeptical that themes are the right place for this. Aren't themes meant
to specify general visual layout, not site hierarchy? I mean, they do some
of the latter, but I feel like (at least for me), when you use a theme you
use it primarily for the visuals.

**Comment by rickb777** [comment]
@synful I agree. It would be a shame to muddle the conceptual model of Hugo.

**Comment by balazswmann** [comment]
I have a similar idea that the issue description with an additional twist.

Lets assume you have a "blog" section with a "posts" directory in it. The actual blog posts will be placed into the "blog/posts" directory for example: "blog/posts/some-content.md". Now, if you don't specify the type attribute in the some-content.md file then the type will be "blog" so the section name will be inherited, but lets assume you want to use the "blog_post" type here. The problem is, that if you want to use the same specific type under "blog/posts" you will have to specify the type attribute in every markdown file. So what I would like to say is that it would be very helpful if the some-content.md file could inherit not just regular attributes but even the type itself. I think the most straightforward way to do this would be to check the nearest _index.html file in the "ancestor directories". For example if there would be an _index.html file in "blog/posts/_index.html" that could specific a type attribute ("blog_post"), and every descendant content would inherit this attribute.
