### ISSUE TITLE
Hugo (BlackFriday) tabSpaceEight enabled by default?

### ISSUE THREAD

**Issue by NfNitLoop** [gohugoio/hugo#4146]
The [docs] say:

> tabSizeEight
>
> default: disabled
> Purpose: When enabled, expand tabs to eight spaces instead of four.

But, tabs in my fenced code are being expanded to eight spaces by default.

Is the documentation or the behavior incorrect?

I tried creating a `bf-config.toml` with the following:

~~~toml
[blackfriday]
extensionsmask = [ "tabSizeEight", "fencedCode" ]
~~~

But that doesn't seem to change anything. (I can't even tell if the file is being read.)

[docs]: https://gohugo.io/content-management/formats/#blackfriday-extensions

**Comment by bep** [comment]
Thanks for getting in touch, but it feels like this is a question  that would be better suited to the [Hugo Discussion Forum](https://discourse.gohugo.io/).  We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug. You may also find the answers you search for in [Hugo Documentation](http://gohugo.io/overview/introduction/).

**Comment by NfNitLoop** [comment]
>  We prefer to use GitHub issues only for bugs and enhancements

It's not a bug that the documentation says one thing, but the behavior does a different thing?
