### ISSUE TITLE
Include node module in static js

### ISSUE THREAD

**Issue by aentan** [gohugoio/hugo#4158]
Installed a node package via `npm i resize-start-end -S'`.

This is the instruction provided by the package:
```
    // ESM
    import resizeStartEnd from 'resize-start-end';
 
    // or CommonJS
    const resizeStartEnd = require('resize-start-end');
```

I'm trying to include the package in a JS file in my hugo static directory. None of the above works (can't be found).

My js is located in `static/src/js` and gulp will concat it into `static/js`.

Advice appreciated.

**Comment by kevingimbel** [comment]
Hi @aentan ,

I think this question is better suited for the Forum at https://discourse.gohugo.io/

The GitHub Issue tracker is for issues with hugo only, in the Forum however people should be able to help. Your problem is related to bundling and/or build steps which are not related to Hugo as a software - most likely your import path(s) are wrong.

All the best,
Kevin

**Comment by aentan** [comment]
Wasn’t aware of that place. Thanks!!!
