### ISSUE TITLE
Short dash cannot be correctly rendered in yaml code.

### ISSUE THREAD

**Issue by lxzxl** [gohugoio/hugo#4171]
Hugo is an excellent tool but I got a problem about "-" in yaml code when it's inside of a list item. It seems that Hugo parses the short dash as a markdown list while it should be a yaml's list. 

![image](https://user-images.githubusercontent.com/2275002/34073215-afafe952-e2cf-11e7-94d4-64b8b43bb632.png)

which result:

![image](https://user-images.githubusercontent.com/2275002/34073222-cf0e6db4-e2cf-11e7-9425-8de984c839f4.png)

Thanks.

**Comment by digitalcraftsman** [comment]
In Markdown you either indent code blocks with four spaces **or** you use fenced code blocks (i.e. the three backticks). Using both doesn't work.

In the future, please refer to the [Hugo Discussion Forum](https://discourse.gohugo.io/) for questions.

**Comment by lxzxl** [comment]
@digitalcraftsman Thank you for your answer! I found 8 spaces can solve the problem.

**Comment by kaushalmodi** [comment]
@lxzxl If I understand correctly, this is the same as this Blackfriday bug: https://github.com/russross/blackfriday/issues/239

**Comment by lxzxl** [comment]
@kaushalmodi Good idea, thank you! But the HYPHEN character breaks YAML file. So it doesn't work for my case.

**Comment by radu-munteanu** [comment]
Gitlab, Github, even Okular in KDE shows the md files right. This is a BUG in Hugo. I don't know if this issue is closed.

- The 8 spaces hack works, but it's not perfect, it indents all code by one tab (4 spaces).
- changing the character with a similar one does fix the looks, but it will fail to create a valid YAML when you copy paste the code.
