### ISSUE TITLE
URL Path need encode

### ISSUE THREAD

**Issue by stkevintan** [gohugoio/hugo#4180]
hugo autogenerated url path should be uriencoded.

eg : the `C#` tag will make some url path become `http://xxxxx/tags/C#` which `#` is a special character in the url.

related issue: <https://github.com/stkevintan/hugo-YAMT-theme/issues/4>

**Comment by bep** [comment]
Thanks for getting in touch, but it feels like this is a question  that would be better suited to the [Hugo Discussion Forum](https://discourse.gohugo.io/).  We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug. You may also find the answers you search for in [Hugo Documentation](http://gohugo.io/overview/introduction/).

**Comment by stkevintan** [comment]
Hello, thanks for your reply.I have read some source code of seveval hugo themes, but I haven't find my answer.

Here is a piece of code in my  `terms.html`: 

```golang
<a href ="/{{ $data.Plural }}/{{ $value.Name | urlize }}">C#</a>
```
but,`urlize` function cannot process `#`,because `#` is fragment identifier. 
so, if we have a tag name `C#`, the above code will generate into:
```html
<a href="/tags/c">C#</a>
```
In fact , `/tags/c%23` should be the correct one, and `/tags/c` may be 404.

I know `urlize` is design for encode the entire url which should not process `#` and `/`, so is there a suitable function that can encode a part uri ? ( just like `encodeURIComeponent` in javascript do)
