### ISSUE TITLE
disqus_identifier with uppercased is changed to lowercase

### ISSUE THREAD

**Issue by seblucas** [gohugoio/hugo#4185]
Hi,

I'm migrating my old blog to Hugo (using 0.31.1 on Windows / Linux 64bits), all went well until I started to migrate disqus.

I have some page name (slug) that were containing uppercase characters. It was an error back when I created them but I must live with it :(.

One of this file has this front matter :

```
---
title: "COPS 1.0.0RC3"
date: 2014-12-30
tags: [calibre,ereader,nginx,opds,php]
slug: cops-1.0.0RC3
disqus_identifier: /blog/cops-1.0.0RC3
---
```

The slug is being lowercased .... that's not surprising and I have no problem with it. But my `disqus_identifier` is also lowercased, check the content of the embedded script in my generated html page : 

```

    var disqus_config = function () {
    this.page.identifier = '\/blog\/cops-1.0.0rc3';
    
    
    };
    (function() {
        if (["localhost", "127.0.0.1"].indexOf(window.location.hostname) != -1) {
            document.getElementById('disqus_thread').innerHTML = 'Disqus comments not available by default when the website is previewed locally.';
            return;
        }
        var d = document, s = d.createElement('script'); s.async = true;
        s.src = '//' + "REDACTED" + '.disqus.com/embed.js';
        s.setAttribute('data-timestamp', +new Date());
        (d.head || d.body).appendChild(s);
    })();
```

Is this a bug or is there a parameter somewhere ?

Disqus is case sensitive so that feel wrong.

**Comment by bep** [comment]
Thanks for getting in touch, but it feels like this is a question  that would be better suited to the [Hugo Discussion Forum](https://discourse.gohugo.io/).  We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug. You may also find the answers you search for in [Hugo Documentation](http://gohugo.io/overview/introduction/).
