### ISSUE TITLE
 RSS error： PCDATA invalid Char value 8

### ISSUE THREAD

**Issue by Jackliu007888** [gohugoio/hugo#4214]
when I update a blog, I found rss error：
_This page contains the following errors:
error on line 455 at column 40: PCDATA invalid Char value 8
Below is a rendering of the page up to the first error._

I do not know whether hugo has regular filtering when generating rss。

**Comment by bep** [comment]
Thanks for getting in touch, but it feels like this is a question  that would be better suited to the [Hugo Discussion Forum](https://discourse.gohugo.io/).  We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug. You may also find the answers you search for in [Hugo Documentation](http://gohugo.io/overview/introduction/).
