### ISSUE TITLE
baseof.html in Theme _default not working

### ISSUE THREAD

**Issue by bastienvinh** [gohugoio/hugo#4226]
Hugo Version: v0.32.2
OS: Mac OSX

When I try to use baseof.html only with only a theme, it is not working, I can't see my single article.

I created a /themes/[theme]/layouts/_default/baseof.html. After that, I tried to verify my code is working on a single article. So I go directly to the page. After that, I found out a 404 page.

Did you implement the 10th case of the template? Is it working? Should I use segment differently?

**Comment by bep** [comment]
Thanks for getting in touch, but it feels like this is a question  that would be better suited to the [Hugo Discussion Forum](https://discourse.gohugo.io/).  We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug. You may also find the answers you search for in [Hugo Documentation](http://gohugo.io/overview/introduction/).
