### ISSUE TITLE
Default page created for mixed-case taxonomy folders with content file 

### ISSUE THREAD

**Issue by nanov** [gohugoio/hugo#4238]
An isolated test case can be found [here](https://github.com/nanov/hugo-taxonomy-test).

When trying to display taxonomy metadata page ( /layout/_default/taxonomy.html ) when the template contains more then one line the ".Params" are not loaded.

In the above example the behaviour can be seen on ( /authors/MaxMustermann ), if another line is added to the template file ( or actually any other content ) nothing is displayed.

As the behaviour is inconsistent I assume it is a bug.

**Comment by bep** [comment]
I can reproduce it, but that is some curious bug ... Thank for the report; esp. appreciate the repro.

**Comment by bep** [comment]
I can also reproduce this for 0.31.1 so this isn't a brand new issue.

**Comment by bep** [comment]
OK, I see what happens. 

* We match by path vs taxonomy to determine if we have a content page for that taxonomy
* The taxonomy name is (if `preserveTaxonomyNames` is not set) normalized to `maxmustermann` while you have the disk folder called `MaxMustermann`.
* This isn't a new issue, but I suspect most people will just name the folder `authors/maxmustermann` and it will just work.
* The inconsistent behaviour you see here is that you will end up with two pages with the same target filename, so it is a little random who will win.

This isn't a regression in Hugo 0.32, but I can see the confusion, and the fix is easy enough, so I will include it in today's release.

**Comment by nanov** [comment]
Thank you very much for the quick response and even quicker fix!
