### ISSUE TITLE
Config : baseURL and baseUrl overwrite url despite the sensitive case ?

### ISSUE THREAD

**Issue by jonathanulco** [gohugoio/hugo#4294]
Hello team,

I have a little problem with the config file.
This one has a baseURL then in[params] I have baseUrl which corresponds to a parameter for a javascript. It is true that baseURL and baseUrl are quite similar, but it seemed to me that Hugo was a case sensitive.
The problem is that Hugo overwrite urls with baseUrl, even if I use absURL. 
I just need to fix the baseUrl for example dataBaseUrl to solve the problem. 

Nevertheless, I wanted to point out this problem.

I hope to be understanding enough.

**Comment by bep** [comment]
Thanks for getting in touch, but it feels like this is a question  that would be better suited to the [Hugo Discussion Forum](https://discourse.gohugo.io/).  We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug. You may also find the answers you search for in [Hugo Documentation](http://gohugo.io/overview/introduction/).
