### ISSUE TITLE
Partial templates broken after 0.31.1

### ISSUE THREAD

**Issue by raghur** [gohugoio/hugo#4300]
So I ran into a nasty issue today - Hugo 0.32.4 (and 0.33) broke my site using this template https://github.com/appernetic/hugo-bootstrap-premium
The error specifically was a "cannot find partial 'head'"
Google pointed me to discussion on discourse to use the full filename - so `{{ partial "head.html" .}}`. I applied that to my template overrides as well as to the theme (fork here - https://github.com/raghur/hugo-bootstrap-premium/tree/partial-html-suffix). However, even with that, hugo the same error persisted. 

I decided to bisect - with the same setup, v0.31.1 is the last version where the site renders. v0.32 onwards, I get a 'partial not found' error.

Has something changed in the way partials are resolved in between those releases (or is there a pointer to some documentation?)

**Comment by vassudanagunta** [comment]
`{{ partial "head" . }}` works in my templates, and I'm pretty sure most of the other themes have that exact same code and they continue to work according to the release notes. 

Something else seems to be going on. I copied your head.html and the partials it depends on into my build and got no such error.

**Comment by bep** [comment]
Thanks for getting in touch, but it feels like this is a question  that would be better suited to the [Hugo Discussion Forum](https://discourse.gohugo.io/).  We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug. You may also find the answers you search for in [Hugo Documentation](http://gohugo.io/overview/introduction/).

**Comment by raghur** [comment]
Ok - I've posted on the support site along with a zip of my blog and the template and outputs with 0.31.1 and 0.33

https://discourse.gohugo.io/t/problem-with-partials-works-with-0-31-1-but-not-afterwards/10091
