### ISSUE TITLE
publishdate page param is not always synced with the Page.PublishDate

### ISSUE THREAD

**Issue by kaushalmodi** [gohugoio/hugo#4323]
**Update**: See [the below comment][3] by @vassudanagunta for the root cause of this issue.

---

Hello,

This can be called a duplicate of https://github.com/gohugoio/hugo/issues/2145. But I am opening this new issue as I find that same issue still unresolved on Hugo v0.34 (and v0.35-DEV as of https://github.com/gohugoio/hugo/commit/3446fe9b8937610b8b628b2c212eb25888a7c1bb).

I had provided a test case that showed that that old issue still looked unresolved. I am pasting that here for convenience.

---

I think the issue is that the `date` in **`.Page.Params`** is left unset if only `publishdate` is set. So if one if looping through all the pages and sorting them in descending order using `.Page.Params.date`, the pages where only `publishdate` is set will be left out.

### Test case

- [Markdown][1] | [Hugo output][2]

Notice the **Page Params (Debug)**  section in the Hugo output linked above. Just as `lastmod` is auto-set based on `publishdate`, the request is that `date` also be auto-set if `publishdate` is specified, but `date` is not specified explicitly in the front-matter. 

---

Copying @vassudanagunta.

[1]: https://gitlab.com/kaushalmodi/hugo-sandbox/raw/ee0f12d396d29b90b047646be4470f95224a5e94/content/bugs/date-and-publishdate.md
[2]: https://hugo-sandbox.netlify.com/bugs/date-and-publishdate/#page-debug
[3]: https://github.com/gohugoio/hugo/issues/4323#issuecomment-360197488

**Comment by vassudanagunta** [comment]
@kaushalmodi The reason I asked you to create a new issue is because I believe this is distinct from that one. #2145 was about [Page Variables](gohugo.io/variables/page/#page-variables), e.g. `.Page.Date` and `Page.PublishDate`. #2145 was fixed when logic was added to default `Page.PublishDate` from `.Page.Date`. 

For whatever reason (I know not the history), Hugo makes (some? all?) Page Variables also available as as [Page-level Params](gohugo.io/variables/page/#page-level-params).  I'm not sure when this was introduced, and which page variables are expected to also be exposed as page params. Your issue is that the `publishdate` page param is synced with the corresponding page variable. I see it in the code. 

Perhaps update your issue title and desc accordingly.

**Comment by vassudanagunta** [comment]
@bep Which Page Variables are shadowed by page params? All of them? I'm working on that part of the code so I can do whatever.

**Comment by bep** [comment]
If you you move this:

https://github.com/gohugoio/hugo/blob/master/hugolib/page.go#L1355

Down to the rest of the "date params setters", it should be correct.

**Comment by kaushalmodi** [comment]
@vassudanagunta Thank you! I confirm the fix.

### Before

![image](https://user-images.githubusercontent.com/3578197/35440970-b9ec3104-026f-11e8-9869-b1f38a0eb4c9.png)

**Note the missing `date` in Page Params.**

### After

*With the exact same front-matter with only `publishdate`.*.. and the `date` is now there, yay!

![image](https://user-images.githubusercontent.com/3578197/35441022-e19aa622-026f-11e8-9b7d-cb18548a4fb2.png)
