### ISSUE TITLE
Nested shortcodes not working in definition list

### ISSUE THREAD

**Issue by Flangour** [gohugoio/hugo#4362]
In a .md file. When you open a shortcode like `container` I want a definition list with a icon in the `<dt>` in the example below it is not working however if you put an enter between the content and the icon it is working. But then the icon is not rendered in the `<dt>`. Am i doing something wrong or is this a bug. If it is a bug. You are welcome!

```
{% container white %}}
{{< icon src="technologies" name="angular" >}}
: De progressive web-app is gebouwd in Angular. Dit framework stelt ons in
  staat snel krachtige webapplicaties te bouwen, met behulp van een moderne
  Webstack.
{{% /container %}}
```
With enter but not in `<dt>`
```
{% container white %}}
{{< icon src="technologies" name="angular" >}}

: De progressive web-app is gebouwd in Angular. Dit framework stelt ons in
  staat snel krachtige webapplicaties te bouwen, met behulp van een moderne
  Webstack.
{{% /container %}}
```

Thanks!

**Comment by bep** [comment]
Thanks for getting in touch, but it feels like this is a question  that would be better suited to the [Hugo Discussion Forum](https://discourse.gohugo.io/).  We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug. You may also find the answers you search for in [Hugo Documentation](http://gohugo.io/overview/introduction/).
