### ISSUE TITLE
Cannot generate a page with hugo v0.35

### ISSUE THREAD

**Issue by 1000ch** [gohugoio/hugo#4367]
https://github.com/openfresh/a11y-guidelines

### `content` folder

- `player/index.md`
- `index.md`

### `public` folder

Output I expect:

- `player/index.html`
- `index.html`

But only `index.html` is generated.

Oddly enough, it renders `public/player/index.html` when I edit `content/player/index.md` after `hugo server`. So `content/**/index.md` seems not to be included as rendering target.

**Comment by bep** [comment]
Thanks for getting in touch, but it feels like this is a question  that would be better suited to the [Hugo Discussion Forum](https://discourse.gohugo.io/).  We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug. You may also find the answers you search for in [Hugo Documentation](http://gohugo.io/overview/introduction/).

**Comment by 1000ch** [comment]
@bep 

I think this is a bug (related #4332 ?), 

> add some more details if you feel this is a genuine bug

To reproduce,

1. Clone https://github.com/openfresh/a11y-guidelines
2. Execute `$ hugo server`
3. Confirm `localhost:1313/a11y-guidelines/player/index.html` is **not rendered**
4. Edit `content/player/index.md`
5. Confirm `localhost:1313/a11y-guidelines/player/index.html` is **rendered**

Is this a behavior that you expect?
