### ISSUE TITLE
Update the internal GA template

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#4479]
https://github.com/gohugoio/hugoDocs/blob/master/themes/gohugoioTheme/layouts/partials/gtag.html#L9

Not sure what to do with the custom dimensions above.  We could add them to site config somehow? We can probably make the `GoogleAnalytics` optionally be a map.

Also see https://discourse.gohugo.io/t/track-outbound-links-with-google-analytics/6289

**Comment by comraderoyce** [comment]
It seems like it would be easier to add a new internal template for Google Tag Manager, then users could manage things like outbound clicks and other events outside of code and without needing to add things to the GA config. It will get hairy doing that because people will still have to add in event tracking, etc. to other areas of the site even after adding things to the GA dimensions. 

Not sure if this makes sense for all use cases, but for things like outbound tracking and other basic events GTM will work without needing configs as a lot of basic event tracking comes out of the box: https://support.google.com/analytics/answer/6164470?hl=en

If someone is trying to set up a super fancy GA setup for their site, they will have to do a bunch of work either way.

**Comment by bep** [comment]
My intention with this was not to add the outbound tracking func from the example above. I think, however, that the best practice today is to use something like this:

```html
{{ with .Site.GoogleAnalytics }}
<script async src="https://www.googletagmanager.com/gtag/js?id={{ . }}"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());
  {{ $site := $.Site.BaseURL | replaceRE "^https?://(www\\.)?([^/]+).*" "$2" }}
  gtag('config', '{{ . }}'});
</script>
{{ end }}
```

The added question above is if we should add some kind of "dimension support" (which is useful, but maybe not known to the common man).

**Comment by brunoamaral** [comment]
What exactly would be saved in the Custom Dimension ?

I work with corporate websites and our strategy is to save in custom dimensions anything that pertains to the user or the session. If it's related to content, we save it as a Content Group.

The difference between the two is that content groups need to be set in each new Google Analytics View (we solve it by copying from a Master View). 

My point here is that the way people implement Custom Dimensions and Content Groups depends on the way they have structured their website and GA Account.

**Comment by martijnvv** [comment]
Hi @bep you may want to have a look at a bit of code I wrote on this topic. As a digital analyst I work with GTM on a daily basis, so I have a good idea of how this should work. Let me know if this is useful: [How to add Google Tag Manager to a Hugo static website](https://martijnvanvreeden.nl/how-to-add-google-tag-manager-to-hugo-static-website/)

**Comment by chalin** [comment]
Might you also consider this issue closed by #8287?
(And/or a dup of #4327?)

**Comment by chalin** [comment]
Updated link to the `gtag.html`: https://github.com/gohugoio/gohugoioTheme/blob/master/layouts/partials/gtag.html#L9

**Comment by dongorgan** [comment]
File deleted https://github.com/gohugoio/hugoDocs/blob/master/themes/gohugoioTheme/layouts/partials/gtag.html#L9
