### ISSUE TITLE
Cross-link to #3459: IsMenuCurrent() returns false if menu item defined inside config file

### ISSUE THREAD

**Issue by Brixy** [gohugoio/hugo#4480]
Sorry. I’m not confident with ‘GitHubbing’.

As I can not reopen #3459 this issue is just a cross-link.

Hope, this is the correct way.

**Comment by bep** [comment]
Thanks for getting in touch, but it feels like this is a question  that would be better suited to the [Hugo Discussion Forum](https://discourse.gohugo.io/).  We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug. You may also find the answers you search for in [Hugo Documentation](http://gohugo.io/overview/introduction/).
