### ISSUE TITLE
Terms (Tags/Categories) output incorrect/broken directory names

### ISSUE THREAD

**Issue by crgeary** [gohugoio/hugo#4519]
I hit a problem where one of my tags contains the hash `#` character, and Hugo is generating a directory with the `#` in it (which of course would not work on the web).

Tag: `"#hi"`
Folder created: `/tags/#hi/`

***

I then ran into another problem. I created a tag called `no` (unquoted), and this seems to create a folder called `false` which I am really confused about.

Tag: `no`
Folder created: `/tags/false/`

***

Hugo version: `v0.37.1`
Mac OS: `v10.11.6`

**Comment by kaushalmodi** [comment]
You cannot have tags contain "#".. rename your tags, and you need to double-quote the "no".. YAML spec. Further discussion better belongs in https://discourse.gohugo.io/ as the issues you raised have already been addressed there in older posts (as recent as last week!).

**Comment by paulcmal** [comment]
I found [this discussion](https://discourse.gohugo.io/t/number-sign-in-post-title-causes-a-broken-link/990) from a while back, but nothing recent. Care to point us in the right direction @kaushalmodi?

Also, if I understand [the code](https://github.com/gohugoio/hugo/blob/eb42774e587816b1fbcafbcea59ed65df703882a/helpers/path.go#L84) correctly, spaces are replaced by dashes, then [UnicodeSanitize](https://github.com/gohugoio/hugo/blob/eb42774e587816b1fbcafbcea59ed65df703882a/helpers/path.go#L118) is called to remove unwanted characters. However, `#` is not an unwanted character in URLs, except in the generated slugs. So that means we need to strip the `#` before? 

I found [this issue](https://github.com/gohugoio/hugo/issues/1017), which inspired me to do a little messing around. It appears `#` is perfectly handled in titles now, but not in URLs generated from filenames (foo#bar.md or foo#bar/index.md). The files in `public` are put in the `foo#bar` folder as expected, but these are unreachable because a such name is against web conventions, `#` being reserved for [fragment identifiers](https://en.wikipedia.org/wiki/Fragment_identifier).

Should this be adressed (i.e. `#` stripped from **generated** URLs) or documented as unsupported?

**Comment by kaushalmodi** [comment]
> but nothing recent. Care to point us in the right direction @kaushalmodi?

It was probably [this][1].

> these are unreachable because a such name is against web conventions, # being reserved for fragment identifiers.

Exactly! Pounds in tag names will end up in the URL and clash with the fragment identifiers. I haven't tried.. but the browser with probably pick the first found # as the fragment identifier. 

[1]: https://discourse.gohugo.io/t/sanitizing-category-names/11087

**Comment by crgeary** [comment]
@shaform unfortunately not.. As of v0.44, this problem still exists.

**Comment by shaform** [comment]
@crgeary Oops, I should have said "this issue might be fixed if the PR gets merged in the future".

**Comment by shaform** [comment]
@crgeary Now that #4388 is merged, I guess the `#` issue is fixed? `#hi` should now output `hi` I guess. So perhaps this issue could be closed.
