### ISSUE TITLE
relLangURL and absLangURL with /engineering and other URLs that has a commonn language part

### ISSUE THREAD

**Issue by nurnware** [gohugoio/hugo#4530]
### Symptom
* Sites created with multilanguage do reference target URLs wrong, if the target starts with the current site's language. For instance, if my default site's language is set to "en" and I link to "/**en**gineering" while the template/theme pipes this through `relLangURL` or `absLangURL`, the resulting target URL is wrong.

### Expected
* Link to "/engineering" with language set to "en" should result in "/en/engineering"
* Link to "/test" wit language set to "en" should result in "/en/test"

### Result
* `relLangURL` and `absLangURL` both return a URL that's wrong, "/engineering" (wrong) or "http://blabla/engineering". 
* It works for strings that do not start with "en", e.g. "/en/test"

### Culprit
* [`hugo/url.go` #261](https://github.com/gohugoio/hugo/blob/ab82a27d055c3aa177821d81a45a5c6e972aa29e/helpers/url.go#L261)
* The code checks if the provided path starts with `getLanguagePrefix` (e.g. "en"). It should check instead, if it starts with "en/" to avoid matches when paths start with "en" (or any other language prefix)

**Comment by bep** [comment]
Thanks for getting in touch, but it feels like this is a question  that would be better suited to the [Hugo Discussion Forum](https://discourse.gohugo.io/).  We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug. You may also find the answers you search for in [Hugo Documentation](http://gohugo.io/overview/introduction/).

**Comment by a-andre** [comment]
This is still an issue. #5369 seems to be the fix. (haven't tested it)
