### ISSUE TITLE
Page rendered only after move

### ISSUE THREAD

**Issue by sascha-andres** [gohugoio/hugo#4539]
# Prerequisites

Assume the structure in /content:

    /cv
        index.md
    index.md

# Current bahavior
The index.md gets rendered always, but CV does not. This does the trick for the development server:

    cd content/cv
    mv index.md cv.md
    mv cv.md index.md

Finally the 404 is gone. Unfortunately this does not work when generating the page.

# Expected bahvior
Pages get rendered correctly

# Additional information
You can see the repository with my site's content here: https://github.com/sascha-andres/livingit.de/tree/fix/content

The branch contains only the CV and no projects or posts, I have moved them away while searching for a solution

hugo env:

    Hugo Static Site Generator v0.37.1 linux/amd64 BuildDate: 2018-03-07T17:56:25Z
    GOOS="linux"
    GOARCH="amd64"
    GOVERSION="go1.10"

**Comment by ManuelHu** [comment]
I have the same issue when I tried to update hugo today. In version 0.31 everything works still OK, in ver 0.32 it's broken. It neither works with `index.md` or `_index.md` as a filename.

In server mode, it doensn't result in a "normal" 404, but just shows a blank page.

Platform: Windows 10
Version of Hugo: 0.32.x

**Comment by bep** [comment]
Thanks for getting in touch, but it feels like this is a question  that would be better suited to the [Hugo Discussion Forum](https://discourse.gohugo.io/).  We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug. You may also find the answers you search for in [Hugo Documentation](http://gohugo.io/overview/introduction/).

**Comment by sascha-andres** [comment]
@bep Link to my question: https://discourse.gohugo.io/t/pages-not-rendering/11137/3

After the comment from @ManuelHu I downgraded hugo to 0.31 and the pages appeared. Anyways I like to know how to reorganize my content to follow hugo development but this can be done at the forum.
