### ISSUE TITLE
Hugo does not detect file changes properly!

### ISSUE THREAD

**Issue by mtrstudio** [gohugoio/hugo#4540]
I followed the [quickstart](https://gohugo.io/getting-started/quick-start/) to create a new site, and add some testing pages. I did some random tests by moving files from one folder to another, or creating new ones, but hugo did not respond as I expected. Here's how to reproduce this problem.

1. Follow the quickstart to create a new site. Start the sever "hugo server -w"
2. Manually create some folders in "content" directory, say, "about", "install".
3. Manually add index.md to each of the folders "about" and "install"
4. Create a file "aa.md" under "about", go to "localhost:1313/about/aa" to see if the changes are detected
5. Move "aa.md" from "about" to "install", go to go to "localhost:1313/install/aa"
6. More similar tests.

It seems to me that hugo uses cached data, instead of updating the directory and file structures each time you make changes. For example, if you want hugo to know the changes in folder "about", you have to change "about" to some other name, i.e. "abouts" and then change it back to "about", now in this way hugo knows what has changed and files in "about" will be detected by hugo. Otherwise, no consist way to make hugo know what has changed!!

**Comment by bep** [comment]
Thanks for getting in touch, but it feels like this is a question  that would be better suited to the [Hugo Discussion Forum](https://discourse.gohugo.io/).  We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug. You may also find the answers you search for in [Hugo Documentation](http://gohugo.io/overview/introduction/).

**Comment by brunoaugusto** [comment]
Then enlighten us, oh, almighty beep, where on the extensive yet not very useful or well-explained documentation issues like this is mentioned and thought how to handle. RIGHT NOW as I type this I had the same issue as the OP and if not for this renaming "trick" Hugo just don't let the cache go away, like a dog and his bone, using templates that changed like 30 minutes ago even though the server has been started with all possible "no caching" flags.
