### ISSUE TITLE
Add a --version command line option. 

### ISSUE THREAD

**Issue by looeee** [gohugoio/hugo#4551]
While raising a previous issue,  I wanted to include the hugo version. It looks like I can render it to HTML, but there doesn't seem to be any way to find it from the command line.

**Comment by bep** [comment]
Thanks for getting in touch, but it feels like this is a question  that would be better suited to the [Hugo Discussion Forum](https://discourse.gohugo.io/).  We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug. You may also find the answers you search for in [Hugo Documentation](http://gohugo.io/overview/introduction/).

**Comment by looeee** [comment]
Thanks for the link to the docs as well, but I do know how to find the version. I'm specifically suggesting that a command line flag to display it would be useful a useful enhancement for Hugo.

**Comment by bep** [comment]
>I'm specifically suggesting that a command line flag to display it would be useful a useful enhancement for Hugo.

That would duplicate an existing commands, and we will not do that.
