### ISSUE TITLE
Page resources not working (as expected) with extract date and slug from filename funtionality

### ISSUE THREAD

**Issue by Brixy** [gohugoio/hugo#4558]
Hi all!

Thanks for the brilliant _extract date and slug from filename_ funtionality.

Page resources does not seem to work in such a case:

```
.
└── blog
    ├── any-folder-name
    │   └── 2018-03-02-file-name.md
    │   └── file.pdf
```

When building, file.pdf is located in `blog/2018-03-02-file-name`.

Yet, I would like to link to file: `<a href="file.pdf">Download</a>`.

That is, the file should be located depending on config settings, e. g.:

```
[permalinks]
blog = "/:slug/"
```

This would be even simpler:

```
.
└── blog
    ├── 2018-03-02-FILE-name
    │   └── index.md
    │   └── file.pdf
```

Thank you!

**Comment by Brixy** [comment]
Would this simple concept make sense:

If filename is `index.md` or `_index.md` get date and slug from parent folder name.

Slug sould be treated as if in front matter. Folder `2018-04-13-name` ist not generated, but e. g. `/2018/name`—including all page resources + index.html.

(Should other md files in the folder also be published to `/2018/name/`?? Would make sense in my setups.)

**Comment by Japanuspus** [comment]
Just wanted to comment that [the duplicate issue](https://github.com/gohugoio/hugo/issues/4609) opened by @onedrawingperday  was more clearly stated.

The date from filename implementation should treat files and leaf page bundles equally, so that the following input file structures should result in the same site:

Input as leaf bundle
```
.
└── blog
    └── 2018-03-02-FILE-name
        └── index.md
``` 
Input as single file
```
.
└── blog
    └── 2018-03-02-FILE-name.md
```

**Comment by onedrawingperday** [comment]
Begone stale bot.

This issue has merit.

**Comment by Japanuspus** [comment]
I have a [proposed fix](https://github.com/Japanuspus/hugo/commit/220368a94ae8236ff4d4a43a3557647e272b530f), and is starting to read through the [contribution guidelines](https://github.com/gohugoio/hugo/blob/master/CONTRIBUTING.md). Is anybody who is already following this issue able to review, or should I ping someone?

This is my first go-code ever, and I must say that the toolchain experience was very nice. From no tools and no language knowledge to an implemented fix and a working binary in the course of a few hours is hard to beat!

## Details of fix
I have changed the definition of the `BaseFilename` field in the `FrontMatterDescriptor` structure provided to the frontmatter handlers, so that in the case of a leaf bundle `index.`-file, the name provided is that of the containing bundle folder.
Since the use of the `FrontMatterDescriptor` is localized to the fronmatter handler, this should not have external effects.

To compute the new value of `BaseFilename`, I have added a `ContentBaseName` method to the `File` interface.
In the current `FileInfo` implementation, I compute the corresponding value on demand, but it might be cleaner to move it to the `lazyinit` function at the cost of storing one more string.

**Comment by Japanuspus** [comment]
Went ahead and moved the code to lazyinit,  added tests, and ran `go fmt` -- will send pull request of the [squashed commit](https://github.com/Japanuspus/hugo/commit/c05958a56eab5e1d9f58127ffb924a47bf6d7627 )
