### ISSUE TITLE
Add a capture shortcode

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#4560]
I think this is a Jekyll concept, but it sounds useful. It is possible for the user to add it him/herself today, but it sounds like a general-purpose shortcode.

So:

```html
{{< capture some_custom_name >}}
This is a content snippet that can be picked up in the templates.
{{< /capture >}}
```
I assume that we just store it in the `Page` `Scratch` with a defined prefix. We should add a `.GetCapture` method, too, as a convenience method, so given the above example I can do this in a template:

```html
{{ with .GetCapture "some_custom_name" }}
{{ . | title }}
{{ end }}
```

Or whatever.

/cc @kaushalmodi @regisphilibert  and gang.

**Comment by regisphilibert** [comment]
Yes sounds good using scratch ‘setInMap’. 

Prefix should be something like core_capture to make sure it doesn’t conflict with users current own  implémentation.

Also along with ‘.GetCapture‘ couldn’t we add a more generic template function to test the presence of a shortcode in the page ? Unless I am mistaken I don’t think there is already a clean / advertised way to do that? 
It is useful to load special scripts etc... 

This is only slight unrelated as this template function may be coded along the ‘.GetCapture’ method.

**Comment by kaushalmodi** [comment]
I didn't quite understand why this is needed. I already do that using front-matter..

In front-matter (TOML):

```toml
some_custom_name = """
Anything can go in here, even **Markdown**.
"""
```

And in the template:

```html
{{ with .Params.some_custom_name }}
    {{ . | markdownify }}
{{ end }}

**Comment by regisphilibert** [comment]
> Anything can go in here, even **Markdown**.

Well you have to admit that adding **Markdown** as a Front Matter string is not ideal.

**Comment by bep** [comment]
There are several benefits from this, esp. for longer Markdown text segments. You can "capture" text parts anywhere in the document and use it in a side bar etc.

>Unless I am mistaken I don’t think there is already a clean / advertised way to do that?

Not sure about the _advertised_ part, but `HasShortcode` is clean enough ... :-)

**Comment by regisphilibert** [comment]
> I believe I used it just once.

@kaushalmodi has a point, @bep you are always asking for use cases before agreeing to work on a new feature :) I'm sure there are plenty but I myself never stumbled upon one.

> Not sure about the advertised part, but HasShortcode is clean enough ... :-)

Ahah, it is indeed.

**Comment by bep** [comment]
> you are always asking for use cases before agreeing to work on a new feature :) 

Not when I have a use case myself. That Trumps everything.

**Comment by regisphilibert** [comment]
> Not when I have a use case myself. That Trumps everything.

What is it then? :)

**Comment by regisphilibert** [comment]
I have one! 

Catching everything before the `<!-- more -->` tag is some time troublesome. You want some HTML but not really all of it. With the `capture` shortcode you could write a nice HTML excerpt directly from your `.md`'s content!

> Or, does that get removed from .Content, and only get accessed via .GetCapture?

For me this is the way to go, unless you have a use case for the alternative?

So I guess we wait for this `.GetCapture` function to be added, and then start working on this simple core shortcode?

**Comment by bep** [comment]
>So I guess we wait for this .GetCapture function to be added, and then start working on this simple core shortcode?

Note that those internals are just convenience stuff. This is all possible today (I have tested it).

**Comment by regisphilibert** [comment]
Instead of having to create a `.GetCapture` function, couldn't the "captured" content be stored as a regular page `.Param` and accessed like so from the template.

Everytime I need an rich html Front Matter param, I just wish I could write it in markdown and I could. Easy example is for a short rich html intro.

This is how it would look:

```
---
title: My Blog Post
date: [...]
---

{{<capture "intro" >}}
This article could have not been written without the help of [whoever.com](Who Ever). The repo is [here](repo.com)
{{< capture "intro" >}}
```

Then from my template:

``` 
{{ with .Params.intro }}
<div class="intro">
{{ . }}
</div>
{{ end }}
```

### Maps ? 
Not sure about that, but using `.Params` it would be nice, to use/navigate with maps.
```
{{< capture "sections.head" >}}
[...]
{{</ capture }}
{{< capture "sections.foot" >}}
[...]
{{</ capture }}
```
Template:
```
{{ with .Params.sections.head }}
[ ... ]
{{ end }}

**Comment by bep** [comment]
>So the advantage over a standard shortcode is that if I have this capture shortcode in my body copy I can pull it out and use it elsewhere. So, then can I have it NOT show in my body copy?

Yes.

And I will repeat myself: This is trivial to implement today with a shortcode + maybe a partial, this issue is about making it easier.

**Comment by mpctx** [comment]
> I think this is a Jekyll concept, but it sounds useful. It is possible for the user to add it him/herself today, but it sounds like a general-purpose shortcode.

Correct, and it can be very helpful. I have a use case for this moving from Jekyll. If implemented like Liquid handles it, you can do this

```
{{ capture $foo }}this is the content {{ .Content }}{{ end }}

{{ $foo }} {{ $foo}} {{ $foo }}
```

This isn't a useful case, but it illustrates the flexibility. Here's my use.

In baseof.html I set the description for the page using conditionals. However, for list pages, I generated the description from combining the .Summary of multiple paginator entries. This works fine if I'm only inserting the description in one place because I can use {{ define "description" }}... to override the baseof value.

However, I have a description entry for twitter and opengraph as well, and there's no way to capture what is inside the block override for use in those blocks of code.

Being able to do this would fix the issue

```
{{ capture $foo }}
  {{ block "bar" . }}{{ "default value" }}{{ end }}
{{ end }}

<meta name="description" content="{{ $foo }}">
<meta name="twitter:description" content="{{ $foo }}">
```

I have played around with various approaches, but in the end I have to use multiple define statements and I had to move twitter and opengraph blocks out of partials and into baseof, which is far from ideal.

Implementing the above, there is added flexibility

```
{{ capture $foo }}
  {{ block "bar" . }}{{ "default value" }}{{ end }}
{{ end }}

{{ .Scratch.Set "baz" $foo }}
{{ partial "twitter" . }}
{{ partial "opengraph" . }}
```
