### ISSUE TITLE
Figure shortcode with baseURL

### ISSUE THREAD

**Issue by qw3ry** [gohugoio/hugo#4562]
Currently, the `figure` shortcode does not work for [sites with a non-standard BaseURL](https://discourse.gohugo.io/t/solved-how-to-add-relurl-to-figure-src/9932).

Because I need this for my current project I coded a custom shortcode prefixing image URLs starting with a `/` with the BaseURL. Basically I fix this by replacing `<img src="{{ .Get "src" }}" … />` with `<img src="{{ .Get "src" | relUrl }}" … />`

I'd be happy to create a PR if this is a wanted addition/change.

**Comment by kaushalmodi** [comment]
> does not work for sites with a non-standard BaseURL.

It wasn't clear from the linked page, but I believe you refer to BaseURL's like `https://example.com/foo/` as non-standard BaseURL. If so, I agree!

This has been a known problem and has appeared on the [Discourse forum][2] too.

> Basically I fix this by replacing <img src="{{ .Get "src" }}" … /> with <img src="{{ .Get "src" | relUrl }}" … />

That, IMO, is not a complete fix. It does not handle the case when images are in one of the content dirs.

I ended up with [this custom `figure` shortcode][1], but here is the relevant piece:

```html
{{ $permalink := $.Page.Permalink }}
{{ $image := .Get "src" }}
{{ $image_link_absolute := (findRE "^/" $image) }}
<figure{{ with .Get "class" }} class="{{ . }}"{{ end }}>
    <!-- snip -->
        {{ if $image_link_absolute }}
            <img src="{{ $image | absURL }}"
        {{ else }}
            <img src="{{ (printf "%s%s" $permalink $image) }}"
        {{ end }}
    <!-- snip -->
```

- I am simply using `absURL` instead of `relURL` in your case. But that's just 1/2 of the fix. That deals with only `src` values that begin with `/`. It is safe to assume that if a user starts `src` value with `/`, they mean to have that path start from the site's BaseURL.
- The other 1/2 of the solution is when `src` does **not** begin with `/`. In that case, I assume that user wants to refer to that `src` in the "current dir" i.e. from the current Page's Permalink. So I prefix the `src` with `$.Page.Permalink` in that case.


[1]: https://gitlab.com/kaushalmodi/hugo-theme-refined/blob/master/layouts/shortcodes/figure.html
[2]: https://discourse.gohugo.io/t/embedding-page-resources-into-posts/11120

**Comment by tomnis** [comment]
I just ran into this. Our solution was to set `canonifyurls = "true"` in `config.toml`

Then we can include image with the figure shortcode like so:
```
{{< figure src="/images/figure1.png" title="Figure 1" >}}
```

**Comment by kaushalmodi** [comment]
You can have:

```
content/
  |_ posts/
        |_ post-1/
              |_ images/
                    |_ foo.svg
              |_ index.md
```

and then `{{< figure src="foo.svg" title="Figure 1" >}}` inside `index.md` should work.. whether that figure is rendered on the post page or via summary on a list page.

The solution I propose above does not need `canonifyurls = "true"`, and also handles the cases where the `figure` `src` is relative to the current page as shown above. Images don't always have to be in `static/`.

**Comment by kaushalmodi** [comment]
@bep Do you have thoughts on my proposal to modify the `figure` shortcode.

[Debug details][1] showing that the current `figure` shortcode breaks if `canonifyURL` is `false` **AND** `baseURL` contains subdir.

[1]: https://discourse.gohugo.io/t/baseurl-path-subdir-sometimes-ignored-by-relurl-absurl/11512/3?u=kaushalmodi

**Comment by bep** [comment]
@kaushalmodi I think you need to conclude in the discussion forum. And my plate is kind of super-full of other stuff at the moment, so do not expect my superfast attention.
