### ISSUE TITLE
Hugo puts square brackets around keywords

### ISSUE THREAD

**Issue by webdona** [gohugoio/hugo#4581]
i have the following front matter in a hugo markdown file
```---
title: Telegram Bot on Netlify Functions
keywords: golang telegram bot, telegram bot go
date: 2018-03-27T11:59:49+03:00
categories:
  - "tutorials"
tags:
  - "function"
  - "bot"
  - "go"
---
```
the issue is when the following template is rendered

```
<!doctype html>
<html lang="en">
<head>
    {{ partial "includes.html" . }}
    <meta name="keywords" content="{{ .Page.Keywords }}">
    <title>{{ .Page.Title }} | WebDona</title>
</head>

<body>
    {{ partial "header.html" . }}

    <main id="blog-post">

        <div id="blog-post-header">

            <h1>{{ .Page.Title }}</h1>
            
            <small>{{ .Date.Format "January 2, 2006" }}</small>
                
            <ul id="tags">
                {{ range .Params.tags }}
                    <li><a class="more" href="/blog/tags/{{ . }}">{{ . }}</a></li>
                {{ end }}
            </ul>

        </div>

        {{ .Content }}

    </main>
    
    {{ partial "footer.html" . }}
</body>

</html>
```

the keywords meta tag has the following content `[golang telegram bot, telegram bot go]`

i am using hugo version `0.37.1`

**Comment by bep** [comment]
Thanks for getting in touch, but it feels like this is a question  that would be better suited to the [Hugo Discussion Forum](https://discourse.gohugo.io/).  We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug. You may also find the answers you search for in [Hugo Documentation](http://gohugo.io/overview/introduction/).
