### ISSUE TITLE
Finding a theme by attributes?

### ISSUE THREAD

**Issue by amca01** [gohugoio/hugo#4597]
I have been spending far too long experimenting with Hugo themes.  The list of attributes on the [themes page](https://themes.gohugo.io) is all very well, but how do I easily find, for example, if a theme:

- is currently maintained?
- has a sidebar?
- supports mathjax?

In fact possibly the top one is the most important: there are themes which although very handsome (at least, I think so), like Red Lounge, are old and don't support new Hugo functionality.  I find myself downloading a theme, setting it up to work with my blog, and then discovering that it is missing some attribute I'd like.  

It'd be nice to be able to search all themes first, instead of downloading and testing.  Is this at all possible?

**Comment by bep** [comment]
Thanks for getting in touch, but it feels like this is a question  that would be better suited to the [Hugo Discussion Forum](https://discourse.gohugo.io/).  We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug. You may also find the answers you search for in [Hugo Documentation](http://gohugo.io/overview/introduction/).
