### ISSUE TITLE
index.md

### ISSUE THREAD

**Issue by Resonanz** [gohugoio/hugo#4611]
If I execute: `hugo new index.md` then `index.md` is created in the root of the `content` folder as expected.

Then, if I set `draft: false` inside the index.md file and execute `hugo` to generate a public site, the `index.html` file that I would expect to find inside `public` (being consistent with other *.md files inside the `content` folder being produced into `public`) is not there.

Is it illegal to create an `index.md` because there is no warning message.

**Comment by bep** [comment]
Thanks for getting in touch, but it feels like this is a question  that would be better suited to the [Hugo Discussion Forum](https://discourse.gohugo.io/).  We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug. You may also find the answers you search for in [Hugo Documentation](http://gohugo.io/overview/introduction/).
