### ISSUE TITLE
Support template lookup in root layouts folder

### ISSUE THREAD

**Issue by ziburski** [gohugoio/hugo#4613]
I use Hugo for very simple sites without themes, multiple content types or multiple sections. I often have just a index.html and a single.html template (e.g. for a basic blog), maybe a baseof.html template.

Right now, these have to be inside layouts/_default/. It would be nice if I could place them straight inside of layouts/, since there are no other templates. Does that make sense, or is there a conflict I’m missing?

**Comment by paulcmal** [comment]
Hi! I'm in the same case where I use the `_default` templates only. However, this clear separation makes sense, because depending on the type, layout, section, section, Hugo will [look up](https://gohugo.io/templates/lookup-order/) many different files. If no specific templating path has been found, it falls back to the `_default` folder within your site root, otherwise within your theme.

I personally consider this a feature, as it forces us to think of it this way, that these templates are used only if we're not having more specific templates (hence the `_default` name). But maybe I'm missing something?

**Comment by bep** [comment]
Creating a `_default` folder does not sound hard enough to make this feature worth while:

* Estimated 1 day of implementation, testing and documentation
* Then an unknown future number of questions here and on the forum related to this future etc.
* And it establishes a naming convention that we may need in the future for more important stuff.
