### ISSUE TITLE
Draft parameter isn't recognized by 'where'

### ISSUE THREAD

**Issue by d3m1gd** [gohugoio/hugo#4650]
```
{{ where $.Site.RegularPages ".Draft" "==" "true" }}
```
Produces `Pages(0)` for a site with drafts. Same as:
```
{{ where $.Site.RegularPages ".Params.draft" "==" "true" }}
```

Expected result - array of draft pages.

```
Hugo Static Site Generator v0.39 linux/amd64 BuildDate: 2018-04-16T07:31:29Z
```

**Comment by bep** [comment]
Thanks for getting in touch, but it feels like this is a question  that would be better suited to the [Hugo Discussion Forum](https://discourse.gohugo.io/).  We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug. You may also find the answers you search for in [Hugo Documentation](http://gohugo.io/overview/introduction/).
