### ISSUE TITLE
Using {{- .Inner -}} still adds newlines

### ISSUE THREAD

**Issue by JordanKnott** [gohugoio/hugo#4657]
According to [this article](https://gohugo.io/templates/introduction/#whitespace), if you add dashes when getting a variable it should strip all new lines and white-space.

I'm currently using a custom shortcode that looks like this:

``` html
<pre><code class="language-{{- .Get 0 -}}">{{- .Inner -}}</code></pre>
```

If I use it like so:

``` html
{{< prism yaml >}}
highlighter: none
{{< /prism >}}
```

It renders output like:

``` html
<pre><code class="language-yaml">
highlighter: none
</code></pre>
```

Which isn't correct because it has newlines surrounding the `highlighter: none` even though the dashes are supposed to remove it.

From my understanding, it should just output `<pre><code class="language-yaml">highlighter: none</code></pre>`.

Is it just user error on my part or something else?

I'm using Hugo version 0.39.

**Comment by bep** [comment]
Thanks for getting in touch, but it feels like this is a question  that would be better suited to the [Hugo Discussion Forum](https://discourse.gohugo.io/).  We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug. You may also find the answers you search for in [Hugo Documentation](http://gohugo.io/overview/introduction/).

**Comment by JordanKnott** [comment]
[Link to the re-posted question](https://discourse.gohugo.io/t/using-inner-still-adds-newlines/11679)
