### ISSUE TITLE
override index.html redirector from multi-lingual subdir setup

### ISSUE THREAD

**Issue by mlake** [gohugoio/hugo#4703]
I'd like my own custom redirector so I can intelligently detect browser language as well as some custom schema stuff.

Would have expected if I put an index.html file in /static that it would override the generated one...seems to be that my index gets squashed by the generated one

**Comment by bep** [comment]
Thanks for getting in touch, but it feels like this is a question  that would be better suited to the [Hugo Discussion Forum](https://discourse.gohugo.io/).  We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug. You may also find the answers you search for in [Hugo Documentation](http://gohugo.io/overview/introduction/).
