### ISSUE TITLE
Hugo does not generate any files and server can't see any files in content

### ISSUE THREAD

**Issue by Arhimondus** [gohugoio/hugo#4740]
When I try this command `hugo` to generate pages - there is no html pages in `public` except `index.html`.
When I try to run server as `hugo server`, hugo can't see any files in `content`, but when I change something in specific file in content only in this way this file will be displayed.

Windows 10 LTSB, Hugo 0.40.3.

PS: I have an old project on Hugo 0.17 and all is fine, so I suppose that problem is not in my system.

**Comment by bep** [comment]
Thanks for getting in touch, but it feels like this is a question  that would be better suited to the [Hugo Discussion Forum](https://discourse.gohugo.io/).  We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug. You may also find the answers you search for in [Hugo Documentation](http://gohugo.io/overview/introduction/).
