### ISSUE TITLE
Spurious 301 redirects when using `hugo server` and aliases with colons

### ISSUE THREAD

**Issue by jack126guy** [gohugoio/hugo#4750]
If you have an alias with a certain sort final component (like `/a:b` or `/a/b:c`), Hugo's server will produce a 301 redirect to the final component (such as `a:b` or `b:c` with the previous examples), which may be interpreted as a URL with an unrecognized scheme.

This happens even when the colons are percent-encoded.

Fortunately, the actual site generation command handles these correctly.

**Comment by jack126guy** [comment]
Yes. Steps to reproduce:

1. Download Hugo v0.40.3.
2. Create a new site using `hugo new site`.
3. Add a random theme.
4. Add the following document to the `content` folder:

    ```
    ---
    title: Test
    aliases:
      - /a:b
      - /a/b:c
      - /a:b/c
    ---

    Hello
    ```

5. Request the aliases (I used Wget with the `--server-response` option).
6. Observe that the first two aliases will give a 301 and the third will not (it's included as a comparison). Interestingly, this only occurs without a trailing slash.

**Comment by bep** [comment]
@jack126guy I have checked. Hugo is a static generator. We do not create any HTTP 301 responses.

**Comment by tanael** [comment]
Hi,

Not looking to re-open this issue, only to leave a comment in case someone else stumbles upon here.

I have noticed the exact same problem, that I solved by ending the `url` links in `config.toml` with a `/`.

I only noticed it after I published my site to production and realized that some menu links were being 301ed. The problem being that the rewritten url contained my webserver's _private network address_ instead of the normal url...

Although the prod issue could be attributed to a misconfiguration on my part, I only managed to debug it because the `hugo server` was behaving the same way.

I am also running this on a 64-bit Debian Testing: `Hugo Static Site Generator v0.80.0/extended linux/amd64 BuildDate: 2021-02-09T18:47:48Z (debian 0.80.0-6)`.
