### ISSUE TITLE
Option to render shortcode arguments again

### ISSUE THREAD

**Issue by Jonny007-MKD** [gohugoio/hugo#4812]
Hi,

I'm using v0.41 and have created a custom img shortcode for responsive images which I pass the url to the image and a caption and the shortcode generates the html code aournd it so that it looks fancy.
Today I wanted to add a link within the caption, like this:
`{{% img src="something" type="jpg" alt="A sun in the blue sky" caption="Now the [sun]({{< ref "sun.md" >}}) is shining %}}`
But I had to escape the ref argument and itself as well as the markdown is not rendered. Is there a way to tell the engine in the shortcode (at the bottom) that the caption shall be rendered? Could such a thing be implemented?

This is the shortcode:
```
{{ $src  := .Get "src" }}
{{ $src  := replace $src " " "%20" }}
{{ $type := .Get "type" }}
<figure>
  <a href="/img/{{ $src }}.{{ $type }}">
    <img src="/img/{{ $src }}.{{ $type }}"
      {{ with .Get "alt" }}alt="{{.}}"{{ end }}
      srcset="
       {{ range $i,$size := .Site.Params.imgSizes }}
         {{ if gt $i 0 }},{{end}} /img/converted/{{ $src }}_{{ $size }}.{{ $type }} {{ replace $size "x" "w" }}{{ end }}
      "
      sizes="
        (min-width: 1024px) 1024px,
        100vw
      "
  /></a>
{{ with .Get "caption" }}  <figcaption>{{.}}</figcaption>{{ end }}
</figure>
```

**Comment by bep** [comment]
Thanks for getting in touch, but it feels like this is a question  that would be better suited to the [Hugo Discussion Forum](https://discourse.gohugo.io/).  We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug. You may also find the answers you search for in [Hugo Documentation](http://gohugo.io/overview/introduction/).
