### ISSUE TITLE
Add support for reading page content from a URL

### ISSUE THREAD

**Issue by geeknoid** [gohugoio/hugo#4817]
I'd like to be able to build a page by reading content from URLs. More specifically, imagine a page with several preformatted blocks whose contents comes from GitHub files. I'd like to dynamically read the files from GitHub and insert them into my page.

Right now, I'm doing dynamically vis JavaScript in the page. It's be a lot cleaner if I could do this as the static site is built.

Imagine a readHttp function that takes a URL and just returns the result as a string.

**Comment by onedrawingperday** [comment]
There has been a similar discussion recently about getting Open Graph tags with Hugo.

Your request is highly unlikely to be implemented because reading URL content over HTTP falls under the web scraping category and Hugo’s lead developer does not want to support this. See relevant [comment](https://discourse.gohugo.io/t/feature-request-getopengraph-func/12022/13)

I’m closing this issue.
