### ISSUE TITLE
Consider names: strings.RuneCount vs strings.CountRunes

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#4821]
@kaushalmodi had some concerns, probably valid.

My argument would be that

* The new kind of matches the one in the stdlib `utf8.RuneCountInString`
* The old should probably be more expressive (it does more than it says), but that is harder to fix, maybe ...

**Comment by kaushalmodi** [comment]
Thanks for opening this issue. Also copying @theory. 

So my concern was that it's confusing (for anyone I believe) to remember what the old *strings.CountRunes* does vs the new *strings.RuneCount*. 

Issues with that:

- The "Rune" and "Count" are switched. 
- One has "Count", other has "Counts".. so a user would be then confused as to which one is correct for their application out of:
    - RuneCounts
    - RuneCount
    - CountRune
    - CountRunes

I don't have a preference on what order of Rune and Count you decide, and if you have Count or Counts, but it should be the same way for both.

---

If you prefer the new *strings.RuneCount*, then I propose to deprecate (give warning) the old *strings.CountRunes*, and suggest users to switch to *strings.RuneCountNoSpaceHTML* (or any other name that's more appropriate, but beginning with *RuneCount*. It that becomes too verbose, then probably name it something else altogether).

**Comment by theory** [comment]
+1 to renaming the existing function, the semantics of which are currently confusing. Frankly it seems quite overloaded and specialized. Ideally, `CountRunes` would just count runes, without regard to content. If someone wanted to count runes without whitespace or HTML, they should use the utilities designed for that purpose:

```
{{% plainify $text | replaceRE "\\s+", "" | strings.CountRunes  %}}
```

This feels more natural to me, in that one can use smaller, more focused tools/functions in combination to get a result, rather than have such a specialized core function.

My suggestion, then:

1. Deprecate `countrunes` and `strings.CountRunes`
2. Rename `strings.RuneCount` to `utf8.RuneCountInString` for symmetry with the known Go function.
2. Propose the above alternative in the docs, or perhaps make a special `cjk.CountPlainifiedNonWhitespaceRunes` function to replace it.

Deprecation is a PITA, though, I get it.

**Comment by kaushalmodi** [comment]
I'm onboard with all of those 3 points.. except that the "InString" portion won't be needed as it already has the "strings." namespace.

**Comment by theory** [comment]
Yeah, but if give it the same name as the existing `strings.CountRunes` function, it might cause headaches for people. Sadly I think it needs a different name. Which is why I originally suggested `strings.RuneLen`.

**Comment by theory** [comment]
Of course, leaving it `strings.RuneCount` prevents the conflict, too. So maybe leave it at that.

**Comment by bep** [comment]
Naming is hard. I see no perfect solution in the above, so I think I will trump it and go for the solution with less work (i.e. keep as is).

These are specialist functions. People who use them should read the documentation and understand them. The important part about the new function is that it is not available under the `runecount` alias which would make it totally confusing.

**Comment by kaushalmodi** [comment]
> I see no perfect solution in the above

I though this proposal was perfect!

1. Keep the new function name as is. 
2. Deprecate the old `countrunes` and `strings.CountRunes` and rename it to `strings.CountPlainifiedNonWhitespaceRunes` (the original suggestion was to give `cjk` namespace, but probably it can just live in `strings` namespace?)

Why wouldn't that work?
