### ISSUE TITLE
Live reload do not works with Content Security Policy

### ISSUE THREAD

**Issue by vitaly-zdanevich** [gohugoio/hugo#4836]
Looks like Hugo needs to alter Content Security Policy too when injecting script.

**Comment by RealOrangeOne** [comment]
The Hugo dev server doesn't support HTTPS, and so doesn't set these headers at all (correctly). Sounds like the issue lies with whatever youre using to SSL-terminate the connections to the dev server, rather than the dev server itself?

**Comment by vitaly-zdanevich** [comment]
I have this in my index.html:

```
<meta http-equiv='Content-Security-Policy' content="default-src 'self';
        script-src
            'self'
            https://www.googletagmanager.com
            https://www.google-analytics.com;
        connect-src
            'self'
            https://api.ipdata.co;
        img-src
            'self'
            https://www.google-analytics.com
            https://stats.g.doubleclick.net;
        font-src
            'self'
            https://fonts.gstatic.com;">

```
... I tried to reproduce this issue but now there is no live reload script in generated html... I run `hugo server` without flags.

**Comment by RealOrangeOne** [comment]
Is the live reload script just blocked from your CSP rules? Take a look at your browser console incase there's a message in there. 

Might be better to discuss this on the forum, as this doesn't immediately look like an issue with Hugo, rather with the tag itself.

**Comment by onedrawingperday** [comment]
As a workaround you could assign ENV variables and call the CSP `meta` tag only when the Hugo site is deployed. Have a look over [here](https://github.com/jfo/weblog/commit/63128ef185b08a91d8cea36890d11f4c61572025) and for a longer discussion [here](https://discourse.gohugo.io/t/how-to-exclude-google-analytics-when-running-under-hugo-local-server/6092/8?u=onedrawingperday)

But I'm closing this issue. It is unlikely that Hugo server will provide CSP support since it's not meant for production.

If you need further assistance please post a topic at https://discourse.gohugo.io
