### ISSUE TITLE
Custom slug is appended to bundle directory name

### ISSUE THREAD

**Issue by regisphilibert** [gohugoio/hugo#4870]
Consider this Front Matter:
```
Title: What we do
slug: what-we-do
```

Depending if it's from a Leaf Bundle or regular md file Hugo will build the url differently:
 
`content/about/services/misc.md`> `http://site.com/about/services/what-we-do/` ✅ 
`content/about/services/misc/index.md`> `http://site.com/about/services/misc/what-we-do/` 🚫

**Comment by DirtyF** [comment]
I just stumbled upon this on a multi-lingual website, the slug gets added to the page bundle:

- `content/en/localization/index.md` > `/en/localization/` ✅ 
- `content/fr/localization/index.md` > `/en/localization/localisation/` 🚫 

I had to set an `url` to get it fixed.

**Comment by erolabzait** [comment]
Same issue as @DirtyF

**Comment by KillianKemps** [comment]
I encountered the same issue because with my previous CMS Grav I was using the `slug` in the Leaf Bundle to specify the URL in other languages.

To workaround, I configured the [permalinks](https://gohugo.io/content-management/urls/#permalinks-configuration-example) in the `config.toml` like this (with `blog` being the section name):
```
[permalinks]
  blog = "/blog/:slug/"
```

However you must check that the URLs are like you wish. In my case, some French articles got accents in their path while before they didn't had so I had to precise the `slug` for those articles in the front matter.

**Comment by regisphilibert** [comment]
This is making a lot of noise in the discourse, so: shameless bump 🤷‍♂️

**Comment by jzeneto** [comment]
I have the same problem of @regisphilibert  and @DirtyF here...

**Comment by bsvinothraj** [comment]
We are facing some issues while updating Hugo to v0.56. We think it has something to do with this issue.

**Note**: We have enabled uglyurls for our site and have not set any slugs.

**Sample content folder structure:**

> content/dir1/page1.md
content/dir1/page2/index.md

Before v0.56, the output would be,

> baseUrl/dir1/page1.html
baseUrl/dir1/page2/index.html

In v0.56, the output is,

> baseUrl/dir1/page1.html
baseUrl/dir1/page2.html

Is the new one, the intended behavior? Any ways to retain the previous behavior?
