### ISSUE TITLE
Extended version has no support for SCSS

### ISSUE THREAD

**Issue by marcusolsson** [gohugoio/hugo#4923]
I tried downloading the `hugo_extended_0.43_macOS-64bit.tar.gz` release, which I gather is the version with SCSS support, and get this error:

```
Building sites … ERROR 2018/07/10 07:15:09 error: failed to transform resource: failed to transform "scss/main.css" (text/css): this feature is not available in your current Hugo version
Total in 13 msError: Error building site: logged 1 error(s)
```

Also, I double-checked the version of the binary and it says it's **v0.44-DEV** (not v0.43):

```
Hugo Static Site Generator v0.44-DEV/extended darwin/amd64 BuildDate: 2018-07-09T18:31:48Z
```

**Comment by bep** [comment]
The version number is me rebuilding last night to get the WIndows build OK. I will fix that. I just tested the MacOS binary on my computer, and that works fine. 

I suspect this is something different, and to me this does not look like the SCSS step -- but PostCSS? Does it work if you remove that step? Because of the mime type. We should improve on the error message here, of course.

**Comment by bep** [comment]
@jojomi please read my post.

**Comment by marcusolsson** [comment]
@bep I can confirm it's working if I remove the `postCSS` step. Am I missing a dependency perhaps?

**Comment by bep** [comment]
> Am I missing a dependency perhaps?

```bash
 npm install -g postcss-cli
```

We obviously have to work on the docs here ...
