### ISSUE TITLE
Prevent resource publishing if only its `.Content` is outputted.

### ISSUE THREAD

**Issue by regisphilibert** [gohugoio/hugo#4944]
Currently, a resource will be published even if only its `.Content` is outputted in the template (and not its `.Permalink`):
```
{{ (resource.Get "inline.scss" | toCSS).Content) | safeCSS }} 
```

I guess this could cost some build time in the rare case where a user needs to output both the `.Content` of a resource and its `.Permalink`.

**Comment by carlmjohnson** [comment]
Vice-versa, I was trying to move a site from my pre-43 system to post-43 and I ran into the issue that my font files were in a subfolder from my SCSS and so when I just moved the SCSS folder from `static` to `assets` the fonts ended up not being published, so I had to move the fonts back but leave the SCSS in `assets`. Now I have `/static/scss/` with no SCSS in it. :-)

My preference is that everything in `assets` should be published and the main difference from `static` is just that it's available for post-processing, not that it must be post-processed in order to exist in the final build.

**Comment by carlmjohnson** [comment]
Another issue: My SCSS refers to a background image. Ideally, the background image should also be hashed somehow? But in any event, I also had to split the `/static/images` folder into two because the images that are referred to in the template need to be `assets` to be hashed, but the ones that aren't in templates need to be in `static` to be published.

**Comment by regisphilibert** [comment]
Hi @carlmjohnson. 

Files in the assets directly should not be automatically published because a lot of them are there to be processed.
You don’t want both your SCSS files and their processed CSS to be published. I know I don’t. 

Your comments are out of scope for this issue. 

You do make an interesting case though and I encourage you to bring it up in the discourse if you have not done already.

**Comment by carlmjohnson** [comment]
> You don’t want both your SCSS files and their processed CSS to be published. I know I don’t.

Why not? The file size is probably trivial, and I'm not worried about someone hacking my site by reading the SCSS. :-) I do see the case for not wanting to publish, e.g., large images multiple times, but in general, I think there's no reason to publish it all by default.

**Comment by bep** [comment]
>My preference is that everything in assets should be published

That will never happen (for several reasons, but I'm not takin that debate -- but it is a fundamental difference between /static and /assets).

I think this was a "glitch in my implementation", as in -- it was meant to be the way @regisphilibert wants it.

And that is in line with what happens if you do `$foo := resources.Get "somefile.js`. 

`$foo` will never get published until you either access `$foo.RelPermalink` or `$foo.Permalink`. 

The transformed resources behave differently, possibly because of an implementation optimation -- I can create an `io.MultiWriter`  and write to both memory and file at the same time.
