### ISSUE TITLE
Resources fetched via resources.Get and similar should be language agnostic

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#5017]
Testing this with multiple languages with SCSS and font paths etc. shows that doing this per site/language, adding the language code to the permalink etc.), probably was a mistake and need some rethinking.

* You get duplication of identical content, with added processing time
* You end up with path issues that seem to be hard to find a way around (`@fa-font-path` is my current head struggler)

It is currently possible to define an assets dir per language, but I think we need to remove that possibility. I doubt that anyone uses it. This also would mean that if you want per-language resources, you would have to set the path yourself.

I think we need to do this sooner rather than later. I just added a second language to a site with a fair amount of SASS files, and doing that twice is doubling the processing time. 

/cc @kaushalmodi @regisphilibert @onedrawingperday

**Comment by regisphilibert** [comment]
I just realized that the resources permalink includes the language (I'd be surprised many people did) so I'm confident this can be changed with minimum codebreak.

I personnaly can't find any use case for having two versions of a resources per language since per language CSS which can easily be achieved within one common stylesheet by targeting the lang attribute.


For JS and the rest, Hugo Pipes gives you sufficient legroom to adapt your pipepline per language (language bundles, specific script tags including lang variables outputted before the main script etc...).

**Comment by bep** [comment]
Yea, I label it as an Enhancement -- but it was obviously a mistake once I started to actually use it.

**Comment by claudix** [comment]
What if we use different hosting per language? (my case). I've noticed that the website relased under French language (hosted in server A) points to the JS/CSS files to the English website hosted in server B. I don't want to have host-dependency across sites. Is there any way to fall back to the previous behavior?
