### ISSUE TITLE
`HUGO_CANONIFYURLS=true` produces incorrect permalinks for resources

### ISSUE THREAD

**Issue by shaform** [gohugoio/hugo#5035]
I discovered this issue because https://github.com/gohugoio/hugoThemes is using `HUGO_CANONIFYURLS=true`.

Basically, if we have the following settings:

In `config.toml`:
```
[permalinks]
  posts = "/:year/:month/:day/:slug/"
```

In frontmatter:
```
resources:
- name: img
  src: 'img.jpg'
```

In template:
`{{ (.Resources.GetMatch "img").Permalink }}`

Then, when executing `hugo -b http://themes.gohugo.io/theme/a-theme/`, the permalink is correct:

http://themes.gohugo.io/theme/a-theme/:year/:month/:slug/img.jpg

But when executing `HUGO_CANONIFYURLS=true hugo -b http://themes.gohugo.io/theme/a-theme/`, the permalink is incorrect:

http://themes.gohugo.io/:year/:month/:slug/img.jpg

**Comment by onedrawingperday** [comment]
I think that I have also encountered this bug. 

When I was testing [this](https://github.com/gohugoio/hugoThemes/issues/395#issuecomment-409029194) theme with the Hugo Themes Site Build Script.

- `.Permalink` produced the wrong URL for resources 
- `.RelPermalink` produced the correct URL

But I hadn't noticed that the Themes Site uses `HUGO_CANONIFYURLS=true`

@shaform what happens when you use `.RelPermalink` for these resources and `canonifyURLs`? Are you getting the correct URL?

**Comment by shaform** [comment]
Oops, if `HUGO_CANONIFYURLS` = `canonifyURLs`, then this seems to be a duplicate of #4998.

**Comment by onedrawingperday** [comment]
Since this is a duplicate I am closing this issue.
