### ISSUE TITLE
Sitemap shows wrong `lastmod` for taxonomy pages with `enableGitInfo`

### ISSUE THREAD

**Issue by tyrondis** [gohugoio/hugo#5045]
Hugo version: `v0.46/extended darwin/amd64`

The `lastmod` field in the default sitemap layout is not showing the correct date of the last modification of a taxonomy page if `enableGitInfo` is set to `true`. It is always an old date that never changes, even though I add pages with a related taxonomy. Disabling `enableGitInfo` fixes this, but I want to use this feature to get the correct `lastmod` info on my pages.

**Comment by gfarrell** [comment]
I have a similar issue. I suspect that `.Lastmod` is getting the last commit time of the *template* file in which it is being called, rather than the item itself. To clarify:

- I have a single.html template which contains the title, publish date, and updated date (from `.Lastmod`).
- I committed changes today, but the `.Lastmod` date hasn't changed since I committed changes to the single.html template.

I'm not 100% sure that my diagnosis is correct, however, since if I try to access instead `$.Page.Lastmod` I get the same answer.
