### ISSUE TITLE
HUGO_THEME succeeds but "-t" fails when config.toml contains theme = ["../.."]

### ISSUE THREAD

**Issue by anthonyfok** [gohugoio/hugo#5061]
I'm not entirely sure it is a Hugo bug at all because it looks like a rare corner case which manifests only when config.toml has a buggy `theme` entry, as described below.

But HUGO_THEME and `-t` being inconsistent here seems worthy of investigation, though admittedly a low-priority one.

### Details

I came across a perculiar error (tested with Hugo 0.46) when building the Hugo themes site locally with the alpha-church theme after I reverted the `HUGO_THEME` workaround back to using the `-t` flag (see https://github.com/gohugoio/hugoThemes/commit/0b4e98b96f0ee4aee3fd22bc8a7a5e65869d255f):

```
 ==== PROCESSING  alpha-church  ====== 
Building site for theme alpha-church using its own exampleSite to ../themeSite/static/theme/alpha-church/
hugo --quiet -s exampleSite2 -d ../themeSite/static/theme/alpha-church/ -t alpha-church -b http://localhost:1313/theme/alpha-church/
ERROR 2018/08/11 10:22:56 Unable to locate template for shortcode "osmap" in page "about.md"
ERROR 2018/08/11 10:22:56 Unable to locate template for shortcode "contact_form" in page "contact.md"
Error: Error building site: logged 2 error(s)
FAILED to create exampleSite for alpha-church
```

However, if I add `HUGO_THEME=alpha-church`, the "Unable to locate template for shortcode" errors go away.

I then noticed in https://github.com/funkydan2/alpha-church/blob/master/exampleSite/config.toml#L4
a somewhat strange `theme = ["../.."]` entry (`themesDir` not defined in config.toml):

```ini
baseURL = "http://example.org/"
languageCode = "en-us"
title = "Alpha Church"
theme = ["../.."]

# etc.
```

It looks like an erroneous use of the `theme` variable, and I suppose it should be corrected to something like this:

```ini
theme = "alpha-church"
themesDir = "../.."
```

But HUGO_THEME and `-t` being inconsistent here seems worthy of investigation, though admittedly a low-priority one.

**Comment by nonumeros** [comment]
The error I'm getting in my end and without modifying any part of the config code, is the following: it fails with both `-t` flag and without the `-t` flag it fails also.

No errors are returned with either the suggested change of having `theme = "alpha-church" or by having the delimiters in place. Because it makes no difference.

H>UGO_THEME succeeds but "-t" fails when config.toml contains theme = ["../.."]

Nope. What you described on your title heading is not what I'm getting. 

As a matter of fact, it's the opposite.

And it doesn't matter whether you'd use `-t` or not. It still returns the errros.

Without `theme` defined on the configuration file, `serve` returns the error, while `-t` flag doesn't.

And with `themes` in place and without modifying any other part of the configuration file, `serve` returns the error, while `-t` doesnt. So this is the only consistent behavior that one would get from this issue.

With `themes` it doesn't matter whether the delimiters are in use or not on the configuration file. 

And I really don't know what the issue is with the path configuration on the configuration file. I concur with the author in that case. So I can't really follow you there.  Wish I could, but not this time around. That is, if you are running hugo from the **exampleSite** directory, it's perfectly understandable to have separated values for that path on that configuration file e.g `[../..]`. If for example, you were to remove the theme itself from the themes directory then the no less expected error that is `unable to find the theme directory` comes back.  

This has nothing to do with the delimiters in use. And I'm not saying that is not erroneous to use them.

**Comment by nonumeros** [comment]
Perhaps this is an ongoing problem that should be more carefully looked up.

Take for example https://github.com/matcornic/hugo-theme-learn

And assuming that a **themes** directory is created within the **exampleSite**

go to the config file on exampleSite directory and change it to

     #theme = "hugo-theme-learn"
     theme = "../.."
     #themesdir = "../.."

Both the `-t` flag and `serve` compile

Now, if I were to change it to:

     #theme = "hugo-theme-learn"
     themes = "../.."
     #themesdir = "../.."

the `-t` flag compiles, while `serve` doesn't.

Whereas the delimiters are in use make no difference.
