### ISSUE TITLE
post and posts folder

### ISSUE THREAD

**Issue by thecodeah** [gohugoio/hugo#5086]
I was having trouble getting Hugo set up for a blog for days simply because I put the posts inside of the `content/posts` folder instead of the `content/post` folder.

The "Quick Start" introduction tutorial also uses `posts`.
https://gohugo.io/getting-started/quick-start/#step-4-add-some-content

I thought it was just a typo. However [this repository](https://github.com/mismith0227/hugo_theme_pickles/tree/develop/exampleSite/content/posts) contains an example folder where once again `posts` is used.

Is this method outdated, or does the issue lie somewhere else?

**Comment by kaushalmodi** [comment]
> does the issue lie somewhere else?

The `hugo_theme_pickles` theme is not well designed. It is [**hard-coding** the posts directory name to "posts"][1]. Hugo does not impose the directory name.

See `.Site.Params.mainSections`. Please close this issue here and you can continue further discussion at https://discourse.gohugo.io/.

[1]: https://github.com/mismith0227/hugo_theme_pickles/blob/3ee082c47e57fcccd7d337a288ce1c63108b510e/layouts/_default/list.html#L3
