### ISSUE TITLE
Reconsider trimming trailing URL slashes

### ISSUE THREAD

**Issue by nhooyr** [gohugoio/hugo#5098]
See the closed PR https://github.com/gohugoio/hugo/pull/3934 that implements this feature.

Given the activity in that thread, many previous discussions and even blog posts regarding how to get around it, the community clearly wants this feature.

It's worth revisiting this.

**Comment by anthonyfok** [comment]
Hi @nhooyr, thanks for raising this issue.

I am an occasional contributor and didn't notice #3934's existence until now, and reopened PR #3934, but noticed several issues:

1. The CLA was not signed.  (Was it ever signed before?)
2. Due to the age of the PR, it now has quite a bit of merge conflicts that need to be resolved.
3. I think it would be better if there is an accompanying addition to the docs as to how to properly set up each web server or each service to have such trimmed-trailing-URL-slashes working.
