### ISSUE TITLE
Error building site with aliases and outputs

### ISSUE THREAD

**Issue by Tazeg** [gohugoio/hugo#5118]
It seems we can’t generate `aliases` and outputs like `amp` together in front matter. Here is how to reproduce the problem :

	hugo new site blog
	cd blog
	hugo new _index.md

Modify `content/_index.md` to remove draft and add aliases :

	---
	title: "Home"
	date: 2018-08-20T18:53:31+02:00
	aliases: ["/oldindex.html"]
	---

`hugo` command works as expected : the public directory is created.

Add this in config.toml :

	[outputs]
		home = ["HTML", "AMP"]

`hugo` command says :

	Error: Error building site: open /home/jeff/tmp/blog/public/oldindex.html/amp/index.html: not a directory

hugo version is : Hugo Static Site Generator v0.47.1 linux/amd64 BuildDate: 2018-08-20T12:56:04Z

**Comment by nonumeros** [comment]
from what I could see you must change `aliases` to `alias` on the **_index.md** file to have it working, but here the working is fuzzy because it creates **categories** **sitemaps** and **tags**

On the other hand if you'd rather have `aliases` it works - by 'works' here it means it creates the above in addition to **index.html** and **oldindex.html** too as long as `output` instead of `outputs` is corrected on the config file. But I don't think that's the parameter's intended behavior

**Comment by Tazeg** [comment]
"alias" instead of "aliases" doesn't generate the HTML alias file. 
And it's not only about home page. I made a sample site test repo with content articles : https://github.com/Tazeg/hugo-test
In the front matter of the content/post/article* we can't use both "aliases" and "outputs", otherwise the command : `rm -rf public/* && hugo` says `Error: Error building site: open /home/jeff/tmp/blog/public/post/article3.html/amp/index.html: not a directory`

**Comment by nonumeros** [comment]
> "alias" instead of "aliases" doesn't generate the HTML alias file.
but that's what I said above it only creates **categories** **tags** and the sitemap
 
>n the front matter of the content/post/article* we can't use both "aliases" and "outputs", otherwise th

but you can use `output`, right or right?

**Comment by Tazeg** [comment]
I'm not sure to understand. `output` in front matter does nothing.

**Comment by nonumeros** [comment]
> I'm not sure to understand. `output` in front matter does nothing.

like you said before:

     [outputs]
	     home = ["HTML", "AMP"]

returns `error building site public/oldindex.html/amp/index.html not a directory` 

whereas with 

     [output]
           home = ["HTML", "AMP"]

it creates on **public** folder  categories, tags, sitemap, oldindex.html and index.html. I ran it with 0.44 up until 0.48. But either way you ought to ask the maintainer here or on their forum for further clarification as to why `outputs` fail on the front matter whereas `output` doesn't.

**Comment by Tazeg** [comment]
This : 
```
 [output]
       home = ["HTML", "AMP"]
```
Has no effects.

Yes, the error is no longer here because there is a new front matter `output` which does nothing about Hugo. It doesn't say to Hugo : i want my pages in HTML and AMP. So with this front matter `output` there is no `amp` directory created at public/ root. 

I could write `chicken` instead of `outputs`. Sure it makes the error vanish but doesn't solve anything.

**Comment by Tazeg** [comment]
Can you make it work with this sample : https://github.com/Tazeg/hugo-test ?
In my case `output` doesn't create the `amp` directory. 
I can't définitly create both amp pages and aliases.
Thanks for your help.

**Comment by nonumeros** [comment]
@Tazeg let's forget about the `amp` directory for a minute, and let's think about a dir chicken

if you were to replace all your instances of `outputs` with `output` ... what do you get? This includes front matter and configuration file

Furthermore and just for consistency's sake, let's replace `amp` with `chicken`

If you look closely on your test case, you have **post/article1.md**, **post/article2.md** and so on which have `outputs` specified on their front matter. Right? Replace them with `output` instead.

For the simple reason that if you were to have it such as 

     ---
      title: "Article1"
      date: 2018-08-30T08:38:44+02:00
      #aliases: "/post/article1.html"
      outputs: ["HTML", "CHICKEN"]
      ---

       article1

Which gives in return `Building sites … ERROR 2018/09/01 07:46:36 Failed to resolve output formats: OutputFormat with key "CHICKEN" not found`

so `outputs` must be replaced

on the other hand, in order to create new directories `TURKEY` you must specify it as such under `aliases` of your **_index.md** file, and unless you remove **public** and later on regenerate it right after, you end up with dirs chicken and turkey that carry the index
