### ISSUE TITLE
Check i18n plural rules

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#5164]
See https://regisphilibert.com/blog/2018/08/hugo-multilingual-part-2-i18n-string-localization/

>If the current language is English, your “Mice count” is 0, and you set the zero plural tag to This story has no Mouse, you’ll still end up with the other string, This story has 0 Mice.

>For the zero string to show, the current language would have to be Arabic or any other one which supports the zero plural tag

The above looks like a very odd restriction to me. I must admit I haven't tested this, but If I define a `zero` for a string in Norwegian, then I know what I'm doing -- I don't see how some "i18n plural ruleset" could do better than me?

/cc @nicksnyder @regisphilibert

**Comment by regisphilibert** [comment]
> I don't see how some "i18n plural ruleset" could do better than me?

If you decide Hugo should allow `zero` and `two` plural tags in any languages, and therefor adopt its own plural rule set rather than the universally accepted one, I would support you, but again I am no professional linguist and may miss something big here.

**Comment by nicksnyder** [comment]
The current design of go-i18n relies on CLDR categories. These categories are abstract because `zero`, `one`, `two` does not mean 0, 1, 2 in all languages. For example, the `zero` category is not used in English and matches more that just 0 in Prussian.

If your application wants to have a special case for a specific number (e.g. 0), then it shouldn’t rely on CLDR categories. Instead, the special case needs to be its own translation id and you need to handle that in application logic.

```go
if mouseCount == 0 {
    // special message for 0
} else {
    // regular message
}
```

See also: https://github.com/nicksnyder/go-i18n/issues/112

I don’t know if “just add an if/else in Go code” works for Hugo users. If it does then that is the right solution. If not then this is essentially a feature request.

Naively allowing users to define `zero` for languages that don’t have that category would only mask the problem for those languages. If the application had both English and Prussian (for example), it would appear to work for English but it wouldn’t be possible to have the special case work in Prussian. This would also only work for 0, 1, 2 unless we allowed users to define their own categories.

A general solution might involve allowing users to specify numeric translation keys for exact matches (instead of overloading the names of CLDR categories). I have not thought through the implications of this.
