### ISSUE TITLE
Add support for image AutoOrientation

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#5181]
See https://github.com/disintegration/imaging/releases/tag/v1.5.0

**Comment by carlmjohnson** [comment]
Awesome! Glad there is a simple solution. This will save me time.

**Comment by jmooring** [comment]
The next release, presumably v0.122.0, includes an [AutoOrient image filter](https://github.com/gohugoio/hugo/pull/11819) that rotates and flips an image as needed per its EXIF orientation tag. For example, to auto-orient and then resize:

```text
{{ $filters := slice
  images.AutoOrient
  (images.Process "resize 200x")
}}
{{ with resources.Get "images/original.jpg" }}
  {{ with images.Filter $filters . }}
    <img src="{{ .RelPermalink }}" width="{{ .Width }}" height="{{ .Height }}" alt="">
  {{ end }}
{{ end }}
```

If you build Hugo from source (HEAD), you can test all EXIF orientation values with:

```text
git clone --single-branch -b hugo-github-issue-11717 https://github.com/jmooring/hugo-testing hugo-github-issue-11717
cd hugo-github-issue-11717
hugo server
```

Two questions come to mind...

1\) Why is this necessary?

Because Go's JPEG decoder ignores the EXIF Orientation tag. An [issue to correct this](https://github.com/golang/go/issues/4341) was opened in 2012, but is unlikely to be addressed due to concerns about backwards compatibility.

2\) Why doesn't Hugo automatically handle this when decoding images?

I guess we might at some point, but similar to the above, the change would not be backwards compatible in some cases; some site and theme authors have already implemented handling for some of the orientation values (those that do not involve flipping/mirroring).

**Comment by bep** [comment]
>2) Why doesn't Hugo automatically handle this when decoding images?

Performance is one argument, reading the EXIF info is not free. I have tens of thousand images processed by Hugo and I know that note one of them need to be "auto oriented" so why would I want to waste all the CPU?

Next Hugo (soon) will have a simple to use `images.AutoOrient` filter.

**Comment by bep** [comment]
We now have a filter that handles this.
