### ISSUE TITLE
in function not accepting variable as ITEM

### ISSUE THREAD

**Issue by mjraval** [gohugoio/hugo#5230]
I am trying to filter out posts of a particular category by the below code
```
{{ range where .Site.Pages "Section" "products"}}
       {{ if in .Params.categories "New Arrival" }}
              <li>{{ .Title }}</li>
       {{end}}
{{end}}
```
the above code works completely fine.
**But if I use a variable instead of a string for the `ITEM`.  It always returns `False`.**

```
{{ $display_product_cat := "New Arrival" }}
{{ range where .Site.Pages "Section" "products"}}
       {{ if in .Params.categories $display_product_cat }}
              <li>{{ .Title }}</li>
       {{end}}
{{end}}
```
**The above code does not work as expected.**
Wondering if I am missing something here. Appreciate your time.

**Comment by bep** [comment]
Thanks for getting in touch, but it feels like this is a question  that would be better suited to the [Hugo Discussion Forum](https://discourse.gohugo.io/).  We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug. You may also find the answers you search for in [Hugo Documentation](http://gohugo.io/overview/introduction/).
