### ISSUE TITLE
go install throws this error: cannot find package

### ISSUE THREAD

**Issue by ashish1dev** [gohugoio/hugo#5333]
Can you guide me what i am missing : 

I get the following error message: 

cannot find package "github.com/gohugoio/hugo/commands" in any of:
	/usr/local/Cellar/go/1.10.3/libexec/src/github.com/gohugoio/hugo/commands (from $GOROOT)
	/Users/user1/go/src/github.com/gohugoio/hugo/commands (from $GOPATH)

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).

**Comment by karlroberts** [comment]
How is this closed? it does not answer the question and the problem still exists!
I followed the documentation for installing hugo from github in the [Hugo Documentation](https://gohugo.io/getting-started/installing/#source) it say "prerequisits, have git and go" I have both, then copy and run the "from_gh.sh" shell script... which is what I did and I get the error mensioned in this issue. 

How is this resolved? What can I do to install from source?

**Comment by larzza** [comment]
I belive this issue is closed because it’s probably not a bug and these kind of questions is better asked and answered at the [Hugo forum](https://discourse.gohugo.io/). If the Hugo forum users doesn’t provide an answer (or recommend to open an issue) a new GitHub issue should be created, referencing this issue and the Hugo forum thread.

**Comment by larzza** [comment]
With the above said I think the problem this issue describes might be solved like this.

Hugo use Go Modules, so be sure to clone the Hugo source code outside of your GOPATH. 
See: [how to install and activate module support](https://github.com/golang/go/wiki/Modules#how-to-install-and-activate-module-support).

**Comment by wbelguidoum** [comment]
Thank you @larzza !

**Comment by zgershkoff** [comment]
Just chiming in in case anyone else runs into this error and can't find the solution on Google: it wasn't working for me because I had an outdated version of go. I assumed it was fine because I just installed go from apt, but apt only has 1.6 and there are a few more steps to get the current version. See https://github.com/golang/go/wiki/Ubuntu for more explanation.

**Comment by stuartcw** [comment]
> Hugo uses the Go Modules support built into Go 1.11 to build. 

This is the important part of the process that people have missed if you get this problem. It would be kinder if the documentation said "run `go version` and don't proceed any further until your version is at least 1.11". I almost gave up when I found that I was going to have to join the discord to get a simple answer to this problem.
