### ISSUE TITLE
Hugo prints escape chars when running in Windows shell

### ISSUE THREAD

**Issue by athanp** [gohugoio/hugo#5377]
When Hugo runs under Windows 10 powershell (or legacy command shell) it prints non sense ANSI escape sequences before and after "Building sites" message

`e[K25lBuilding sites … e[?25h`

**Comment by GregorioMartinez** [comment]
Since Windows 10.1607 it looks like we need to set `ENABLE_VIRTUAL_TERMINAL_PROCESSING`  using `SetConsoleMode` if we want ANSI support.

Previous builds had it enabled by default (Windows 10.1511) and older versions did not support it.

Here is some of the docs I found on this:

- https://docs.microsoft.com/en-us/windows/console/console-virtual-terminal-sequences
- https://docs.microsoft.com/en-us/windows/console/getconsolemode#ENABLE_VIRTUAL_TERMINAL_PROCESSING
