### ISSUE TITLE
Fix BuildDate in Windows releases

### ISSUE THREAD

**Issue by akshaybabloo** [gohugoio/hugo#5388]
The BuildDate for Hugo is always Unknown. Is there a reason why you are still using it?

**Comment by bep** [comment]
What do you mean by "always"? It is set at build time when we release, and also if you build with `mage`:

https://github.com/gohugoio/hugo/blob/master/magefile.go#L27

**Comment by akshaybabloo** [comment]
Not on Windows though. I get

```
Hugo Static Site Generator v0.50/extended windows/amd64 BuildDate: unknown
```

**Comment by akshaybabloo** [comment]
Doing this locally on PC with `mage hugo` is working.

**Comment by felicianotech** [comment]
I'm confirmed the following:

Does the build date show?

| | Linux | Windows |
| --- | --- |
| Regular Build | yes | yes |
| Extended Build | yes | no |

I think this issue is related to GoReleaser config. The build date is set different for the regular build vs extended build (I don't know why). For the extended build though, Windows is doing something different than Linux and macOS is. I believe that's why this is an issue. I've submitted a PR above to fix it.

I don't have the ability to run the GoReleaser build in a Windows computer right now so I'd need someone to config that my PR fixes this issue.

P.S. Building this with Mage does the correct thing regardless, which is why I think GoReleaser is the issue.

**Comment by akshaybabloo** [comment]
This is now fixed.
