### ISSUE TITLE
"summaryLength" is invalid for Chinese

### ISSUE THREAD

**Issue by yanzhenjie** [gohugoio/hugo#5443]
Hugo version: 0.51  
I read a few issues related, but still can't solve my problem. This is my config.json:
```
{
    "baseURL": "https://www.yanzhenjie.com",
    "languageCode": "zh-CN",
    "title": "Zhenjie Yan",
    "theme": "vienna",
    "copyright": "&copy; <a href=\"http://www.yanzhenjie.com\">Zhenjie Yan</a> 2018",
    "summaryLength":50
}
```
summaryLength has no effect on Chinese, whether its value is larger or smaller.

If you use `<!--more-->`, summary will have a length limit, but the preview of markdown is shown in summary, like this:
![image](https://user-images.githubusercontent.com/13534988/48546244-d0f93700-e902-11e8-8fb0-c8e243bc9fa5.png)

**Comment by sabhiram** [comment]
Not an author or contributor, but had a few minutes to kill so I bit :)

Here is the code that decides if the `autoSummary` should be truncated by words or sentences (both of these will check the `summaryLength` and do different things.  
https://github.com/gohugoio/hugo/blob/b8b8436fcca17c152e94cae2a1acad32efc3946c/hugolib/page.go#L809

Notice that for CJK languages it will use the `TruncateWordsByRune` method (here: https://github.com/gohugoio/hugo/blob/3d4a9882bfc81215fb4f9eba8859324958747d4a/helpers/content.go#L511). 

It would be trivial to see if this is expected behavior if you could post the raw content string somewhere. Hope this points you in the right direction.
