### ISSUE TITLE
How can I install snap in centos 7?

### ISSUE THREAD

**Issue by shuaijunlan** [gohugoio/hugo#5458]
How can I install `snap` in centos7?
I have tried some methods, but all of them can't install successfully.
Could someone give me some more detailed installing steps?

*Environment*
`uname -a` 
`Linux izwz98ghtp8fhm1jr7ifmtz 3.10.0-514.26.2.el7.x86_64 #1 SMP Tue Jul 4 15:04:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by anthonyfok** [comment]
Hi @shuaijunlan,

Support questions like the one that you have posted are better suited for https://discourse.gohugo.io/.
GitHub issues are for reporting bugs or requesting new features in Hugo.

So, please visit https://discourse.gohugo.io/ and post your question again, but this time, with more detail please.  In particular, what methods did you try, and what error messages did you see?
For example, were you trying the instructions at https://computingforgeeks.com/install-snapd-snap-applications-centos-7/ and running into problem?  In so, please copy-and-paste the entire procedure that you did, and in particular, the error message that you got stuck on.

In your case, it may be easier to install the Hugo RPM from https://copr.fedorainfracloud.org/coprs/daftaupe/hugo/ instead of using Snap.

Closing this issue.  Please continue the discussion on https://discourse.gohugo.io/ .
