### ISSUE TITLE
Consider relative cacheDir

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#5487]

**Comment by bep** [comment]
See https://discourse.gohugo.io/t/error-setting-cachedir-to-a-relative-folder-since-0-52/15596/2

**Comment by jmooring** [comment]
I believe the intent of this proposal, given the context of the related [forum topic](https://discourse.gohugo.io/t/error-setting-cachedir-to-a-relative-folder-since-0-52/15596/2), is covered by the ability to [configure file caches](https://gohugo.io/getting-started/configuration/#configure-file-caches).

Can we close this issue?

**Comment by travier** [comment]
I think this is not solved (and a better default would be implementing https://github.com/gohugoio/hugo/issues/7391). The configuration right now requires absolute paths which basically makes this unusable to store the cache per-project.
