### ISSUE TITLE
{{.File.Dir}} inserts %5c on Windows

### ISSUE THREAD

**Issue by Xeenych** [gohugoio/hugo#5515]
I Use Hugo for Windows.
{{.File.Dir}} outputs coorect path but adds %5c at the end.

**Comment by bep** [comment]
Thanks for getting in touch, but it feels like this is a question  that would be better suited to the [Hugo Discussion Forum](https://discourse.gohugo.io/).  We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug. You may also find the answers you search for in [Hugo Documentation](http://gohugo.io/overview/introduction/).

**Comment by brendan-mccoy** [comment]
Is this not a bug then?

**Comment by brendan-mccoy** [comment]
The issue I'm seeing in windows is that, when using like so: <a href="{{ $geekdocRepo }}/{{ $geekdocEditPath }}/{{ .File.Path }}">

or rather, in the theme I'm using, .File.Path is using in a variable which is this used in: <a href="{{ $geekdocRepo }}/{{ $geekdocEditPath }}/{{ $.Scratch.Get "geekdocFilePath" }}">

on the Windows Hugo (hugo v0.87.0-B0C541E4+extended windows/amd64 BuildDate=2021-08-03T10:57:28Z VendorInfo=gohugoio) the backslashes that would be returned in .File.Path used elsewhere will be replaced with %5c, which will cause broken hyperlinks that were built using .File.Path.

**Comment by moorereason** [comment]
Please don't comment on issues that were closed years ago.  Open a new issue and reference this one.
