### ISSUE TITLE
I suspect that there is a bug in hugo's Pagination.

### ISSUE THREAD

**Issue by Y4er** [gohugoio/hugo#5560]
I suspect that there is a bug in hugo's Pagination.
![image](https://user-images.githubusercontent.com/40487319/50389357-4f4bc300-0764-11e9-9e11-7e808bac6b2b.png)
This is the code for my pager。
![image](https://user-images.githubusercontent.com/40487319/50389363-6ab6ce00-0764-11e9-8bd6-55c07625311a.png)
However, he is divided into two pages.but,I only have 9 articles,I have not changed the default parameters of paging。His second page is empty。
![image](https://user-images.githubusercontent.com/40487319/50389391-b8333b00-0764-11e9-9ac4-72c8414a2752.png)
like this.

hope to get your reply : )

**Comment by Y4er** [comment]
The specific effect can be seen on my blog.    https://Y4er.com
This is my theme repositories.    https://github.com/Y4er/maupassant-hugo

**Comment by bep** [comment]
Thanks for getting in touch, but it feels like this is a question  that would be better suited to the [Hugo Discussion Forum](https://discourse.gohugo.io/).  We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug. You may also find the answers you search for in [Hugo Documentation](http://gohugo.io/overview/introduction/).
