### ISSUE TITLE
random number has fixed seeding

### ISSUE THREAD

**Issue by pjebs** [gohugoio/hugo#5641]
I am trying to generate a random number between 1-6:

```
{{  index (seq 6 | shuffle) 1 }}
```

This always generates the same sequence which is unfortunate.

**Comment by pjebs** [comment]
Perhaps adding to colletions.go:

```
import (
"math/rand"
"time"
)

func init() {
rand.Seed(time.Now().UTC().UnixNano())
}

```

**Comment by bep** [comment]
Thanks for getting in touch, but it feels like this is a question  that would be better suited to the [Hugo Discussion Forum](https://discourse.gohugo.io/).  We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug. You may also find the answers you search for in [Hugo Documentation](http://gohugo.io/overview/introduction/).
