### ISSUE TITLE
Machine-readable version output

### ISSUE THREAD

**Issue by emilmelnikov** [gohugoio/hugo#5642]
Currently, the output of `hugo version` is not machine-readable:

```
$ hugo version
Hugo Static Site Generator v0.53/extended darwin/amd64 BuildDate: unknown
```

Machine-readable version output would make it easier to use Hugo from scripts.
See example in #5638 that started this discussion.

Hugo also has the `env` command whose output is used to report bugs:

```
$ hugo env
Hugo Static Site Generator v0.53/extended darwin/amd64 BuildDate: unknown
GOOS="darwin"
GOARCH="amd64"
GOVERSION="go1.11.4"
```

My suggestion is to split the info from the version line into something like the following, and also add more identifiable information (e.g. git commit hash).
However, I am not sure what the _extended_ version flavor means and how to represent it here.

```
VERSION="0.53"
BUILD_DATE=""
GIT_COMMIT="5b45961431f3ed3a0104c03a8e78657a6413fb01"
```

Then, the standard unix tools could be used to extract the raw values:

```
$ hugo env | grep GOVERSION | cut -d= -f2 | tr -d \"
go1.11.4
```

**Comment by renantarouco** [comment]
Is this one still open for grab? I would like to start contributing and I think this one is a good start. The purpose of the project is awesome, and I found it right when I was looking to start writing some posts for practice.

I'm looking the other issues as well, but as a first-timer I think this one is achievable for me.

Thanks!

**Comment by renantarouco** [comment]
Another question is if YAML would suit the needs and which information would be relevant. I see in some places people comparing the CLI tool with the docker one, sou I was kind of take inspiration in it. Is that ok?

**Comment by patti24k** [comment]
yep

**Comment by renantarouco** [comment]
Well, for the part of providing a machine readable output of the `hugo version` command I used the *yaml* package already imported by the project, and used its API to output it to os.Stdout, so it can be integrated with terminal pipes and etc.

```go
versionOut := yaml.MapSlice{
	yaml.MapItem{
		Key:   "Program",
		Value: "Hugo Static Site Generator",
	},
	yaml.MapItem{
		Key:   "OS/Arch",
		Value: runtime.GOOS + "/" + runtime.GOARCH,
	},
	yaml.MapItem{
		Key:   "Version",
		Value: hugo.CurrentVersion.String(),
	},
}
return yaml.NewEncoder(os.Stdout).Encode(versionOut)
```

Now the `hugo version` command gives me the following output:

```
Program: Hugo Static Site Generator
OS/Arch: linux/amd64
Version: 0.59.0-DEV
```

The *commitHash* and *buildDate* information are missing from the original output, because they are stored in unexported fields and I'd like to know if I should proceed like this or change them to exported fields in the *hugo* package. The same doubts apply for the `hugo env` command, which I'll have to access the same information.

To start the PR to close this issue I'll wait for your feedback on this so I can finish both commands: `hugo version` and `hugo env`.

I'm am also having problems in the `mage -v check` fase, but the failing tests are not related to the package I'm working, or at least their names and outputs doesn't point to it.

Thank you very much!

**Comment by renantarouco** [comment]
In a separate branch I made the refactor in the `hugo env` command. Now it outputs:

```
HUGOPROGRAM="Hugo Static Site Generator"
HUGOVERSION="0.59.0-DEV"
GOOS="linux"
GOARCH="amd64"
GOVERSION="go1.13.1"
```

I prefixed it with HUGO just to be sure that it would not mess up with other predefined env variables. I would like to know if this is ok so I can merge my two branches before proposing a pull request.

Thanks.

**Comment by bep** [comment]
While I agree that Hugo could need a "machine friendly API", making the output of the version/env command into YAML is rather arbitrary and will probably break some scripts in the wild that uses `cut` or something to extract that value.
