### ISSUE TITLE
Using {{highlight}} removes colons from code

### ISSUE THREAD

**Issue by infosec-handbook** [gohugoio/hugo#5683]
Hugo 0.54 and previous versions remove multiple colons and omit enclosed text when used in {{highlight}} blocks.

Example:
```
{{< highlight apache "linenos=table,linenostart=1" >}}
[…]
# Modern configuration, tweak to your needs
SSLProtocol +TLSv1.2
SSLCipherSuite ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256
SSLHonorCipherOrder on
SSLCompression off
SSLSessionTickets off
SSLOpenSSLConfCmd Curves secp521r1:secp384r1:prime256v1
SSLOpenSSLConfCmd ECDHParameters secp521r1
[…]
{{< / highlight >}}
```

Final HTML file contains:
```
[…]
# Modern configuration, tweak to your needs
SSLProtocol +TLSv1.2
SSLCipherSuite ECDHE-ECDSA-AES256-GCM-SHA384ECDHE-ECDSA-CHACHA20-POLY1305ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256
SSLHonorCipherOrder on
SSLCompression off
SSLSessionTickets off
SSLOpenSSLConfCmd Curves secp521r1prime256v1
SSLOpenSSLConfCmd ECDHParameters secp521r1
[…]
```

As you can see, the lines SSLCipherSuite and SSLOpenSSLConfCmd contain less colons and some enclosed parameters are missing. This is also true for IPv6 addresses in highlight blocks as they contain several colons.

**Comment by bep** [comment]
I assume you use the Chroma (default) highlighter.

If so, this needs to be addressed upstream:

https://github.com/alecthomas/chroma/issues

**Comment by alecthomas** [comment]
@bep We are completely unable to replicate this in Chroma. See linked issue for details.

**Comment by Jos512** [comment]
I looked into this issue for the Chroma repository last week, and couldn't replicate it. In that issue there was also someone who did had their site source on GitHub, so I went to their code and settings and compared with mine in which it didn't show.

I was able to replicate this issue with the `highlight` shortcode and the `enableEmoji` setting.

### Example code
~~~
{{< highlight crystal "hl_lines=8" >}}
Onyx.post "/items", Actions::Items::Create # << New line
{{< / highlight >}}
~~~

### Hugo rendered output
Without the `enableEmoji` setting (so, `enableEmoji = false`), this renders as:

~~~
Onyx.post "/items", Actions::Items::Create # << New line
~~~

When I add `enableEmoji = true` to the site config, that line changes to:

~~~
Onyx.post "/items", Actions::Create # << New line
~~~

So it seems that the `::Items::` part is accidentally passed through the emoji processor. Since that isn't a valid Emoji, it's dropped from the code output.

To replicate, I used [this](https://github.com/onyxframework/blog) repository. The code example comes from the `creating-json-apis-with-onyx-part-2.md` file, starting at line number 236.

**Comment by alecthomas** [comment]
Nice find @Jos512 !
