### ISSUE TITLE
Taxonomies names does not match urlized

### ISSUE THREAD

**Issue by allanjude** [gohugoio/hugo#5687]
The documentation here says:
https://gohugo.io/content-management/taxonomies/#preserve-taxonomy-values

> "Therefore, if you want to have a taxonomy term with special characters such as Gérard Depardieu instead of Gerard Depardieu, set the value for preserveTaxonomyNames to true in your site config."

> "Note that if you use preserveTaxonomyNames and intend to manually construct URLs to the archive pages, you will need to pass the taxonomy values through the urlize template function."

However, in v0.54.0 this is not the behaviour I am seeing. preserveTaxonomyNames is false, but names are not normalized.

I have defined a taxonomy called "author" which has peoples names in it.

However, when I do:

```
    {{ with $.Site.GetPage (printf "/author/%s" ( $author | urlize )) }}
      <a href="{{ .RelPermalink }}">{{ $author }}</a>
    {{ end }}
```

It doesn't get the page for authors with accents in their names

```
{{ "Olivier Cochard-Labbé" | urlize }} = olivier-cochard-labb%C3%A9
```

but the taxonomy is: olivier-cochard-labbé

How do I encode the url the same way that the taxonomy is encoded, or get the taxonomy to be urlize'd?

**Comment by gcushen** [comment]
@bep this is a very common problem being reported with Academic theme since Hugo 0.54/0.55.

Does it appear to be a Hugo bug or should there be extra logic applied to non-ASCII characters when using GetPage with urlize as above?

Thanks :)

**Comment by gcushen** [comment]
Occurs when `author = "authors"` in taxonomy config and author pages are stored at `content/author/`. Prior to Hugo 0.54/0.55 this setup worked fine.

**Comment by gcushen** [comment]
Simple steps to reproduce the problem can be found at https://discourse.gohugo.io/t/v0-54-bug-getpage-is-broken-with-non-ascii-chars-invalid-taxonomy-url-generated/18498

**Comment by a-fortunato** [comment]
Hey,
I was struggling with this too, but I managed to make it work adding `removePathAccents = true` to the config file.

(I found the answer here https://github.com/gohugoio/hugo/issues/1180 and here https://discourse.gohugo.io/t/problem-with-taxonomies-in-foreign-languages/7955/10).

That should be enough for languages that mainly have to deal with accents, but it seems there's still some problems with other special characters, like explained here: https://github.com/gohugoio/hugo/issues/3476.

Good luck!

**Comment by gcushen** [comment]
@a-fortunato thanks for the input. That is a possible workaround rather than a fix for the inconsistent (actual taxonomy page URL vs invalid URL given by GetPage) and buggy handling of non-ASCII characters.

**Comment by vintikzzz** [comment]
I've got it working by fixing theme templates by changing from this
```
{{ $series := .Params.series | urlize}}
```
to this
```
{{ $series := .Params.series | anchorize}}
```
Anchorize function doesn't do urlencoding.

**Comment by HughP** [comment]
It is not just accents in my case I am using Saltillo `U+A78B LATIN CAPITAL LETTER SALTILLO` and it still breaks.

**Comment by vintikzzz** [comment]
@HughP have you tried my solution?
I had Russian text that looks like this "Смотри фильмы онлайн с любого сайта" and anchorize just convert it to "смотри-фильмы-онлайн-с-любого-сайта" (that works) instead of urlize that makes it "%D1%81%D0%BC%D0%BE%D1%82%D1%80%D0%B8-%D1%84%D0%B8%D0%BB%D1%8C%D0%BC%D1%8B-%D0%BE%D0%BD%D0%BB%D0%B0%D0%B9%D0%BD-%D1%81-%D0%BB%D1%8E%D0%B1%D0%BE%D0%B3%D0%BE-%D1%81%D0%B0%D0%B9%D1%82%D0%B0" (don't work)

**Comment by HughP** [comment]
@vintikzzz Yes that works for me. But I don't really understand the difference in what is happening.

**Comment by vintikzzz** [comment]
@HughP in my case there was a code like this
```
{{ $posts := index .Site.Taxonomies.series $series }}
```
`.Site.Taxonomies.series` - is a map of weighted pages like so
```
map[
  смотри-фильмы-онлайн-с-любого-сайта:[
    WeightedPage(0,"Смотри фильмы онлайн с rutracker.org")
    WeightedPage(0,"Смотри фильмы онлайн с rutor.org")]
  что-нового:[
    WeightedPage(0,"Представляем Webtor 1.0")
  ]
]
```
As you can see here, the key there is an `anchorized` value not `urlized`.
`urlize` and `anchorize` works the same for ASCII charset, because urlencoding (that additionally used in `urlize`) doesn't do additional conversion fo ASCII character set ([except reserved chars](https://en.wikipedia.org/wiki/Percent-encoding#Percent-encoding_reserved_charactersl)). That's why, I think, many theme developers doesn't meet this problem. Characters from Romance language group use a lot of characters from ASCII, the main difference is that there are so called "Accents", and that's why `removePathAccents = true` solves issue for them without changing theme templates.

**Comment by amoutiers** [comment]
I've the same problem, I think hugo should have a function/modifier to calculate a key from a name (a term name here) like toKey or toIndex with the same logic it's internal do to calculate the index/key

**Comment by gcushen** [comment]
@bep using urlize as per the docs can still fail in GetPage as above. If we don't fix this GetPage behaviour with urlize then perhaps we can implement a dedicated function to resolve the inconsistency in Hugo such as @amoutiers suggested above?

**Comment by sumpfralle** [comment]
The issue still exists: it is quite cumbersome to retrieve the page associated with a generic taxonomy term value.

In my case (the automatically generated [Munin Plugin Gallery](https://github.com/munin-monitoring/munin-plugin-gallery)) I need to use *both* `urlize` and `anchorize` (as alternatives, if the other fails) in order to reliably transform the given the string.

My workaround is the following:
```
{{- $page := (default (index $.Site.Taxonomies.authors (anchorize .)) (index $.Site.Taxonomies.authors (urlize .))).Page -}}
```

The above code snippets attempts to retrieve the term key first via `anchorize` and (if that fails) with `urlize`. The order of both operations is probably only relevant for rare (almost identical) strings.

`urlize` seems to be the right choice, if special characters like a dot (`.`) are part of the string.

`anchorize` seems to be the right choice, if special characters like accents are part of the string.

@amoutiers suggestion feels like the proper way to solve this issue. Otherwise users will need to apply the above ugly conversion manually whenever they want to access generic taxonomy term keys safely.
