### ISSUE TITLE
Can filename contain "()" and "$" ?

### ISSUE THREAD

**Issue by ssy341** [gohugoio/hugo#5737]
Hi all,
I have one file named "$().md", I access "http://localhost:1313/$()/" or "http://localhost:1313/%24()/" both returns 404 code. I have no idea about this. What should I do?

here is $().md file content
```markdown
+++
title = "$()"
+++
Hello hugo
```

**Comment by bep** [comment]
Have you tried renaming the file?

**Comment by ssy341** [comment]
thanks @bep 
but I can't rename the file, this filename is about jQuery plugin‘s API, if I change the filename then the content doesn't match API name, it makes confusing

**Comment by bep** [comment]
> then the content doesn't match API name, it makes confusing

Sure, but I'm pretty sure `$()` isn't a valid URL, so at some point you need to adjust it. And you can have anything you want in the title.

**Comment by ssy341** [comment]
@bep I run `hugo server --renderToDisk` command then generate the files in public folder. I found out hugo will ignore "()" or "$" character. I use jekyll to generate website before, the same filename can be generated. I can access "http://localhost:4000/%24()" get the page. For hugo, this result count a bug? Or I did a wrong way?

![image](https://user-images.githubusercontent.com/1725705/53929741-b3c2c100-40c9-11e9-814e-e92c283dff73.png)
![image](https://user-images.githubusercontent.com/1725705/53929802-e5d42300-40c9-11e9-941b-9e3dddb35c2a.png)

**Comment by steven-linden** [comment]
I ran into a similar problem when some of my markdown files have the : character embedded in their name, and when they were converted to HTML by Hugo, the : characters were dropped and the resulting filename wasn't what we were expecting.

Eventually, I traced this to [path.go](https://github.com/gohugoio/hugo/blob/master/helpers/path.go#L141-L144) where the filenames are sanitized, and issue [1292](https://github.com/gohugoio/hugo/issues/1292) (where the % characters are stripped out of filenames) also seems relevant. 

I understand the reasoning for not allowing certain characters in filenames because they are not permitted in the URL specs, and that doing the percent-encoding may not be within the scope of Hugo (plus, certain cloud storage providers do their own encoding on upload, which can further complicate matters).

However, I didn't see any mention in the documentation regarding which characters are permitted to be used in filenames, and which ones will be dropped; nor does the documentation indicate that these characters will be dropped silently, even when running Hugo in verbose mode.

@bep - I am happy to add this information into the documentation, but would appreciate a pointer to a suitable location to do so. If the information is already there, could it be made more obvious?
