### ISSUE TITLE
Any good trailheads for troubleshooting logs?

### ISSUE THREAD

**Issue by weisisheng** [gohugoio/hugo#5743]
On Ubuntu 18.04, I created some test websites 6 months ago, I believe on version .50.  They ran great.  

Upgraded to 0.54 and trying out some sample repos from hugo website and contributors (vex-hugo, meghna, mkdocs variants).  Nothing renders or I get a few, very few in fact, items from the 'custom' set.  I have tried git clone and git submodule add, neither has the correct effect. And I change my .toml file accordingly for the right theme.  I thought maybe permission issue so I opened folders for read/write for everyone and again no effect.

Reverted back to version 0.52 thinking a few versions back might stabilize, still in same predicament. Also tried hugo extended?

Thanks in advance.

**Comment by weisisheng** [comment]
As an aside, I have periodically been getting a permissions issue too.  I try do a render using 'hugo' and server with 'hugo server' and the message is permission denied.  Even if I use sudo and this doesn't occur elsewhere on my system.

**Comment by bep** [comment]
Thanks for getting in touch, but it feels like this is a question  that would be better suited to the [Hugo Discussion Forum](https://discourse.gohugo.io/).  We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug. You may also find the answers you search for in [Hugo Documentation](http://gohugo.io/overview/introduction/).
