### ISSUE TITLE
Create a "resource file adapter" for Git LFS/Netlify’s Large Media support   

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#5749]
https://discourse.gohugo.io/t/netlifys-large-media-support/17259/9

```go
version https://git-lfs.github.com/spec/v1
oid sha256:e6df77690697794deacb9d6963e574044448bef923f7d688aab1d856c54388a3
size 4074082
```

I assume there are Git LFS Go libraries out there so we should be able to do this effectively.

**Comment by fool** [comment]
In netlify's build environment, by the time hugo is running, there won't be permissions to pull new files from the repo (all git permissions are dropped before build, after cloning), so while this might be useful in other circumstances, it won't solve build problems at Netlify for people using the large media feature.  

As far as I could determine don't currently have plans to make those files available directly during build.

**Comment by mkasu** [comment]
Just a comment, I'm not sure whether it would fit here or in the Discourse thread.

The way Netlify's Large Media support currently works is that the actual git repository and the git-lfs remote are completely separate. On each push, it will upload all LFS files to a separate server. On CI, it will only pull the main repository and some LFS metadata stubs, but no binary files, so Hugo would have no way to ever actually process data. As Netlify also makes money by selling Image Transformations as add-ons, I would assume that this is more or less on purpose and they wouldn't want to change it.

On the other hand, if using a normal GIT-LFS setup, you can set up Netlify to actually pull all binary LFS files into the build environment. Then, it'll just do a post-processing step replacing all metadata stubs with the real binary data after pulling the repo into the CI. Then, GIT LFS + Netlify + Hugo already works pretty flawlessly. My website uses this without issues. I have almost 4000 images when including all transformations done by Hugo. Although, doing all transformations would took about 10-15 minutes on each deploy, so I now usually commit the cache into the repo (also using git-lfs for this.)

**Comment by bep** [comment]
@mkasu thanks for the input, some of these issues I create without too much thought, as a reminder. Sometimes they are good ideas, sometimes they can lead to other good ideas.

>Although, doing all transformations would took about 10-15 minutes on each deploy,

If you configure your image to use `:cacheDir`, e.g.:

```bash
[caches.images]
dir = ":cacheDir/_gen"
```

Hugo will use Netlify's cache dir, which, in my tests, should survive deploys.

**Comment by mkasu** [comment]
> @mkasu thanks for the input, some of these issues I create without too much thought, as a reminder. Sometimes they are good ideas, sometimes they can lead to other good ideas.

Sure, just giving some viewpoints as I have played around with GIT LFS/Netlify Large Media Support quite a bit.

I think a proxy format would still be a good idea, not in LFS context, but if somebody wants to deploy images separately (e.g. their CDN or another server.) I played around with making a photography website in the past. I wouldn't necessarily want to deploy the images together, but rather just link to them and upload them somewhere else. Of course I could just link them in articles, but having a proxy format and being able to use asset management would allow for more integration with other Hugo stuff. 

> ```shell
> [caches.images]
> dir = ":cacheDir/_gen"
> ```
> 
> Hugo will use Netlify's cache dir, which, in my tests, should survive deploys.

Ah yeah, thanks. I think I already did that once in the past but forgot about it.

Now I just need to clean up my GIT LFS repository (Hint: LFS is terrible and does not provide a way to actually prune old files, ever, so repositories just keep growing. Makes sense from a git-standpoint of preserving all history but gets ridiculous for in LFS context targeting big binary blobs.)

**Comment by bep** [comment]
> LFS does not provide a way to actually prune old files, ever, so repositories just keep growing.

Oh my ...

**Comment by mkasu** [comment]
> > LFS does not provide a way to actually prune old files, ever, so repositories just keep growing.
> 
> Oh my ...

Sorry for going off-topic but I can't resist to add the workaround GitHub recommends for pruning old files:

https://help.github.com/en/articles/removing-files-from-git-large-file-storage#git-lfs-objects-in-your-repository
> To remove Git LFS objects from a repository, delete and recreate the repository.

**Comment by jwarner112** [comment]
I'd like to bump this -- I've been building my first Hugo website (fantastic tool btw, thanks guys) and kept having the most bewildering problem of an image showing up and being accessible and visible, but the local server and online servers couldn't show the image.

By process of elimination I discovered that it was unknowingly treating Git LFS pointers as their host file, and giving no warning to this fact -- it would port the file from `assets/images` just fine and even provide a valid `.Permalink` to the file, and that's the only work I was doing with it so all was "fine" from the rendering side. But in display, the browser saw a corrupt PNG file and acted as such.

If not proper proxy file handling, then perhaps for now the `resource` objects could begin parsing files based on their header info? I'm able to rename `image.png` to `image.jpg` and it will still render in Firefox, suggesting that if it _can't_ open the file it's because the contents are corrupt or unknown. This _would_ allow people to do such renaming within a Hugo project, but it would _also_ let Hugo know when the file someone's trying to use can't be.

Then again, this would complicate operations like resource type-matching... Hrm. Maybe the proxy file handler would be easier after all?
