### ISSUE TITLE
hugo creates directories too early

### ISSUE THREAD

**Issue by laroche** [gohugoio/hugo#5756]
Thanks for your wonderful software. The following log shows that "resources/_gen" is created
if hugo is invoked within a new directory. As you error out due to a missing "content" directory,
maybe this check could be done even earlier?

data$ mkdir web2
data$ cd web2
data/web2$ hugo
Total in 3 ms
Error: Error building site: open /home/flaroche/data/web2/content: no such file or directory
data/web2$ ls -laR
.:
insgesamt 12
drwxr-xr-x 3 flaroche flaroche 4096 Mär 17 09:06 .
drwxr-xr-x 7 flaroche flaroche 4096 Mär 17 09:06 ..
drwxr-xr-x 3 flaroche flaroche 4096 Mär 17 09:06 resources

./resources:
insgesamt 12
drwxr-xr-x 3 flaroche flaroche 4096 Mär 17 09:06 .
drwxr-xr-x 3 flaroche flaroche 4096 Mär 17 09:06 ..
drwxr-xr-x 4 flaroche flaroche 4096 Mär 17 09:06 _gen

./resources/_gen:
insgesamt 16
drwxr-xr-x 4 flaroche flaroche 4096 Mär 17 09:06 .
drwxr-xr-x 3 flaroche flaroche 4096 Mär 17 09:06 ..
drwxr-xr-x 2 flaroche flaroche 4096 Mär 17 09:06 assets
drwxr-xr-x 2 flaroche flaroche 4096 Mär 17 09:06 images

./resources/_gen/assets:
insgesamt 8
drwxr-xr-x 2 flaroche flaroche 4096 Mär 17 09:06 .
drwxr-xr-x 4 flaroche flaroche 4096 Mär 17 09:06 ..

./resources/_gen/images:
insgesamt 8
drwxr-xr-x 2 flaroche flaroche 4096 Mär 17 09:06 .
drwxr-xr-x 4 flaroche flaroche 4096 Mär 17 09:06 ..

**Comment by bep** [comment]
If I understand the issue, the side effect of this is that we create some directories that could have avoided if we had caught this earlier?

We could have done this check earlier, but in "all of Hugo" there will be always an endless list of similar issues: If we abort processing at 50% because of an error situation, you will have 50% of the files and directories, so I'm not sure we can do anything about that.

**Comment by laroche** [comment]
Ok, if there is no "easy fix" then I just close this issue. I'd rather see "real features" being
developed.

best regards and big thanks for hugo,

Florian La Roche
