### ISSUE TITLE
Corrupt HTML output

### ISSUE THREAD

**Issue by geeknoid** [gohugoio/hugo#5774]
[hugobug.zip](https://github.com/gohugoio/hugo/files/2995057/hugobug.zip)

Attached is a minimal Hugo project which demonstrates a problem with surprising behavior in markdown conversion. Unzip and run hugo 0.54 with no command-line options. Look at the generated index.html to see the bad HTML. Note the LI and OL closing tags which were inserted somehow in the middle of the previously generated DIV block.

warning.html is producing a simple `<div>stuff</div>` which gets embedded into a tab which is part of a tabset. What is inserting the IL/OL closing tags in the middle of this fully rendered HTML.

In case it matters, I see this behavior on macOS.

**Comment by Jos512** [comment]
I took a look at your code. It happened to me too with Hugo 0.54. The problem seems to be combining Markdown with nested shortcodes.

I don't know if this is a bug or a "feature" of how BlackFriday works.

---

For others, here's a quick summary of what's in the zip. A content file:

~~~
---
---
{{< tabset >}}
{{< tab >}}
1. First bullet
    {{< warning >}}
    {{< /warning >}}
{{< /tab >}}
{{< /tabset >}}
~~~

`tabset.html` shortcode has:

~~~
{{- $tabs := .Scratch.Get "tabs" -}}
{{- $text := .Inner -}}
{{- range $tabs -}}
{{- . | markdownify -}}
{{- end -}}
~~~

`tab` shortcode has:

~~~
{{- if not (.Parent.Scratch.Get "tabs") -}}
{{- .Parent.Scratch.Set "tabs" slice -}}
{{- end -}}
{{- $.Parent.Scratch.Add "tabs" .Inner -}}
~~~

And `warning` shortcode has:

~~~
<div>
{{- $text := .Inner -}}
{{- $text = "<p>First para</p>\n\n<p>Second para</p>\n" -}}
{{- $text | safeHTML -}}
</div>
~~~

The rendered HTML from that content file is:

~~~
<ol>
<li>First bullet
<div><p>First para</p></li>
</ol>

<p><p>Second para</p>
</div></p>
~~~

I recall that there was already an issue earlier about shortcode output being wrapped in `<p></p>` tags, which is part of the thing that happened here. I cannot find that issue, however (don't recall its title).

**Comment by bep** [comment]
@Jos512 I'm not a big fan of "me too" comments on existing threads unless they obviously add some new information that is vital to solving the issue.

@geeknoid I will keep this issue open, but I have limited time to do open source support these days, so you may get faster response at https://discourse.gohugo.io/ -- if this is an issue with inter-shortcode-communication via scratch I would recommend that you double check the ordering and remember that shortcodes are rendered inside-out.

**Comment by geeknoid** [comment]
I'm pretty sure the shortcode logic is working. I've got a bunch of complicated tests on my site for all manner of compositions of the real-world version of those shortcodes (https://istio.io/test). The only composition that doesn't work is when I try to produce a shortcode in a markdown list, nested in a tab. 

The problem doesn't appear if the <warning> shortcode outputs a single paragraph instead of two.

**Comment by christianrondeau** [comment]
Here's a very simple reproduction of this issue (hopefully it's the same one) using only one shortcode and a very simple page. I tried variations for hours, so I'm only attaching one that breaks the HTML output. It feels like the shortcode handling within lists is somehow broken (I get `<p>` around `<div>`, and `<ol>` is broken in multiple parts - this is using Hugo 0.55.3, the issue doesn't seem to affect 0.54.0 though it's hard to say, since shortcode handling is different)

Shortcode `request.html`:

```
<div class="request">
    {{ .Inner }}
</div>
```

Content `page.md`:

```
1. This is a request:
    {{%request%}}
    ```http
    GET /url HTTP/1.1
    ```
    {{%/request%}}
2. This is another request:
    {{%request%}}
    ```http
    HTTP/1.1 200 OK
    Content-type: "application/json"
    ```
    {{%/request%}}
3. This is a third point.
```

Result:

![image](https://user-images.githubusercontent.com/251037/56681402-47ab1500-6697-11e9-80ba-43f67647ba28.png)

Resulting HTML:

```html
<div class="post-content">
<ol>
<li><p>This is a request:
<div class="request"></p>

<pre><code class="language-http">GET /url HTTP/1.1
</code></pre></li>
</ol>

<p></div></p>

<ol>
<li><p>This is another request:
<div class="request"></p>

<pre><code class="language-http">HTTP/1.1 200 OK
Content-type: &quot;application/json&quot;
</code></pre></li>
</ol>

<p></div></p>

<ol>
<li>This is a third point.</li>
</ol>

</div>
```

**Comment by christianrondeau** [comment]
Interestingly, using a `<section>` instead of a `<div>` in the shortcode _still breaks_ the numbering, but it stops inserting `<p>` everywhere.

Note that using the resulting HTML directly in the list instead of using shortcodes yield correct numbering (the  `</li></ol>` is not inserted).

**Comment by christianrondeau** [comment]
Last update on my end, it looks like the `{{% ... %}}` shortcodes when used in lists actually are wrapped in `<p>`, which break everything.

My solution was actually very similar to https://github.com/gohugoio/hugo/issues/4717#issuecomment-449440991, which was:

1. Use `{{< request >}}` instead of `{{% request %}}`, so Hugo stops trying to re-markdownify
2. Manually figure out the indentation, and remove it from the content of the shortcode so Hugo can re-insert it later.

So my shortcode now looks like this (NOTE: I'm not saying this is in any way a fix for the underlying issue, but maybe it'll help other people "fix" their Hugo site):

```
{{- $code := trim .Inner "\n\r" -}}
{{- $indentMatch := findRE `^ +` $code 1 -}}
{{- if gt (len $indentMatch) 0 -}}
  {{- $indent := index $indentMatch 0 }}
  {{- $code = $code | replaceRE (printf "(?m)^%s" $indent) "" -}}
{{- end }}
<section class="request">
    {{ $code | markdownify }}
</section>
```
