### ISSUE TITLE
Conditional checks not working in href attribute of anchor tag in shortcodes

### ISSUE THREAD

**Issue by praveendinesh6** [gohugoio/hugo#5796]
I'm using conditional checks inside the href attribute of anchor tags in shortcode. I have the content file as 

```
---
country: "us"
---

Hello, world. Here is some text.

{{< redirection-url "somewebsitepageurl">}}

```

In the shortcode, I'm using
```
<a href="{{if $.Page.Params.country }}/{{$.Page.Params.country}}{{end}}/{{ index .Params 0}}">
  Click here
</a>
```
The above code is not rendering the shortcode. 

Whereas, I can use the condition as a block like this

```
{{if $.Page.Params.country}}
  <a href="/{{$.Page.Params.country}}/{{ index .Params 0}}">Click here</a>
{{else}}
  <a href="/{{ index .Params 0}}">Click here</a>
{{/if}}
```

**Comment by bep** [comment]
Thanks for getting in touch, but it feels like this is a question  that would be better suited to the [Hugo Discussion Forum](https://discourse.gohugo.io/).  We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug. You may also find the answers you search for in [Hugo Documentation](http://gohugo.io/overview/introduction/).

**Comment by zwbetz-gh** [comment]
The re-posted question: https://discourse.gohugo.io/t/conditional-checks-not-working-in-href-attribute-of-anchor-tag-in-shortcodes/17784
