### ISSUE TITLE
Can't use content/design/ as a Section

### ISSUE THREAD

**Issue by frankwiles** [gohugoio/hugo#5807]
Hello, apologies if this is posted in another issue, but I couldn't find any reference to it. 

I'm currently using Hugo v0.54.0 and am building a simple theme to use for some internal documentation with a client of ours. Nothing fancy, just a couple of templates and some syntax highlighting. 

I thought I was doing something wrong, but it seems that you cannot have a Content Section of `content/design/`.  Renaming this directory to something else like `content/arch/` makes it work with existing layouts. 

For completeness sake here is the structure: 

```
content/
    _index.md
    design/
        _index.md
    ops/
        _index.md
    testing/
       _index.md
layouts/
    _default/
        single.html
        list.html
        section.html
    index.html
```

Did I perhaps stumble upon some reserved word perhaps?

**Comment by onedrawingperday** [comment]
>Did I perhaps stumble upon some reserved word perhaps?

No design is not a reserved word in Hugo. I know first hand because I am using a design section in one of my projects.

Something else is at play here. I suggest that you open a topic in the [Hugo Support Forum](https://discourse.gohugo.io) and make sure to read the forum's [guidelines](https://discourse.gohugo.io/t/requesting-help/9132) for requesting help.
