### ISSUE TITLE
Consider relative url vs lang prefix

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#5818]
I saw a multilingual site in the wild with this front matter:

```bash
url: en/pictures
```

Since we in Hugo 0.55 supports page-relative URLs in front matter (a good thing!), the above would end up below `/en/en/pictures/`, which is obviously not correct.

Both of the below would produce correct output:

```bash
url: /en/pictures
```

```bash
url: pictures
```

I suspect that it is more common than not to have a leading `/` in URLs, but I will think about the above and consider if we can add an additional check (I thought we did).

/cc @divinerites

**Comment by divinerites** [comment]
Hey Bep !! Thanks for the cc:
Just to give some context about my use case for that.

If I juste use folder and file name automatically created by hugo out of the box it works fine.

But it doesn't goes well with SEO because file names/url/contents are quite differents.

So in order to keep SEO happy I had to change url name to be consistent with each language (ex : hiking/randonnees).

And I couldn't find an other workaround than putting the language prefix in urls (en/hiking, fr/randonnees).

But avoiding to have hardcoding language in URL would be perfect.

**Comment by bep** [comment]
>If I juste use folder and file name automatically created by hugo out of the box it works fine.

Sure, I have no problem with the "why" -- my motivation behind this issue is to reduce the number of questions/issues about this particular issue once we release 0.55. I so I might add another check.

**Comment by Brixy** [comment]
Sorry: I am not sure whether this is related.

The reason why I need to use e.g.

```
url: /en/contact/
```

is because

```
slug: contact
```

results in this URL: `/en/kontakt/contact/`.

If helpful, I can upload a minimal working setup.

**Comment by divinerites** [comment]
just to report that I removed all my `en/`, 'nl/`, ... from url front matter. My use case works like a charm and as expected I do not have to worry to add language as a prefix any more.

The warning will be helpfull tho.
