### ISSUE TITLE
Markdown content in shortcode is not correctly rendered

### ISSUE THREAD

**Issue by MHerbst** [gohugoio/hugo#5888]
I have tested it with Hugo 0.55.3 on Windows 10

I have added a call toan own shortcode to my text with the following content:
```
{{% box type="info"  %}}Ich habe `openssl` in der Ubuntu Shell von Windows 10 ausgeführt. {{% /box %}}
```
As you can see in this screenshot the backticks are not recognized:
![image](https://user-images.githubusercontent.com/616792/56511535-1f9fa280-652d-11e9-8d69-3556bbf22bf4.png)

This is the definition of the shortcode:
```
<div class="bs-callout bs-callout-{{ .Get "type" }}">
  {{ if .Get "icon"}}
  <div style="float: left;font-size: 32px;padding-right: 10px"><i class="fas fa-{{ .Get "icon" }}"></i></div>
  {{ end }}
  <div>
    {{ if .Get "caption" }}
    <h4>{{ .Get "caption" }}</h4>
    {{ end }}
    {{ .Inner }}
  </div>
</div>
```

**Comment by bep** [comment]
Thanks for getting in touch, but it feels like this is a question  that would be better suited to the [Hugo Discussion Forum](https://discourse.gohugo.io/).  We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug. You may also find the answers you search for in [Hugo Documentation](http://gohugo.io/overview/introduction/).

**Comment by MHerbst** [comment]
To me, it looked like a bug because I can't see any error in the shortcode definition. But I will create a post in the forum.
