### ISSUE TITLE
Parsing markdown inside shortcodes

### ISSUE THREAD

**Issue by pawelgrzybek** [gohugoio/hugo#5900]
Hi.

```
$ hugo env
Hugo Static Site Generator v0.55.3/extended darwin/amd64 BuildDate: unknown
GOOS="darwin"
GOARCH="amd64"
GOVERSION="go1.12.4"
```

I have a shortcode `update`.

```
<p class="update">{{ .Inner  }}</p>
```

When I use it with some markdown content (link for example).

```
{{% update %}}This is link to a [google](https://google.com).{{% /update %}}
```

It is not getting converted to HTML anymore. I am almost sure it used to work just fine on previous versions of Hugo. Currently it outputs a plain text.

Still ❤️ Hugo and thanks for building amazing software!

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).

**Comment by SamWhited** [comment]
@bep I'm not sure if this is the same thing, but as of the latest version this behavior has changed for me. That used to render markdown, and now it doesn't. I don't see anything in the documentation that would explain that change. Are you sure this should have been closed?

**Comment by pawelgrzybek** [comment]
Hi @SamWhited 

https://gohugo.io/content-management/shortcodes/#shortcodes-with-markdown

**Comment by SamWhited** [comment]
@pawelgrzybek I have read that; I apparently don't understand what it means, because I don't even know what the old or new behavior is. That makes it sound like the new behavior should still be rendering markdown, but I'm not getting any markdown rendered anymore. Is that he cause of this problem? If so, why does it just break every single shortcode I have in my theme and sites and should I be reverting to the old behavior or piping `.Inner` to markdownify? What are the tradeoffs to doing it one way or the other?

**Comment by pawelgrzybek** [comment]
The solution is mentioned in the docs. This is everything that you have to do. 

https://github.com/pawelgrzybek/pawelgrzybek.com/commit/6c0e63e522a3ded1ef64b478ab444fc95e5e6b08

Hopefully that helps.

**Comment by SamWhited** [comment]
On Thu, Apr 25, 2019, at 20:33, Pawel Grzybek wrote:
> The solution is mentioned in the docs. This is everything that you
> have to do.

What does that even mean? What are the side effects? What is the
difference between that and `markdownify`? The docs are incomplete and
it still feels like a bug that everything suddenly broke. I'm worried
about not picking the correct solution because there's no information in
the docs about what any of this does or why it broke.

Maybe all of this is clear if you're familiar with the Hugo internals,
but it's not clear to me or any of the other people who have asked on
the list or filed issues. Please clarify the situation.

—Sam

**Comment by pawelgrzybek** [comment]
Good morning Sam. Documentation clearly describes what happened. If you are not happy you can always downgrade to version 0.54.

> In Hugo 0.55 we changed how the % delimiter works. Shortcodes using the % as the outer-most delimiter will now be fully rendered when sent to the content renderer (e.g. Blackfriday for Markdown), meaning they can be part of the generated table of contents, footnotes, etc.
> 
> If you want the old behavior, you can put the following line in the start of your shortcode template:

```
{{ $_hugo_config := `{ "version": 1 }` }}
```

This is exactly what I did to make my shortcode work as it used to do. To find out even more about it, you can have a look at the changelog for 0.55.

https://gohugo.io/news/0.55.0-relnotes#shortcodes-revised

In depth stuff and authors reasoning here:

https://github.com/gohugoio/hugo/issues/5763

Hopefully that helps.

**Comment by SamWhited** [comment]
Am I really the only one that thinks that is confusing and doesn't tell me anything? What does it even mean that it is "fully rendered"?

I still have no idea if that's an okay solution, or if it's just going to go away in a few months since apparently whatever the old behavior was is deprecated. Also, what is the difference between doing that and piping to markdownify and why would I use one over the other?

**Comment by pawelgrzybek** [comment]
Thats the beauty of open source. If you think you can do better — stop complaining and do it. I am super thankful for Hugo because it helps me a lot.

Bye

**Comment by SamWhited** [comment]
I don't want to do better, that might be fine. I just want it documented what the options are and what the benefits and drawbacks are in such away that's understandable to someone who isn't familiar with Hugo's internals and just uses it to build websites.

**Comment by fritzmg** [comment]
I agree that the documentation is confusing. It clearly states that, even in 0.55, if you want to use markdown in your shortcodes, you have to use the `%` delimiter.

However, that is exactly what is not working.

**Comment by SamWhited** [comment]
Please listen to @fritzmg and all the other people that opened issues for this. We can't update the docs because no one understands what this means, and I'm still lost as to what actually changed or what solution I should use. Stop blaming your users for being confused and write clearer docs.

**Comment by fritzmg** [comment]
I have contributed to this discussion thread here, I think this clears things up a little: https://discourse.gohugo.io/t/misunderstanding-of-shortcode-syntax-in-0-55/18538

**Comment by SamWhited** [comment]
That all makes a lot more sense than the documentation; thanks for linking the thread.

**Comment by fritzmg** [comment]
Though I discovered that the new approach is not without problems: https://discourse.gohugo.io/t/misunderstanding-of-shortcode-syntax-in-0-55/18538/25

**Comment by wilitp** [comment]
For anyone actually looking for a solution...

If you are using your shortcode as
```markdown
{{ myclosingsc }} 
# heading 
{{ myclosingsc /}}
```

`shotcodes/myclosingsc.html`:
```html
{{ .Inner | markdownify}}
```

this outputs: 
```html
<h1>heading</h1>
```

**Comment by kuncevic** [comment]
Got this issue https://github.com/zwbetz-gh/papercss-hugo-theme/issues/8 using https://github.com/gohugoio/hugo/issues/5900#issuecomment-780084646 solution.
