### ISSUE TITLE
Live reload not working again

### ISSUE THREAD

**Issue by BolajiAyodeji** [gohugoio/hugo#5914]
This has been working before now.

When I make new changes, live reload does not work and nothing changes in my browser.
I've cleared my cache and tried all I could, but it still is not reloading new changes.
`hugo server` and `hugo server -D` results the same issue

```
  Pages            | 112
  Paginator pages  |   1
  Non-page files   |   0
  Static files     | 105
  Processed images |   0
  Aliases          |  45
  Sitemaps         |   1
  Cleaned          |   0

Total in 362 ms
Watching for changes in C:\Hugo\Sites\ba\{content,data,layouts,static,themes}
Watching for config changes in C:\Hugo\Sites\ba\config.toml
Environment: "development"
Serving pages from memory
Web Server is available at http://localhost:1313/ (bind address 127.0.0.1)
Press Ctrl+C to stop
```
Here's my current hugo version
`Hugo Static Site Generator v0.53/extended windows/amd64 BuildDate: unknown`

**Comment by BolajiAyodeji** [comment]
Aside from the watching feature.
It does not display new changes at all.
I need help please

**Comment by bep** [comment]
Thanks for getting in touch, but it feels like this is a question  that would be better suited to the [Hugo Discussion Forum](https://discourse.gohugo.io/).  We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug. You may also find the answers you search for in [Hugo Documentation](http://gohugo.io/overview/introduction/).

**Comment by BolajiAyodeji** [comment]
Here's a link to the question on Hugo Discourse.
https://discourse.gohugo.io/t/live-reload-not-working-again-how-can-i-fix/18436/4
