### ISSUE TITLE
Make language-specific BaseURL accessible from Languages map

### ISSUE THREAD

**Issue by 39otrebla** [gohugoio/hugo#5948]
We have a Multilingual **Multihost** installation. We would like to generate `hreflang` meta for each page, from the base template.

Attempting to do this:
```
{{ range .Site.Languages }}
  <link rel="alternate" hreflang="{{ .Lang }}" href='{{ path.Join .BaseURL $.RelPermalink }}' />
{{ end }}
```

we've realized that `.BaseURL` is not available, which is wired since i.e. `.Lang` and `.Weight` both work.

**NOTE**:
Having `.BaseURL` available in languages map would also be convenient for building language-switch menù.

**Comment by tofikst** [comment]
@39otrebla

**Comment by bep** [comment]
Thanks for getting in touch, but it feels like this is a question  that would be better suited to the [Hugo Discussion Forum](https://discourse.gohugo.io/).  We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug. You may also find the answers you search for in [Hugo Documentation](http://gohugo.io/overview/introduction/).

**Comment by 39otrebla** [comment]
@bep I believe this an enhancement...

**Comment by 39otrebla** [comment]
For anyone having the same problem: I realized it is possible to access `.Params.BaseURL` when in scope of a specific language (i.e. in a `range`). That gives the BaseURL defined for that language.
