### ISSUE TITLE
Allow markdownify as a block for .Inner

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#5975]
Typical construction  is:

```
{{ .Inner | markdownify }}
```

The current logic is that we remove surrounding `<p></p>` if there is only one paragraph.

For people doing `{{ .Inner }}` => `{{ .Inner | markdownify }}` because of the changes made in 0.55, this behaviour would be subtle breaking. 

I don't think we'd want this for every `.Inner` (that would breaking it for others), but I suggest we add a new `block` keyword (it has been discussed before), so you would then do:

```
{{ .Inner | block | markdownify }}
```

Also see https://github.com/gohugoio/hugo/issues/3040

**Comment by fritzmg** [comment]
I think the other way around makes more sense, e.g.
```
{{ .Inner | markdownify | inline }}
```
The default behaviour of any markdown parser is that regular text is always wrapped in a paragraph. Imho it's a more special case to want markdown "inline" somewhere.

**Comment by Brixy** [comment]
`inner` seems more obvious because the `block` behaviour is what you would normally expect.

If I get it correctly either `inner` or `block` would make ‘hacks’ like this obsolete ([source](https://github.com/martignoni/hugo-notice/blob/master/layouts/shortcodes/notice.html)).

```
{{/* Workaround markdownify inconsistency for single/multiple paragraphs */}}
{{- $raw := (markdownify .Inner | chomp) -}}
{{- $block := findRE "(?is)^<(?:address|article|aside|blockquote|canvas|dd|div|dl|dt|fieldset|figcaption|figure|footer|form|h(?:1|2|3|4|5|6)|header|hgroup|hr|li|main|nav|noscript|ol|output|p|pre|section|table|tfoot|ul|video)\\b" $raw 1 -}}
```

**Comment by biodranik** [comment]
What about adding a config option about markdownify behavior? E.g. “strip <p> if one paragraph”, “do not strip <p>”, “split paragraphs by <br>”, etc.? Or even make “markdownifyNoParagraph” or something similar?

**Comment by charneykaye** [comment]
Just discovered this annoying "invented here" behavior of stripping `<p>` tags when the content is only one line. I have this line in my **single.html** template:

```
{{ .Content | markdownify }}
```
But when the content of an item has only one line, there is no P tag added, and the style of the single template breaks.

Seems to me that having special behavior of ignoring the addition of `<p>` tags is the problem here.

**Comment by dinoboff** [comment]
@fritzmg The issue with `{{ $string | markdownify | inline }}` is that you have to format your string and then parse it again to trim a wrapping block element. It's more efficient to to have `{{ $string | someOptions | markdownify }}`.

**Comment by dinoboff** [comment]
IMHO, `markdownify` inlining the content of a single paragraph might be helpful but when it's not, the error is difficult to catch. Assuming hugo wasn't stripping any paragraph and had an easy way to get the inline content of the first block element, something like `<h1>{{ .Title | markdownify }}</h1>` would fail but it would always fail. You just need the solution to be easy to find.

You could deprecate markdownify and leave it with current behaviour, replace it with `markdown.format` and `markdown.inline`, e.g.:

```
<h1>{{ .Title | markdown.Inline }}</h1>
{{ .Content | markdown.Format }}
```

**Comment by jmooring** [comment]
It seems like this issue was resolved with creation of the [.RenderString](https://gohugo.io/functions/renderstring/) page method. For example, 

```
.RenderString (dict "display" "block") "foo bar baz"
```

Can we close this issue?

**Comment by jmooring** [comment]
@salim-b I notice your "thumbs down" on https://github.com/gohugoio/hugo/issues/5975#issuecomment-808457585. Please explain. Thanks.

**Comment by salim-b** [comment]
IMHO not having an easy-to-remember "type-safe" alternative to `markdownify` is not a good API design choice – from a user perspective. And I guess it will be easier to make theme authors switch to using something like `{{ . | block | markdownify }}` or `markdown.format .` for variable markdown content than ` .Page.RenderString (dict "display" "block") .`.

I'm aware it's kind of a luxury problem since the assortment of [functions, page methods](https://gohugo.io/functions/), [variables](https://gohugo.io/variables/) etc, I'd call the Hugo theming API is not a particularly"shining example" in this regard. It's just something I would _wish_ for. 🙂

**Comment by benjaoming** [comment]
> But that's a side effect of the original mistake of inventing new behavior for something as ubiquitous as Markdown.

:+1: :dart: 

Two additional proposals:

## 1. Add a completely new function

Could the existing function simply be deprecated in favor of a new function with a different name and a strict implementation w/ explicit options for the old inline behavior?

Would it cause issues to call a new function simply `markdown`?

## 2. Deprecate and replace the default behavior of `markdownify`

The old default behavior of `markdownify` could be replaced in some version and deprecated. In order to do that, warnings should be raised for unmarked usage of the current default. That could be:

`{{ .Inner | deprecated | markdownify }}` = Keep old behavior, silence warnings
`{{ .Inner | inline | markdownify }}` = Explicit behavior for inline
`{{ .Inner | block | markdownify }}` = Explicit behavior for block
`{{ .Inner | autoinline | markdownify }}` = I don't think anyone needs this.. but in case you'd want the old deprecated behavior to persist, it could have a proper name that doesn't appear deprecated.

Warning message:

> markdownify's default behavior will change in Hugo 0.XYZ. Please use either "inline" or "block" options. See docs: ...

This decision keeps being postponed because there's not obvious way to fix it and breaking stuff has a lot of consequences. I'd suggest a pretty long deprecate path (1 year) and adding proper documentation once new keyword options are introduced.

**Comment by loikein** [comment]
Proposed solution:

Improve the example code on [.RenderString documentation](https://gohugo.io/functions/renderstring/) a bit, because it is not obvious at all that you can do 
`{{ .Inner | $.Page.RenderString (dict "display" "block") }}`
to achieve what is required here. (And not with `$p`.)

I was mostly pleased with the result it gives, except footnotes in this Inner will not work with the rest of the page in any shape or form. I wonder why is that…

**Comment by jmooring** [comment]
> Improve the example code on [.RenderString documentation](https://gohugo.io/functions/renderstring/) a bit, because it is not obvious at all that you can do
{{ .Inner | $.Page.RenderString (dict "display" "block") }}

Done.
