### ISSUE TITLE
Add a map deep merging function.

### ISSUE THREAD

**Issue by regisphilibert** [gohugoio/hugo#5992]
As `return` partials become more and more popular users need for safely manipulating data will grow.

First use case I can think of is for declaring defaults vs bespoke arguments in a partial, and gracefully merge the later with the former, but I can see so much more.

It would be interesting for Hugo to provide a safe deep merge solution so users don't need to build their own.

I don't think we need this to work with raw Page context, users can always reshape their data inside custom maps.

Examples follow.

```
{{ $default := dict "title" .Title }}
{{ $bespoke = maps.Merge $default .Params }}

{{/* In a partial context /*}} 
{{ $default := (site.GetPage "default").Params }}
{{ $bespoke := maps.Merge $default . }}
```

**Comment by carlmjohnson** [comment]
In general, simpler tools for mutating dicts would be appreciated. See, e.g, [this LD-JSON file](https://github.com/spotlightpa/poor-richard/blob/e9da97fa1370a6c411c76efb8403d47aa0da316d/layouts/partials/ld-json.html) where I was having some issues with bad escaping (Go thinks the LD-JSON is JavaScript and escapes it in a way that Google does not understand), so I decided to do things the "safe" way by building one big dict and writing the whole thing out at once. That works, but the code is very ugly because there's no simple way to just mutate a dict in place. Instead I use a scratch.
