### ISSUE TITLE
Filter and paginate posts based on date

### ISSUE THREAD

**Issue by aureooms** [gohugoio/hugo#5995]
Is there a convenient way to paginate and filter based on a time `.Param`?

For example the following does not work because `where` works with keys and not expressions (building with `--buildFuture=true`):

```
{{ range first 3 (where (where .Site.RegularPages (.Section == "post")).Reverse ((time (.Param "date")).After now)) }}
...
{{ end }}
```
I can simulate that quite painfully with `$.Scratch` variables by maintaining a counter and doing the filtering manually.

However, I have no idea how to go about pagination over future/past posts.

**Comment by aureooms** [comment]
I guess for pagination a working idea would be two have two different sections: a `future` Section and a `past` section. That would also solve the filtering issue.

**Comment by aureooms** [comment]
I think I'll go with the split section solution because with the `time ... .After/.Before now` based solution the site needs to be rebuild anyway to reinterpret future events as past events. If anybody thinks this is a good solution please close this issue!

**Comment by bep** [comment]
Thanks for getting in touch, but it feels like this is a question  that would be better suited to the [Hugo Discussion Forum](https://discourse.gohugo.io/).  We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug. You may also find the answers you search for in [Hugo Documentation](http://gohugo.io/overview/introduction/).
