### ISSUE TITLE
Feedback on default behavior for selecting layouts for content

### ISSUE THREAD

**Issue by jmoyers** [gohugoio/hugo#6065]
As a new user, I found the default behavior of selecting a layout for my home page to be unintuitive. I had a simple `content/_index.html`, a `layout/_default/index.htm` with a `{{.Content}}` block and it was not working.

After an hour of fussing around I found this key line in the docs: 

> Note that if you want your HTML files to have a layout, they need front matter. It can be empty, but it has to be there.

So adding an empty front-matter block to the _index.html file resolved my issue.

However, the error messages I got were not informative:
`WARN 2019/06/27 15:34:26 found no layout file for "HTML" for "home": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.`

I moved my index.html template around to probably 10 different places trying to match the lookup path. Pretty sure all of them were valid - I checked the path precedence in the docs 5 or 6 times, changed the name, etc.

It would be great to change the default behavior to use the template if its present, or at least to warn you that a front-matterless html file won't use a template even if its present on the CLI. It was very easy to miss that solitary line in the docs.

**Comment by therealplato** [comment]
I tried to rebuild a previously working site and got the same "found no layout file" error and no output.

Where can I find documentation of this breaking change?

**Comment by therealplato** [comment]
I'm running v0.57-0-DEV linux/amd64 against this content: https://github.com/therealplato/therealplato.com/tree/master/hugosite

**Comment by bep** [comment]
Thanks for getting in touch, but it feels like this is a question  that would be better suited to the [Hugo Discussion Forum](https://discourse.gohugo.io/).  We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug. You may also find the answers you search for in [Hugo Documentation](http://gohugo.io/overview/introduction/).

**Comment by therealplato** [comment]
Reposted at https://discourse.gohugo.io/t/where-can-i-find-documentation-of-breaking-change-found-no-layout-file/20068
