### ISSUE TITLE
[Feat Request]Sort titles of articles by time desc in categories

### ISSUE THREAD

**Issue by dawnarc** [gohugoio/hugo#6084]
As shown in the following image, order of articles are muddled in **Categories** page, could hugo sort articles by time desc?
![image](https://user-images.githubusercontent.com/3351764/60943604-0d0d5c00-a319-11e9-97ab-bb416c1bca9c.png)

**Comment by reuixiy** [comment]
@dawnarc Hey, dude. This is not Hugo’s problem, it’s your theme [hugo-tranquilpeak-theme](https://github.com/kakawait/hugo-tranquilpeak-theme/)’s bug. You should submit an issue there instead of here.

FYI, I have found a temporary workaround after I checked the relevant code.

## How (TL;DR)

1. Change `true` to `false`

https://github.com/kakawait/hugo-tranquilpeak-theme/blob/36538b8a6b34aed09032d5e3333b8accd800e5d7/exampleSite/config.toml#L117-L119

2. Delete `.ByDate`

https://github.com/kakawait/hugo-tranquilpeak-theme/blob/36538b8a6b34aed09032d5e3333b8accd800e5d7/layouts/taxonomy/category.terms.html#L105

## Why

In [category.terms.html](https://github.com/kakawait/hugo-tranquilpeak-theme/blob/master/layouts/taxonomy/category.terms.html), you can find this `if`:

https://github.com/kakawait/hugo-tranquilpeak-theme/blob/36538b8a6b34aed09032d5e3333b8accd800e5d7/layouts/taxonomy/category.terms.html#L76

And there must be one bug inside, this line:

https://github.com/kakawait/hugo-tranquilpeak-theme/blob/36538b8a6b34aed09032d5e3333b8accd800e5d7/layouts/taxonomy/category.terms.html#L84

However, the code at the top of the file is too complicated, I don't have time to check. So just edit `else`,  delete `.ByDate`, change `hierarchicalCategories` to `false`.

But why delete `.ByDate`? In Hugo’s [document](https://gohugo.io/templates/lists/#order-content), you can find that `Date` is in the default order and its `desc` already after my test.

**Comment by dawnarc** [comment]
@reuixiy Thanks very much! it works! have a nice day~
