### ISSUE TITLE
Hugo strips emoji in taxonomy keys

### ISSUE THREAD

**Issue by mro** [gohugoio/hugo#6117]
reopening #5367

```sh
$ hugo version
Hugo Static Site Generator v0.55.6-A5D4C82D darwin/amd64 BuildDate: 2019-05-18T07:56:30Z
```

… content of the term-page supposed to list the pages http://vorschau.mro.name/blog/tags/🚗 overwrites http://vorschau.mro.name/blog/tags/. I guess hugo trims the emoji from the filesystem path.

Failing page is e.g. http://vorschau.mro.name/blog/2019/07/tempo30/, source https://code.mro.name/mro/blog.mro.name/src/72c4ed16c329ba6f67b38304312041c2a8875cd2/content/posts/2019-07-21-tempo30/index.md config https://code.mro.name/mro/blog.mro.name/src/72c4ed16c329ba6f67b38304312041c2a8875cd2/config.yaml tries various themes, including hugo default.

**Comment by mro** [comment]
nobody else using emojis for tags or am I missing something obvious?

**Comment by neexee** [comment]
Hello. I have similar problem, I wanted to use ★ in my tags.
The problem lies in UnicodeSanitize function.
https://github.com/gohugoio/hugo/blob/0e75af74db30259ec355a7b79a1e257d5fe00eef/helpers/path.go#L142
It is used by getTaxonomyKey. https://github.com/gohugoio/hugo/blob/0e75af74db30259ec355a7b79a1e257d5fe00eef/hugolib/site.go#L1411

Allowed character set for a taxonomy keys is pretty narrow. So getTaxonomyKey receives a tag with emoji and strips the emoji. And the stripped tag goes to a theme template.

So the only possibility right now is to extend isAllowed condition by yourself. I have no idea how to extend it in a good way (it might break existing sites), maybe developers know.

https://github.com/gohugoio/hugo/issues/4032 is related, I think.

**Comment by neexee** [comment]
Maybe we can add something like this and provide a config option.
https://github.com/neexee/hugo/commit/61c2edfd6db7d43238abfc4e6a69746465a7608e

**Comment by mro** [comment]
closing in favour of #4032
