### ISSUE TITLE
<nil> is not a Resource

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#6128]
```bash
error calling fingerprint: <nil> is not a Resource
```

Got the above and similar when porting `gohugoioTheme` to a module in Hugo Docs today.

**Comment by SiamKreative** [comment]
@bep How was this solved? I am running into a very similar issue on Cactus theme

```
executing "partials/head.html" at <toCSS>: error calling toCSS: type <nil> not supported in Resource transformations
```

**Comment by bep** [comment]
You need to do a nil check in the templates. The thing is, `resource.Get("someresource.css")` returns nil if not found.

We could probably improve the error message, but you need to do something ala:

```
{ { $scss := resource.Get("foo.scss") }}

{{ if $scss }}
// call toSCSS
{{ end }}
```

**Comment by dallashudgens** [comment]
If my files are under the assets folder:  resources/_gen/assets/sass/main.scss, I don't understand why it can't find it. 

```{{ $style := resources.Get "sass/main.scss" | toCSS | minify | fingerprint }}
    <link rel="stylesheet" href="{{ $style.Permalink }}">```

**Comment by queiroz** [comment]
@dallashudgens The documentation states the following:

> Asset files must be stored in the asset directory. This is /assets by default, but can be configured via the configuration file’s assetDir key.

then given the example on that page:

```html
{{ $style := resources.Get "sass/main.scss" | resources.ToCSS | resources.Minify | resources.Fingerprint }}
<link rel="stylesheet" href="{{ $style.Permalink }}">
```

I ended up with the same error.
So I've decided to add a `/` to the beginning of the `resources.Get "/sass/main.scss"` and voila it worked  😄 

I am totally new to Hugo and am just giving a go, I understand the frustration when trying something new and it doesn't work as expected.

**Comment by DavidOliver** [comment]
I'm finding that `hugo server` needs to be stopped and restarted after asset files have been placed in `/assets` in order for `resources.Get` to work. Probably worth mentioning in the docs. :)

**Comment by rogeralsing** [comment]
This is highly confusing.

I've tried the following paths:

/static/assets/scss
/resources/_gen/assets/scss

/themes/mytheme/static/assets/scss
/themes/mytheme/resources/_gen/assets/scss

the call to resource.Get is inside my baseof inside mytheme


None of this works.

Ideas?

**Comment by khanakia** [comment]
Same issu e

**Comment by iaeiou** [comment]
I had the same error message and the problem was that for testing purpose I was leaving in my code *commented* lines like these:

```
<!-- {{ $style := resources.Get "scss/main.scss" | toCSS }} -->
<!-- <link rel="stylesheet" href="{{ $style.Permalink }}"> -->
```

Removing them solved the issue for me

I don't know if it's an expected behavior BTW, should I open an issue?

Here is the full error message I got:

`ERROR 2021/01/07 07:01:43 render of "page" failed: execute of template failed: template: _default/single.html:4:7: executing "_default/single.html" at <partial "head.html" .>: error calling partial: "/home[..]/themes/beautifulhugo/layouts/partials/head.html:49:51": execute of template failed: template: partials/head.html:49:51: executing "partials/head.html" at <toCSS>: error calling toCSS: type <nil> not supported in Resource transformations`

**Comment by davidsneighbour** [comment]
That is expected behaviour. If you want to comment out Golang template markup use Golang template markup comments ;)

```
{{/* {{ commented out code }} */}}
```
