### ISSUE TITLE
Footnotes continually breaking

### ISSUE THREAD

**Issue by sharontherese** [gohugoio/hugo#6150]
Hi! My website is chock full of footnotes, which I've been formatting: 

> "Scholars say that ...[^1]."
> 
> [^1]: Scholars, Some. 2019.

After about an hour or so, the footnotes add backward slashes, thus breaking the hyperlink. I've tried editing it in github and in the raw editor in forestry, but to no avail. Any help would be appreciated!

**Comment by bep** [comment]
Thanks for getting in touch, but it feels like this is a question  that would be better suited to the [Hugo Discussion Forum](https://discourse.gohugo.io/).  We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug. You may also find the answers you search for in [Hugo Documentation](http://gohugo.io/overview/introduction/).

**Comment by sharontherese** [comment]
Thank you!
