### ISSUE TITLE
upgrade mmark in order to avoid blocking Debian

### ISSUE THREAD

**Issue by retokromer** [gohugoio/hugo#6163]
Your dependency is blocking the upgrade of `mmark` to version 2 in [Debian](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=933837).

**Comment by onedrawingperday** [comment]
I suppose that you are referring to building Hugo from source since the binaries have no dependencies.

However as far as I know upgrading `mmark` is not an easy thing to do since it no longer uses https://github.com/russross/blackfriday which is the Markdown engine that Hugo uses. 

There is a long story about this if you want to read it please visit: https://github.com/gohugoio/hugo/issues/5124

**Comment by retokromer** [comment]
@onedrawingperday Thank you for the answer, which I forwarded: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=933837.
