### ISSUE TITLE
Shortcode quotes now escaped.

### ISSUE THREAD

**Issue by p-groarke** [gohugoio/hugo#6198]
I was using 0.46, which doesn't have this issue. Updating to 0.56.3, shortcode quotes are now escaped : `&quot;` which breaks html tags.

**Comment by bep** [comment]
You need to be more specific.

**Comment by p-groarke** [comment]
Create a shortcode which uses a doublequote `"`. When rendered it is parsed as `&quot;`. This breaks my shortcodes. It didn't happen before.

**Comment by bep** [comment]
Thanks for getting in touch, but it feels like this is a question  that would be better suited to the [Hugo Discussion Forum](https://discourse.gohugo.io/).  We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug. You may also find the answers you search for in [Hugo Documentation](http://gohugo.io/overview/introduction/).

**Comment by p-groarke** [comment]
Hey no problem, you are right its not a bug! https://github.com/gohugoio/hugo/issues/461
