### ISSUE TITLE
Bad include

### ISSUE THREAD

**Issue by cup** [gohugoio/hugo#6322]
Using this file:

~~~
#+INCLUDE: "app.php" src php
~~~

I get this result:

~~~
WARN 2019/09/09 23:04:11 Bad include
org.Keyword{Key:"INCLUDE", Value:"\"app.php\" src php"}:
open posts\app.php: The system cannot find the path specified.
~~~

Using this file:

~~~
#+INCLUDE: "posts\app.php" src php
~~~

I get this result:

~~~
WARN 2019/09/09 23:05:23 Bad include
org.Keyword{Key:"INCLUDE", Value:"\"posts\\app.php\" src php"}:
open posts\posts\app.php: The system cannot find the path specified.
~~~

**Comment by cup** [comment]
https://github.com/niklasfasching/go-org/issues/10

**Comment by kaushalmodi** [comment]
@cup You're an Org mode user too (I have seen you in the Nim community too)! :)

Copying @niklasfasching on this issue as he's the maintainer of **go-org**.

**Comment by cup** [comment]
@kaushalmodi, yeah. The only problem with Org mode syntax highlighting is pretty
bad with Jekyll, as GitHub refuses to open source their highlighter:

https://github.com/cup/rosso/blob/master/publish/markup.md#org-mode

However I think Hugo has its own highlighter, so if I can resolve this issue
with includes I could switch away from Jekyll finally.

**Comment by cup** [comment]
https://github.com/github/markup/issues/1266

**Comment by jerith** [comment]
The problem here is that the path in `DocumentName` is relative to the content dir rather than the repo root. This means that when go-org expands the relative path, it gets with `/path/to/repo/foo.org` instead of `/path/to/repo/content/foo.org` (and similarly for nested dirs within `content`).

I'm currently working around this by symlinking `posts` to `content/posts`, but I think the solution is for hugo to either pass an absolute path to go-org's `Parse` method or pass `DocumentName` with `content/` prefixed to it so that it's relative to the repo root again.

**Comment by jerith** [comment]
I seem to get the correct behaviour if I compile my own hugo with this very hacky change:
```diff
diff --git a/helpers/content.go b/helpers/content.go
index f6576c04..9dce57fc 100644
--- a/helpers/content.go
+++ b/helpers/content.go
@@ -22,6 +22,7 @@ import (
        "fmt"
        "html/template"
        "os/exec"
+       "path/filepath"
        "runtime"
        "unicode"
        "unicode/utf8"
@@ -762,7 +763,12 @@ func orgRender(ctx *RenderingContext, c ContentSpec) []byte {
                return highlightedSource
        }

-       html, err := config.Parse(bytes.NewReader(ctx.Content), ctx.DocumentName).Write(writer)
+       contentDir := ctx.Cfg.GetString("contentDir")
+       if contentDir == "" {
+               contentDir = "content"
+       }
+       docpath := filepath.Join(contentDir, ctx.DocumentName)
+       html, err := config.Parse(bytes.NewReader(ctx.Content), docpath).Write(writer)
        if err != nil {
                jww.ERROR.Printf("Could not render org: %s. Using unrendered content.", err)
                return ctx.Content
```
There's almost certainly a much cleaner way to do it, but I'm not sufficiently familiar with hugo's code to find it, unfortunately.

**Comment by jerith** [comment]
Here is where the `RenderingContext` is constructed when rendering a full page: https://github.com/gohugoio/hugo/blob/13768c3c50ce9d088f81a5724ee97bdc309199b8/hugolib/page__per_output.go#L313-L319

As seen in the above code, `DocumentName` is set to `p.File().Path()`. If we added a new field to `RenderingContext` (maybe `DocumentFilename`?) we could set it to `p.File().Filename()` (which returns the absolute path) and then use it in `orgRender()` rather than trying to glue the content path back onto `DocumentName`.

**Comment by niklasfasching** [comment]
Includes of content directory files are fixed in master / the next release - @cup your example should work now..

We could look into supporting includes from other directories as well, this just fixes the most common use-case.

**Comment by cup** [comment]
@niklasfasching I ended up just writing a shortcode:

~~~
{{ $path := .Get 0 -}}
{{ $input := path.Join "content" .Page.File.Dir $path | readFile -}}
{{ $lang := index (split $path ".") 1 -}}
{{ if .Get 1 -}}
   {{ $lang = .Get 1 -}}
{{ end -}}
{{ highlight $input $lang "" -}}
~~~

so I am using that with MarkDown. At any rate, Thanks for your work

**Comment by niklasfasching** [comment]
Thx! Cool, so this can be closed?

**Comment by cup** [comment]
well, I can test it after work if you want - otherwise go ahead

**Comment by cup** [comment]
This works now
