### ISSUE TITLE
Shorcodes: Check for .Inner in linked partial templates

### ISSUE THREAD

**Issue by Brixy** [gohugoio/hugo#6338]
Hi!

I am using some partials that can be accessed via shortcodes or from template files. The shortcode shows an error message if no `.Inner` is provided although `.Inner` is used in the partial template.

That is probably the intended behaviour. But maybe it is possible that Hugo checks for `.Inner` in the linked partial file(s)?

**This is a minimal example for a `figure` shortcode:**

```
{{ $inner := .Inner }}{{/* This is necessary although var is not used */}}
{{ if in (.Get "src")  "svg" }}
  …
{{ else }}
  {{ partial "figure.html" . }}
{{ end }}
```

**Comment by Lesik** [comment]
Hi,

I came across this quirk today. To better illustrate, I will expand the example a little bit:

`layouts/shortcodes/usespartial.html`:
```html
{{ partial "mypartial" . }}
```

`layouts/partials/mypartial.html`:
```html
{{ .Inner }}
```

`content/_index.md`:
```md
{{< usespartial >}}
Hello World!
{{< /usespartial >}}
```

The `{{ $inner := .Inner }}` trick is a great workaround, I only thought of `<!-- {{ .Inner }} ->>` which is obviously subpar.

**Comment by Lesik** [comment]
It's hard to say if it's a bug. The fact that Hugo checks `usespartial.html` (in my example) for the use of `.Inner` is definitely a good feature. The algorithm could be made even smarter by checking in sub-partials (`mypartial.html`), but it may also cause too much overhead? Otherwise a small note in the docs would be good.

**Comment by Lesik** [comment]
It's hard to say if it's a bug. The fact that Hugo checks `usespartial.html` (in my example) for the use of `.Inner` is definitely a good feature. The algorithm could be made even smarter by checking in sub-partials (`mypartial.html`), but it may also cause too much overhead? Otherwise a small note in the docs (to use the `{{ $inner = .Inner }}` trick) would be good.

**Comment by bep** [comment]
While this would be possible to implement, it's not something I'm spending 5 hours on my free time to do. It's also not something that I would consider fixing unless the fix itself was simple.

The workaround is simple: Just do a `$notused := .Inner` in the shortcode.

**Comment by Lesik** [comment]
This can be closed imho.
