### ISSUE TITLE
hugo not auto-recompiling scss on ubuntu

### ISSUE THREAD

**Issue by marceljay** [gohugoio/hugo#6364]
Somehow, I need to stop the server and start it again, so my scss would be recompiled on ubuntu. My friend working on the same project does not have the issue on his Windows machine. 

Did anyone encounter such problem?

```
$ hugo version
Hugo Static Site Generator v0.56.3/extended linux/amd64 BuildDate: unknown
```

**Comment by bep** [comment]
>Did anyone encounter such problem?

You may find a broader audience to ask at https://discourse.gohugo.io/

I would guess an editor issue, but I thought we had ironed out those issues. What text editor do you use? Does it make any difference if you edit it with nano? I don't use Ubuntu on a regular basis, so I cannot test this easily. Maybe others will chime in.

**Comment by marceljay** [comment]
Thank you for your suggestions. I just tried Vim and gedit but unfortunately it does not make a difference.

**Comment by dtvn** [comment]
I don't use Hugo extend so I don't know anything about this. However, if I was you, I would separate the compiling SCSS task away Hugo. I usually let Hugo do the rendering layout task, meaning while the compiling theme task will be handled by Gulp auto built script. Because you are not always change SCSS so separating them would help to speed your site up.

**Comment by marceljay** [comment]
With the new update (0.58.3) it's not an issue anymore and now seems to works fine.
