### ISSUE TITLE
Increase default timeout value

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#6502]
See https://github.com/gohugoio/hugo/issues/6501 etc.

The main motivation behind the timeout is to bail out of circular loops, and if that is 10 seconds or 30 seconds does not matter too much.

/cc @anthonyfok I noticed you did a recent change in Mage file. Maybe we should agree on a new default "higher value"

**Comment by anthonyfok** [comment]
> /cc @anthonyfok I noticed you did a recent change in Mage file. Maybe we should agree on a new default "higher value"

I did not set a custom timeout to magefile.go, but rather, just in .travis.yml, i.e. setting the environment variable HUGO_TIMEOUT=30000 specifically for the `mage -v check` run on arm64 (or non-amd64) because I thought it was somewhat specific to the current ARM64 hardware that Travis CI uses.

I am certainly fine with increasing the default timeout value to whatever is appropriate to fix e.g. #6501.  The only concern I could think of is that a longer timeout, if not accompanied by a message notifying what Hugo is currently doing, might leave the end user wondering why Hugo seemingly becomes unresponsive.  (though probably a non-issue)
