### ISSUE TITLE
Consider markdown extensions for math typesetting in Hugo

### ISSUE THREAD

**Issue by onedrawingperday** [gohugoio/hugo#6544]
Since the release of Hugo 0.60.0 the new default markdown library is Goldmark and mmark is deprecated and going to be removed at some point.

I am opening this issue to track the matter of math typesetting in Hugo with the new default markdown library.

The present situation is like so: 

https://github.com/litao91/goldmark-mathjax is an extension that offers support for goldmark.

Currently there is no KaTex extension that offers support for goldmark. (ref: https://github.com/yuin/goldmark/issues/32 )

**Comment by severen** [comment]
The lack of support for maths typesetting with Goldmark (and specifically with using KaTeX to render it) is currently a blocker for me.

**Comment by mobop** [comment]
Some one should write a KaTex extension for goldmark

**Comment by onedrawingperday** [comment]
I have just come across a KaTex extension for Goldmark.

https://github.com/graemephi/goldmark-qjs-katex

As mentioned in the first post there is another for MathJax over here:
https://github.com/litao91/goldmark-mathjax

cc: @bep

**Comment by oblitum** [comment]
Would be nice to have a rationale for this here. I came here from build warning and have no idea why of the deprecation, as Mmark coupled with KaTeX has been working great for me and I use it in all of my posts....

**Comment by onedrawingperday** [comment]
@oblitum The release notes for 0.60.0 provide all the rationale you request.

Also the former default Blackfriday is largely unmaintained. mmark decided to switch to another Markdown engine that unfortunately came with its own performance penalties. So in the end it was decided that Goldmark which is Commonmark compliant should be adopted.

**Comment by jemus42** [comment]
Proper KaTeX and/or mathjax support by hugo would be huge. So far I always had to resort to various hacky solutions that never lasted without breaking in one way or another.

**Comment by oblitum** [comment]
Well this sucks and I used to recommend Mmark for math savvy hugo bloggers (it's a great and simple solution that works), I hope they don't come hunting me now, I made a dozen of people adopt it.

**Comment by oblitum** [comment]
@onedrawingperday I checked the [release notes](https://github.com/gohugoio/hugo/releases/tag/v0.60.0) and it doesn't state anything regarding why remove Mmark, the point there is more about the default parser Blackfriday being substituted, which by the way is less critical in thesis, as people that were relying on Blackfriday weren't relying on math extensions, etc, just standard Markdown which is covered by CommonMark. I never relied on Blackfriday as it never supported the features I needed, specially for math, so it was great when I found out about Mmark support.

 Is it really necessary, as you're going to break everyone that are relying on Mmark extensions for a solution that solves CommonMark? Couldn't it keep supporting Mmark just like before, in dual mode?

**Comment by oblitum** [comment]
@jemus42 it has always worked in Hugo if you used [`.mmark` files](https://mmark.miek.nl/post/syntax/#mmark-v2-syntax).

**Comment by onedrawingperday** [comment]
You need to ask your questions at  [Hugo Discussion Forum](https://discourse.gohugo.io/). 

This issue is about tracking the addition of Math extensions in Hugo.

We are not going to have a discussion here. Also note that currently as shown in my status I am BUSY. Please respect that fact and not mention me any further.

**Comment by oblitum** [comment]
> This issue is about tracking the addition of Math extensions in Hugo.

Which have been available and working since circa 2015.

**Comment by onedrawingperday** [comment]
I am closing this issue due to trolling.

If someone else wishes to track the development of Math Typesetting extensions feel free to open another issue.

Enough already.

cc: @bep

**Comment by AnomalRoil** [comment]
I'm not sure I've understood what's the current state of math typesetting using Hugo.
I get that mmark with KaTeX still works, but will be deprecated at some point.

Do we have a working alternative right now that does not imply changing Hugo's source code ourselves or not? (The above Goldmark extensions appears to require such changes for now)

I see that pandoc has the `--mathjax` helper,  so I guess this is currently the only way around the deprecation of mmark? (At the cost of some client side performances, since MathJax is slower than KaTeX)

**Comment by jemus42** [comment]
#6842 (adding the graemephi/goldmark-qjs-katex extension) couldn't be merged because (from my layman's understanding) the katex extension in question includes a dependency on C (cgo), which is... a problem? At least there's a "no cgo rule", as the PR discussion shows. Therefore: No goldmark-katex extension for the foreseeable future (at least not *this* one).

As far as pandoc is concerned: From what I understand the pandoc support / configuration options form the hugo side are fairly limited, meaning you can use `pandoc --mathjax`, but you may not be (easily, through `config.toml`) able to adjust other pandoc options relevant to your needs. Since pandoc is a very, very powerful tool, this is both understandable due to its complexity and also unfortunate.

**Comment by davidvandebunte** [comment]
At the moment, it doesn't seem inline math works with the combination of Katex and goldmark. The only way to get it to work in my case was with this workaround of using mmark:
https://eankeen.github.io/blog/posts/render-latex-with-katex-in-hugo-blog/

**Comment by KevCaz** [comment]
@davidvandebunte I got it work after tweaking the delimiters https://stackoverflow.com/questions/27375252/how-can-i-render-all-inline-formulas-in-with-katex see https://github.com/KevCaz/funkyflex/blob/master/layouts/partials/math.html
