### ISSUE TITLE
Additional empty line in syntax-highlighted code fences when using Windows line endings

### ISSUE THREAD

**Issue by frerich** [gohugoio/hugo#6596]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
Hugo Static Site Generator v0.60.0/extended darwin/amd64 BuildDate: unknown
</pre>

### Does this issue reproduce with the latest release?

Yes.

### How to reproduce

1. Create a new document with a code block using synatx highlighting, e.g.

    ```markdown
        ```python
        # Launch the program.
        def main():
            pass
        ```
    ```

2. Make sure this file is stored using Windows line endings.
3. Generate HTML

### Expected behaviour

HTML should be rendered which looks something like

```python
# Launch the program.
def main():
    pass
```

### Observed behaviour

When using Windows line endings, an additional empty line is printed -- but only for the comment! I.e. I see

```python
# Launch the program

def main():
    pass
```

### Additional notes

It appears that when using Windows line endings, *any* comment in syntax-highlighted code fences (at least for Python and Perl) gets an additional empty line appended.

**Comment by Jos512** [comment]
To add to the above report, the issue doesn't happen with every code highlight. C# and Go, for example, work fine with CRLF and LF line endings. 

-----

Because the issue still happens with Hugo 0.62.2, I've made an example repository [here](https://github.com/Jos512/code-line-endings). There are two content files in there. One intended to use LF line endings, the other CRLF. 

If you run the website with `hugo server`, you'll see that the identical code examples in the CRLF file look different than those in the LF file because of how line endings affect code.

-----

I hope this issue can be fixed since it's confusing to the less-technical people I work with. Plus it even confuses me sometimes because the issue doesn't happen with every kind of code example.

Would perhaps a simple `strings.Replace(input, "\r\n", "\n")` call on the Chroma input string fix this?
