### ISSUE TITLE
Indentation in .html and .gohtml shortcodes are outputed as code blocks

### ISSUE THREAD

**Issue by iu4u57k3** [gohugoio/hugo#6599]
Lets say you created a shortcode named `info.html` or `info.gohtml` in idea community edition editor with gohtml plugin installed.

You opened it in code editor and pressed `Ctrl + Alt + L` to beautify it for the nice formatting.

Then it looks something like this:

![hugo_info_1](https://user-images.githubusercontent.com/52806368/70514478-bcb15900-1b59-11ea-9a3b-b19a80380599.png)

Then you added this shortcode to a post using:
![hugo_info_2](https://user-images.githubusercontent.com/52806368/70514563-e9fe0700-1b59-11ea-999e-a157ee960afe.png)

However, they are being treated as markdown code blocks and not .gohtml or .html files:

![hugo_info_3](https://user-images.githubusercontent.com/52806368/70514591-f4b89c00-1b59-11ea-96c7-4d15da7045c0.png)

Once the first indent is removed, then code starts to get rendered correctly.

`.gohtml`, `.html` and `.md` shortcodes must be treated differently by hugo,.

This issue is somewhat similar to:
https://github.com/gohugoio/hugo/issues/6553

**Comment by moorereason** [comment]
This is the correct behavior for CommonMark.

**Comment by iu4u57k3** [comment]
So what's the fix?

**Comment by moorereason** [comment]
Read https://spec.commonmark.org/0.29/#html-blocks (esp. start condition 6).

Don't indent the first line of embedded HTML blocks.  End the HTML block with a blank line.

**Comment by iu4u57k3** [comment]
Ok, thanks!

**Comment by iu4u57k3** [comment]
Can these optimizations be done by hugo itself for html and gohtml files and these files being treated differently?

**Comment by moorereason** [comment]
@bep,
Am I correct here?

When a content file contains a shortcode, does Hugo insert the rendered shortcode output into the main markdown content and then render the combined content (essentially re-rendering the shortcode output)?  Did the rendering pipeline/workflow change with the addition of goldmark?

I'm assuming the rendering pipeline is essentially that same and that blackfriday allowed indented HTML whereas goldmark follows the CommonMark spec.

**Comment by satotake** [comment]
I think this is the intentional behaviour .

According to https://gohugo.io/content-management/shortcodes/#shortcodes-with-markdown ,
In @iu4u57k3 7k3 's case, it is proper to use 
not `{{% info title="Some product name"%}}` 
but `{{< info title="Some product name">}}` .
They are different.

The former is handled as texts to be process further so it is converted into code blocks.
The latter is treated as raw (=ready to use) html by hugo.
I checked it works at least with v0.65.2.

Honestly speaking, I did not know this tip until now. 
I have been and am using `{{< xxx >}}` without intension
