### ISSUE TITLE
confusing output of hugo list future or drafts if you use both in front matter

### ISSUE THREAD

**Issue by zwotzie** [gohugoio/hugo#6644]
### Does this issue reproduce with the latest release?
Yes, just tested it with 0.61.0

front matter:
```
date = "2099-10-19"
draft = true
```

the output of "list draft" or "list future" will not show anything.
I would expect this page in both or even better with comment for the other type.

```
$ ./hugo list future
content/map.md (draft)

$./hugo list draft
content/map.md (future)
```

And thanks for the great Software :)

**Comment by thetanil** [comment]
I just spent some time trying to reproduce this. It appears that any file with a date in the future is filtered out. I tried 

* with toml and yaml
* with a title and without
* in the future 1 day or 100 years

If the file is dated in the future at all, it's removed from both drafts and future.

I was not able to get any configuration of a future file to show up in the list.

**Comment by jasikpark** [comment]
I got the same result with 0.63-DEV: No output from either command if Draft = "true" and Date is in the future.

**Comment by jasikpark** [comment]
So it seems that the page gets lost somewhere in being built -- because my site doesn't even render the page if it's both a draft and future post.

<img width="815" alt="Screen Shot 2019-12-31 at 11 23 56 PM" src="https://user-images.githubusercontent.com/10626596/71638402-bbd58980-2c24-11ea-9547-9eeeea80f817.png">
[[ Draft only ]]
<img width="815" alt="Screen Shot 2019-12-31 at 11 24 06 PM" src="https://user-images.githubusercontent.com/10626596/71638403-bbd58980-2c24-11ea-9749-dfea2fdd9108.png">
[[ Draft and Future ]]

**Comment by jasikpark** [comment]
the even weirder part is that it shows up in `hugo list all`

`content/day-on-the-trails/index.md,,A Day on the Trails,2020-12-30T09:48:43-06:00,0001-01-01T00:00:00Z,2020-12-30T09:48:43-06:00,true,https://jasik.xyz/day-on-the-trails/`

**Comment by brmassa** [comment]
I would like to see a work around this. I normally write new posts using "draft: true", even if I intend to publish later date. their is not future+draft option to list such posts
