### ISSUE TITLE
Add MathJax build support -- post-hugo processing

### ISSUE THREAD

**Issue by jasikpark** [gohugoio/hugo#6694]
https://github.com/litao91/goldmark-mathjax is available as a supported extension, linked to on their README..

could it be possible to add it as an integration with the Goldmark in Hugo so that you don't need to create a MathJax include html file?

**Comment by awwong1** [comment]
I came across this issue because I'm interested in getting hugo to generate server side math.

The [goldmark-mathjax](https://github.com/litao91/goldmark-mathjax) only wraps the math in html tags. With [mathjax@3](http://docs.mathjax.org/en/latest/web/configuration.html) these tags aren't necessary. You would still have to [load MathJax javascript](http://docs.mathjax.org/en/latest/web/configuration.html#loading-components-individually) and render in the browser. 

From the markdown:
```markdown
$$
\mathbb{E}(X) = \int x d F(x) =
\left\{ \begin{aligned} \sum_x x f(x) \; & \text{ if } X \text{ is discrete}
\\ \int x f(x) dx \; & \text{ if } X \text{ is continuous }
\end{aligned} \right.
$$

Inline math $\frac{1}{2}$
```

Default settings would currently output:
```html
<p>$$
\mathbb{E}(X) = \int x d F(x) = \left{ \begin{aligned} \sum_x x f(x) ; &amp; \text{ if } X \text{ is discrete}
\ \int x f(x) dx ; &amp; \text{ if } X \text{ is continuous }
\end{aligned} \right.
$$</p>
<p>Inline math $ \frac{1}{2} $</p>
```

With the goldmark-mathjax plugin enabled (inline: `$`, block: `$$`), you'd see:
```html
<p><span class="math display">$$\mathbb{E}(X) = \int x d F(x) =
\left\{ \begin{aligned} \sum_x x f(x) \; &amp; \text{ if } X \text{ is discrete}
\\ \int x f(x) dx \; &amp; \text{ if } X \text{ is continuous }
\end{aligned} \right.
$$</span></p>
<p>Inline math <span class="math inline">$\frac{1}{2}$</span></p>
```

**Comment by jasikpark** [comment]
Hmmm ok, thanks for the info!! You reminded me that somehow I removed MathJax from my website.

Now I've re-added it via https://github.com/jasikpark/jasik-xyz/commit/334c1805d57d420cbd2b3f4f66ae63b2a349c762

`mathjax.html`
```html
<script>
    MathJax = {
        tex: {
            inlineMath: [['$', '$'], ['\\(', '\\)']]
        },
        svg: {
            fontCache: 'global'
        }
    };
</script>
<script type="text/javascript" id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-svg.js">
</script> 
```

`header.html`
```html
{{ if .Page.Params.isMath }}
    {{ partial "mathjax.html" . }}
{{ end }}
```

And adding `isMath = "true"` to the frontmatter of posts that require MathJax

**Comment by jasikpark** [comment]
Actually, could MathJax be added as a go module that processes the html post-build? So that the CSS and images are generated on the build server rather than the client?

**Comment by netw0rkf10w** [comment]
Please consider this feature. It would be great if one could build server-side math formulas.

**Comment by jasikpark** [comment]
Maybe Hugo Pipes https://gohugo.io/hugo-pipes/ is the right solution?

**Comment by jph00** [comment]
@bep I wonder if you'd consider re-opening this - it was closed as stale, despite having significant interest, and no correct workaround. The posted workaround does not provide an answer, as discussed by @hadley here:

https://discourse.gohugo.io/t/use-goldmark-mathjax-extension/25721

For scientific discourse, wrapping every use of math in shortcodes (both inline and block math) isn't really a satisfactory option - for many papers that would more than double the size of the markdown, and making writing it extremely painful.

Many thanks for you consideration, and for creating Hugo, which we're currently considering switch to for https://nbdev.fast.ai/ - however since many of our users (including ourselves!) write a lot of math, this is a blocker for us. (We can try to figure out how to build it with mathjax support ourselves, of course, although golang isn't something we've worked with much before, and we'd also need to setup something to ensure that releases are synced with official releases here.)

**Comment by jph00** [comment]
See also open PR for this feature: #7435

**Comment by RoyiAvital** [comment]
Any update on this issue?

**Comment by jasikpark** [comment]
Perhaps this could be integrated with js.Build and use the server side render capabilities of Katex? https://graemephi.github.io/posts/server-side-katex-with-hugo-part-2/

**Comment by danmackinlay** [comment]
In the broader ecosystem this leads to pain also - see the hacks that [RMarkdown resorts to](https://yihui.org/en/2018/07/latex-math-markdown/) to keep mathematical markup functional.

**Comment by peaceiris** [comment]
That is interesting, but it cannot solve the problem...

![Screen Shot 2020-12-13 at 16 03 21](https://user-images.githubusercontent.com/30958501/102005549-ec8ed000-3d5c-11eb-90d2-b1dd6478b953.png)
![Screen Shot 2020-12-13 at 16 03 29](https://user-images.githubusercontent.com/30958501/102005553-f284b100-3d5c-11eb-9dd9-0195f714866b.png)

**Comment by jasikpark** [comment]
To more clearly define what I was looking for when opening this issue - was to create an ergonomic way to have server-side rendered latex, I feel that there are two problems/solutions here: trying to combine markdown & latex together and trying to get server-side rendering simply and ergonomically a part of the build process

**Comment by shreevatsa** [comment]
Yes, my understanding is that (at least) two issues are mixed up here:

1. Input syntax: MathJax (LaTeX) syntax versus Markdown. The question of whether a user can just type LaTeX syntax, or needs to incorporate many workarounds like escaping underscores and backslashes, so that after passed through Markdown the intended LaTeX syntax remains. (This seems to be 

2. Server-side versus client-side processing: Whether the HTML ultimately generated by Hugo should simply contain the MathJax input (to be processed by client-side—i.e. JavaScript—MathJax in the reader's browser) or should already be processed (server-side) via MathJax (so no JavaScript needs to run client-side).

If a user is happy with special input and client-side MathJax, then this is already possible with stock Hugo by 

(1) being super-careful about escaping all Markdown-special characters in one's input (probably not practical), or [using shortcodes / `.inner`](https://discourse.gohugo.io/t/use-goldmark-mathjax-extension/25721/4), and

(2) loading the MathJax (or KaTeX) JavaScript in the header or body of one's page.

But otherwise, either problem is unsolved AFAICT.

**Comment by Whotakesmyname** [comment]
Without proper new features or documented workarounds, the math of Hugo is in fact broken so far. Since Hugo seems having no interest in involving markdown renderer issues, then leveraging Goldmark's existed extension is a less painful choice IMO.

Client-side math rendering means we need to introduce a way to keep some blocks, including some inline blocks untouched as it is in the output. This will be an extension to markdown to some extent, and will break quite a few markdown previewers today.

**Comment by cld4h** [comment]
I'd like this issue to be reopened too.

I've followed [this tutorial](https://geoffruddock.com/math-typesetting-in-hugo/) to add MathJax 3 in my hugo site.
All works fine **except** the double backslash issue:

I have a source code like this:

```markdown
$$
\begin{equation*}
\left\lbrace
\begin{aligned}
	x \equiv & a_1 \bmod m_{1}\\
	x \equiv & a_2 \bmod m_{2}\\
	& \vdots\\
	x \equiv & a_n \bmod m_{n}\\
\end{aligned}
\right.
\end{equation*}
$$
```

It is rendered like this:

```tex
\begin{equation*}
\left\lbrace
\begin{aligned}
x \equiv & a_1 \bmod m_{1}\

x \equiv & a_2 \bmod m_{2}\

& \vdots\

x \equiv & a_n \bmod m_{n}\

\end{aligned}
\right.
\end{equation*}
```

I know I could use a shortcode to avoid this unnecessary escaping by goldmark.

Or I could use `\\\\`

But I wonder if escaping the backslash between two `$$`s is a conflict to the markdown syntax.

What's the right syntax?
