### ISSUE TITLE
Markdown render hooks for code blocks

### ISSUE THREAD

**Issue by acalvo** [gohugoio/hugo#6702]
Would it be possible to have markdown render hooks for code blocks, just as we do for links and images since v0.62?

Say I want to add a "copy" button in all code snippets in my site. Right now I'm forced to use a shortcode around my code snippets that adds it. If we had something similar to link/image render hooks, we could keep using standard markdown syntax and implement these kind of features in an elegant way.

**Comment by frerich** [comment]
I would love to have this. Right now, I use a custom short code (e.g. `{{< code language="perl" >}}`) but that doesn't work too well with common Markdown editors (e.g. Typora).

In case this is implemented, it would be great if the entire info string of fenced code blocks is passed to the render hook. Right now, my short code supports specifying an optional caption for the code snippet, e.g. `{{< code language="perl" caption"After refactoring the login function" >}}`. It would be great if I coculd use e.g.

    ```perl "After refactoring the login function"
    ...
    ```

or something along the lines of that to specify an optional caption.

**Comment by maelle** [comment]
A render hook for code blocks would also make it possible to add links to documentation / hover information on some elements inside the code blocks.

Something like [GitHub code navigation](https://help.github.com/en/github/managing-files-in-a-repository/navigating-code-on-github#jumping-to-the-definition-of-a-function-or-method).

**Comment by frerich** [comment]
I'd still greatly appreciate this feature. To avoid that this ticket gets closed due to a lack of activity, I'd like to summarise.

There are many plausible features associated with code blocks:

* Adding a 'Copy' button next to each code snippet which lets users copy the code block to the clipboard
* Custom (more semantic?) HTML markup
* Adding a caption to each code snippet
* Adding hyperlinks to code blocks (e.g. having function calls automatically reference the relevant API documentation)

Right now, implementing any of these features requires a custom shortcode. However, a shortcode has a number of downsides:

* Fellow authors need to be taught about it - it's a custom extension to Markdown
* Tool need to be (but usually cannot be) taught about it. As a consequence, popular Markdown editors like Typora won't highlight code snippets marked up with a custom shortcode as code.

**Comment by kdabir** [comment]
I can add one more use case 

To be able to process something like [mermaid](https://mermaid-js.github.io/mermaid/#/) using standard code fence

    ```mermaid
         graph TD
             Start --> Stop
    ```

Shortcodes block are not rendered as code in any text editors or Github, making it very hard to read as a Markdown content.

I would love to see hooks for code blocks and even inline code. IMHO, the more we can get out from standard markdown syntax the better it is for the entire ecosystem 🙏 .

**Comment by bep** [comment]
>In case this is implemented, it would be great if the entire info string of fenced code blocks is passed to the render hook.

You would get a map of `.Attributes` in your hook, so you could make up your own, e.g.:


    ```bash
    echo "foo";
    ```
    {comment="Hugo is cool"}

Which would allow this hook:

```html
{{ comment := .Attributes.comment }}
```

(note to self: #8313)

**Comment by shafiemukhre** [comment]
I really need this, is anyone is working on this? I would like to work on this and appreciate any guidance or direction and files that I need to update/modified? Thank you so much 

This will be my first issue
