### ISSUE TITLE
Use GitIgnore syntax with ignoreFiles

### ISSUE THREAD

**Issue by ghost** [gohugoio/hugo#6764]
currently Hugo allows you to ignore certain files:

https://gohugo.io/getting-started/configuration#ignore-content-files-when-rendering

Contrast with GitIgnore, which has a negate syntax:

> An optional prefix `!` which negates the pattern; any matching file excluded
> by a previous pattern will become included again.

https://git-scm.com/docs/gitignore

that allows you to ignore a certain type with an exception:

~~~
*.txt
!sunday.txt
~~~

or even all files with exception:

~~~
*
!*.md
~~~

**Comment by cup** [comment]
I want to add that I have tried some other things as a workaround, with no luck.
For example you could use a negative lookahead:

~~~yaml
ignoreFiles:
- \.(?!md$)
~~~

but Hugo doesnt accept it:

~~~
Invalid regexp "\\.(?!md$)" in ignoreFiles: error parsing regexp: invalid or
unsupported Perl syntax: `(?!`
~~~

another option is something like this:

~~~
ignoreFiles:
- /_
~~~

but Go doesnt like it:

~~~
$ go run _app.go
package main: no Go files in C:\
~~~

best option I have come up with is like this:

~~~
ignoreFiles:
- _\.
~~~

then file like this:

~~~
app_.go
~~~

**Comment by davidsneighbour** [comment]
What happens if you ignore the gitignore syntax and use a regexp, as the error message suggests? I am not to versed in it, but `^(.?)[\.]!(md)$` might do the trick. First brackets "everything else greedy", second should hit the last dot and the last one is "not md". $ is the end of the string. I am really not sure about this, but as I wrote: It's a regexp. Maybe search for a gitignore to regexp converter. Regexp is more powerful in the end than .gitignore syntax. I wouldn't change that :)

**Comment by cup** [comment]
@davidsneighbour no, `!` matches the character `!` literally. It doesnt act as an operator in the example youve given.

**Comment by cup** [comment]
@davidsneighbour no, `!` matches the character `!` literally. It doesnt act as
an operator in the example youve given.

But I must thank you, as I had pretty much given up on Hugo because of this, and
you inspired me to look a little more. I found this, which doesnt use any Perl
syntax:

https://stackoverflow.com/questions/406230/-/7286050

Result:

~~~yaml
ignoreFiles:
- \.([^m]|m[^d]|md.).*$
~~~

This will ignore these:

~~~
.e
.ee
.mde
.me
~~~

but not this:

~~~
.md
~~~

I still think a better solution should be implemented, like GitIgnore or PCRE,
but this is a workaround for now.
