### ISSUE TITLE
It will be great if hugo can build only what changed lines ex: new post/page3.md

### ISSUE THREAD

**Issue by okabrionz** [gohugoio/hugo#6810]
I would to recommend it will be great if hugo can build only what changed codes. as example if i edit contents/posts/page3.md then hugo only build what created, edited as it. I mean only build the page3.md and update the change to /public directory.

**Comment by bep** [comment]
How do you suggest we do that?

**Comment by sureshkumargondi** [comment]
Maybe based on the log files, we can see what file changed, and what not?

**Comment by okabrionz** [comment]
> How do you suggest we do that?

If we can detect what changed on git commits we could do it. Or, any better ideas?



> Maybe based on the log files, we can see what file changed, and what not?

I don't even see what logs do :grin:. But, it's brilliant.

**Comment by bep** [comment]
Note that:

* The "what changed?" isn't the hard part about this problem.
* The hard problem is "when you change X -- what do I need to rebuild? What uses X?" and X is a content file, a template, a data file etc.
* We do some of this when you run `hugo server` today. It works mostly great.
* We do however render everything on every build, as we really don't know what the template uses. This is a hard problem.
* So, if we want to scale Hugo to "millions of pages", we probably need to solve these problems better, even for the Hugo command. But we need to do it right. Which is why I would appreciate it if you could add some kind of design outline to proposals like these, an outline that answers some or all of the problems outlined above.
