### ISSUE TITLE
Hugo 0.64 missing files in mounts

### ISSUE THREAD

**Issue by XhmikosR** [gohugoio/hugo#6854]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
Hugo Static Site Generator v0.64.0-241DB8F7 windows/amd64 BuildDate: 2020-02-04T09:09:27Z

</pre>

### Does this issue reproduce with the latest release?

Yes.

This does not happen with v0.63.2.

* missing static files: https://github.com/twbs/bootstrap/runs/425228408#step:9:229
* mounts config: https://github.com/twbs/bootstrap/blob/master/config.yml#L25-L42

**Comment by bep** [comment]
The latest Boostrap 4 SASS source fails to build with Hugo. We can do a bug trade ...

**Comment by XhmikosR** [comment]
I think this has already been fixed in master. Is there any issue about this?

**Comment by bep** [comment]
@XhmikosR no issue, and yes it's fixed in master.

Also, this issue should be fixed now. Sorry for the breakage; I had to dive into my own code to fix a related issue for 0.64, and I had a hard time understanding my own code, so I more or less rewrote the mount file system. That would have been splendid if we had solid test cases for your situation.

I took the Bootstrap site for a spin. Notice you build the SCSS source with Hugo -- pretty nice editing experience, I suspect.

**Comment by XhmikosR** [comment]
We actually build only the docs SCSS with Hugo. In master there's no need to install anything else to fiddle with the docs :)

**Comment by XhmikosR** [comment]
And thanks for the quick fix!

**Comment by bep** [comment]
A little heads up about my latest addition to master: 40ba7e6d63c1a0734f257a642e46eb1572116a32 -- which updates LibSass to the newest release version. I tested it with the Bootstrap site and it "looked fine". node-sass is still on some old version (3.5.5?).  Nothing particularly new functionality in this LibSass, but they're in the process of porting all the upstream Dart changes for LibSass 4.0 (Sass Modules ...?).

**Comment by XhmikosR** [comment]
Yup. We test from time to time with Dart Sass for the core, and I plan to at least build everything on each commit with Dart Sass so that we at least catch compilation errors.
