### ISSUE TITLE
Heading anchors not verified in `relref`?

### ISSUE THREAD

**Issue by michalrus** [gohugoio/hugo#6863]
When I use:

```
{{% relref "some-page#i-dont-exist" %}}
```

… then only `some-page` part is verified, and an error is issued if its Markdown file can’t be resolved.

However, the `#i-dont-exist` part is not checked, and accepted even if there’s no such heading/anchor in that page.

This leads to broken links over time. How can this be resolved?

### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
Hugo Static Site Generator v0.58.0/extended linux/amd64 BuildDate: unknown
</pre>

### Does this issue reproduce with the latest release?

Probably…

**Comment by bep** [comment]
>How can this be resolved?

You currently cannot in a practical way.

**Comment by michalrus** [comment]
still important to me

Because of correctness and having no broken links

**Comment by michalrus** [comment]
still important to me

**Comment by xeraa** [comment]
would also be a great feature for me to have

**Comment by davidsneighbour** [comment]
The `#` part of an URL is inside of the resulting document and not part of the URL itself. So it basically does not exist before the browser on the user's side parses the HTML and creates the DOM-structure with that ID in an anchor. That is what makes it more or less impossible to have Hugo does this job.

You are expecting Hugo to interpret what it creates based on your input (in layouts and content-markdown). That is something that would slow down the process immensely and is not really useful for the whole "the speediest static website generator out there" thingy.

I can think of two ways to get this issue solved for your use case:

1) Create your own shortcode to use instead of relref. Let that shortcode use `getPage` to load the page referenced, then use the `.Content` part to go through with a regExp and find out if your anchor exists (which would mean there is a 'id="i-dont-exist"' in the dom or not) and react accordingly (maybe throw an errorf or warnf). Something like `{{< myshortcode link="some-page#i-dont-exist" >}}`. 

2) Use an external tool (I don't know any that checks anchors, mostly because I never needed to check for it, but linkcheck-tools should be able to parse the resulting page? [[g](https://www.google.com/search?channel=fs&client=ubuntu&q=linkcheck+anchor+exists)]) to run over the resulting site and alarming you to missing anchors. 

I would probably start with method 1, because 2 will be very resource intense. You need to let a headless browser run over every resulting HTML file, parse it and check the DOM.

**Comment by marshall007** [comment]
@bep does the introduction of `.Page.Store` in https://github.com/gohugoio/hugo/pull/9547 help with this at all?

I guess that's probably scoped to the page and not global to the site, but I was thinking if we just kept a simple hashed set containing `content/<section>/<page>.md#<header>` for every `h` tag and another set for every `a[href]` we come across, we could delay the evaluation of reference checks till the end and produce errors, warnings simply by comparing the two sets.

The interesting thing about this approach is that it would work without even requiring explicit use of `ref`/`relref` shortcodes. All links could be checked automatically (even if they are in HTML) just by enabling some config setting.

/cc @jmooring

**Comment by jbergstroem** [comment]
> The `#` part of an URL is inside of the resulting document and not part of the URL itself. So it basically does not exist before the browser on the user's side parses the HTML and creates the DOM-structure with that ID in an anchor. That is what makes it more or less impossible to have Hugo doing this job.

At least in the case of `.md`, [Hugo generates the id](https://gohugo.io/content-management/cross-references/#heading-ids); so I'm guessing those references are held at some point. Wouldn't that work for validation?

**Comment by jmooring** [comment]
The heading element IDs are created (a) automatically according to 3 different config options, (b) with markdown attributes, and (c) a markdown render hook.

Markdown attributes can be used to assign an ID to other block level elements, so checking headings is insufficient.

We would have to full render the target page to perform the check.
