### ISSUE TITLE
Params case handling doesn't work in where when given a sequence of pages

### ISSUE THREAD

**Issue by StarfallProjects** [gohugoio/hugo#7009]
## The problem

Struggling to get `where` to behave like an example in the docs. I asked for help on the forums ([discussion here](https://discourse.gohugo.io/t/struggling-to-get-where-to-behave-like-docs-example/23787/5)) and the "solution" was to lowercase a parameter name. This solved the issue, but without lowercasing it in the frontmatter. It also seemed inconsistent, as accessing the camelcased parameter name worked with other functions.

There are code examples in the discussion. I have also added a branch to my repo to preserve the broken vs working examples (as I want to continue working on the project) https://github.com/StarfallProjects/habermas-concepts/tree/brokenWorkingWHERE

If you clone, checkout that branch, run `hugo server --buildDrafts`, and from the homepage select **Concepts** > **A concept**, you should get an example output for this layout: https://github.com/StarfallProjects/habermas-concepts/blob/brokenWorkingWHERE/layouts/concepts/single.html

It has various ways of doing the same thing, broken and working.

### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
Hugo Static Site Generator v0.65.3-211BA42A windows/amd64 BuildDate: 2020-02-23T09:58:40Z
</pre>

### Does this issue reproduce with the latest release?

Yes

**Comment by moorereason** [comment]
This issue was originally meant to be fixed by https://github.com/gohugoio/hugo/commit/a3fe5e5e35f311f22b6b4fc38abfcf64cd2c7d6f, but I don't see where the tests actually cover the `{{ range where .Site.Pages "Params.MYPARAM" "foo" }}` case.  `checkWhereArray()` handles the case of [a slice of Params maps](https://github.com/gohugoio/hugo/blob/a3fe5e5e35f311f22b6b4fc38abfcf64cd2c7d6f/tpl/collections/where.go#L381), but not when the sequence is a slice of pages.

**Comment by xoxys** [comment]
Same here:

```
---
title: Getting Started
weight: -20
geekdocSearchExclude: true
---
```

Works: `where .Site.Pages "Params.geekdocsearchexclude" "ne" true`
Works not: `where .Site.Pages "Params.geekdocSearchExclude" "ne" true`
