### ISSUE TITLE
Overriding default substitutions in Goldmark's Typographer extension

### ISSUE THREAD

**Issue by saadatm** [gohugoio/hugo#7026]
Goldmark allows [overriding of default substitutions in its Typographer extension](https://github.com/yuin/goldmark#typographer-extension), which can come in handy for RTL languages (or others that use [their particular quote marks](https://en.wikipedia.org/wiki/Quotation_mark#Summary_table)). Can such substitutions be introduced in Hugo's configuration of Goldmark too?

**Comment by saadatm** [comment]
> If this is a **feature request**, and you feel that it is still relevant and valuable, please tell us why.

When using Goldmark in Hugo, the ability to use correct curly quotes for RTL languages (or to specify different quotes suited to other languages/scripts) will be nice. :)

**Comment by rootwork** [comment]
I'd like to voice support for this as well.

In addition to multilingual support, this would allow customization of substitution for dashes. Currently Typographer converts `--` to an endash (as in "9–5") and `---` to an emdash (as in "a break — in thought"). But importing from plain-ASCII often has `--` in text standing in for emdashes (because that was the old typewriter convention), and these get converted to endashes incorrectly.

Anyway, it'd be nice to access this ability of Goldmark to configure this substitution.
