### ISSUE TITLE
Hugo parses curly brackets in HTML files contained within Page Bundles.

### ISSUE THREAD

**Issue by wschenk** [gohugoio/hugo#7030]
I would like to have an `.html` file with VueJS code as a part of a page bundle copied over to my build directory.  Vue also uses `{{` and `}}` as its templating, but hugo is attempting to parse the file even without any front matter.  The docs state `To be treated as a content file, with layout, shortcodes etc., it must have front matter. If not, it will be copied as-is.` so I expect that it would not parse the file in anyway if there was no front matter.

### Test case

https://github.com/wschenk/hugo-bug-example

The offending line in the [html is line 10 of static.html](https://github.com/wschenk/hugo-bug-example/blob/master/content/page/test_post/static.html#L10 ) and hugo throws the error

```
Error: Error building site: "/hugo-bug-example/content/page/test_post/static.html:10:1": template: __/hugo-bug-example/content/page/test_post/static.htmlHTML:10: function "message" not defined
```

### Link to discourse discussion about it

https://discourse.gohugo.io/t/hugo-is-processing-curly-brackets-in-html-files-contained-within-page-bundles/23792

### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo env
Hugo Static Site Generator v0.65.3-211BA42A linux/amd64 BuildDate: 2020-02-23T09:59:37Z
GOOS="linux"
GOARCH="amd64"
GOVERSION="go1.13.7"
</pre>

### Does this issue reproduce with the latest release?
Yes

**Comment by onedrawingperday** [comment]
A couple of notes from me.

While testing the provided sample repo I tried the following with no effect:
- Making the Page Bundle headless.
- Use the new [Build Options](https://gohugo.io/content-management/build-options/#readout) in the front matter so that resources are not published.

Hugo choked every time when encountering the double curly brackets in the HTML of said resource.

**Comment by bep** [comment]
So, this is a bug according to the documentation, but I'm pretty sure this is how it always behaved and that it was intentional back when it was implemented (before my time). I say this because I remember having a test on this fail on me at some point. But it's a rather ugly and slow behaviour which have been causing me some headaches, and the bug in #7028 would not have been without this bug.

I need to think a little before changing this... I suspect someone will shout.

/cc @kaushalmodi @moorereason

**Comment by onedrawingperday** [comment]
@bep 

If changing this behavior is undesirable then perhaps there could be some kind of front matter parameter flag to disable the processing of curly brackets.

It doesn't quite make sense to me that Hugo processes a HTML file sans front matter...

**Comment by bep** [comment]
>It doesn't quite make sense 

Agree. I think I'm going to do it to fix #7028 and this issue. And it is what it says in the docs. I'm not fixing this by adding even more complexity (I have enough on my plate as it is).

**Comment by kaushalmodi** [comment]
@bep Reading the commit message in https://github.com/gohugoio/hugo/commit/ffcb4aeb8e392a80da7cad0f1e03a4102efb24ec, I think that change should be fine and non-breaking.

**Comment by bep** [comment]
@kaushalmodi I will buy send you an envelope with Hugo stickers if there are 0 people complaining about "this thing broke my site" within the first month of the release.

**Comment by bep** [comment]
That said, I got 10 kilos lighter getting rid of that fragile code.

**Comment by kaushalmodi** [comment]
@bep Hah, certainly there would be few people complaining about this. But it should not be a headache as the past breaking changes (that "unsafe" HTML boolean default change in goldmark still bugs me) .. we'll see :)
