### ISSUE TITLE
Hugo not recover from error after failed to parse invalid .Data

### ISSUE THREAD

**Issue by pamubay** [gohugoio/hugo#7043]
Since you are working on #7042 , i believe this bug also in the same topic.

### What version of Hugo are you using (`hugo version`)?

<pre>
Hugo Static Site Generator v0.68.0-DEV-B1106F87/extended linux/amd64 BuildDate: 2020-03-11T08:17:58+0700
</pre>

### Does this issue reproduce with the latest release?
Yes.

### When hugo failed to parse data in `/data` directory, Hugo not recover even after we fixed the invalid data

it happened to all three formats (`toml`,`yaml`,`json`)

Let's says we have this `/data/testdata.json`. 
```json
{
  "key": "value",
  "array": [
    "value1",
    "value2"
  ]
}
```
### Reproducing The Bug
1. Make it becomes invalid JSON by removing a comma or anything. 
2. Hugo throws ERROR. 
```
ERROR 2020/03/11 08:42:34 failed to load data: failed to load data: "data-bug-reload/data/test_json.json:10:1": unmarshal failed: invalid character '"' after object key:value pair
```
3. Fixed the JSON, make it valid JSON.
4. HUGO still throwing ERROR.

but after editing a `config` file, Hugo trigger full rebuild, then the ERROR gone.

#### a repo to repoduce the bug 
[hugo-data-error-reload](https://github.com/pamubay/hugo-data-error-reload)

**Comment by aBvezwegQZQHxnCkMuNfnBygvcwQqQoWwEvFbP** [comment]
Same error here as I missed a ":"
After saving `config.toml` Hugo triggered a rebuild and the error was gone.

`Hugo Static Site Generator v0.68.3/extended darwin/amd64 BuildDate: unknown`

**Comment by pamubay** [comment]
unstale bot :robot:

**Comment by pamubay** [comment]
unstale bot :robot:

**Comment by davidsneighbour** [comment]
What you don't write @pamubay is, how you run your server. It might be that you run it with parameters that do not rebuild everthing on changes? If not, then this might be a data-directory watching issue.

**Comment by pamubay** [comment]
its basic `hugo server`.

i even try `--disableFastRender` hopes Hugo always rebuild  the whole site for each rebuild trigger. But doesnt work.

Hugo rebuild triggered after i changed the file under `data/`, but it still responds with the last ERROR about invalid data format.

**except**, we edit the config file, then Hugo will rebuild and works correctly.

hugo version:
```
Hugo Static Site Generator v0.80.0-DEV-81975F84/extended linux/amd64 BuildDate: 2020-12-18T07:42:21+0700
```

**Comment by davidsneighbour** [comment]
Running `hugo server` - is the data directory in the list of watched locations that are printed by hugo?

**Comment by pamubay** [comment]
> Running `hugo server` - is the data directory in the list of watched locations that are printed by hugo?

Yes

**Comment by michidk** [comment]
Just had the same issue on `hugo v0.82.0+extended linux/amd64 BuildDate=unknown`. Very annoying!

**Comment by HugoBelotDeloro** [comment]
Having this issue on `hugo v0.89.3+extended linux/amd64`, build date unknown.

**Comment by darrenaddy** [comment]
Having this issue also.
Mine happened with the Tella theme. 
Tella came with two slides which I replaced with my own images and added a third, which was not showing up.
I was also looking for the default text that shows over the home page slides and found BOTH were in /data/slide.json (which I thought was weird for changes in CONTENT to be done there). 

I changed the file from this:

`[
  {
    "title": "Tella, A Hugo Theme for Companies",
    "image": "img/slide/slide01.jpg"
  },
  {
    "title": "Title Goes Here",
    "image": "img/slide/slide02.jpg"
  }
]`
to this:
`[
  {
    "title": "My Changed Title, Slide 2",
    "image": "img/slide/slide01.jpg"
  },
  {
    "title": "My Changed Title, Slide 2",
    "image": "img/slide/slide02.jpg"
  }
 {
    "title": "My Changed Title, Slide 3",
    "image": "img/slide/slide03.jpg"
  }
]`

You can see I forgot to add the comma after 2nd array item. This threw the error:
`failed to load data: failed to load data:`
(Note the message is doubled).
followed by the path to the json file stating the error was on line 11:1
followed by 
`unmarshal failed: invalid character '{' after array element`

I first added the needed comma (and tried to reload the page. both by clicking the "Reload Page" link on the error page AND by doing a Force Reload with the browser. The page does not refresh.

I went back and removed my 3rd slide completely from the /data/slide.json (including the comma added after the 2nd slide) and saved it. I then again tried to reload the page. both by clicking the "Reload Page" link on the error page AND by doing a Force Reload with the browser. The page does not refresh - still shows the original error message.

Even attempting to load the site in another BROWSER results in the same original error message page.

Going back to my Command Prompt, I see that Hugo detected each change I made in the /data/slide.json document:
`Change detected, rebuilding site.`
The errors reported were:
`ERROR 2021/12/01 12:25:58 failed to load data: failed to load data: "D:\Hugo\HugoSites\cheeky\data\slide.json:11:1": unmarshal failed: invalid character '{' after array element
ERROR 2021/12/01 12:25:58 failed to load data: failed to load data: "D:\Hugo\HugoSites\cheeky\data\slide.json:11:1": unmarshal failed: invalid character '{' after array element
ERROR 2021/12/01 12:25:58 Rebuild failed:

ERROR 2021/12/01 12:25:58 Failed to load data: failed to load data: "D:\Hugo\HugoSites\cheeky\data\slide.json:11:1": unmarshal failed: invalid character '{' after array element
Total in 17 ms`

Killing Hugo (Windows: ctrl -C)
and restarting it with: Hugo server -D

Resulted in a solution. In fact, I changed the /data/slide.json file CORRECTLY and now the 3rd slide loads with my title. 
(In my case, hugo's server now had to be called on a DIFFERENT localhost port (I had a different Hugo server running a different site on :1313) - so if you are simply reloading your original browser window you will now be getting a "This site can't be reached" error because localhost is no longer answering the previous port. Look carefully at the "Web Server is available at:" line in your terminal ).
