### ISSUE TITLE
No Chinese index in markdown, no internal jump

### ISSUE THREAD

**Issue by tangMans** [gohugoio/hugo#7098]
hi,
if my markdown file like this:
## index
- [header1](#header1)
- [header2](#6605 )

##header1
test1
##header2

------------------------------------------------------------------------------
when this file change to html, when i click index it can jump to the right location.
but when i change "##header1" to chinese like "##头部1",it can not jump to the right location.

Looking forward to your reply.

**Comment by satotake** [comment]
You need 1 space after `#` in whichever language.

I tested with `Hugo Static Site Generator v0.65.2/extended darwin/amd64 BuildDate: unknown`
it seems to work correctly

You can view my sample [here](https://raw.githubusercontent.com/satotake/hugo-test/anchor-in-chinese/content/proj/mycontnte.md)

By the way, this is basic of markdown instead of Hugo's development.
You cloud get answers timely at the [forum](https://discourse.gohugo.io/)

**Comment by tangMans** [comment]
ok, thanks
