### ISSUE TITLE
Add travis support

### ISSUE THREAD

**Issue by mxlit** [gohugoio/hugo#7119]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
Hugo Static Site Generator v0.68.3/extended linux/amd64 BuildDate: unknown
</pre>
### .travis.yml
<pre>
language: go
install:
- go get -v github.com/spf13/hugo
script:
- hugo version
- make build
branches:
 only:
 - master
</pre>

The command "go get -v github.com/spf13/hugo" failed and exited with 2 during .
![Screenshot from 2020-04-02 10-19-45](https://user-images.githubusercontent.com/54666990/78221134-7e0a2a80-74cb-11ea-8953-2ff8a0c9fe3e.png)
![Screenshot from 2020-04-02 10-17-18](https://user-images.githubusercontent.com/54666990/78221181-98440880-74cb-11ea-9756-a816d88f26bb.png)

**Comment by mxlit** [comment]
The command "go get -v github.com/spf13/hugo" failed and exited with 2 during .

The command "go get -v github.com/gohugoio/hugo" failed and exited with 2 during .

The command "go get -v https://github.com/gohugoio/hugo" failed and exited with 1 during .

**Comment by moorereason** [comment]
First, this is not a Hugo problem and should have been posted to the forums instead.

Second, it would probably be better to download the latest [binary release](https://github.com/gohugoio/hugo/releases) in your CI instead of building Hugo from source.

But lastly, if you insist...  The default Go version in Travis CI is too old to build Hugo.  I would recommend telling Travis to use the latest Go version.

Any further questions should be posted to the forums.  Thanks

**Comment by mxlit** [comment]
Thanks for info
