### ISSUE TITLE
hugo via snap in other than `$HOME` locations?

### ISSUE THREAD

**Issue by ozika** [gohugoio/hugo#7134]
This directly relates/follows-up from #3143. The snap install of hugo still only works in the home folder which I find quite limiting. I keep most scripts/data mounted from other locations.
Thanks for considering.

**Comment by khufkens** [comment]
This took me ages to figure out what was going on. Anyway, would appreciate this feature as well.

**Comment by davidsneighbour** [comment]
I would say this is not a Hugo issue but a general Snapd issue. I never needed that for myself, but there are plenty of reasons, why snap should put it's files somewhere else than the $HOME directory. It's however not the task of the Hugo snap package to solve that inconvenience - that's why there are plenty of other options ;)

Here is a description how to move ALL snap packages out of the home directory. Not sure though if some of the snaps are unhappy about that - if they use relative links to config files and such.

https://askubuntu.com/questions/1029562/move-snap-packages-to-another-location-directory

**Comment by khufkens** [comment]
Thanks for clarifying, from the discussion it seemed to have been a hugo specific thing.

**Comment by davidsneighbour** [comment]
Oh, ehm, that is my opinion only based on experiences with many other snap applications. 

It could be that there are ways to work around these things, but we should not forget, that snap-apps are a very "easy" way to install apps, not a way to create specific environments. 

It might probably work better to use some kind of `make` script instead of using snap if you need a specific installation with varying folders.

There are plenty of snap apps that require a `--classic` installation without newer security features (sandboxing) so that they can use other apps, tools or scripts or work outside of their "box". I prefer to use "handmade" installations instead of snap apps in these cases. Snap is good to have an app contained and "untouchable" by other system components. 

In my very (personal and opiniated) opinion (hehe): the Snap version of Hugo is for very generic quick use cases. The moment you have to go `--classic` is when you should think of compiling by yourself or installing via .deb packages or other ways.

And to make it clear again: this is my personal opinion/experience. Not the "official Hugo stance".

**Comment by khufkens** [comment]
Would love to install the .deb files, but my system lags behind (Ubuntu 16.04 LTS) and so do the debs. I can compile from source, but then I also need to compile Go and I'm not sure where this leads in terms of dependency hell.

**Comment by bep** [comment]
I suggest you continue the discussion on the forum. I will close this, as I think it at least falls outside of what we have time to do.
