### ISSUE TITLE
scss not working

### ISSUE THREAD

**Issue by copepod** [gohugoio/hugo#7192]
https://gohugo.io/hugo-pipes/introduction/#from-file-to-resource
not working 
error calling toCSS: no Resource provided in transformation

### What version of Hugo are you using (`hugo version`)?
<pre>
$ hugo version
Hugo Static Site Generator v0.69.0/extended windows/amd64 BuildDate: unknown
</pre>

### Does this issue reproduce with the latest release?
yes

**Comment by bep** [comment]
Thanks for getting in touch, but it feels like this is a question  that would be better suited to the [Hugo Discussion Forum](https://discourse.gohugo.io/).  We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug. You may also find the answers you search for in [Hugo Documentation](http://gohugo.io/overview/introduction/).
