### ISSUE TITLE
IsMenuCurrent() returns false for Multi Lang menus  in config files

### ISSUE THREAD

**Issue by zbayoff** [gohugoio/hugo#7233]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
Hugo Static Site Generator v0.69.2/extended darwin/amd64 BuildDate: unknown
</pre>

### Does this issue reproduce with the latest release?
Yes.

`.IsMenuCurrent` or `.HasMenuCurrent` return false on pages with languages other than the default language when the menus are defined in config files.

#### Steps to Reproduce
Clone the test repo created here: https://github.com/zbayoff/quickstart4

Run `hugo server`

You can see the active main menu item is red, and switching to another page will reflect the active page. 

When switching to another language other than english, however, the active (red) state no longer applies.

I've used the menu template code straight from the [Hugo Docs](https://gohugo.io/content-management/multilingual/#menus) and tested other combinations of `.IsMenuCurrent`, but to no avail. 

I believe this issue is related to this previously reported issue: https://github.com/gohugoio/hugo/issues/3459

**Comment by pamubay** [comment]
in `menus.fr.yaml`
```
main:
  - name: Chez moi (Home)
    url: / <-- This One
```
Because you set the the `url` of menu entry manually, Hugo not automagically converting that `url` to prepend the language prefix `/fr/`.

Even in the `partials/menu.html`, you use `absLangURL` on `.URL` to make Hugo to generate the correct URL for current language `fr`.
```
{{ .URL | absLangURL }}
```
workaround for this, of course by manually write the language prefix in the url

```
main:
  - name: Chez moi (Home)
    url: /fr/
```
