### ISSUE TITLE
http-equiv="Refresh" does not work any more

### ISSUE THREAD

**Issue by CicoZhang** [gohugoio/hugo#7315]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
0.71 

</pre>

### Does this issue reproduce with the latest release?

When I was using version 0.59, I put 

```
<meta http-equiv="Refresh" content="0; url=https://youtu.be/6Esn6Agr-AU" />
```
into the document, it worked perfectly, redirecting to that URL;

but after I installed 0.71, this no longer works.

**Comment by bep** [comment]
Thanks for getting in touch, but it feels like this is a question  that would be better suited to the [Hugo Discussion Forum](https://discourse.gohugo.io/).  We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug. You may also find the answers you search for in [Hugo Documentation](http://gohugo.io/overview/introduction/).
