### ISSUE TITLE
Extraneous p-tag around shortcodes

### ISSUE THREAD

**Issue by didenko** [gohugoio/hugo#7339]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
Hugo Static Site Generator v0.71.1 linux/amd64 BuildDate: unknown
</pre>

### Does this issue reproduce with the latest release?
Yes

### Setup

A single page is calling a sequence of shortcodes

The plugin structure has the baseof file which wraps ul-tags around the content. The content is a series of shortcodes resulting in series of li-tags.

Expected resulting code:
```html
<!DOCTYPE HTML>
<html>
<body><ul id="main"><li>Item1</li>

<li>Item2</li>
</ul></body>
</html>
```

Actual resulting code:
```html
<!DOCTYPE HTML>
<html>
<body><ul id="main"><p><li>Item1</li>

<li>Item2</li>
</p>
</ul></body>
</html>
```

### Full test case

For whatever reason GitHub refused to upload either .gz or .zip, so the test case is uploaded to the repository https://github.com/didenko/hugo_test_case_extra_p

**Comment by jmooring** [comment]
The combined output will be wrapped in a `<p>` tag if you do this:

```html
{{< item text="Item1" >}}
{{< item text="Item2" >}}
```

Neither the combined output nor the individual ouput will be wrapped in a `<p>` tag if you do this:

```html
{{< item text="Item1" >}}

{{< item text="Item2" >}}
```

I've run into this before. The fact that you are wrapping `<li>` tags with a `<ul>` tag is irrelevant. You can reproduce the behavior with shortcodes that render text only.

Is this a bug or a feature? In some cases I have taken advantage of the behavior, in others I have had to add a blank line between the calls in order to achieve the desired output.

The question has come up before:
<https://github.com/gohugoio/hugo/issues/1642>
<https://discourse.gohugo.io/t/5559>

**Comment by didenko** [comment]
Thank you, I see the behavior - really appreciate the pointer.

Useful of not, feels very counterintuitive.
