### ISSUE TITLE
Use Hugo shortcodes in files imported with include function

### ISSUE THREAD

**Issue by xexio** [gohugoio/hugo#7469]
There's a way to use the Hugo shortcodes inside files that I imported with the include function?

I have two files, _fileOne.adoc_ and _fileTwo.adoc_

In the file _fileOne.adoc_ I have this:

```
include::fileTwo.adoc[]
```
And in the _fileTwo.adoc_ I have this:
```
---
title: Page test
author: me
email: me@me.com
orgname:  myself
---
.
.
.
[source,bash]
....
# test {{% param orgname %}}
....
```
But this renders as:
```
# test {{% param orgname %}}
```
instead of:
```
# test myself
```

**Comment by xexio** [comment]
@bep Which is the other issue with the same problem? There's a workaround to solve this?

**Comment by muenchhausen** [comment]
Using `fileTwo.adoc` directly without include seems also not rendering correctly, right? 

There might be a workaround, if you use AsciiDoc variables - but the substitution might not work within source sections:

```
:orgname: myself

This is {orgname}.

[source,bash]
....
# test {orgname}.
....
```

**Comment by xexio** [comment]
If I access `fileTwo.adoc` directly works well.

The problem only happens with the include function. I can’t use AsciiDoc variables to solve this because I need some custom shortcodes.

Maybe we can take a look at the code where the shortcodes are processed @muenchhausen 

Thanks for your help.

**Comment by muenchhausen** [comment]
You were right. It seems, that the Hugo replacement is done before AsciiDoc include. 

Please explain why you need this exactly. Personally I would try not to use Hugo metadata  in AsciiDoc sections, because these cannot be rendered e.g. in PDF or other output formats.

Therefore I usually try to create a minimal AsciiDoc file ìndex.adoc` or `_index.adoc` for encapsulating Hugo rendering. That file `includes` the documentation sections without any Hugo metadata. You can name `index.adoc` a kind of adapter. The advantage here is that you can reuse these sections for rendering in other output formats without any side effects. 

`index.adoc` - as kind of adapter for Hugo rendering:
```
---
title: Page test
orgname:  myself
---
:orgname: {{% param orgname %}}
include::fileTwo.adoc[]
```

`fileTwo.adoc` - this is pure AsciiDoc and can be also rendered in PDF:
```
[source,bash,subs=attributes+]
....
# test {orgname}.
....
```

I just found, that you can even use variables within AsciiDoc code blocks - see `subs=attributes+`. The AsciiDoc variable substitutions are very powerful.

**Comment by xexio** [comment]
@muenchhausen I’m using this functionality to load values from toml files. But you’re right, with this approach this shortcodes are not going to be replaced in PDF :’(

I’m going to create some custom extensions.

I was looking in the documentation but I don’t find the way to pass custom extensions to AsciiDoctor when I using in combination with Hugo.

There’s a way to do that?

**Comment by muenchhausen** [comment]
You can directly set AsciiDoc variables using the [attributes](https://gohugo.io/content-management/formats/#external-helper-asciidoc) arguments in `config.toml`:
```
[markup.asciidocext]
    extensions = ...
    workingFolderCurrent = true
    [markup.asciidocext.attributes]
        orgname = "myself"
```

Doing that, you don't need Hugo metadata.

**Comment by xexio** [comment]
@muenchhausen thanks, I’m going to use this approach.

One question not related to the issue. There’s a way to call custom extensions from hugo?
