### ISSUE TITLE
Improving the ESBuild import resolver to support "Hugo modules imports"

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#7474]
Ref. #7321

**Comment by acalvo** [comment]
@bep I found an oddity and I'm not sure if it's related to this issue.

The thing is: suppose I have the following `demo.js` code:
```js
require("core-js/modules/es.array.from");
console.log(Array.from(document.querySelectorAll("div")));
```

I have `core-js` set as as dependency in my `package.json`. If I `<script src="{{ (resources.Get "js/bug.js" | js.Build).RelPermalink }}"></script>` from a template, it works like a charm (the `require` is resolved and a everything is bundled in a single file 🥳).

If I move that code to my theme, which is included in my project as a Hugo module, and test it locally (`replace xxx` in my `go.mod`) keeps working OK. But the time I push the changes to my theme repo, stop testing it locally (remove `replace xxx` in my `go.mod` from my Hugo) and pin my Hugo module theme version to that new commit, I get this error when I run it:

```
hugo serve
Built in 168 ms
Error: Error building site: JSBUILD: failed to transform "js/demo.js" (application/javascript): Could not resolve "core-js/modules/es.array.from"
make: *** [site-serve] Error 255
```

In that moment, if I execute `hugo mod vendor` to vendor the theme and run `hugo serve`, everything gets back to work.

Is that what this issue is about? Or should I open another issue to discuss this feature lack / bug report?

**Comment by bep** [comment]
>Is that what this issue is about? 

Yes, but please don't ask me to elaborate workarounds here, use the discussion forum for troubleshooting.

**Comment by bep** [comment]
I think this should be OK now.
