### ISSUE TITLE
Render problem of template with HTML comment.

### ISSUE THREAD

**Issue by joywek** [gohugoio/hugo#7477]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
Hugo Static Site Generator v0.72.0/extended darwin/amd64 BuildDate: unknown
</pre>

### Does this issue reproduce with the latest release?

My code(layout/index.html):

```html
{{ define "main" }}
<h1>Hello</h1>
{{ end }} <!-- main -->
```

When I enter comment after the {{ end }}, the page cannot be rendered properly.

**Comment by bep** [comment]
Thanks for getting in touch, but it feels like this is a question  that would be better suited to the [Hugo Discussion Forum](https://discourse.gohugo.io/).  We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug. You may also find the answers you search for in [Hugo Documentation](http://gohugo.io/overview/introduction/).
