### ISSUE TITLE
.Format Function converts '+' to &#43; even when contained inside a <time></time> tag

### ISSUE THREAD

**Issue by Bas-Man** [gohugoio/hugo#7488]
### What version of Hugo are you using (`hugo version`)?
Hugo Static Site Generator v0.74.1/extended darwin/amd64 BuildDate: unknown

### Does this issue reproduce with the latest release?
Yes. This is the latest version and I only initially noticed it after updating as I am trying to workout a different issue.

I suspect this is a bug as it would seem that:
```txt
&#43;
```
would not conform to the specification for the <time> tag as noted at https://www.w3schools.com/tags/att_time_datetime.asp

Seems there might be a need for the .Format function to be able to preserve the '+' character in some cases.

Example of code from a the Ananke theme I am currently using

```html
      {{/* Hugo uses Go's date formatting is set by example. Here are two formats */}}
      <time class="f6 mv4 dib tracked" datetime="{{ .Date.Format "2006-01-02T15:04:05Z07:00" }}">
        {{- .Date.Format "January 2, 2006" -}}
      </time>
```
Produces
```html
     <time class="f6 mv4 dib tracked" datetime="2020-07-16T00:00:00&#43;09:00">July 16, 2020</time>
```

**Comment by Bas-Man** [comment]
This issue may actually trace back to the actual .Date and .Lastmod function.
I have found that the same issue occurs even without the .Format function.

**Comment by bep** [comment]
Thanks for getting in touch, but it feels like this is a question  that would be better suited to the [Hugo Discussion Forum](https://discourse.gohugo.io/).  We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug. You may also find the answers you search for in [Hugo Documentation](http://gohugo.io/overview/introduction/).
