### ISSUE TITLE
store the static website in a sqlite3 database

### ISSUE THREAD

**Issue by rbucker** [gohugoio/hugo#7500]
I was watching a presentation from the author of SQLite and he presented an interesting idea. They store the SQLite website in a SQLite database. SQLite is very efficient on small files. Much faster than a plain filesystem. Granted I do not have a webserver but I'd implement one once the structure was in place.

I think this is the schema they are using - https://www.sqlite.org/cgi/docsrc/file?name=schema.tcl&ci=tip

Thanks

**Comment by moorereason** [comment]
Thanks for the suggestion.  We agree, but I'm going to close this issue for two reasons:

1. We already have issues for this general idea (cf. #4485 & #5074)
1. The SQLite schema you referenced looks very specific to their use case.  Hugo's solution would likely need to be much more general and, therefore, complex--which is why we don't have a solution yet.
