### ISSUE TITLE
Can't have multi-word strings in org mode front matter

### ISSUE THREAD

**Issue by shosti** [gohugoio/hugo#7525]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
Hugo Static Site Generator v0.74.3-DA0437B4/extended linux/amd64 BuildDate: 2020-07-23T16:30:30Z
</pre>

### Does this issue reproduce with the latest release?
Yes

# Issue
When using org mode, the front matter using the `+#key[]` syntax doesn't allow multi-word strings. For example:

```org
#+series[]: My cool series
```
will end up with three series, `My`, `cool`, and `series`. This seems like intended behavior, but there seems to be no way to override it. For instance:

```org
#+series[]: "My cool series"
```
will still end up with three series, `"My`, `cool`, and `series"`. It seems like there should be some way to "escape" whitespace for things like multi-word series titles, but it doesn't currently seem to be possible.

**Comment by tom10x** [comment]
Hello @bep, I see you added the Upstream label to this issue. Could you elaborate on where the problem is located?

**Comment by bep** [comment]
github.com/niklasfasching/go-org

/cc @niklasfasching

**Comment by tom10x** [comment]
Hello @niklasfasching , what are your thoughts on supporting multi-word strings in #+keywords like #+TAGS? Looking at https://orgmode.org/manual/Tags.html , it seems org-mode itself requires tags to be "normal words", i.e. no spaces. Would you still consider adding support for it in go-org?

**Comment by bep** [comment]
Could you take this discussion at the upstream issue tracker?

**Comment by tom10x** [comment]
@bep Sadly, I don't think org-mode actually supports this. I could be wrong, but if I'm right then we can't expect go-org to implement it upstream. If the maintainer wants to do it I feel they could let us know in this issue.

But I eventually found a solution/workaround which works for me. I can get a tag "foobar" to display as e.g. "Foo Bar" by creating a file "content/tags/foobar/_index.md" with a front-matter title: "Foo Bar". See https://gohugo.io/content-management/taxonomies/#add-custom-metadata-a-taxonomy-or-term  That's good enough for me. How about you, @shosti ?

**Comment by niklasfasching** [comment]
org mode frontmatter parsing is internal to hugo - `go-org` doesn't even get to see the frontmatter as hugo only provides the content for rendering.

The corresponding logic is in [`metadecoers/decoder.go`](https://github.com/gohugoio/hugo/blob/fd7969e0b09e282d1cd83281bc0f5a62080afe5a/parser/metadecoders/decoder.go#L217-L245), more specifically
```go
if strings.HasSuffix(k, "[]") {
	frontMatter[k[:len(k)-2]] = strings.Fields(v)
}
```

The easiest solution I can see is just using yaml front matter.

```org
---
title: "hugo let's you choose your preferred frontmatter format"
tags: ["yaml supports tags with spaces"]
---
content
```

If you really want to use org mode native frontmatter I guess you could change `strings.Fields` to a csv parser instead.

**Comment by niklasfasching** [comment]
Just a thought: If this is about keeping org mode documents valid outside of hugo we could introduce a special key (e.g. `frontmatter`) and parse and merge it's contents as one of the frontmatters hugo supports. I don't know how much I like this idea - I still think just using yaml is the right choice.
```
		} else if k == "frontmatter" {
			parts := regexp.MustCompile(`\s`).Split(v, 2)
			format, bytes := Format(parts[0]), []byte{}
			if len(parts) == 2 {
				bytes = []byte(parts[1])
			}
			if err := d.UnmarshalTo(bytes, format, &frontMatter); err != nil {
				return err
			}
		}
```

`post.org`
```
#+TITLE: title
#+FRONTMATTER: json {"tags": ["a b c", "d e f"}
```
multiline works just as well because duplicate keys are concatenated using `\n`
```
#+TITLE: title
#+FRONTMATTER: json
#+FRONTMATTER: {
#+FRONTMATTER:   "tags": ["a b c", "d e f"]
#+FRONTMATTER: }
```

**Comment by mdorman** [comment]
> If you really want to use org mode native frontmatter I guess you could change `strings.Fields` to a csv parser instead.

So I'll just state up-front that I dislike the idea of using YAML, if there's an equivalent org construct---one day I might want to use something other than Hugo.

I think the mismatch here is that org's approach to handling a setting with multiple values is different from how hugo+go-org approach it.  Per the manual where it talks about `#+` keywords:

https://orgmode.org/manual/In_002dbuffer-Settings.html#In_002dbuffer-Settings

    Org also accepts multiple lines for a keyword

And even more specifically:

    ‘#+TAGS: TAG1(c1) TAG2(c2)’

    These lines (several such lines are allowed) specify the valid tags in this file, and (potentially) the corresponding fast tag selection keys. The corresponding variable is org-tag-alist.

If it were up to me---and I realize that it really isn't, as I'm unlikely to write the code---I would say that since `#+TAGS[]` and `#+CATEGORIES[]` are Hugo-specific *anyway*, the semantics should be that each of those can appear more than once, and the value is trimmed of leading/trailing whitespace but otherwise unmodified.  This seems to address a need that I (and others) have, while remaining completely consistent with org semantics.  Honestly,

**Comment by niklasfasching** [comment]
This would be just as easy to implement as switching to a csv parser - you'd just split on newline and trim space. I'm not convinced it's more natural coming from org - afaiu the todo example actually behaves like the current implementation by allowing multiple lines and more than one value  per line. In the end I don't mind and the thing stopping me from implementing either is that we break existing behaviour. If there's any suggestion how to deal with that i can take a stab to finally close this issue.

**Comment by pprevos** [comment]
I use a workaround. Any names with spaces are written with dashes, which I filter out in the theme.

`#+categories[]: Org-Mode` becomes "Org Mode" Rendered.
