### ISSUE TITLE
Add post encryption to content

### ISSUE THREAD

**Issue by GoGoGoDoge** [gohugoio/hugo#7547]
I want to add a post encryption feature to hugo. 
Right now there is a work around as proposed by this author in this repo:
https://github.com/Li4n0/hugo_encryptor/blob/master/README.md

It would be nice to integrate this solution into hugo.

**Comment by GoGoGoDoge** [comment]
It is actually related to #7154 
The repo I mentioned above implements in a way to use python with beautiful soup to parse a specific html node and encrypt it on demand.

**Comment by moorereason** [comment]
First, cryptography is surprisingly hard.  Generally speaking, only cryptographers should write crypto solutions.

Second (and perhaps making my first point), the examples linked to above use AES-CBC.  AFAIK, CBC encryption is now considered weak due to padding oracle attacks.

Third, the easiest solution would be to use a verified, turn-key solution such as nacl [secretbox](https://pkg.go.dev/golang.org/x/crypto/nacl/secretbox?tab=doc), but the algorithms used by nacl are not widely supported (by crypto-js or WebCrypto).

Forth, I, for one, don't want to be responsible for maintaining a turn-key solution in Hugo.  I'm not a cryptographer.  The most I'd be willing to support is a general crypto API via template functions that essentially exposes the Go stdlib API, but even that would be need some careful thinking.  Which all feels like a lot of work for a small reward.

I'm interested in the idea of a general crypto API, but I'll have to thinking about it.

@bep, what are your thoughts?

**Comment by GoGoGoDoge** [comment]
Thank you for the detailed response. This is indeed a lot of work for a small reward. I have to admit that encrypted web page is not a common use case in static website.

**Comment by moorereason** [comment]
@Lednerb,
As I said before, I would only be willing to support nacl secretbox.  I'm not interested in supplying a javascript solution around the template functions.  I only mentioned javascript and WebCrypto to point out the difficulty in writing a client-side companion piece to go along with nacl secretbox.

Would a nacl secretbox implementation solve your need?  It would look something like this, I suppose:

```
{{ $Password := "change this password to a secret" }}
{{ $enc := secretbox.Seal $Password "hello world" }}

{{ $enc | base64Encode }} ->
rjfsV4uz4m9XV+znsnm/bNfHDkOKrafW0uIi0P2nL/0GskOXc8N08WlRJ3zq+1chMpvN

{{ secretbox.Open $Password $enc }} ->
hello world
```

I want the implementation to be super-simple and essentially front-end the `golang.org/x/crypto/nacl/secretbox` API.

**Comment by Lednerb** [comment]
@moorereason 
>Would a nacl secretbox implementation solve your need?

This would be totally fine and is the most flexible way of handling this, enabling also the possibility to set the password via frontmatter.

It will also be possible to use a javascript implementation of `nacl` like [tweetncl](https://github.com/dchest/tweetnacl-js/wiki/Examples) to craft some interactive decryption on the website etc.

**Comment by bep** [comment]
We need some:

* Great arguments as to "why this would be useful" -- "I want to encrypt" is not a good argument.
* Usage examples.

**Comment by GoGoGoDoge** [comment]
> We need some:
> 
> * Great arguments as to "why this would be useful" -- "I want to encrypt" is not a good argument.
> * Use cases
> * Is this useful to many?

Argument:
1. It is best used under a scenario that author wants to share message as long as readers have a token. And author doesn't mind if readers share the token to others. 
2. Avoid search engine caching if the message users want to share is encrypted 

Use cases:
1. In my own use case, I store all mail service tracking link (they are public accessible as long as you have the tracking number) with my friends in a hugo static page. I have encrypted those links into a secret message and share token with my friend. I don't really mind if my friend sharing the token to others (i.e. my friend is sharing his tracking link to others)

**Comment by Lednerb** [comment]
Hey @bep,
I will gladly provide further information on this

> We need some:
> 
>     * Great arguments as to "why this would be useful" -- "I want to encrypt" is not a good argument.
>     * Use cases
>     * Is this useful to many?

In my case I'm hacking machines on [HackTheBox](https://www.hackthebox.eu/) and want to publish some Write-Ups for machines / challenges. To ensure that only users can read that Write-Up / Walkthrough that have already hacked the machine by themselfs, the content should be encrypted with a password / token / flag / hash that is found when the machine was hacked / the challenge was solved.

One way to provide this would be to upload a password-protected PDF or 7z file for downloading, but after a while the HTB machines get "retired" and the walkthroughs can be published without any protection. In this case, it would be possible to re-publish the content.

A better approach would be (for me as the maintainer of the [bilberry-hugo-theme](https://github.com/Lednerb/bilberry-hugo-theme) to implement a frontmatter option `encryptWithSecret` (or a better name found in the future) that will ensure that the markdown-rendered content is encrypted when the `hugo` command runs. By removing the `encryptWithSecret` setting the content will not be encrypted on the next build, but visible for the public.


Although this use-case was my main intention to search for away to encrypt the content, there might be more use-cases and I'm looking forward to follow up this thread.

**Comment by RichyHBM** [comment]
Hello, realise this issue is a year old but wanted to provide another use case that I imagine I'm not alone in being interested in.
So In my case I would like to have my resume/cv on my website, but want to control some amount of privacy over it so that for example robots dont cache it, or anyone can just look at it and view my personal information. In addition to this I use netlify to deploy my site and as such cant make use of 3rd party tools like those linked in the thread. That said, I feel like this thread isnt the best place to convay the conversation as it was initially meant for a much higher level function (built in post encryption) where as my preference would be to expose some sort of encryption API as a function, to that matter I have created this issue to better reflect that, #8969.

**Comment by r3pek** [comment]
Can this be revived? Makes no sense no close a bug report that's not fixed.
