### ISSUE TITLE
Calling partial that returns value without arguments (or a zero argument) just silently fails

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#7572]

**Comment by ericselin** [comment]
I get that this is was a bug in the expected behavior. However, this fix broke my particular use case:
```hbs
{{ with partial "helpers/get-image" .image }}
  <!-- do something with image if found -->
{{ end }}
```
In my case `.image` may be empty, and in this case it is completely correct to silently "fail" and return `nil` from the partial.

Just my five cents: maybe better to make a warning out of similar cases as opposed to a full error, so current behavior is not broken?
