### ISSUE TITLE
Fix CLI docs formatting/summary

### ISSUE THREAD

**Issue by emelens** [gohugoio/hugo#7608]
The content in the below shown blocks looks to ignore all formatting of the underlying markdown file and render as plain text

It also includes the word "synopsis" as part of inline content.

This does not seem correct.

![image](https://user-images.githubusercontent.com/18240627/80854634-a05da800-8c31-11ea-92e5-f8c1cba68b33.png)

**Comment by DanielVF** [comment]
The page at https://gohugo.io/commands/ displays a text-only, no linebreaks summary of the richly formatted command pages. 

Here's an example command page shown in the docs: https://gohugo.io/commands/hugo/

Here's the source that drives the command page: https://github.com/gohugoio/hugo/blob/master/docs/content/en/commands/hugo.md

Other "index" pages don't seem to have this problem, and also seem to use rich text. For example: https://gohugo.io/templates/

![image](https://user-images.githubusercontent.com/837/95581985-f0723f00-0a07-11eb-9ba1-b8772a7a09e3.png)

The appears to be because the YAML frontmatter for the templates page contains a description section, for example:

https://raw.githubusercontent.com/gohugoio/hugo/master/docs/content/en/templates/introduction.md

"description: Hugo uses Go's `html/template` and `text/template` libraries as the basis for the templating."

It seems like the only thing needed to fix this issue is adding description fields to the commands documents.

**Comment by sebastiaan-lampo** [comment]
The list template fills the boxes using the boxes-section-summaries partial. That partial uses .Param.description (piped to markdownifiy) with a fallback for .Param.summary (no pipe). The page template includes .description at the top, which means that it would be duplicated if that's used. 

However, these pages are auto-generated. Last line in the content files:
`###### Auto generated by spf13/cobra on 13-Sep-2020`
I suspect that the "docshelper" has something to do with that but I haven't figured out how (yet).

My proposed changes would be:

- include summary in the front matter. Use either synopsis up to first code section or the intro line ahead of synopsis
- replace the text now in summary with shortcode <<{ param "summary" >}} in the content to avoid duplication

Further potential enhancements unrelated to this issue:
- add 'toc: true' in the front matter for consistency with the rest of the docs 
- change capitalization of 'See also' section to match the rest of the docs style.

**Comment by sebastiaan-lampo** [comment]
I recommend that this be closed as a "won't fix".

As a learning experience I tracked down the docs generation into the spf13/cobra package. The GenMarkdownTreeCustom command is what hugo relies on to generate the docs. ([cobra code blob](https://github.com/spf13/cobra/blob/893ebf6e36ac744887c934361ce95ce9ce8cffaf/doc/md_docs.g)). The "prepender", which generates the front matter only has access to the file string, not any of the content. That means there is no easy way of modifying the front matter without overloading this function (I'm not a GO programmer, so not sure if that's possible). Overall, too much effort for what it's worth.

It is possible to "clean" the page by inserting `summary: " "` into the prepend code which lives in the hugo code itself. I personally don't think that looks any better because now the reader must click to learn anything.
![commands_empty](https://user-images.githubusercontent.com/26228724/107669301-d3b47500-6c4e-11eb-8221-3bc594036462.png)

I'll shortly create a pull request that resolves the matter but as far as I could figure out it cannot be done without what I consider a hack. It involves parsing the content with string search to identify the relevant content portion to include in the summary box. It is significantly less elegant than the rest of the documentation templates. As such, I stand by my advice to close the issue (and discard my upcoming pull request).

PS: is the etiquette to update my previous comment or leave these as separate ones?
