### ISSUE TITLE
hugo server fails to delivery static style.css file

### ISSUE THREAD

**Issue by ngdangtu-vn** [gohugoio/hugo#7613]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
Hugo Static Site Generator v0.74.3-DA0437B4 linux/arm
BuildDate: 2020-07-23T16:22:34Z
</pre>

Currently I'm testing this on:
- Chromium 78.0.3904.108 on Raspberry Pi Buster OS
- Firefox ESR 68.11.0esr (32-bit) on Raspberry Pi Buster OS

### Does this issue reproduce with the latest release?
![Style Sheet could not be loaded](https://i.imgur.com/hQG54Ca.png)

Here is how I messed it up:
1. `hugo server --ignoreCache --debug --i18n-warnings`
2. Open localhost
3. Receive
    - msg on Firefox with network response code 200 for style.css
    - nothing on Chromium and no network response

So far, I did:
- Restart `hugo server`
- Use `absURL` for style.css file
- Check if file exists -> it does
- Try to get style.css directly from browser -> load normally, browsers just refuse to load and render it.

The only thing I didn't try yet is restart a whole PC. I will report this after I wake up.

After googled it, I found out this is server side, which is hugo serve:
- https://stackoverflow.com/questions/36989220
- https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content/How_to_fix_website_with_mixed_content

I have not research about this yet, but I think a few options for server configuration might be able to fix this.

**Comment by bep** [comment]
Thanks for getting in touch, but it feels like this is a question  that would be better suited to the [Hugo Discussion Forum](https://discourse.gohugo.io/).  We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug. You may also find the answers you search for in [Hugo Documentation](http://gohugo.io/overview/introduction/).

**Comment by ngdangtu-vn** [comment]
It was my fault for [not checking typo](https://discourse.gohugo.io/t/hugo-server-fails-to-delivery-static-style-css-file/27948/2). I should have used template code so I won't mistype `type='text/css'` to `type='text/stylesheet'`. Silly me. Sorry about this.
