### ISSUE TITLE
hugo new resources/foo.md created in project/resources/foo.md

### ISSUE THREAD

**Issue by pointyfar** [gohugoio/hugo#7710]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
Hugo Static Site Generator v0.75.1-A4A7BAB7/extended linux/amd64 BuildDate: 2020-09-15T06:57:20Z
</pre>

### Does this issue reproduce with the latest release?
Yes, and reproducible at least down to `0.49`

Running `hugo new resources/foo.md` creates `foo.md` under `project/resources/` instead of under `project/content/resources/`.

**Comment by jmooring** [comment]
This is not specific to `resources`.

If the `xxx` directory exists in the project root, `hugo new xxx/foo.md` will create `foo.md` in the `xxx` directory instead of creating it in `content/xxx`. 

Related: if the `content` directory does not exist in the project root, `hugo new xxx/foo.md` will create `foo.md` in the `xxx` directory (creating the `xxx` directory if necessary) instead of creating it in `content/xxx`.

**Comment by pointyfar** [comment]
TIL, thanks.
