### ISSUE TITLE
resources.PostProcess causes --path-warnings to falsely report duplicate content

### ISSUE THREAD

**Issue by carlmjohnson** [gohugoio/hugo#7735]
If I have `resources.PostProcess` in my template, it falsely reports the page as duplicated with `hugo --path-warnings`.

### What version of Hugo are you using (`hugo version`)?

 v0.75.1/extended darwin/amd64 BuildDate: unknown

### Does this issue reproduce with the latest release?
Yes

**Comment by jmooring** [comment]
Minimal example

```bash
git clone --single-branch -b hugo-github-issue-7735 https://github.com/jmooring/hugo-testing hugo-github-issue-7735
cd hugo-github-issue-7735
npm ci
hugo --printPathWarnings
```

**Comment by rhcarvalho** [comment]
I'm updating a website to use TailwindCSS 3.x and following the patterns in https://github.com/bep/hugo-starter-tailwind-basic. Turns out hugo-starter-tailwind-basic relies on `resources.PostProcess` and having that in my template broke my build script, which runs `hugo` with `--printPathWarnings` and `--panicOnWarning` in the hopes of catching problems earlier.

Took me quite some time today until I was able to pin down the problem and find this issue.

Since Tailwind support seems to be something that's been worked on lately, could this issue be pinned to help others find about it earlier?
