### ISSUE TITLE
JS minifier broken in 0.76

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#7792]

**Comment by bep** [comment]
I'll revert to what we had in 0.75.1:

github.com/tdewolff/minify/v2 v2.6.2

**Comment by tdewolff** [comment]
Just curious, did you happen to encounter a new bug?

**Comment by moorereason** [comment]
Bug report in the forums:  https://discourse.gohugo.io/t/0-76-0-breaks-lazy-loading-on-my-website/28696

Previous discussion on the upgrade PR: https://github.com/gohugoio/hugo/pull/7701

**Comment by tdewolff** [comment]
Thanks @moorereason , I'd like to fix any issue there is with `minify` so that the latest version can be used with Hugo. However, I'm unable to reproduce the bug in the forums, if anyone can reproduce it please let me know how. With respect to the upgrade PR, I've commented there that the technique used for minification is very common amonst minifiers. Currently I'm unaware of any issues with `minify`, but please keep me posted when a problem rises.
