### ISSUE TITLE
Revisit the Sushi vs go-toml issue

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#7799]
I was reminded about this issue: 

https://github.com/gohugoio/hugo/issues/7794
Dotted keys would be useful:

https://toml.io/en/v1.0.0-rc.3#keys

**Comment by moorereason** [comment]
I looked at moving to `go-toml` a few weeks ago.  I'm waiting on https://github.com/pelletier/go-toml/issues/436 so that we don't have to rewrite a bunch of tests (haven't tried fixing it myself).

Performance is still an issue (https://github.com/pelletier/go-toml/issues/167), although less so now.  I made some improvements in https://github.com/pelletier/go-toml/pull/438, but there's more work to do (see https://github.com/pelletier/go-toml/issues/167#issuecomment-691538332).  I think `go-toml` may end up being more performant than `BurntSushi`, but time will tell.

**Comment by 89z** [comment]
I would hold off on this, I just discovered a significant Unmarshalling issue with Slice of Maps.

**Comment by jmooring** [comment]
BurntSushi/toml is no longer maintained. <https://github.com/BurntSushi/toml/commit/ea60c4def909bde529d41a7e0674e31eba751da3>

**Comment by arp242** [comment]
> BurntSushi/toml is no longer maintained. [BurntSushi/toml@ea60c4d](https://github.com/BurntSushi/toml/commit/ea60c4def909bde529d41a7e0674e31eba751da3)

It is now (by me); FYI. There should be a new release soon™, which includes TOML 1.0 support, and some other improvements.

Especially the detailed errors will probably be very useful for Hugo, the default error is still:

    toml: line 1 (last key "naughty"): invalid escape in string '\x'

But you can also print:

```
toml: error: invalid escape in string '\x'

At line 1, column 11-13:

      1 | naughty = "\xAg"
                     ^^
```

Or even:

```
toml: error: invalid escape in string '\x'

At line 1, column 11-13:

      1 | naughty = "\xAg"
                     ^^

A '\' inside a "-delimited string is interpreted as an escape character.

The following escape sequences are supported:
\b, \t, \n, \f, \r, \", \\, \uXXXX, and \UXXXXXXXX

To prevent a '\' from being recognized as an escape character, use:

- a ' or '''-delimited string; escape characters aren't processed in them; or
- two backslashes to get a single backslash: '\\'.

If you're trying to add a Windows path (e.g. "C:\Users\martin") then using '/'
instead of '\' will usually also work: "C:/Users/martin".
```

I'll make a PR to update it once it's done.

**Comment by jmooring** [comment]
Can this be closed per https://github.com/gohugoio/hugo/pull/8815?
