### ISSUE TITLE
Hugo 0.76.* i18n .Count warning message

### ISSUE THREAD

**Issue by Vimux** [gohugoio/hugo#7822]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
Hugo Static Site Generator v0.76.4/extended darwin/amd64 BuildDate: unknown
</pre>

### Does this issue reproduce with the latest release?

Yes.

It works correctly in 0.48.0 – 0.75.1 without any warnings.

---

### Problem

[Mainroad](https://github.com/Vimux/Mainroad/) demo build log shows the following warning messages since bumping to Hugo 0.76.*:

```
WARN 2020/10/12 13:40:31 Failed to get translated string for language "en" and ID "authorbox_name": template: :1:9: executing "" at <.Count>: can't evaluate field Count in type string
WARN 2020/10/12 13:40:31 Failed to get translated string for language "en" and ID "authorbox_name": template: :1:9: executing "" at <.Count>: can't evaluate field Count in type string
WARN 2020/10/12 13:40:31 Failed to get translated string for language "en" and ID "authorbox_name": template: :1:9: executing "" at <.Count>: can't evaluate field Count in type string
WARN 2020/10/12 13:40:31 Failed to get translated string for language "en" and ID "authorbox_name": template: :1:9: executing "" at <.Count>: can't evaluate field Count in type string
WARN 2020/10/12 13:40:31 Failed to get translated string for language "en" and ID "authorbox_name": template: :1:9: executing "" at <.Count>: can't evaluate field Count in type string
```

As a result, i18n string (`authorbox_name`)  does not work as before.

<details>
  <summary>Screenshot</summary>
  <img src="https://user-images.githubusercontent.com/21033483/95775708-e616a600-0c90-11eb-8499-be92476eae1a.png">
</details>

### Example

You can see it in action (authorbox block at the bottom of the page):

[Demo 0.48.0](https://mainroad.netlify.app/post/hugoisforlovers/)

[Hugo Themes demo (0.76.4)](https://themes.gohugo.io//theme/mainroad/post/emoji-support/)

### Steps to reproduce

1. Clone Mainroad repository and cd in the exampleSite dir

    ```bash
    git clone https://github.com/vimux/mainroad.git
    cd mainroad/exampleSite/
    ```

1. Run Hugo server with the following command:

    ```bash
    hugo server --themesDir ../..
    ```

1. Visit http://localhost:1313/post/hugoisforlovers/ in your browser and scroll to the bottom of the page.

---

Related parts:
[i18n/en.yaml](https://github.com/Vimux/Mainroad/blob/8c2da72f92947e0bda55eacce1a70df8c3296ba5/i18n/en.yaml)
[partials/authorbox.html](https://github.com/Vimux/Mainroad/blob/8c2da72f92947e0bda55eacce1a70df8c3296ba5/layouts/partials/authorbox.html)

**Comment by lingsamuel** [comment]
I change `{{ .Count }}` to `{{ . }}`, it works as before again

**Comment by Vimux** [comment]
> I change {{ .Count }} to {{ . }}, it works as before again

The problem is that it works as before in Hugo v0.76.* only. Any other versions like `v0.59.1`, `v0.68.3`, or even `v0.75.1` returns a different result in that case.

> in fact I don't know why the theme is using Count

I can't speak for everyone, but I use this expression to pass variable in the translation string.

**Comment by cyChop** [comment]
> > in fact I don't know why the theme is using Count

> I can't speak for everyone, but I use this expression to pass variable in the translation string.

This is per [documentation](https://gohugo.io/content-management/multilingual/#translation-of-strings)

**Comment by kevinclevenger** [comment]
Seeing the same thing with 0.76.3 and the Beautiful Hugo theme, destroys the posted on date in the generated site.

    WARN 2020/10/17 16:33:10 Failed to get translated string for language "en" and ID "postedOnDate": template: :1:4: executing "" at <.Count>: can't evaluate field Count in type string

**Comment by cyChop** [comment]
A note after some experimentation on my own site: `{{ .Count }}` is still required for numbers (integers), but you need to use `{{ . }}` for any other kind of object (at least for datetimes). It adds some readability, but it's a breaking change. From what I understand, not from Hugo itself but from go-i18n.

I think it's hard to find the best way to go here. For ease of use, keeping things compatible is great, but that's a complicated way to go since developers would have to do the same for all libs Hugo depend upon (which would end being an impossible task and might kill Hugo's performances in the end).

As far as I'm concerned, and Hugo's developers will of course have the final word, this should be divided into two tasks:
- Hugo's documentation should be updated to help make this subtlety better-known;
- Theme developers should be informed of this change, and that their theme is no longer fully compatible with Hugo 0.76+.

A workaround for people who use not-updated themes would be to write translation files and overwrite the problematic translations in your local files. It's a quickfix, but if I'm correct on Hugo's order of precedence, it will take the translation you provide over the one included inside the theme. You would just need to write the failing translations, no more.

One open question: I don't know who adds the "Count" variable? Is it Hugo when wrapping an int it passes to go-i18n, or is it go-i18n itself? In the first case, wouldn't it be possible to send it as `{{ . }}`, so that all variables are called in a uniform fashion, no matter what their type is?

**Comment by nonumeros** [comment]
testing it with v0.76.4ext as the op's, if there's a variable named `name` somewhere, why would the same name is used as a parameter on the config file. Whether it'd be yaml or toml.

Anyhow.

if I were to have as the op's
```
[Author]
  name = "John Doe"
```

on the config file, and I'd name `name` to something else, or comment it out, ,then  the  `at <.Count>: can't evaluate field Count in type string` would not come up. But I have no idea whether this issue was ever resolved or not, as it shows it's still open.

**Comment by jmooring** [comment]
Related: https://github.com/gohugoio/hugoDocs/issues/1410
