### ISSUE TITLE
Multilingual: 'message "xxxx" has no plural form for "one"

### ISSUE THREAD

**Issue by cyChop** [gohugoio/hugo#7839]
With the latest updates, my site generation generates a lot of warnings like the following:

> i18n|MISSING_TRANSLATION|fr|xxxxxx
> WARN 2020/10/15 18:34:15 Failed to get translated string for language "fr" and ID "xxxxxx": message "readingTimeShort" has no plural form "one"

I use the "--i18n-warnings" option. Some of the concerned messages use a dynamic count, others don't.

The messages that generate these messages are called with a .Count argument (`{{- i18n "xxxxxx" $count -}}`), but don't need specific singular/plural forms.

### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
Hugo Static Site Generator v0.76.5-60F0725B/extended linux/amd64 BuildDate: 2020-10-14T15:25:14Z
</pre>

### Does this issue reproduce with the latest release?

Yes.

**Comment by bep** [comment]
I will have a look at this soonish, but today I'm busy busy with other things. This i18n upgrade from v1 to v2 was certainly more painful than I expected, but hopefully it's worth it.

**Comment by cyChop** [comment]
That is certainly not a priority. These are only warnings, but the site is correctly generated nonetheless.

Thanks for having a look at it anyway! :)

**Comment by jmooring** [comment]
About the warnings...
<https://github.com/gohugoio/hugoDocs/issues/1410#issuecomment-824686546>

**Comment by jmooring** [comment]
@cyChop I suspect that the warnings are correct, and would like to close this issue. Please review my [comments here](https://github.com/gohugoio/hugoDocs/issues/1410#issuecomment-824686546), and let me know your thoughts. Thanks.

**Comment by cyChop** [comment]
Hi @jmooring ! Obviously, the warning is correct, but it was a surprising behaviour change.

> Although the current implementation of https://github.com/nicksnyder/go-i18n uses other as a fallback category when the correct category is not defined, it was never intended to be used that way. The other category is explicitly defined by the CLDR plural rules, and is an implicit fallback only when all other categories for a given language are defined.

This seems to be exactly what happens. And from the formalism of go-18n, it makes sense. I just went to [Hugo's multilingual documentation](https://gohugo.io/content-management/multilingual/#query-a-flexible-translation-with-variables) and see that I'm still using the old formalism, where precising the `one` or `other` was not mandatory.

For instance, I still have:

```yaml
- id: wordCount
  translation: This article has {{ .WordCount }} words.
```

instead of

```yaml
wordCount:
  other: This article has {{ .WordCount }} words.
```

**With this new approach, this issue is obsolete and may be closed.** I'll let the project contributors do it.

I just have one question for you, @jmooring , since you seem to know your way around go-i18n much better than me: is there a way to tell go-i18n explicitly to fall back to `other`? I hate duplicating, but the only way I can think of correcting this warning in my project would be the following:

```yaml
readingTime:
  one: {{ .Count }} min. reading
  other: {{ .Count }} min. reading
```

Thanks for having had a look at it!

**Comment by jmooring** [comment]
@cyChop

> is there a way to tell go-i18n explicitly to fall back to other?

No. 

If it falls back to `other` due to a missing translation, a warning message will be generated.

If it falls back to `other` due to a missing translation and `other` is not defined, the output will be an empty string, and a warning message will be generated.

**Comment by salim-b** [comment]
So, an issue I've noticed after upgrading to Hugo 0.83: When you want to use "simple" `i18n` without pluralization, it now depends on the language whether you have to define `other` or `one`!

When you call `i18n` without a count, say `i18n "read_more"`, `i18n` internally assumes a `.Count` value of `0`. That means, while you have to define `other` in `i18n/en.toml`...

```toml
[read_more]
other = "Read more"
```

...you'll have to define `one` in `i18n/fr.toml`...

```toml
[read_more]
one = "Lire la suite"
```

... in order to avoid the warning message:

```
WARN (...) Failed to get translated string for language "fr" and ID "read_more": message "read_more" has no plural form "one"
```

<sub>(The warning message is also suboptimal in talking of a `plural form "one"`... might be better to use a sentence like `has no cardinal form "[one|few|other|...]"`)</sub>

This is because the [Language Plural Rules](https://unicode-org.github.io/cldr-staging/charts/37/supplemental/language_plural_rules.html)  for `fr` are different than those for `en` (and most other european languages): For `en`, the `one` form is only used when [`i = 1 and v = 0` ](https://unicode.org/reports/tr35/tr35-numbers.html#Operands) but for `fr`, the `one` form is always used when `i = 0,1`.

---

Now while technically this seems all fine, it would be awesome if Hugo could make life easier for theme authors: If a translation is specified without an explicit cardinal form (what @cyChop called the "old formalism"), Hugo should not blindly assign it to `other` but rather respect Language Plural Rules and thus assign it to `other` for `en` but to `one` for `fr` etc.

What do you think, @jmooring?
