### ISSUE TITLE
Failed to extract shortcode: template for shortcode "callout" not found

### ISSUE THREAD

**Issue by zhi-peng-yang** [gohugoio/hugo#7850]
<pre>
$ hugo version
Hugo Static Site Generator v0.76.4/extended darwin/amd64 BuildDate: unknown\
</pre>

I only had this problem after updating my hugo (which is done automatic) from 0.75 to 0.76.4. Meanwhile, the deployment on netlify by 0.75.1 works as normal. The project can be found here:

https://github.com/zhi-peng-yang/zhipeng.yang.math 

Even deleting the callout module does not resolve this issue.

A snapshot of the bug report:

<img width="1082" alt="截屏2020-10-16 19 50 07" src="https://user-images.githubusercontent.com/60237900/96291850-fd36fa00-0fe8-11eb-893f-e4a00d66936b.png">

**Comment by bep** [comment]
Thanks for getting in touch, but it feels like this is a question  that would be better suited to the [Hugo Discussion Forum](https://discourse.gohugo.io/).  We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug. You may also find the answers you search for in [Hugo Documentation](http://gohugo.io/overview/introduction/).
