### ISSUE TITLE
Add `dateFormatTimeZone` function to allow formatting a date/time string from a specific timezone

### ISSUE THREAD

**Issue by virgofx** [gohugoio/hugo#7860]
Add a new function that internally utilizes Go's `time.ParseInLocation()` such that a date can be formatted from a dynamic `time`, `date`, and `timezone`. 

Specifically, allow a date string that does not contain any timezone information to parse and output a new `dateFormat` like string where the date/time is loaded from a specific timezone identifier (e.g. `America/Los_Angeles`).

Reference: #1882

**Comment by moorereason** [comment]
Thanks for jumping all over this issue with a PR; however... :smile:  I'm mulling over the API design.

I think I'd rather see us add an optional `location` parameter to `time.AsTime`.  Let me know if you see any flaws in my thinking.

Cc: @bep 

#### Proposed API

Go signature:
```go
func (ns *Namespace) AsTime(v interface{}, location ...interface{}) (interface{}, error)
```

Template signature:
```
time TIME [LOCATION]
```
Template usage:
```
{{ time "2015-01-21" }}
{{ time "2015-01-21" "America/Los_Angeles" }}
```
*We do [a trick](https://github.com/gohugoio/hugo/blob/b886fa46bb92916152476cfac45c7a5ee5e5820a/tpl/time/init.go#L41) to use the namespace `time` as an alias to `time.AsTime`.*

I think this would accomplish everything you're looking for.

#### Implementation Hints

Your first PR looked pretty good, so I'm hoping you'll take another stab at it if @bep is onboard with this proposal.  Here are my notes if you do:

1. As you probably noticed, `github.com/spf13/cast` doesn't provide a `ToTimeInLocation[E]` function, so for now we can roll our own solution (as you did in your existing PR).  We'll see if we can get upstream extended later.

1. If `len(location) == 0`, I'd just use `cast.ToTimeE` and return early.  See [`strings.FindRE`](https://github.com/gohugoio/hugo/blob/b886fa46bb92916152476cfac45c7a5ee5e5820a/tpl/strings/regexp.go#L25) for an example of how we use a variadic parameter for options (`limit` in that case).

1. Your previous PR failed the CI checks because you didn't `gofmt` the Go source files.

1. The documentation should point people to a list of valid location names.  According to the [Go time docs](https://golang.org/pkg/time/#LoadLocation), the list includes "UTC", "Local", or any valid location in the IANA Time Zone database.  The best list of those I could find is on [Wikipedia](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones).

**Comment by moorereason** [comment]
One clarification:  the Hugo limitation in view here is that you can't parse a time string in a non-default location.  That's the issue we're trying to solve.

Converting an existing `Time` object to another location is already supported.  Once you have a `Time` object in the templates, you have direct access to the Go stdlib `time.Time` API.  You should be able to do:

```
{{ $ny := $utc.In "America/New_York" }}
```
See https://golang.org/pkg/time/#Time.In.

**Comment by bep** [comment]
I agree with @moorereason  on this.

**Comment by moorereason** [comment]
I forgot that @bep has already sailed through these waters, and there be dragons: https://github.com/spf13/cast/pull/80.  Hmm.

**Comment by virgofx** [comment]
Gotcha. Thanks for the feedback. @moorereason Yes ... I didn't see the location support in cast so I rolled my own. I do see it in the PR mentioned but not yet merged o.O
