### ISSUE TITLE
Fix flaky integration tests on CI

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#7866]
```
ERROR 2020/10/21 07:25:56 Failed to get JSON resource "https://api.instagram.com/oembed/?url=https://instagram.com/p/BWNjjyYFxVx/&hidecaption=1": Failed to retrieve remote file: Bad Request
```

Also similar for the Twitter.

**Comment by moorereason** [comment]
I'm assuming this is a rate limit issue?  I wonder if it would it help to add backoff+retry options to the getJSON func.

**Comment by bep** [comment]
We're not adding stuff to `getJSON` -- that will soon (hopefully)  be replaced by a (hopefully) more robust `resources.GetRemote` (or something).

**Comment by onedrawingperday** [comment]
Finally!!

cc: @kaushalmodi

**Comment by kaushalmodi** [comment]
@onedrawingperday Thanks for tagging me here (and even remembering that I very much was troubled by that getJSON error).

**Comment by onedrawingperday** [comment]
@kaushalmodi You're welcome. I've also been beaten by this error myself and I followed the discussion back then between you and Bjørn Erik closely. So of course, I remembered.

**Comment by digitalcraftsman** [comment]
Due to failed HTTP requests the instagram short code has been removed from https://github.com/gohugoio/hugoBasicExample. However, approximately 20 whitelisted themes on www.themes.gohugo.io use a (customized) version of the https://github.com/gohugoio/hugoBasicExample that still include the instagram shortcode. Thus the demos for this themes can't be build.

As mentioned by Alexandros [here](https://github.com/gohugoio/hugo/issues/7228#issuecomment-714490456) the error can be suppressed for the whitelisted themes with an config option once Hugo 0.77.0 is released.

---

The actual reason why `getJSON` fails seems to be that the `instagram` shortcode is generating urls that point to a deprecated Instragram API endpoint. 

When using the `instagram` shortcode with id [BWNjjyYFxVx](https://www.instagram.com/p/BWNjjyYFxVx/) the shortcodes uses [this](https://github.com/gohugoio/hugo/blob/08e4f9ff9cc448d5fea9b8a62a23aed8aad0d047/tpl/tplimpl/embedded/templates.autogen.go#L394) template to construct the url https://api.instagram.com/oembed/?url=https://instagram.com/p/BWNjjyYFxVx. When opening it a notice informs you about the deprecation of the linked API endpoint.

**Comment by onedrawingperday** [comment]
Hello @digitalcraftsman 

> instagram shortcode is generating urls that point to a deprecated Instragram API endpoint.

The above merits its own issue in the main issues tracker.

Apparently Instagram is ending the last remaining public API endpoint.

The Instagram shortcodes will either need to be refactored or removed.

**Comment by digitalcraftsman** [comment]
Hello Alexandros,

I've added the information for context but created a new issue as suggested by you.
