### ISSUE TITLE
Js code built with the esbuild pipe is not minified

### ISSUE THREAD

**Issue by mpsq** [gohugoio/hugo#7939]
Tested with Hugo `0.78.1`.

The documentation states: 

> Note that you can also minify the final HTML output to /public by running hugo --minify.

Source: https://gohugo.io/hugo-pipes/minification/

This does not seem to be the case, when I use `hugo --minify`, the JavaScript bundle generated by `js.Build` is not minified, I have to set the flag manually in order for the minification process to kick in. 

Thank you

**Comment by bep** [comment]
Thanks for getting in touch, but it feels like this is a question  that would be better suited to the [Hugo Discussion Forum](https://discourse.gohugo.io/).  We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug. You may also find the answers you search for in [Hugo Documentation](http://gohugo.io/overview/introduction/).
