### ISSUE TITLE
The internal GA template does not work with the new analytics version

### ISSUE THREAD

**Issue by onedrawingperday** [gohugoio/hugo#7954]
The internal GA analytics template has been reported as non functioning with the [new Google Analytics version](https://support.google.com/analytics/answer/10089681).

Also see: https://discourse.gohugo.io/t/google-analytics-ga4-property-doesnt-work/29362

Related Issues: #7879 #7893

**Comment by debanjanbasu** [comment]
This needs to be addressed soon.

**Comment by flyinprogrammer** [comment]
It also should support CSP: https://developers.google.com/tag-manager/web/csp#enabling_the_google_tag_manager_snippet with a nonce variable

**Comment by djatwood** [comment]
Since analytics.js is not depreciated so I think we should support both UA-PROPERTY_ID<sup>analytics.js</sup> and G-MEASUREMENT_ID<sup>gtag.js</sup>. I'm assuming a simple `hasPrefix . "UA-"` and `hasPrefix . "G-"` should be enough to tell the difference.

 I will have to learn about implementing the same [privacy options](https://gohugo.io/about/hugo-and-gdpr/#googleanalytics) with gtag.

---
Anyone know why the functions are namespaced differently? There's `hasPrefix` and `strings.HasSuffix`.

**Comment by djatwood** [comment]
I forgot to mention my PR #8264

**Comment by onedrawingperday** [comment]
Since https://github.com/gohugoio/hugo/pull/8287 was merged I am closing this.
