### ISSUE TITLE
Update Hugo to 0.80 generate Fill error

### ISSUE THREAD

**Issue by kosssi** [gohugoio/hugo#8158]
Hello,

I generate a website with Hugo 0.79 everything is fine.
With the last version 0.80, I have an error :  `Fill: *resources.genericResource is not an image`
The source code is here https://git.weko.io/weko/cremeaux
I don't understand why, maybe it's a bug.

### What version of Hugo are you using (`hugo version`)?

Before
<pre>
$ hugo version
Hugo Static Site Generator v0.79.0-1415EFDC/extended linux/amd64 BuildDate: 2020-11-27T09:16:17Z
</pre>

After
<pre>
$ hugo version
Hugo Static Site Generator v0.80.0-792EF0F4/extended linux/amd64 BuildDate: 2020-12-31T13:46:18Z
</pre>

### Does this issue reproduce with the latest release?

yes

thanks for Hugo <3

**Comment by jmooring** [comment]
@kosssi:

I was able to reproduce the problem with v0.82 at your commit [9c3162fece](https://git.weko.io/weko/cremeaux/commit/9c3162fecef291785b7e617918b815e4bd2ed07c).

I was _unable_ to reproduce the problem with v0.82 at your next commit [00d79ea049](https://git.weko.io/weko/cremeaux/commit/00d79ea0491e40d872d3dad793f7725f8ad033bf).

It looks like you were trying to process PDF files in `content/viemunicipale/compte-rendus` as images, causing the `*resources.genericResource is not an image` error. You masked the problem by moving the PDF files to the `static` directory.

The real problem is here:
https://git.weko.io/weko/cremeaux/src/branch/master/layouts/partials/header.html#L6

```
{{ $image := default ($headless.Resources.GetMatch "*") (.Resources.GetMatch (default "*" .Params.image)) }}
```

The `*` glob pattern matches all files, regardless of file type. Use something like `**.jpg` instead. See: <https://gohugo.io/content-management/page-resources/#pattern-matching>.

In the future, please use the [forum](https://discourse.gohugo.io/) for questions and troubleshooting. We prefer to use GitHub for verified bugs and enhancements.

**Comment by kosssi** [comment]
Thanks you very much @jmooring and sorry for this error. Long life to hugo!
