### ISSUE TITLE
Make timestamp parsing more flexible

### ISSUE THREAD

**Issue by subsoap** [gohugoio/hugo#8285]
Currently timestamps seem to need to be in this format

2021-02-23T11:38:53-08:00

Other forms of timestamps could be detected / supported / automatically converted

5:08 PM Thursday, February 25, 2021

or

5:10 PM 2/25/2021

Or allow a timestamp format to be set in the config.

This would allow timestamps to be more flexible and human readable / writeable.

**Comment by moorereason** [comment]
For the record, the hugo docs about time formats is [here](https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference).  The underlying code for all supported formats are listed [here](https://github.com/spf13/cast/blob/8d17101741c81653ee960aa20f9febb31f1218aa/caste.go#L1243-L1266).  The entries referencing the Go `time` package can be seen [here](https://golang.org/pkg/time/#pkg-constants).

**Comment by subsoap** [comment]
Good to know, so timestamps grabbed from sites like http://timestampnow.com/ work.

**Comment by jmooring** [comment]
Here are examples of the timestamps that Hugo's [`dateFormat`](https://gohugo.io/functions/dateformat) function is able to parse. Unless otherwise noted, these are all string values.

### Date, Time, and Offset

```
05 Apr 21 14:31 -0700
05 Apr 21 14:31 PDT
2021-04-05 14:31:59 -07:00
2021-04-05 14:31:59 -0700
2021-04-05 14:31:59.111222333 -0700 PDT
2021-04-05T14:31:59-0700
Mon Apr 05 14:31:59 -0700 2021
Mon Apr 5 14:31:59 PDT 2021
Mon, 05 Apr 2021 14:31:59 -0700
Mon, 05 Apr 2021 14:31:59 PDT
Monday, 05-Apr-21 14:31:59 PDT
1617658319 (integer)
```

### Date and Time (No Offset)

```
2021-04-05 14:31:59
2021-04-05T14:31:59
Mon Apr 5 14:31:59 2021
```


### Date and Time (No Year, No Offset)

```
Apr 5 14:31:59.111
Apr 5 14:31:59.111222
Apr 5 14:31:59.111222333
Apr 5 14:31:59
```

### Date Only

```
05 Apr 2021
2012-04-05
```

### Time Only

```
2:31PM
```

**Comment by subsoap** [comment]
@jmooring  Some examples of what do not work:

```
12:52 PM 4/6/2021
12:53 PM Tuesday, April 6, 2021
```

These are from Notepad++ TextFX Insert Date & Time

**Comment by jmooring** [comment]
@subsoap 

When I upgraded NPP last year I learned that the TextFX plugin is not available for the 64-bit version . So I started using the PythonScript plugin instead. It turns out this is more flexible, allowing me to define as many formats as I need.

Short format (mapped to F5)

```
# C:\Users\joe\AppData\Roaming\Notepad++\plugins\config\PythonScript\scripts\InsertDateShort.py
import time
timeStr = time.strftime( '%B %#d, %Y' )
editor.addText( timeStr )
```

Long format (mapped to Ctrl + F5)

```
# C:\Users\joe\AppData\Roaming\Notepad++\plugins\config\PythonScript\scripts\InsertDateLong.py
import time
timeStr = time.strftime( '%Y-%m-%dT%H:%M:%S-07:00' )
editor.addText( timeStr )
```

Instructions here: <https://stackoverflow.com/a/38465954>

Notes

1. I hard-coded the offset (-07:00) in the long format because I couldn't get %z to work.
2. Make sure you restart NPP before trying to map your keyboard shortcuts.
