### ISSUE TITLE
Opengraph template locale-  fallback to site's locale param

### ISSUE THREAD

**Issue by coliff** [gohugoio/hugo#8296]
Currently the built-in Opengraph template only adds the `<meta property="og:locale" content="" />` meta tag to a page if the locale param is in the frontmatter of the page. It'd be great if no param was specified in the frontmatter then it used the locale param in the sites config instead. It could make maintenance easier (if you have a 200-page site in a single language you only need to define the locale in the site config).

Maybe something like this?

```go
{{- with .Params.locale }}<meta property="og:locale" content="{{ . }}" />
{{else}}
{{- with .Site.Params.locale }}<meta property="og:locale" content="{{ . }}" />
{{ end }}
```

cc @djatwood 

REF:
https://github.com/gohugoio/hugo/blob/master/tpl/tplimpl/embedded/templates/opengraph.html

**Comment by davidsneighbour** [comment]
This should be done because the Facebook documentation on that tag says "Defaults to en_US." - which is probably not what everyone wants as default if left empty. I would suggest:

```
{{- with .Params.locale }}<meta property="og:locale" content="{{ . }}" />
{{else}}
{{- with .Site.Params.locale }}<meta property="og:locale" content="{{ . }}" />
{{ else }}
<meta property="og:locale" content="en_US" />
{{ end }}
{{ end }}
```

**Comment by coliff** [comment]
I disagree. If, for example, a French-language site doesn't specify (forgets or doesn't know - or for whatever reason) a locale param on their site then they will specifically specify that their site is in American English. This would be bad. It'd be better to not specify it than specify the wrong value.

https://ogp.me/
`og:locale` isn't a required tag - so it'd be ok to leave it out.

**Comment by davidsneighbour** [comment]
"og:locale - The locale these tags are marked up in. Of the format language_TERRITORY. Default is en_US."

I understand that as "if it's not set it is assumed en_US". Maybe add a warnf instead of the default tag so that people using that partial will know that something is going on? With a link to the resulting documentation or this issue here.

**Comment by coliff** [comment]
I don't think it should add locale unless the user specifies it on the page or in the site config. It's not a required param. If you check Hugo's homepage with https://developers.facebook.com/tools/debug/?q=https%3A%2F%2Fgohugo.io%2F - it doesn't have any errors or warnings about the locale not being set.

**Comment by davidsneighbour** [comment]
I am not saying you are wrong, I am saying if Hugos website would be Chinese, Facebook would think it's en_US due to not having a og:locale tag. If that template is touched why not make it perfect with a quick notice if it's not set up properly?

**Comment by coliff** [comment]
Maybe a site scanning for Opengraph tags would fallback to the `lang` attribute on the html element `<html lang="">` tag? Not sure though...
I still don't think Hugo should give any warnings about an optional parameter not being specified.

**Comment by davidsneighbour** [comment]
I am just suggesting ;) I am not using the internal templates myself - mostly because Hugo does create my site, not my HTML :) The thumbs up on the starting post still stands.

**Comment by djatwood** [comment]
So I looked over the current situation with multilingual mode. I believe the opengraph template has been left behind with all the updates to multilingual support. Open Graph wants the locale specified with as `language_TERRITORY` but Hugo can't even produce this format right now.

Using this config
```toml
languageCode = "en-US"
defaultContentLanguage = "en_US"

[languages]
    [languages.en_US]
        title = "English site title"
    [languages.es_ES]
        title = "Spanish site title"
```

You can then access `page.Language`
```html
<!-- layouts/_default/baseof.html -->
<head>
<!-- This translation -->
{{ with .Language }}<meta property="og:locale" meta="{{ .Language.Lang }}">{{ end }}

<!-- Other translations -->
{{ range .Translations }}
<meta property="og:locale:alternate" content="{{ .Language.Lang }}" />
{{ end }}
</head>
```

> **.Language**  a language object that points to the language’s definition in the site config. .Language.Lang gives you the language code.


_[See docs](https://gohugo.io/variables/page/) `.Language` and `.Language.Lang` produce the same result but the documentation says to use the latter_


Produces this result:
```
public
| en_US/
| | index.html containing no body
|
| en_us/
| | content...
|
| es_es/
| | content...
```
With the locale all lower case.
```html
<meta content="es_es">
<meta property="og:locale:alternate" content="en_us">
```

I'm not sure what's the best way to go about fixing this. Hugo supports 2 different ways of translating content. Content directory `content/locale/` and `page.locale.md`. Maybe adding a territory param to the language config would be the easiest option. But - and I don't know if this is something that happens in the real world - what about translating the same language but to different territories?
```toml
[languages]
  [languages.es]
    territory = "ES"

**Comment by djatwood** [comment]
Okay fooling around some more and I've come up with this solution.

```toml
# config.toml
defaultContentLanguage = "en"
[languages]
    [languages.en]
        title = "English Site Title"
        locale = "en_US"
    [languages.es]
        title = "Spanish Site Title"
        locale = "es_ES"
```
```html
<!-- baseof.html or opengraph.html -->

{{ with .Language.Params.locale }}
<meta property="og:locale" content="{{ . }}">
{{ end }}

{{ range where .Translations "params" "locale" }}
<meta property="og:locale:alternate" content="{{ .Language.Params.locale }}" />
{{ end }}
```

Produces:
```html
<meta property="og:locale" content="es_ES">
<meta property="og:locale:alternate" content="en_US">
```

This way it only adds languages with the locale specified.

**Comment by bep** [comment]
I think this should do:

```
{{ with .Param "locale" }}
<meta property="og:locale" content="{{ . }}">
{{ end }}
```

Also, we should probably also add `Locale` (if that's the name we go for, I think it's working?) on `Language`, so we could do:


```
{{ with .Language.Locale }}
<meta property="og:locale" content="{{ . }}">
{{ else }}
{{ with .Param "locale" }}
<meta property="og:locale" content="{{ . }}">
{{ end }}
```

We currently have `Lang` which many uses for this (which is basically the language key/name) set in config, but that may be different than the string you want in `locale`.

Or something.

**Comment by djatwood** [comment]
@coliff any chance to review the changes?

**Comment by bep** [comment]
Sorry for the delayed response.

I do agree that this needs to be fixed, and I do agree (as in the PR that was opened against this, #8306) that the configuration needs to live on `Language`. #8306 adds a new `Language.Locale` attribute. I think we have templates today that use the `Lang` value where you currently suggest using a new `Locale`, and we certainly have lots of Go code using `Lang`.

With #8306 we would get: 

```toml
[languages]
    [languages.en]
        locale = "en_US"
````

==>

```toml
lang="en"
locale="en_US"
```

So, before we do this we need to determine if,

1. Do we need a new field and is `locale` a fitting name?
2. Why not use `lang`, the below TOML should work ?
3. If we add `locale` should we then use that in every place where `lang` is currently used?

```toml
[languages]
    [languages.en_US]
```

/cc @jmooring

**Comment by jmooring** [comment]
#### Terminology 

Term|Example|Notes
:--|:--|:--
language|`en`|
region|`US`|
locale|en-US|Also known as a `language tag` per [RFC 5646](https://www.rfc-editor.org/rfc/rfc5646.html)

#### Overview

From a site author's perspective, Hugo's language key (e.g., the `en` in `[languages.en]`) currently has four primary roles:

1. It is prepended to the path portion of the published site (e.g., `https://example.org/en/articles/foo`)
2. It links the site with a translation file in the `i18n` directory. To properly pluralize a translation, the language key must match one of the _languages_ in:
<https://github.com/nicksnyder/go-i18n/blob/main/v2/internal/plural/codegen/plurals.xml>
3. It is used to localize dates, numbers, percentages, and currencies. To properly localize these values, the language key must match one of the _locales_ in:
<https://github.com/gohugoio/locales>
4. It is used to determine collation when sorting. This is relatively new, and I am not yet familiar with the implementation details. I imagine it is dependent on _language_, not _locale_, but I could be wrong.

When we read the language key from the site configuration, we convert it to lower case, and you do not have access to the original value from the templates.

If I want an English language site localized to England, Wales, and Scotland, I must set the language key to `en-gb` or `en-GB` (hyphens, not underscores). 

- If I just use `en` the translation/pluralization will be correct (depends on _language_), but dates, numbers, percentages, and currencies will not be correctly localized (depends on _locale_).
- If I use `en_gb` or `en_GB` (underscores), dates, numbers, percentages, and currencies will be localized correctly, but the corresponding translation file in the `i18n` directory is not used.

In some configurations the language key is just the _language_ (e.g., `en`) while in other configurations it is the _locale_  (e.g., `en-GB`).

And at some point in the distant past we added `.Site.LanguageCode`, typically set in site configuration to something like `en-us`, `en-US`, `en_US`, etc.  This isn't a language code; it's a _locale_. Currently, in the Hugo code base, I think it is only used twice:
- <https://github.com/gohugoio/hugo/blob/master/tpl/tplimpl/embedded/templates/_default/rss.xml#L19-L20>
- <https://github.com/gohugoio/hugo/blob/master/tpl/tplimpl/embedded/templates/alias.html#L2>

#### Example configuration

```
defaultContentLanguage = 'en-gb'
defaultContentLanguageInSubdir = true

[languages.en-gb]
  contentDir = 'content/english-in-gb'
  languageCode = 'en_GB'  # locale
  languageName = 'English (GB)'
  weight = 1

[languages.en-us]
  contentDir = 'content/english-in-us'
  languageCode = 'en_US'  # locale
  languageName = 'English (US)'
  weight = 2
```
#### Recommendations

Now (this issue):
- Use `.Site.LanguageCode` with a fallback to `Site.Language.Lang`. 
- Make sure other embedded templates do the same (alias, rss, etc.).

Later:
- Create a `locale` key under `languages`. If this key is not defined in site configuration, read the value from `.Site.LanguageCode`.
- Remove `.Site.LanguageCode` from the documentation (deprecate).
- Update all internal templates to use `.Site.Language.Locale` instead of `.Site.LanguageCode`.

Much later:
- Allow independent control of translation, localization, and URL path prefix for each site. That would allow a site author to have one translation file for two sites in different locales, and use whatever URL path prefix they want.
