### ISSUE TITLE
Localhost is blank

### ISSUE THREAD

**Issue by Oxko** [gohugoio/hugo#8309]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
Hugo Static Site Generator v0.80.0-792EF0F4 windows/amd64 BuildDate: 2020-12-31T13:37:57Z
</pre>

### Does this issue reproduce with the latest release?
yes, i would assume so, as it had to update, closed and since it reopened localhost1313 has been blank. 
Tried to install previous versions, did not help either. Can you advise?

**Comment by bep** [comment]
Thanks for getting in touch, but it feels like this is a question  that would be better suited to the [Hugo Discussion Forum](https://discourse.gohugo.io/).  We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug. You may also find the answers you search for in [Hugo Documentation](http://gohugo.io/overview/introduction/).
