### ISSUE TITLE
Cache partials from within partials

### ISSUE THREAD

**Issue by davidsneighbour** [gohugoio/hugo#8314]
Specific Use Case:

Having a partial that echoes SVG-icons currently requires the icon title to be called twice so it can be cached, like this:

```
{{- partialCached "bsicon" "chevron-right" "chevron-right" -}}
```

It would be nice to have some form of:

```
{{- partial "bsicon" "chevron-right" -}}
```

and then in the partial some form of:

```
{{ cache_identificator := . }}
```

for the "chevron-right" part. 

Basically some form of "internal" definition of a caching parameter for whatever is commited as parameter to the partial.

**Comment by moorereason** [comment]
#### Existing Behavior

The way this currently works:

```
partialCached NAME CONTEXT [VARIANT]
```

1. When no variant is passed, the cache key is (essentially) `{NAME, nil}`.
1. When variant is passed, the cache key is `{NAME, hash(VARIANT)}`.
1. The CONTEXT is only used to render the partial prior to caching (`partial NAME CONTEXT`).  It's not used as a part of the cache key.
1. The partial never sees the VARIANT value.  It's only used for the cache key.

####  Requested Change

You're asking that the first point above be changed to:

1. When no variants are passed, the cache key is `{NAME, hash(CONTEXT)}`.

This would mean that point 3 would no longer be true since it would place CONTEXT into the cache key.

Is this correct?

#### Thoughts

This could potentially be a breaking change if a user is currently passing different CONTEXT values to a `partialCached` call.  Right now the first completed rendering is cached.  That use case is probably a bug on the user's part, but the existing caching behavior may be hiding it.

**Comment by moorereason** [comment]
True.  Plus, getting a hash of `.` for every `partialCached` call could be really expensive (the hash must happen on each call).
