### ISSUE TITLE
Problem of <p> tag generation

### ISSUE THREAD

**Issue by uPagge** [gohugoio/hugo#8323]
I recently checked one of my articles for html validity and noticed many errors related to p tag

Let's say I have a text like this. A heading, followed by a text with a link, a picture, and then a list.
![изображение](https://user-images.githubusercontent.com/40397740/111028122-b289a480-8405-11eb-9997-f738cdeaeb74.png)

This is how it renders in html

![изображение](https://user-images.githubusercontent.com/40397740/111028155-ecf34180-8405-11eb-90f7-afd7e7a785a3.png)

Some incomprehensible indentation and closing p tag where is it from there?

-- -- -- -- --
hugo version: Hugo Static Site Generator v0.78.2-959724F0/extended linux/amd64 BuildDate: 2020-11-13T10:16:23Z

**Comment by uPagge** [comment]
As far as I understand, according to the specification, there should be nothing in the p block and the problem is in the div, but I would like to leave this div

**Comment by uPagge** [comment]
Yes, the problem went away when I removed the div. But what about figure and figcaption

**Comment by uPagge** [comment]
![изображение](https://user-images.githubusercontent.com/40397740/111028597-a4895300-8408-11eb-8fd1-042c1a439fac.png)

It might be better not to wrap the image in a p tag if I use _markup / render-image.html. If I need to, I will wrap it in the p tag there

**Comment by davidsneighbour** [comment]
Separate the image via empty lines from the list and the paragraph above. THAT is the proper way to have a standalone image. The way you did it was inside of the paragraph above, on a new line. The closing p comes from the opening p in the paragraph. It's red because your render-image-hook created another block-level element inside of a block-level element. All the "behaviour" are proper results given the markdown you are using in your sample. Work more with empty lines to separate content. And probably have a look at your render hook. It seems it is unable to render inline images this way. I would work with a span instead of a div and then give it an inline-block display attribute in CSS. 

This by the way is what was noted as "please open a post in discourse.gohugo.io for support requests" when you created the issue. Over there help is faster and we can work out issues before they are declared a bug.
