### ISSUE TITLE
Content Security Policy header breaks code samples

### ISSUE THREAD

**Issue by davidgs** [gohugoio/hugo#8402]
### What version of Hugo are you using (`hugo version`)?

<pre>
hugo v0.81.0+extended darwin/amd64 BuildDate=unknown

</pre>

### Does this issue reproduce with the latest release?
Yes. 

All of the code formatting for 
```go
some := getGo()
```
for code blocks is done via in-line styles. Unless you set your Content Security Policy header to allow `unsafe-inline` styles, code won't render correctly. 

`unsafe-inline` is very much **not** recommended.

**Comment by jmooring** [comment]
@davidgs You can use a style sheet instead of in-line styles.

config.toml

```
[markup.highlight]
noClasses = false
```

From the root of your project:

```
mkdir -p assets/css
hugo gen chromastyles --style=monokai > assets/css/syntax.css
```

Then in `<head>` something like:

```
{{ $r := resources.Get "css/syntax.css" | minify | fingerprint }}
<link rel="stylesheet" href="{{ $r.RelPermalink }}" integrity="{{ $r.Data.Integrity }}">
```

References:
- <https://gohugo.io/getting-started/configuration-markup#highlight>
- https://gohugo.io/content-management/syntax-highlighting/#generate-syntax-highlighter-css

In the future please use the forum (https://discourse.gohugo.io) for questions and troubleshooting. We prefer to use GitHub for verified bugs and vetted enhancements. Thanks.
