### ISSUE TITLE
Improve image filters API

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#8439]
Given:

```html
{{ $img := $original.Resize "400x300 q55" }}
{{ $img = $img | images.Filter (images.GaussianBlur 6) (images.Pixelate 8) }}
```

There are currently some problems with the above:

1. The image gets encoded twice
2. There is no way to control the encoding (e.g. quality) for the second operation.
3. If you want the end result encode to different formats, you need to repeat the image processing for each target format (e.g. JPEG and WEBP)

I suggest that we 

* add a target options argument to `images.Filter` which can be a string (e.g. `webp`) or a map (which also allows setting quality settings)
* Export the resize functions (Resize, Fill, Fit) as filters.

This way you can do:

```
{{ $img = $img | images.Filter (images.Resize 400 300)  (images.GaussianBlur 6) (images.Pixelate 8) (images.EncodeTo "webp")  }}
```

I'm tempted to also use the same `images.Filter` to return a slice if multiple `images.EncodeTo` arguments is passed, e.g.:

```
{{ $imgages := $img | images.Filter (images.Resize 400 300)  (images.GaussianBlur 6) (images.Pixelate 8) (images.EncodeTo "webp")  (images.EncodeTo "jpeg")  }}
```

But it's probably best to just add a new function, e.g.:

```
{{ $imgages := $img | images.FilterAll (images.Resize 400 300)  (images.GaussianBlur 6) (images.Pixelate 8) (images.EncodeTo "webp")  (images.EncodeTo "jpeg")  }}
```

Feedback welcome, @jmooring @moorereason @onedrawingperday and gang.

**Comment by onedrawingperday** [comment]
> The image gets encoded twice

Yes. 've been using the image filters to colorise some thumbnails and I noticed the resized yet not colorised thumbnails under the `resourceDir`.

>But it's probably best to just add a new function, e.g.:
>
>`{{ $imgages := $img | images.FilterAll (images.Resize 400 300)  (images.GaussianBlur 6) (images.Pixelate 8) (images.EncodeTo "webp")  (images.EncodeTo "jpeg")  }}`

I agree that it is  better to add the new function `images.FilterAll` instead of adding arguments to the existing one.

**Comment by jmooring** [comment]
Can Rotate be exported as well?

Can Rotate be exported as well?

I assume the operations are performed in the sequence I provide. So if I wanted to (for whatever reason) I could encode, then rotate, then resize?



x

This behaves kind of like pipes, but not quite. Just wondering if users would expect something like this instead?

```
{{ $img = $img | images.Resize 400 300 | images.Rotate 270 | images.EncodeTo "webp" }}
```

**Comment by bep** [comment]
>Can Rotate be exported as well?

Yes it can.

>I assume the operations are performed in the sequence I provide. 

Yes.

>{{ $img = $img | images.Resize 400 300 | images.Rotate 270 | images.EncodeTo "webp" }}

Yes, that would be nice, and I will think long and hard about it. That said, the nice thing about thinking about the filters as lists is that you can reuse them, e.g.:

```html
{{ $commonFilters := slice  (images.GaussianBlur 6) (images.Pixelate 8) }}
{{ $image := $img.Filter (images.Rotate 90) $commonFilters }}

```

**Comment by onedrawingperday** [comment]
Regarding the proposed `images.EncodeTo` please consider adding a setting for image quality.

For example 

`images.EncodeTo "q70 webp"`


cc:

**Comment by MartinHotmann** [comment]
May I add some more infos as I was the creator of this topic [IMAGES / WEBP just convert solely](https://discourse.gohugo.io/t/images-webp-just-convert-solely/32653)

I like this issue as it adresses the core problem, as the Image processing API peobably should be improved.

I think combining these all things into one function "`image.process`" would be clever. Then all (resize, filter, convert, quality, edit) functuions can be combined into one function which applies what needs to be done. Also the name `resize` is a little confusing because it does way more then resizing which can me misunderstood.



`{{ $img := $original.Process "400x300 q55" }}`

basically is:

`{{ $img := $original.Resize "400x300" }}` 
&&
`{{ $img := $original.Compress "400x300 q55" }}` OR `{{ $img := $original.Optimize "400x300 q55" }}`

I think people (like myself) want more flexibility like:
1. just resizing
2. just changing quality
3. just converting
4. just applying filters

I for myself can think of using this image.processor in this way:

`{{ $img := $original.Process "680x800 q100 webp" }}`
OR
`{{ $img := $original.Process "q100 webp" }}`

The processor can automatically detect what should be done:
1. if dimensions/numbers are given like `680x` or `680x800` = RESIZE
2. if quality or filesize is given like `q100` or `70kb` = COMPRESSION / OPTIMIZATION
3. if a known minetype is given like `webp`, `jpeg`, `avif`, `png` = CONVERT
4. filters etc etc etc

For the mentioned filters:
I like them they in my vision can be realised like this:

I want the same picture resized in quality 70 and in these three formats: `webp`, `png`, `avif` and some filter should be applied

`{{ $imgTemp := $original.ImageTemplate "400x300 q70  GaussianBlur6 Pixelate8" }}`
`{{ $img := $imgTemp.Process "webp" }}`
`{{ $img := $imgTemp.Process "png" }}`
`{{ $img := $imgTemp.Process "avif" }}`

The function **`ImageTemplate`** shall keep the resized and decoded original-Image in Cache and just encodes it on the final `$imgTemp.Process` call. Just then the filters and settings apply. The good thing about this: you also just have to decode the image once.

You also should be able to overwrite other settings from the ImageTemplate like:
`{{ $imgTemp := $original.ImageTemplate "400x300 q70  GaussianBlur6 Pixelate8" }}`
`{{ $img := $imgTemp.Process "webp q100" }}`
`{{ $img := $imgTemp.Process "png  GaussianBlur0" }}`
`{{ $img := $imgTemp.Process "1200x avif Pixelate2" }}`

Goal is it to have all needed informations at the end, when the .Process function is called and all functions intelligently applied that are needed, but also be able just to convert or just to apply a single function is needed.
