### ISSUE TITLE
Add Permalink option for section pages

### ISSUE THREAD

**Issue by writeonlycode** [gohugoio/hugo#8523]
I have something like the following option in the config.toml:

```
[permalinks]
posts = "/new-posts/:filename/"
```

If I visit `http://localhost:1313/new-posts/post-name/` I get the intended page. But if I visit `http://localhost:1313/new-posts/` I don't get the list page, as I would expect. Instead, I get nothing at all.  I still have to go to `http://localhost:1313/posts/` to get the list page.

The version I'm using:

```
hugo v0.83.1+extended linux/amd64 BuildDate=unknown
```

I'm not sure if this behavior is intended. But it would be a good idea to have the ability to change the URL of the list pages using the permalinks option as well. Right now, I have to add the `url` parameter in the front matter of the `_index.md` to make the list page have the different url.

**Comment by writeonlycode** [comment]
I don't really know how it works behind the scenes. But we already have the ability to change the URL of list pages. We just have to use the `url` parameter in their front matter. The "problem" I'm having is that I want to change the whole folder to a different URL, so, on top of adding the `permalinks` option, I also have to add the `url` in all `_index.md` files in that folder and subfolders. The proposal would be to have an option to add to the config.toml that does this job of "adding the `url` option to all list pages". Not a huge problem really, but it would be convenient.

**Comment by bep** [comment]
So, on the technical side this isn't a problem. 

But it's a permalink config, so they should be ... permanent. And the only permanent part of a section is the ... section path. 

Given 2 common  examples (assuming no date is set in section front matter):

```
[permalinks]
  "posts" = "/:year/:month/:filename/"
```

```
[permalinks]
  posts = "/:06/:1/:2/:title/"
```

How stable would the above be? And would it be a good URL?

**Comment by bep** [comment]
@writeonlycode yes, something like that could work, but we need to somehow rework the existing `permalinks` struct in a backwards compatible way (we're not adding something ... else)... I suggest we somehow use the page `Kind`. I'm not sure if this is even valid TOML, but:

```toml
[permalinks]
[permalinks.section]
posts = "/some/new/path/"
[permalinks.page]
posts = "/:06/:1/:2/:title/"
```

**Comment by writeonlycode** [comment]
That looks good! And it is be valid TOML as far as I can see. I suppose the assumption should be that if no kind is specified, it defaults to single pages, so the following two should be equivalent:

```
[permalinks]
posts = "/:06/:1/:2/:title/"
```

```
[permalinks]
[permalinks.page]
posts = "/:06/:1/:2/:title/"
```

In this way, it will be backwards compatible. And in addition to those, we could have the `section` option, to accommodate the new behavior:

```
[permalinks]
[permalinks.section]
posts = "/some/new/path/"
```

This looks like a good way to go!

**Comment by BenSouchet** [comment]
Another way / syntax to handle the `section` case would be that the value of the keys in `[permalinks]` can be either a string `""` or an array `["", ""]`.

If an array is specified :
- the first string define the path of `page` (or `term` if it's a taxonomy).
- The second define the `section` path.

Current version:
```toml
[permalinks]
posts = "/:06/:1/:2/:title/"
```

Proposition:
```toml
[permalinks]
# Classic way
categories = "/projects/:slug/"
# Advance way to define also the section path
posts = [ "/:06/:1/:2/:title/", "/articles/" ]
```

**Comment by istr** [comment]
This would be very helpful, indeed. I am facing the same situation in a multilingual setup.
At least there would be only _one_ place to define the translated section name.
Currently I have to define the translation both in the configuration for the pages and in the list page in the `url` frontmatter entry.

config.yml
```yaml
languages:
  de:
    permalinks:
      offer: /angebot/:slug/
```

offer/_index.md
```yaml
---
weight: 30
title: Angebot
url: /angebot/
---
```

This is doable, but shifts parts of the translation into the configuration, which is not optimal.

For multilingual content management it is _way_ easier to keep the path and filenames untranslated and translate the _target_ only. One of the reasons for that is that you need lots of `translationKey` entries if you simply translate the section path in the file system. The second reason is that most tools are capable of translating _file contents_ only, but not _file paths_. In these scenarios the limitation that the _target_ of a section cannot be changed at build time in hugo makes content maintenance much more complicated.

The translation tools I am aware of are capable of translating frontmatter and content (_file content_), but not the configuration. And they cannot translate path segments in the file tree of the generated output (_file path_).

Having that said, it would be even better to have an option where the `url` of list pages is simply inherited for all children, so _effectively_ a means to set _permalink_ from _frontmatter_ for list pages _and_ the children. But this would be a different _Enhancement_ (obviously of the sort that would change a _fundamental_ design decision as per https://gohugo.io/content-management/sections/) and I absolutely understand that these are not accepted these days.

+1 for @BenSouchet 's proposal, because this structure keeps the multiple options in one place _per section_.

**Comment by ardacarofficial** [comment]
> 

It makes a lot of sense that way. It would be great if this problem is fixed with a new update.

**Comment by ardacarofficial** [comment]
> That looks good! And it is valid TOML as far as I can see. I suppose the assumption should be that if no kind is specified, it defaults to single pages, so the following two should be equivalent:
> 
> ```
> [permalinks]
> posts = "/:06/:1/:2/:title/"
> ```
> 
> ```
> [permalinks]
> [permalinks.page]
> posts = "/:06/:1/:2/:title/"
> ```
> 
> In this way, it will be backwards compatible. And in addition to those, we could have the `section` option, to accommodate the new behavior:
> 
> ```
> [permalinks]
> [permalinks.section]
> posts = "/some/new/path/"
> ```
> 
> This looks like a good way to go!

It makes a lot of sense that way. It would be great if this problem is fixed with a new update.

**Comment by omerfdmrl** [comment]
any update?

**Comment by jhvanderschee** [comment]
I would love this feature. I like this solution: https://github.com/gohugoio/hugo/issues/8523#issuecomment-1192894337.

**Comment by macdweller** [comment]
I'll add another use case for this FWIW:

I'm currently working with the mechanism espoused in [this discussion](https://discourse.gohugo.io/t/29161).  After jumping through a few hoops (mostly media related), it works fairly well -- except that I've also set up non-default permalinks, and none of my multi-page posts appear in the correct location unless I deliberately configure their front matter, which is very inconvenient.

I can see other potential uses, but this is the concrete one I'm fighting with *literally right now*.  😀

**Comment by jhvanderschee** [comment]
It is a daily fight for me, as most of my Hugo websites are multilingual and my front matter is accessible to my clients/content editors. Therefore I would love to have a way to configure this properly.

**Comment by mproyyan** [comment]
> @writeonlycode yes, something like that could work, but we need to somehow rework the existing `permalinks` struct in a backwards compatible way (we're not adding something ... else)... I suggest we somehow use the page `Kind`. I'm not sure if this is even valid TOML, but:
> 
> ```toml
> [permalinks]
> [permalinks.section]
> posts = "/some/new/path/"
> [permalinks.page]
> posts = "/:06/:1/:2/:title/"
> ```


has this been implemented yet?

**Comment by ardacarofficial** [comment]
> > @writeonlycode yes, something like that could work, but we need to somehow rework the existing `permalinks` struct in a backwards compatible way (we're not adding something ... else)... I suggest we somehow use the page `Kind`. I'm not sure if this is even valid TOML, but:
> > ```toml
> > [permalinks]
> > [permalinks.section]
> > posts = "/some/new/path/"
> > [permalinks.page]
> > posts = "/:06/:1/:2/:title/"
> > ```
> 
> has this been implemented yet?

No, just a suggestion. If developers want to make this feature, they will be inspired by the ideas here. Ultimately, if the update comes, it's up to the developer to code this solution.

**Comment by istr** [comment]
@Mai-Lapyst I think that a PR would be highly welcome.

**Comment by Mai-Lapyst** [comment]
> @Mai-Lapyst I think that a PR would be highly welcome.

@istr Have created one; you can test it out if you want.
