### ISSUE TITLE
Livereload does not refresh pages from the /static area

### ISSUE THREAD

**Issue by crisperdue** [gohugoio/hugo#8543]
The "hugo server" command notices changes to files in the /static area and rebuilds the site as needed. Most pages refresh via livereload when the server rebuilds, but if the page source is under /static, the server does not inject the livereload code into it and it does not automatically refresh.

It would be desirable to inject the livereload script code into these pages as well.

I can create a small repo to demonstrate the situation if desired.

### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.82.1-60618210+extended darwin/amd64 BuildDate=2021-04-20T11:02:50Z VendorInfo=gohugoio
</pre>

### Does this issue reproduce with the latest release?
Yes

**Comment by davidsneighbour** [comment]
The `static` folder is for static files. Meaning they don't change. Hugo adds the livereload server snippet only in pages it CREATES, static files are only copied. You will have to somehow create an output format that will take the content from a folder like static and outputs them each time, so that Hugo adds anything to it.

**Comment by crisperdue** [comment]
Yes, I have assumed that these are the facts of the situation.  I would be happy if someone could mark this issue as an enhancement request.
