### ISSUE TITLE
Shortcode scratch side-effects are lost during live reload

### ISSUE THREAD

**Issue by EmpireJones** [gohugoio/hugo#8707]
### What version of Hugo are you using (`hugo version`)?

<pre>
0.84.1

</pre>

### Does this issue reproduce with the latest release?

Yes

### Issue Description

To reproduce:
- In a shortcode, write to page scratch
- Via a partial called from a layout file, read the scratch data
- Run `hugo server` (i.e. with live reloading)
- Modify some files, such as a layout file or partial for a page/post

Result:
- The page’s scratch gets cleared, but side effects from shortcodes don’t get re-run, causing the partial to not see the scratch data until the next full build.

Expected:
- Shortcodes and side effects should re-run, if scratch is cleared, or don't clear the scratch data

---

I made a simple repo for testing on the scratch_issue branch at: https://github.com/EmpireJones/hugoBasicExample/tree/scratch_issue

---

### First Load (summary is generated from page's scratch):
![image](https://user-images.githubusercontent.com/15959998/123578165-14d69d00-d78a-11eb-97b1-b301a89dbbce.png)

### After change occurs (summary is generated from page's scratch - but has no data):
![image](https://user-images.githubusercontent.com/15959998/123578248-43ed0e80-d78a-11eb-8c01-51896aae2114.png)
---

https://github.com/gohugoio/hugo/issues/8255 seems similar, but I don't think it's discussing the exact same thing.

**Comment by gj52** [comment]
Had a "fight" with this problem in the last two days.

Want to use SVG sprites references in the page, saving the needed sprites in a scratch map, to include the sprite at the end of the page. Must set scratch deep in called partials and process it from baseof.html ( with a partial ).

Please don't push it to later versions, it is open  for 18 months.

**Comment by bep** [comment]
So, I fighted with this myself some time ago, and figured out that I couldn't change the current behaviour without breaking stuff, so I added a new scratch variable.

Now there are:

```
.Store
.Scratch
```

On `Page`. The `.Store` will never be erased.

**Comment by gj52** [comment]
Thanks, nothing in the DOCS about .Store, looked in the source.
Seems not to work in lists templates.   
This is the place where the sprites can have a big space impact.

**Comment by bep** [comment]
>Seems not to work in lists templates.

It's a new method on the `Page` interface, so it should work everywhere.

Also, I'm working on a revised documentation with a complete reference section as I'm writing this.

**Comment by jmooring** [comment]
> I made a simple repo for testing on the scratch_issue branch at:
> https://github.com/EmpireJones/hugoBasicExample/tree/scratch_issue

I can reproduce the problem using this example with v0.101.0 and earlier.
With [v0.102.0](https://github.com/gohugoio/hugo/releases/tag/v0.102.0) and later there are no problems.

There were 3 commits in v0.102.0 that affected LiveReload:

- commands: Fix embed in livereload.go https://github.com/gohugoio/hugo/commit/3fefea06b884ff905509f5854cb13bc54d092f38 
- livereload: Inject script without head or body tag https://github.com/gohugoio/hugo/commit/b017f7cb0136ee33f5d19749a15bf3365a991ac5
- Externalise and embed livereload.js string https://github.com/gohugoio/hugo/commit/21562e3aad2ea461073f672fc83c5c897bfcf556

For anyone stumbling across this in the future...

1\) Use [`.Page.Store` ](https://gohugo.io/methods/page/store/) instead of [`.Page.Scratch` ](https://gohugo.io/methods/page/scratch/)

> The Store method on a Page object creates a persistent [scratch pad](https://gohugo.io/getting-started/glossary/#scratch-pad) to store and manipulate data. In contrast with the [Scratch](https://gohugo.io/methods/page/scratch/) method, the scratch pad created by the Store method is not reset on server rebuilds.

2\) Make sure that the content is rendered before reading the Scratch/Store. For example, if you need a Scratch/Store value at the top of a template, before the content has been rendered, force content rendering with something like:

```text
{{ $noop := .WordCount }}
{{ .Store.Get "foo" }}
```

There are several methods you can call to force content rendering. See [this FAQ](https://gohugo.io/troubleshooting/faq/#which-page-methods-trigger-content-rendering).
