### ISSUE TITLE
transform.Plainify should return template.HTML instead of a string

### ISSUE THREAD

**Issue by richtera** [gohugoio/hugo#8732]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.84.0+extended linux/amd64 BuildDate=unknown
</pre>

### Does this issue reproduce with the latest release?

This is the latest release.

When using `plainify` hugo many times does the wrong thing. I realize that this is a feature, but I wonder if there is a better way to do it. Specifically, if the HTML contains any HTML entities `plainify` returns the plain HTML with the entities but not marked as a HTML safe string. So the `plainify` output for HTML like `<div>This &amp; that</div>` will be `This &amp; that`. Now it's easy to pipe it through `safeHTML` or `markdownify` or `htmlUnescape` to solve the problem, but it seems `plainify` should probably include an automatic `htmlUnescape` or at least mark the output as HTML safe.
This is a petty kind of thing, but in our code, we always must do `plainify | htmlUnescape` and whenever we forget it the entities are shown on the screen. Seems cumbersome.

**Comment by davidsneighbour** [comment]
You should open that in the discourse instead of here. 

Regarding the issue at hand: I think it's because of the security model of Golang templates. Go expects the developer to make everything safe, so plainify can't just do an html unescape or mark the string as safe. I think it was recently only that script and style tags were removed by plainify. Lot's of hijinks would have been possible if Go just assumes that the string is safe. 

See here: https://golang.org/pkg/html/template/#hdr-Security_Model (the whole chapter is an interesting read)

**Comment by richtera** [comment]
Yes I don't like the safeHTML either, maybe to include htmlUnescape would be safer and useful. What is the current use case for plainify? In my code 100% of my plainify calls have to be followed by one of the other filters. Maybe there should be a new method to extract plain text from html and return it as unescaped string rather than messing with plainfy.

**Comment by jmooring** [comment]
These transformation functions return `template.HTML`

- transform.Emojify
- transform.Highlight
- transform.Markdownify

I think it makes sense to add `transform.Plainify` to the list.
