### ISSUE TITLE
0.87.0 Blackfriday deprecation warning should go to STDERR, not STDOUT

### ISSUE THREAD

**Issue by jgreely** [gohugoio/hugo#8864]
Printing the new warning message to STDOUT interferes with scripts that parse the output of commands like `hugo list expired`. It should go to STDERR.

```
$ hugo list expired 2> /dev/null
WARN 2021/08/06 16:21:23 markup.defaultMarkdownHandler=blackfriday is deprecated and will be removed in a future release. See https://gohugo.io//content-management/formats/#list-of-content-formats
content/post/0025/002523.md,2017-10-15T00:00:00Z
```

### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.87.0+extended darwin/amd64 BuildDate=unknown
</pre>

### Does this issue reproduce with the latest release?

Yes

**Comment by ptgott** [comment]
This happens because the [`helpers.Deprecated`](https://github.com/gohugoio/hugo/blob/32569285c181c8798ef594c12d3cfd7f9a252a04/helpers/general.go#L390-L401)  function involves making a call to one of two loggers initialized with [`NewBasicLogger`](https://github.com/gohugoio/hugo/blob/022c4795510306e08a4aba31504ca382d41c7fac/common/loggers/loggers.go#L222-L225): 

```go
// NewBasicLogger creates a new basic logger writing to Stdout.
func NewBasicLogger(t jww.Threshold) Logger {
	return newLogger(t, jww.LevelError, os.Stdout, ioutil.Discard, false)
}
```

We could flip `os.Stdout` to `os.Stderr`, but since most of the other `New[A-Za-z]+Logger` functions in the `loggers` package wrap `NewBasicLogger`, and are used throughout the codebase, I'm not sure what kinds of unintended effects that would have.

What do you think, @bep?

**Comment by jmooring** [comment]
No longer relevant. Blackfriday was removed with https://github.com/gohugoio/hugo/pull/9945. If your site configuration contains this:

```text
[markup]
defaultMarkdownHandler = 'blackfriday'
```

Hugo throws this error:

```text
ERROR 2023/05/18 14:24:28 markup: Configured defaultMarkdownHandler "blackfriday" not found. Did you mean to use goldmark? Blackfriday was removed in Hugo v0.100.0.
```
