### ISSUE TITLE
Module conflict with Taxonomies

### ISSUE THREAD

**Issue by cromozooom** [gohugoio/hugo#8866]
### What version of Hugo are you using (`hugo version`)?

0.87.0

### Does this issue reproduce with the latest release?

Yes

Adding Modules in config makes Taxonomies usless:

```
baseURL = "/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "hugo"

[module]
[[module.imports]]
path = "github.com/cromozooom/gohugo-modules"

[taxonomies]
	category = "categories"
	tag = "tags"
	artwork = "artworks"
	support = "support"
	subject = "subject"
```

This was reported first time [here](https://discourse.gohugo.io/t/module-conflict-with-taxonomies/34141/2) and It looks like the problem was introduced with v0.84.0.

No problems with v0.83.1.

**Comment by jmooring** [comment]
> Adding Modules in config makes Taxonomies useless:

Specifically, none of the taxonomy sections are rendered in the publish directory.

**Comment by ptgott** [comment]
I'm not sure if any work has been done on this issue since the last comment, but it looks like the upstream module `github.com/twbs/bootstrap`, listed in @cromozooom 's [module config](https://github.com/cromozooom/gohugo-modules/blob/6d78f35394893bdf053b8f420e595db9af07c775/config.toml#L11), includes `taxonomy` under `disableKinds` (https://github.com/twbs/bootstrap/blob/9e1d81a851cac268ca70e95d62c3e968e7293b41/config.yml#L21).

I'm pretty sure the issue has to do with [this](https://github.com/gohugoio/hugo/commit/bb2aa08709c812a5be29922a1a7f4d814e200cab) commit, which is included in the v0.84.0 release and changes the way module configuration is merged into a Hugo project's configuration ([release notes](https://github.com/gohugoio/hugo/releases/tag/v0.84.0)). I haven't dug into the commit at all, but I have some time this weekend to start work on a possible PR.

**Comment by ptgott** [comment]
Forgot to note: @cromozooom to fix your issue now, add `disableKinds = []` to your config. This will preempt the `disableKinds` setting for upstream modules.

**Comment by cromozooom** [comment]
Thank you Paul

best regards Razvan Nicu
+44 07783363309
www.solopx.com - Please consider the environment before printing this email

**Comment by davidsneighbour** [comment]
```
[[imports]]
path = "github.com/twbs/bootstrap"
disable = false
ignoreConfig = true
ignoreImports = true
```

for the twbs/bootstrap module solves this.

**Comment by bep** [comment]
>disableKinds = [] to your config. This will preempt the disableKinds setting for upstream modules.

By default, that setting should not be merged in from upstream modules, but it may look like that is what happens ...

**Comment by davidsneighbour** [comment]
That is not the problem (specifically in this case with Bootstrap). Have a look at Bootstrap's config.yml. They do [some weird stuff with module imports recursive to their own repo](https://github.com/twbs/bootstrap/blob/main/config.yml#L25). Disabling the import of their config completely does the trick.
