### ISSUE TITLE
Make rel shortcode work for page resources

### ISSUE THREAD

**Issue by rothgar** [gohugoio/hugo#8889]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.87.0+extended linux/amd64 BuildDate=unknown
</pre>

### Does this issue reproduce with the latest release?
yes

I have a static file I would like to show the full URL for in a page.

```
content/index.md
static/deployment.yaml
```
In my page I would like to have this content rendered (backslashes added to escape GH formatting)
```
\```bash
kubectl apply -f {{< ref "/deployment.yaml" >}}
\```
```
But instead I get an error that the page is not found

```
[en] REF_NOT_FOUND: Ref "/manifests/hello-eks-a.yaml": "/home/rothgar/src/website/content/index.md:14:18": page not found
Rebuild failed:

Logged 1 error(s)
```

Can this check be disabled or can static files be supported by the ref shortcode?

**Comment by jmooring** [comment]
> Can this check be disabled

1. You can format the shortcode within the code fences such that it will not be evaluated:

   ```
   {{</* ref "/deployment.yaml" */>}}  
   ```

   This will be rendered as:

   ```
   {{< ref "/deployment.yaml" >}}
   ```

2. You can configure the `ref` and `relref` functions (and their corresponding shortcodes) to throw a warning instead of an error. See <https://gohugo.io/content-management/cross-references/#ref-and-relref-configuration>

> can static files be supported by the ref shortcode?

Currently the `ref` and `relref` functions (and their corresponding shortcodes) are limited to pages, but you could do something like this:

layouts/shortcodes/absurl.html

```
{{ absURL (.Get 0) }}
```

Then in your content:

```
{{< absurl "/deployment.yaml" >}}
```

**Comment by rothgar** [comment]
Thanks for the quick comment. I saw a thread about ignoring the rendered content but in this case I **want** the content to be rendered properly in the code block.

I was hoping to avoid creating a custom shortcut but I'm guessing that's probably the easiest solution.

I also didn't know about configuring the error level. That might be another good alternative but I would be worried that won't catch other situations where I want an error for missing pages.
