### ISSUE TITLE
when I update the hugo version form 0.79 to 0.87, then " found no layout file for "HTML" for kind "page""

### ISSUE THREAD

**Issue by George-Gou** [gohugoio/hugo#8890]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version

</pre>

**Comment by George-Gou** [comment]
hugo v0.87.0-B0C541E4 linux/amd64 BuildDate=2021-08-03T10:57:28Z VendorInfo=gohugoio

**Comment by bep** [comment]
Thanks for getting in touch, but it feels like this is a question  that would be better suited to the [Hugo Discussion Forum](https://discourse.gohugo.io/).  We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug. You may also find the answers you search for in [Hugo Documentation](http://gohugo.io/overview/introduction/).
