### ISSUE TITLE
Can't support hugo server command under exampleSite subfolder?

### ISSUE THREAD

**Issue by elkan1788** [gohugoio/hugo#8936]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.87.0-B0C541E4 windows/amd64 BuildDate=2021-08-03T10:57:28Z VendorInfo=go
hugoio

</pre>

### Does this issue reproduce with the latest release?

I used the latest version of Hugo. 

### Bug Description

Before used  the  latest version of Hugo  I can build server with my themes past through the below command:

```
$ cd my-hugo-theme/exampleSite
$ hugo sever -t ../..
```

But after I upgrade the Hugo to latest version, It can't worked the above command to testing my themes in local. And got the error like this :

```
Error: module "hugo-theme-next" not found; either add it as a Hugo Module or sto
re it in "D:\\GitRepos\\hugo-theme-next\\exampleSite\\themes".: module does not
exist
```

So what's new change of latest version of Hugo?

**Comment by bep** [comment]
Thanks for getting in touch, but it feels like this is a question  that would be better suited to the [Hugo Discussion Forum](https://discourse.gohugo.io/).  We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug. You may also find the answers you search for in [Hugo Documentation](http://gohugo.io/overview/introduction/).

**Comment by elkan1788** [comment]
@bep Yeah, I had found some in Hugo Discussion Forum, but couldn't fond any things, then I think it maybe bug work new version that open this issues.
