### ISSUE TITLE
Improve access to .File variables from archetypes

### ISSUE THREAD

**Issue by jmooring** [gohugoio/hugo#9032]
When used within an archetype:

1. `.File.Lang` returns an empty string. This is true for:

   - Simple pages (content/post/foo.md)
   - Leaf bundles (content/post/bar/index.md)
   - Branch bundles (content/post/baz/_index.md)

2. `.File.ContentBaseName` returns the wrong value for leaf and branch bundles:

   - Leaf bundles (content/post/bar/index.md --> returns `index`, expected `bar`)
   - Branch bundles (content/post/baz/_index.md --> returns `_index`, expected `baz`)

Example:

```bash
git clone --single-branch -b hugo-github-issue-9032 https://github.com/jmooring/hugo-testing hugo-github-issue-9032
cd hugo-github-issue-9032
hugo server
```

**Comment by bep** [comment]
I have briefly looked at the code doing this, and I think we can do be better.

In my head we have several related issues:

* This issue and #7589 
* Hard to reason about in multilingual sites
* ...

I think the above can be fixed by:

* We first write a placeholder content file to the given path, build options set to it does not show up in any page collection.
* We then render the archetype template with the `.Page` as a new attribute. So, `.File` and `.Page.File` will point to the same object and all file paths will be the same as you would build the site with that content file.
* The language (`.Site`) will also automatically be correct (as we would use the same logic as in the regular build).

Sounds like a plan?

**Comment by jmooring** [comment]
Is the placeholder written to disk or memory? Or, more to the point:
- If I'm running hugo server and create a new page, will it rebuild three times (once each for placeholder creation, page creation, placeholder deletion)
- If I crash a build (intentionally or unintentionally), could the placeholder (if on disk) become orphaned?

> build options set to it does not show up in any page collection

It should not show up in taxonomy collections either.

**Comment by bep** [comment]
>Is the placeholder written to disk or memory? Or, more to the point:

I haven't thought about changing that logic as part of this, we currently write to disk only. The `hugo new` command does not share any context with any running server.

>It should not show up in taxonomy collections either.


Yea, well, that's an unrelated issue. I don't think it's common to list taxonomies in content page archetype files.

**Comment by bep** [comment]
>Disregard. Path to new file depends on whether or not you have defined languages in site configuration

Yes, and it would much better support multiple content mounts (there are currently lots of guessing in that code, and often we get it wrong).

I have quickly worked up a prototype, and I think it will greatly simplify what we have. The below is what you would then get in the archetype template as the `.`; backwards compatible, but more correct.


```go
// archetypeFileData represents the data available to an archetype template.
type archetypeFileData struct {
	// The archetype content type, either given as --kind option or extracted
	// from the target path's section, i.e. "blog/mypost.md" will resolve to
	// "blog".
	Type string

	// The current date and time as a RFC3339 formatted string, suitable for use in front matter.
	Date string

	Page page.Page
}

func (f *archetypeFileData) File() source.File {
	return f.Page.File()
}

func (f *archetypeFileData) Site() page.Site {
	return f.Page.Site()
}

func (f *archetypeFileData) Name() string {
	return f.Page.File().ContentBaseName()
}

```
