### ISSUE TITLE
Add optional seed argument to shuffle

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#9247]
See https://discourse.gohugo.io/t/make-shuffle-show-different-posts-per-post/35900

**Comment by jmooring** [comment]
The lack of randomization in the referenced forum topic was due to a cached partial. 

The current `shuffle` seed is `time.Now().UTC().UnixNano()`.

1. The UTC() conversion is not necessary.
2. I don't understand how #4337 had any beneficial effect.
3. Are there cases where the current seed is insufficient?

I'm not against adding an arg, I just haven't encountered a problem with this before.

**Comment by bep** [comment]
>Are there cases where the current seed is insufficient?

The current seed is fine, but there are 2 situations where I imagine a custom seed would be useful.

1. If you want a more stable shuffle (same order on every build), just pass in `42` or something as the seed.
2. You want new _shuffle_ on each build, but slightly different between the sections ...

**Comment by bep** [comment]
Never mind, I'm not sure this is a great idea ...
