### ISSUE TITLE
Remote image gets: *resources.genericResource is not an image

### ISSUE THREAD

**Issue by regisphilibert** [gohugoio/hugo#9275]
### What version of Hugo are you using (`hugo version`)?

`hugo v0.90.1-48907889+extended darwin/amd64 BuildDate=2021-12-10T10:56:41Z VendorInfo=gohugoio`

### Does this issue reproduce with the latest release?

Yes

I'm trying to fetch an image remotely (https://images.unsplash.com/photo-1611323593958-0fec16fa2909) and grab its `.Width` and `.Height` or use `.Resize`. But the following ensue: `error calling Width: *resources.genericResource is not an image` or `error calling Resize: *resources.genericResource is not an image`

Note that `MainType` and `SubType` are `image` and `jpeg` respectively.

This might be because the URL do not point to a file per say, but and endpoint serving a file. But then, the MainType/SubType are misleading and prevent any testing before trying to apply image transformation.

```
  {{ with resources.Get "https://images.unsplash.com/photo-1611323593958-0fec16fa2909" }}
  {{ with .Err }}
    {{ warnf "%s" . }}
  {{ else }}
    {{ with .Resize "300x"}}
    <img src="{{ .RelPermalink }}" width="{{ .Width }}" height="{{ .Height }}" alt="">
    {{ end }}
  {{ end }}
```

**Comment by regisphilibert** [comment]
Seem to have the same problem with local image and `.Resize`... but will investigate monday.

**Comment by jmooring** [comment]
```
{{ with resources.Get "https://images.unsplash.com/photo-1611323593958-0fec16fa2909" }}
  {{ .RelPermalink }} --> /photo-1611323593958-0fec16fa2909_5636203134359007483.jpe
{{ end }}
```

The extension is `jpe`.

**Comment by regisphilibert** [comment]
Which might be what causes the error, but if you download the image, you'll see that the file's extension is jpg. If this is indeed a JPE file, and Hugo does not support, we should be able to test this through `MainType/SubType` or else.

**Comment by eyllanesc** [comment]
> Which might be what causes the error, but if you download the image, you'll see that the file's extension is jpg. If this is indeed a JPE file, and Hugo does not support, we should be able to test this through `MainType/SubType` or else.

It seems that the browser infers the type of the image if the path does not have an extension, so it adds .jpg. If you use wget, you get the binary file without an extension whose operation is similar to what hugo does.

**Comment by regisphilibert** [comment]
Interesting. So maybe the problem is that the Hugo returns a SubType of `jpg`?

**Comment by jmooring** [comment]
When we retrieve this image, this is what happens.
1. Determine the MIME type (`image/jpeg`) from the response header.
2. Determine the extension from the MIME type. But with `image/jpeg` there are several possibilities, so we try something else.
3. Determine the extension from the file name. But this file doesn't have an extension, so we try something else.
4. Determine the MIME type (again) by looking at the first 512 bytes.
5. Determine the extension from the MIME type. But with `image/jpeg` there are several possibilities, _so we pick the first one_.

On Ubuntu, the sorted list of extensions associated with `image/jpeg` is `.jpe`, `.jpg`, and `jpeg`. The last two are Go built-ins, but the list is augmented by the OS (that's where `.jpe` comes from).

So, the first extension on the list is `.jpe`, and Hugo doesn't treat that as an image.

[#9278](https://github.com/gohugoio/hugo/pull/9278) says, if it's an `image/jpeg` without an extension, make the extension `.jpg` instead of picking the first one from the list. This way people who save an image locally can open it. Although my Ubuntu system knows that `.jpe` is an `image/jpeg`, the extension is not associated with any viewers.

I'll create a separate PR to treat `.jpe` files as images.
