### ISSUE TITLE
hugo compiles (sass ) file very slow on mac os system 

### ISSUE THREAD

**Issue by maogou** [gohugoio/hugo#9291]
### What version of Hugo are you using (`hugo version`)?

<pre>
➜  blog git:(develop) hugo server 
Start building sites … 
hugo v0.90.1+extended darwin/amd64 BuildDate=unknown

                   | ZH  | EN   
-------------------+-----+------
  Pages            | 131 | 132  
  Paginator pages  |   3 |   3  
  Non-page files   |   3 |   3  
  Static files     | 129 | 129  
  Processed images |   0 |   0  
  Aliases          |  36 |  35  
  Sitemaps         |   2 |   1  
  Cleaned          |   0 |   0  

Built in 7717 ms
Watching for changes in /Users/maogou/work/blog/{archetypes,content,static,themes}
Watching for config changes in /Users/maogou/work/blog/config/_default
Environment: "development"
Serving pages from memory
Running in Fast Render Mode. For full rebuilds on change: hugo server --disableFastRender
Web Server is available at http://localhost:1313/ (bind address 127.0.0.1)
Press Ctrl+C to stop

![121639462210_ pic_hd](https://user-images.githubusercontent.com/48229139/146005185-688527f3-c04c-4b01-946d-64118b582a28.jpg)

</pre>

### Does this issue reproduce with the latest release?

yes 

###  my issue ↓↓

The same blog code compiles very fast on windows 10 OS  wls, but compiles very slow on mac os system, please help me

**Comment by bep** [comment]
Thanks for getting in touch, but it feels like this is a question  that would be better suited to the [Hugo Discussion Forum](https://discourse.gohugo.io/).  We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug. You may also find the answers you search for in [Hugo Documentation](http://gohugo.io/overview/introduction/).
