### ISSUE TITLE
Markdown Render Hook - Email

### ISSUE THREAD

**Issue by septs** [gohugoio/hugo#9319]
Allow user define email render template, generate protected email logic code or ui

before input, e.g:
```markdown
<sample@example.com>
[user-defined text](mailto:sample@example.com)
[![user-defined image](https://example.com/sample.png)](mailto:sample@example.com)
```

**Comment by jmooring** [comment]
Your examples are markdown _links_ where the URL scheme is "mailto" (either explicit or implied). Because these are links, use the _link_ render hook, e.g.,

layouts/_default/_markup/render-link.html

```
{{ if eq (urls.Parse .Destination).Scheme "mailto" }}
  <a href="{{ .Destination }}">{{ .Text | safeHTML }} (email)</a>
{{ else }}
  <a href="{{ .Destination }}">{{ .Text | safeHTML }}</a>
{{ end }}
```

In the future, please use the forum (https://discourse.gohugo.io) for questions and troubleshooting. We prefer to use GitHub for verified bugs and vetted enhancements. Thanks.
