### ISSUE TITLE
Hugo's word count is wrong in the HTML content written in Japanese even if hasCJKLanguage is true.

### ISSUE THREAD

**Issue by mikanmi** [gohugoio/hugo#9335]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ Hugo version
hugo v0.91.2+extended darwin/amd64 BuildDate=unknown
</pre>

### Does this issue reproduce with the latest release?

We know Hugo v0.91.2 is the latest version.

Hugo's word count is wrong in the HTML content written in Japanese even if [hasCJKLanguage](https://gohugo.io/getting-started/configuration/#hascjklanguage) is true.

Hugo's word count gives the number of characters in the HTML content written in Japanese.
We know Hugo's word count gives the number of words in contents written in English and other languages at least except Japanese.

We expect Hugo's word count gives the number of not characters but words in HTML contents written in Japanese if hasCJKLanguage is true.

hasCJKLanguage of Hugo-defined variables:
<https://gohugo.io/getting-started/configuration/#hascjklanguage>

**Comment by jmooring** [comment]
This has been [discussed before](https://github.com/gohugoio/hugo/issues/1266). 

From a [research paper](https://aclanthology.org/P19-2060.pdf) presented at the Proceedings of the 57th Annual Meeting of the Association for Computational Linguistics (July 28 - August 2, 2019):

> In computational linguistics, the first step in text processing tasks is segmenting an input text into words. Most languages make use of white spaces as word boundaries, facilitating this segmentation step. However, Japanese is one of the few languages that does not use a word delimiter. This particular problem has been the focus of many researchers...

It looks like Google's [Natural Language API](https://cloud.google.com/natural-language/) performs word segmentation, but making an API call every time you need to count words would be expensive.

The [github.com/go-ego/gse](https://github.com/go-ego/gse) package purportedly provides word segmentation for "English, Chinese, Japanese and other."

Neither of these approaches is trivial to implement or maintain, and I question the value of doing so. With limited exceptions, the only reason I ever need the word count is to estimate the reading time. And with CJK, you can base reading time on rune count. For example, [medium.com](https://medium.com/blogging-guide/how-is-medium-article-read-time-calculated-924420338a85#7227) calculates CJK reading time based on 500 runes/min.

**Comment by patineboot** [comment]
Hello @jmooring,

We need Hugo's word count for the '.Summary' feature of Hugo also.
You can confirm the Japanese summary is too short on [💃Patineboot Dancing👠](https://patineboot.com) built with Hugo.

Visit and see [💃Patineboot Dancing👠](https://patineboot.com).
The "Recent Article" section has enough summaries of every article.
But, the "Recent Weblog" section written in Japanese has TOO short summaries of every weblog.

I expect Hugo returns the summary with enough length from '.Summary' of the Japanese contents.

We, developers and users of the Summary feature of Hugo, expect Hugo's word count gives the number of not characters but words in HTML contents written in Japanese.

**Comment by davidsneighbour** [comment]
Japanese, Thai and plenty of other Asian languages HAVE NO WORD BOUNDARIES. So Hugo can't calculate them. Specifically, in Thai, it's not possible to discern between Vowel-Consonant combinations and word boundaries without knowing the meaning of the characters. Simply put: ba could be a word (1 character with a vowel sign on top) as well as baba (double that character count), but IF that is the case can be only discerned in the context of the other words around that and the meaning of the full sentence. 

So: Hugo CAN'T count words in Japanese. In the code, it also states that in languages like Japanese it counts character (runes) instead of words. The documentation should reflect that.

If a developer and user of Hugo (not the summary feature, it's not a feature) requires a proper word count the way to do that is to use an external program to calculate this additional information and put it into a frontmatter variable that can be used by the theme developer to display information about the content. 

There is by the way plenty of discussion about that not only in the links above, but the online tools that count words display messages like "We count the actual words for all languages with a few exceptions that use a symbol-to-word ratio.
These are Chinese: 0.75, Korean: 0.5, and Thai: 0.25."

**Comment by patineboot** [comment]
@davidsneighbour

You SHOULD write "Hugo's word count gives the number of not characters but words" on the document.
You used "CAN'T," "NO," "NOT," or negative words to us.
Your post is badly negative.

You can NOT solve this issue. 
Don't reply anymore.

I want to discuss this issue with @jmooring here.

**Comment by davidsneighbour** [comment]
What @jmooring is telling you is that this is not a solvable issue. What _I_ am telling you is that the documentation will be updated to include a note that word count is only working in languages with clear defined word borders. Regarding the "Don't reply anymore" - re-assess your approach to open source and discourse.

**Comment by patineboot** [comment]
@davidsneighbour

@davidsneighbour SHOULD write "Hugo's word count gives the number of not characters but words" on the document.
Don't reply anymore before you update the document.

@jmooring,
No reply yet.

We, developers and users of the Summary feature of Hugo, expect Hugo's word count gives the number of not characters but words in HTML contents written in Japanese.

I expect Hugo returns the summary with enough length from '.Summary' of the Japanese contents.
- English summary has approximately 430 characters.
- Japanese summary has approximately 80 characters.

**I request @jmooring replies to my comments.**

**Comment by patineboot** [comment]
I hope that @bep join to this discussion here.

**Comment by patineboot** [comment]
Not stale.
@bep does not join this discussion yet.
