### ISSUE TITLE
Add minimal analytics to Hugo

### ISSUE THREAD

**Issue by afrophi** [gohugoio/hugo#9341]
I use [minimal analytics](https://gist.github.com/DavidKuennen/443121e692175d6fc145e1efb0284ec9) on my site and I was wondering if there is a way to incorporate it to Hugo and define it in the config file?

**Comment by bep** [comment]
Thanks for getting in touch, but it feels like this is a question  that would be better suited to the [Hugo Discussion Forum](https://discourse.gohugo.io/).  We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug. You may also find the answers you search for in [Hugo Documentation](http://gohugo.io/overview/introduction/).

**Comment by nfriedli** [comment]
The solution is here: https://discourse.gohugo.io/t/minimal-analytics/36327/2?u=nfriedli
