### ISSUE TITLE
Automatically create default Archetype based on config file format

### ISSUE THREAD

**Issue by ktprograms** [gohugoio/hugo#9365]
(follow up to #9363)

With `hugo new site -f toml name-of-site` (or `-f json` or `-f yaml`), the format of the configuration file can be changed. Currently, this does not change the format used for frontmatter in new content.

I think it might be a good idea to generate different `archetypes/default.md` files based on the format selected when creating a new Hugo site.

If you want to make it _really_ customisable, maybe add a `--frontmatter-format` option to `hugo new site` so that the frontmatter format can be set independently of the config file format. This would also allow the frontmatter in the default archetype to be in Org Mode format.

**Comment by ktprograms** [comment]
I'm quite busy this weekend, but if after that a fix hasn't been submitted I'll look into submitting a PR myself.

**Comment by jmooring** [comment]
I wouldn't spend any time on this:

1. The majority of sites that I have seen use TOML for config and YAML for front matter. 
2. Creating a new site is an infrequent task.
3. The effort required to manually change the archetype format after site creation is minimal.
4. The selection of formats is opinionated. For example, I would _never_ use YAML for front matter, but I might use YAML for a complex site configuration. To some extent this is a tabs/spaces discussion, which is fruitless, because everyone knows spaces are the correct choice.

**Comment by bep** [comment]
We're not doing this.
