### ISSUE TITLE
Check hang on --panicOnWarning

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#9380]
https://discourse.gohugo.io/t/hugo-paniconwarning-hangs-forever/36548

**Comment by Ephex2** [comment]
I think I've found the bug. I'm going to do my best to follow the contributor guide to prepare a PR.

**Comment by bep** [comment]
@Ephex2 That would be much appreciated (I've been a little busy myself lately ...)! The `loggers.PanicOnWarning` is a global variable (unfortunately, but that was a pragmatic choice ...); you should be able to trigger the panic in a test from `hugolib`, but remember to 1) Not call t.Parallel() and do a `defer func() { loggers.PanicOnWarning = false }` so the other tests don't ... panic.

**Comment by Ephex2** [comment]
I took note of the resetting the value of loggers.PanicOnWarning, thanks for pointing that out.

I found the bug in general.go, so I added the test into general_test.go -- let me know if there's a better test file to host it. I think that it can be put almost anywhere, since the only helpers function it uses is public. 

I'll create the PR, let me know if you see anything amiss, I'm pretty new to contributing on GitHub.
