### ISSUE TITLE
Incorrect HTML around simple shortcode

### ISSUE THREAD

**Issue by goose3228** [gohugoio/hugo#9545]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.92.2+extended linux/amd64 BuildDate=unknown
</pre>

### Does this issue reproduce with the latest release?

Yes

### Sample site

**layouts/index.html**
```
{{ .Content }}
```

**layouts/shortcodes/div.html**
```
<div></div>
```

**content/_index.md**
```
+++
title = "Home page"
+++
{{< div >}}
some text
```

### Expected output
```
<div></div>
some text
```
Or
```
<div></div>
<p>some text</p>
```

### Current output
```
<p><div></div>

some text</p>
```

Note that `<p>` can not contain `<div>`, so most browsers would interpret this as
```
<p></p>
<div></div>
some text
```

### Workaround
Add newline after shortcode
```
{{< div >}}

some text
```

It's quite confusing - usually when markdown generates excess paragraphs you remove newlines, not create.

**Comment by davidsneighbour** [comment]
How is your workaround a workaround if this is the standard way of CommonMark, which is implemented by Goldmark which is the default markdown engine for Hugo?

If this is implemented wrongly then it's something that needs to be fixed "upstream" in the Goldmark module, but I don't think that's a bug.

https://spec.commonmark.org/0.29/#example-56 - check these examples and the following. Everything without a double new line is deemed content of the current block level element.

**Comment by jmooring** [comment]
@goose3228 I understand your confusion, and I apologize in advance for the lengthy explanation.

The CommonMark specification states that this markdown:

```text
<div></div>
foo
```

Must produce this HTML:

```html
<div></div>
foo
```

And it does -- [try it](https://spec.commonmark.org/dingus/?text=%3Cdiv%3E%3C%2Fdiv%3E%0Afoo%0A).

So you would think that your shortcode would be a simple substitution, producing exactly the same thing. But instead you get this:

```html
<p><div></div>
foo</p>
```

Why? Because of how and when the substitution is handled.

When you call a shortcode using this `{{< foo >}}` notation, we do not render the shortcode before sending the page content to the markdown renderer ([Goldmark](https://github.com/yuin/goldmark)). Instead, we send a placeholder, effectively something like this:

```text
HAHAHUGOSHORTCODE-UNIQUE-ID
foo
```

Which produces this HTML ([try it](https://spec.commonmark.org/dingus/?text=HAHAHUGOSHORTCODE-UNIQUE-ID%0Afoo)):

```html
<p>HAHAHUGOSHORTCODE-UNIQUE-ID
foo</p>
```

When we get this back from Goldmark, we replace the placeholder with the rendered shortcode, producing this:

```html
<p><div></div>
foo</p>
```

You discovered the way most people get around this: break the flow with a blank line beneath the shortcode.

But you can also force your shortcode to be rendered _before_ we send the page content to Goldmark by using this notation:

```text
{{% div %}}  <-- notice the percent symbols
foo
```

This will produce:

```html
<div></div>
foo
```

However, you must place this in your site configuration:

```
[markup.goldmark.renderer]
unsafe = true
```

Is this an "unsafe" configuration? If you are in control of your content files, no. If others that you do not trust are providing content, yes. Read more about Hugo's security mode [here](https://gohugo.io/about/security-model/#web-application-security).

I'll leave this issue open for a few days, but the behavior is expected (albeit surprising) when using the `{{< foo >}}` notation.

**Comment by goose3228** [comment]
Thanks for explanation, makes more sense now.

In the docs `{{% %}}` and `{{< >}}` are called with/without markdown, but the real difference which is render order relative to the rest of the page is not well outlined.
