### ISSUE TITLE
Expose .Name and .Position within codeblock render hook

### ISSUE THREAD

**Issue by jmooring** [gohugoio/hugo#9574]
Primarily for using with `errorf`, `erroridf`, and `warnf`. Of the two values, `.Position` is the most important. Usage:

```
{{ errorf "The language you have specified for the %q template is invalid. See %s" .Name .Position }}
```

> The language you have specified for the "render-codeblock" template is invalid. See "/home/user/project/content/_index.md:20:1"

**Comment by bep** [comment]
>Expose .Name and .Position

So, the issue title makes this look easy, and I initial thought that, too, but this needs to be calculated. I have the byte offset from Goldmark, but there is a potential big diff in the source Goldmark sees and the original (considering front matter and shortcodes), so those offsets are not useful. Since this is (hopefully) only used for error situations, we could probably do a string search in the original source on demand. I agree that this would be useful.

**Comment by jmooring** [comment]
> I understand the need, but I find it a little bit foreign and confusing to add that to the interface.

The `.Position` value will be enough to help the user resolve the error in most cases. The template name would be nice to have,  but I understand that might be more difficult. Thank you for this. I'll test #9575 in a few minutes.

**Comment by bep** [comment]
>The template name would be nice to have, but I understand that might be more difficult

I would not say difficult, the information is there ... but I don't know where to ... put it.

**Comment by bep** [comment]
Closing this for now.
