### ISSUE TITLE
Open links in new tab by default

### ISSUE THREAD

**Issue by chuck-confluent** [gohugoio/hugo#9584]
Right now, any links defined in markdown will open in the same tab in which they are clicked. In order to override this, you have to create your own render-link.html file as a layout like this:
- https://github.com/chuck-alt-delete/blog-source/blob/main/layouts/_default/_markup/render-link.html

I think this should be the default behavior for links, or at least make it easier to enable, or even provide some official documentation/guidance. Thanks!

**Comment by davidsneighbour** [comment]
It is not task of a website to define where to open links. If users want to open links in a new window they can do so in most browsers by middle click or right click > open in new window. The default behaviour for links should be the one that was intended since the beginning of HTML, which is using the current viewport and show the target of the link. That is literally the meaning of "link", not adding, but linking to a page.

You already found the correct way to render your links on your own will which is a standard feature in hugo for exactly that. 

By the way, the method you are using will open a new window even if the user just clicks from one page on your site to another. That is very unusable for visitors. 

- https://www.smashingmagazine.com/2008/07/should-links-open-in-new-windows/
- https://www.nngroup.com/articles/new-browser-windows-and-tabs/

**Comment by chuck-confluent** [comment]
> By the way, the method you are using will open a new window/tab even if the user just clicks from one page on your site to another. That is very unusable for visitors.

It in fact does not

**Comment by davidsneighbour** [comment]
> It in fact does not.

You are right. If your site does not utilize the canonical URLs configuration it doesn't. Doesn't also change a thing about my response about your feature request being a custom configuration requirement that does not follow common standards of web development.

**Comment by jmooring** [comment]
@chuck-confluent 

There's an example in the documentation:
<https://gohugo.io/getting-started/configuration-markup/#link-with-title-markdown-example>

If you feel that this is insufficient, please submit an issue or PR to the docs repository:
<https://github.com/gohugoio/hugoDocs/>

Thanks.

**Comment by chuck-confluent** [comment]
@jmooring thanks! So it looks like the `blackFriday` markdown parser does in fact have a config `hrefTargetBlank`, and then I see the `render-links.html` snippet further down. I think I will work on a PR for the docs since this was very hard to find. Googling "hugo open link in new tab" doesn't take people anywhere near that docs page, and searching "open link in new tab" inside the docs just takes you to a page that seems irrelevant (https://gohugo.io/content-management/taxonomies/#default-taxonomies)

**Comment by jmooring** [comment]
FYI - Blackfriday will be removed at some point:
<https://github.com/gohugoio/hugo/issues/6487>
