### ISSUE TITLE
Hugo serve does not respect the baseUrl for static content

### ISSUE THREAD

**Issue by ohubaut** [gohugoio/hugo#9608]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.93.1+extended darwin/amd64 BuildDate=unknown
</pre>

### Does this issue reproduce with the latest release?

Yes.

### Problem description 

When defining a baseURL with a path (e.g.: https://example.org/mysite/ ) the `hugo serve` does not properly prepend the `mysite` part to access assets in the static folder.
This result in a different behaviour between the `hugo serve` and plain `hugo` command where the files will be placed at the correct location.

### Workaround

The only way I managed to get a reasonable workaround was to create a specific development config without the path as part of the baseUrl. But that itself is not really suitable when working with multiple modules that compose a bigger website.

**Comment by bep** [comment]
Thanks for getting in touch, but it feels like this is a question  that would be better suited to the [Hugo Discussion Forum](https://discourse.gohugo.io/).  We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug. You may also find the answers you search for in [Hugo Documentation](http://gohugo.io/overview/introduction/).

**Comment by ohubaut** [comment]
I'm sorry but I disagree with you. 
Either the [documentation](https://gohugo.io/content-management/static-files/) is wrong, or the behaviour of `hugo server` is incorrect.

Please reconsider.
