### ISSUE TITLE
image showing in markdown but not in actual website(server)

### ISSUE THREAD

**Issue by whatthesamuel** [gohugoio/hugo#9776]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version 0.96.0

</pre>

### Does this issue reproduce with the latest release?
I installed the latest version as of writing this issue and it persists.

As the title says, my png image shows fine on markdown preview on VS Code, but when I actually run the server, the image won't render. It only shows the temporary text, and when I try to open the image in a new tab via right clicking, it returns a 404 error.

 **I think this may be a bug since,** as I previously mentioned, on VS Code the image shows fine without any problems. So I think that means the problem is not the directory, but something with the compiler or the renderer. Unless there is something that I don't know?

Regardless, I've tried too google and fix it myself by
* changing the image directory from static to static/images
* changing the image directory to local(where the markdown post is)
* using the ` {{ $image := .Resources.GetMatch "image.png" }} ` (yes, I changed the image name)
with no change in results.

I would like to attach screenshots, but it is a post with semi-advertising(it's about a game asset that I made), so I thought people wouldn't like it. but I will if anyone finds it necessary.

**Comment by bep** [comment]
Thanks for getting in touch, but it feels like this is a question  that would be better suited to the [Hugo Discussion Forum](https://discourse.gohugo.io/).  We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug. You may also find the answers you search for in [Hugo Documentation](http://gohugo.io/overview/introduction/).
