### ISSUE TITLE
Data files can't have numbers as name

### ISSUE THREAD

**Issue by robsonsobral** [gohugoio/hugo#9796]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.95.0-9F2E76AF+extended windows/amd64 BuildDate=2022-03-16T14:20:19Z VendorInfo=gohugoio
</pre>

### Does this issue reproduce with the latest release?

I think so, as I couldn't find anything related on the changelog.

### Bug

I'm getting `unexpected ".2018" in operand`. I discovered trying to move the data from `data/candidates.json` to a nested folder `data/candidates/2018.json`.

![image](https://user-images.githubusercontent.com/931642/163826028-aff7b392-2e2e-46e1-9eca-55d6b545c1ac.png)

**Comment by bep** [comment]
I'm suspected that there is more to this story. What's the template look like where you access this data?

**Comment by jmooring** [comment]
This is a Go restriction, documented [here](https://go.dev/ref/spec#Identifiers). Identifiers must begin with an underscore or a Unicode letter, followed by zero or more underscores, Unicode letters, or Unicode digits.

You can either:
- Rename the data file, or
- Use the `index` function

Do this:

```
{{ index site.Data "2018" "foo" }}
```

Instead of this:

```
{{ site.Data.2018.foo }}
```

**Comment by jmooring** [comment]
@robsonsobral 

Will do, at some point. See <https://github.com/gohugoio/hugoDocs/issues/1728>.
