### ISSUE TITLE
Make the title func follow some style guide

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#989]
This template func could be very useful, if it was done properly.

Right now it title cases first char of each word.

So 

This is a title => "This Is A Title"

From the doc:

```
// Title returns a copy of the string s with all Unicode letters that begin words
// mapped to their title case.
```

Have a look at http://titlecapitalization.com/

Pick a style, but it would cool if AP style was the default, then add an option for the other two. 

Do not underestimate the importance of this.

@anthonyfok - you are the style guide / copy edit expert in here. What do you think? I can implement this if more people than me thinks it is important ...

**Comment by EricR** [comment]
I think this would be useful :+1:

**Comment by anthonyfok** [comment]
@bep: Hoho!  You are flattering me!  I am no expert.  ;-)

But yes, I think what you suggest would be a great thing to have.
Hugo docs used to use `text-transform: capitalize` for the sidebar menu,
and having "Of", "The" etc. capitalized was very disconcerting,
hence commit 769ab9e22476f3ddfbffae62f9ece3a8f2213d38.

The only concern I have is that languages other than English may have different styles/rules.  For example, it seems to me that French titles tend to use "sentence case" rather than "title case".  But I think I am worrying too much.  ;-)

English is most likely the most-used language for Hugo and for any static website generator / CMS out there, so I'd say it is a very valuable feature and a noble effort.  Thank you for taking this initiative!

**Comment by bep** [comment]
I'm from Norway, and we have no title case ...

**Comment by bep** [comment]
**Note/Update:** This issue is marked as stale, and I may have said something earlier about "opening a thread on the discussion forum". Please don't.

If this is a **bug** and you can still reproduce this error on the latest <code>release</code> or the <code>master</code> branch, please reply with all of the information you have about it in order to keep the issue open.

If this is a **feature request**, and you feel that it is still relevant and valuable, please tell us why.

**Comment by yihui** [comment]
I'd not say it is a bug, but... `"This Is A Title"` just looks terrible, although English is not my native language. I don't care which style to use, but any style would be significantly better than no style at all.

My actual use case is to display all category names of a site, and I'm in a dilemma. If I use `preserveTaxonomyNames = true`, I get ugly URLs (e.g. `/categories/This is a Category/`); if I set it to `false` (default), I get ugly names for humans (`this-is-a-category`). In the latter case, I could use `string | humanize | title`, but it gives me `"This Is A Category"`. If only the original category names were stored and accessible from `.Site.Taxonomies.categories`...
