### ISSUE TITLE
Bug in relURL with leading slash when baseURL includes a subdirectory

### ISSUE THREAD

**Issue by jmooring** [gohugoio/hugo#9994]
This is not a new issue; behavior present in v0.54.0 through v0.100.2.

config.toml

```toml
baseURL = 'https://example.org/foo/'
```

template

```
{{ $url := "/foo/bar" }}
{{ $url | relURL }}
{{ $url | absURL }}
```

result

```
/foo/foo/bar
http://localhost:1313/foo/bar
```

Notice that the subdirectory from `baseURL` is repeated when using `relURL`, but it is _not_ repeated when using `absURL`. 

This has come up a few times in the forum, usually in conjunction with menu iteration:
- <https://discourse.gohugo.io/t/39014>
- <https://discourse.gohugo.io/t/38614>

Note that the same differences are present when comparing `relLangURL` and `absLangURL`.

**Comment by bep** [comment]
So, this is a bug, but not as described. It's `absURL` that behaves badly. The `relURL` behaviour may seem convienient, but how would you then construct `/foo/foo/bar`?

**Comment by bep** [comment]
>So, this is a bug, but not as described. It's absURL that behaves badly. The relURL behaviour may seem convienient, but how would you then construct /foo/foo/bar?

OK, looking at the code, my conclusion above wasn't right, we:

* Treat argument with a leading slash as host relative (or to be more precise, language root-relative)
* Treat argument without a leading slash as relative to the baseURL.

So, given that, the example above would be:

```
baseURL = 'https://example.org/foo/'

{{ $url := "/foo/bar" }}
{{ $url | relURL }}
{{ $url | absURL }}

/foo/bar
http://localhost:1313/foo/bar
```

**Comment by gravis** [comment]
I had a regression upgrading from hugo 0.100.2 to 0.101.0 and this seems to be the only change that would be related: `relURL` is now stripping the `baseURL` path. So if my base url is https://example.org/hugo/, `<link href="{{ "/css/fontawesome.min.css" | urlize | relURL }}" rel="stylesheet">` will generate `<link href="/css/fontawesome.min.css" rel="stylesheet">` instead of `<link href="/hugo/css/fontawesome.min.css" rel="stylesheet">` with `0.100.2`. Could that be related?

**Comment by bep** [comment]
@gravis comments on closed issues/PRs are rarely read, please open a new issue if you feal this is an issue, but I suggest you  just remove the leading "/" from your ref.
